### ISSUE TITLE
2018 Summer: release indigo

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#1000]
TODO
Steps to do to make this release happen:
- [x] Move full_pr2 pkgs to `moveit_pr2` repo -> done https://github.com/ros-planning/moveit_pr2/pull/98
- [x] Resolve circular dependency -> PR https://github.com/ros-planning/moveit/pull/1111
- [x] Update rosdistro indigo about the moveit_full_pr2 relocation (currently its [in moveit](https://github.com/ros/rosdistro/blob/d578284e09cfefefa780b6f06d7ae5767d33b58a/indigo/distribution.yaml#L7461) section). -> PR made https://github.com/ros/rosdistro/pull/19343
  - While this can be done either by making release of moveit indigo, cleanest is to open a PR to rosdistro to just update the location and nothing else. Once that's done, nothing further shouldn't be neeed regarding moveit_full_pr2 location (no version update for moveit_full_pr2 so no new release shouldn't be needed, unless we want to weave in the information about relocation explicitly in the release info).
- [x] `moveit_pr2`: package versions are not aligned b/w moveit_full_pr2 (that is 0.7.14 while the rest is 0.6.6).
- [x] Release moveit_pr2 -> delegated at https://github.com/ros-planning/moveit_pr2/issues/100
- [ ] Make Indigo release from moveit repo.

----

We want to have another indigo release to distribute the last few bugfixes in the indigo-devel branch.

Unless users request other patches in indigo, this might very well be the last release for this ROS distribution.
We stopped cherry-picking back to indigo for quite a while now
and with some effort the `kinetic-devel` branch can be compiled and used on Ubuntu 14.04 too.

I will run the ABI checks and report back until the end of the week.

**Comment by gavanderhoorn** [comment]
Nice, issue #1000.

**Comment by v4hn** [comment]
@130s 

The only ABI-incompatible changes I found are https://github.com/ros-planning/moveit/pull/443
@davetcoleman removed the alternative time parameterization method again, because it was supposed to be replaced by the better alternative.
However, the new alternative was not merged into `indigo-devel` anymore.

I believe it is ok to release the branch as is. Alternatively, we could backport the newer spline parameterization method to provide another alternative for indigo.

**Comment by davetcoleman** [comment]
Ah I hadn't realized the newer [time parameterization plugin](https://github.com/ros-planning/moveit/pull/441) was kinetic only. I think it makes sense to cherry-pick back to indigo, but it also probably doesn't matter much since its a new barely used feature that doesn't belong in an old LTS

**Comment by 130s** [comment]
Does releasing Kinetic and/or Melodic together make sense, or does that need a separate discussion?

**Comment by v4hn** [comment]
> Does releasing Kinetic and/or Melodic together make sense, or does that need a separate discussion?

To be honest I don't know right now.

Given that GSoC will end soon I lean towards having the next release kinetic+ *after* the results get merged.

**Comment by 130s** [comment]
I see.

I'm planning to make release on this weekend, for Indigo only.

**Comment by 130s** [comment]
Can anyone list the ticket numbers that need to be addressed before Indigo release?

**Comment by v4hn** [comment]
> Can anyone list the ticket numbers that need to be addressed before Indigo release?

None to the best of my knowledge.

**Comment by 130s** [comment]
Ah, then I might have misunderstood the few previous posts like https://github.com/ros-planning/moveit/issues/1000#issuecomment-413307231. So now my understanding: indigo release is ready (and it has been...turned out I've just slacked off from it. I thought there were blockers). I'll get to it this weekend.

**Comment by rhaschke** [comment]
I think #1000 was mainly addressing Kinetic/Melodic blockers - despite the original issue title ;-)

**Comment by davetcoleman** [comment]
Indeed, this issue was suppose to just be about releasing kinetic.

@130s let's get that released! :-)

**Comment by 130s** [comment]
Sorry to keep this pushed back. Will be done by WMD 2018.

**Comment by davetcoleman** [comment]
friendly ping @130s

**Comment by 130s** [comment]
Please hold backport to Indigo as I'm planning to make a release into Indigo very soon (I doubt there are maintainers who do this though).

**Comment by 130s** [comment]
Done https://github.com/ros/rosdistro/pull/19320

**Comment by 130s** [comment]
https://github.com/ros/rosdistro/pull/19320 is closed due to the pre-release test failure https://github.com/ros-planning/moveit/issues/1106.

**Comment by 130s** [comment]
Steps to do to make this release happen:
- [ ] Resolve circular dependency -> PR https://github.com/ros-planning/moveit/pull/1111
- [ ] Update rosdistro indigo about the moveit_full_pr2 relocation (currently its [in moveit](https://github.com/ros/rosdistro/blob/d578284e09cfefefa780b6f06d7ae5767d33b58a/indigo/distribution.yaml#L7461) section).
  - While this can be done either by making release of moveit indigo, cleanest is to open a PR to rosdistro to just update the location and nothing else. Once that's done, nothing further shouldn't be neeed regarding moveit_full_pr2 location (no version update for moveit_full_pr2 so no new release shouldn't be needed, unless we want to weave in the information about relocation explicitly in the release info).
- [ ] Make Indigo release from moveit repo.

**Comment by 130s** [comment]
Done https://github.com/ros/rosdistro/pull/19347
