### ISSUE TITLE
Enable to run path planning !! RVIZ

### ISSUE THREAD

**Issue by zubair123khan** [ros-planning/moveit#1016]
### Description
Hello all

I am unable to load the map from ardrone_testworld.launch in RVIZ. 
Please see the attached sreenshot from RVIZ, and please guide me whats missing !

Thanks

### Your environment
* ROS Distro: [Kinetic]
* OS Version: Ubuntu 16.04

![rviz](https://user-images.githubusercontent.com/17492699/43680242-a889e074-982d-11e8-98a3-7b792321a145.png)

**Comment by davetcoleman** [comment]
Agreed, this issue is too problem specific and lacks actionable details
