### ISSUE TITLE
ROS Lint Packages

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#102]
Cleanup the code base by using [roslint](http://wiki.ros.org/roslint):

> CMake lint commands for ROS packages. The lint commands perform static checking of Python or C++ source code for errors and standards compliance.

Start with just one package (moveit_core?) so that you can get feedback from the maintainers and try to keep each PR small.

**Comment by v4hn** [comment]
duplicate of #34

**Comment by davetcoleman** [comment]
``catkin lint`` and ``ros lint`` are two separate things! AFAIK the former only helps cleanup your CMake files, while the latter cleans up your code

**Comment by gavanderhoorn** [comment]
@davetcoleman: yep. `catkin_lint` 'only' checks `package.xml` and `CMakeLists.txt`.

**Comment by v4hn** [comment]
Ah, right, sorry I missed that. Haven't used roslint in quite a while, so I was primed to `catkin_lint`..

Sounds like a lot of work, that would improve MoveIt!

**Comment by davetcoleman** [comment]
Closing this in light of moveit2 development.

**Comment by v4hn** [comment]
I don't feel strongly about these issues, but I don't see the connection to MoveIt ROS2 development.

**Comment by davetcoleman** [comment]
The more optional "cleanup" type tasks we do in moveit1, the harder it will be to sync forward to moveit2.

**Comment by v4hn** [comment]
I do see your line of argument, but I am not convinced this is sufficient
to argue against cleanup patches.

Let's briefly address this in the maintainer meeting later today, if time allows.
