### ISSUE TITLE
floating joints not initialized correctly in moveit_ros_visualization/PlanningScene-display

### ISSUE THREAD

**Issue by xaver-k** [ros-planning/moveit#1044]
### Description

When using floating joints and the `moveit_ros_visualization/PlanningScene`-display in Rviz, the transformation for the floating joints is not displayed correctly until we change a 1-DOF joint.

In most cases, it looks like the visualized robot model is offset to what TF and RobotModel are showing. 

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04
* Source, git commit 5f04de1babb2ee37047daedaada18d4d0399bd50 (latest available kinetic-devel)

### Steps to reproduce

See the example-setup in this package for the steps to reproduce:
https://github.com/xaver-k/rviz_plugin_offset_test

### Expected behaviour
The floating joint transformation should be correct right after initialization of the display panel.

### Notes

I think that this behavior has something to do with how the transforms of floating joints are updated in the 
`CurrentStateMonitor`. The floating joints updated via `CurrentStateMonitor::tfCallback()`, which is only called when `CurrentStateMonitor::jointStateCallback()` detects that a 1DOF-joint has **changed**.

If I just apply the following patch, which triggers `tfCallback()` on every joint state callback, everything looks like it works properly:
[update_change.patch](https://github.com/ros-planning/moveit/files/2343302/update_change.patch.txt) ( (change the extension from .txt to .patch, Github won't accept .patch as an upload file format).

**Comment by felixvd** [comment]
Fixed by #984.
