### ISSUE TITLE
RobotState Display broken on DE locale on melodic

### ISSUE THREAD

**Issue by simonschmeisser** [ros-planning/moveit#1050]
### Description

I just finished an experimental port of our software to Melodic/Bionic. The RobotState rviz plugin unfortunately shows all positions of links as "0 0 0". All links of the robot are also displayed centered at the origin. Colors also fail for unknown reasons.
![screenshot_20180906_141027](https://user-images.githubusercontent.com/372442/45156694-30d6b180-b1df-11e8-8e2b-05d48464d31e.png)
 If I set the locale to "c" (i.e. no locale) instead of "de_DE.UTF-8" it works as expected. So somewhere locale sensitive text to number conversion seems to be used (or rviz does "input" validation?) as "0.123" is not a valid number in German (we use "0,123" mainly to annoy programmers)

### Your environment
* ROS Distro: melodic
* OS Version: Ubuntu 18.04
* Source or Binary build? Binary
* If binary, which release version? MoveIt! 0.10.01-0bionic.20180807
 rviz: 1.13.1-0bionic.20180807
* If source, which git commit or tag?

### Steps to reproduce
  LANG=de_DE.UTF-8 rviz

add RobotState display, observe

  LANG=c rviz

now works as expected

**Comment by gavanderhoorn** [comment]
This is probably https://github.com/ros/urdfdom_headers/issues/41.

Note also https://github.com/ros/urdfdom_headers/issues/45.

**Comment by simonschmeisser** [comment]
I filed an Ubuntu bug report asking for an update, you can vote there by clicking "this bug affects me":

https://bugs.launchpad.net/ubuntu/+source/urdfdom-headers/+bug/1817595
