### ISSUE TITLE
Get joint values from SRDF

### ISSUE THREAD

**Issue by keerthanamanivannan** [ros-planning/moveit#1063]
### Description

Get joint values specified in the `group_state` in the SRDF in moveit_config

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04
* Binary Build
* Binary release version: 0.9.12-Alpha

I realize that this is not an issue per se, but more of a question. I posted in answers.ros.org and I haven't gotten any replies, thus I am posting here. 

Say, I have three poses of robot described in the robot SRDF. How would I access these values with a moveit_commander instance?

@gavanderhoorn @v4hn 

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by keerthanamanivannan** [comment]
ok, I see that `get_named_target_values` haven't been exposed in [here](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_commander/src/moveit_commander/move_group.py). I guess I can expose it and make a PR or something.

**Comment by rhaschke** [comment]
Yes, you are welcome to file a PR.

**Comment by simonschmeisser** [comment]
@rhaschke @keerthanamanivannan can be closed right?

**Comment by rhaschke** [comment]
Yep. The PR is merged. Thanks for checking.
