### ISSUE TITLE
IK failed, Manipulation plan failed at stage 'reachable & valid pose filter' 

### ISSUE THREAD

**Issue by AIWintermuteAI** [ros-planning/moveit#1064]
### Description

I'm using MoveIt to control 4-DOF robotic arm I built myself. The first stage is documented here 
https://steemit.com/robot/@wintermuteai/ros-moveit-robotic-arm
I'm at the second stage now, where I'm trying to use Python API for pick and place pipeline. First the arm goes to the pre-grasp pose using set_pose_target command, which arm can execute 80 percent of the time.
But pick operation always fails with following error:

[ WARN] [1537283456.419090736]: All supplied grasps failed. Retrying last grasp in verbose mode.
[ INFO] [1537283456.419349063]: Re-added last failed plan for pipeline 'pick'. Queue is now of size 1
[ INFO] [1537283456.425039540]: IK failed
[ INFO] [1537283456.432710067]: IK failed
[ INFO] [1537283456.441817085]: IK failed
[ INFO] [1537283456.441934449]: Sampler failed to produce a state
[ INFO] [1537283456.442002976]: Manipulation plan 8 failed at stage 'reachable & valid pose filter' on thread 0

### Your environment
* ROS Distro: [Kinetic]
* OS Version: e.g. Ubuntu 16.04
*  Binary

### Steps to reproduce
Here's my urdf file 

```
<robot name="test_robot">
  <link name="base_cylinder">
	<visual>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/base_cylinder.stl" scale ="0.001 0.001 0.001"/>
         </geometry>
        </visual>
        <collision>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/base_cylinder.stl" scale ="0.001 0.001 0.001"/>
         </geometry>
        </collision>
  </link>

  <link name="platform">
	<visual>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/top_plate.stl"/>
         </geometry>
        </visual>
        <collision>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/top_plate.stl"/>
         </geometry>
        </collision>
  </link>

  <link name="lower_arm">
	<visual>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/lower_arm.stl"/>
         </geometry>
        </visual>
        <collision>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/lower_arm.stl"/>
         </geometry>
        </collision>
  </link>

  <link name="upper_arm">
	<visual>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/top_arm.stl"/>
         </geometry>
        </visual>
        <collision>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/top_arm.stl"/>
         </geometry>
        </collision>
  </link>

  <link name="wrist">
	<visual>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/wrist.stl"/>
         </geometry>
        </visual>
        <collision>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/wrist.stl"/>
         </geometry>
        </collision>
  </link>

  <link name="claw_base">
	<visual>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/clawbase.stl"/>
         </geometry>
        </visual>
        <collision>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/clawbase.stl"/>
         </geometry>
        </collision>
  </link>

  <link name="claw_l">
	<visual>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/clawl.stl"/>
         </geometry>
        </visual>
        <collision>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/clawl.stl"/>
         </geometry>
        </collision>
  </link>

  <link name="claw_r">
	<visual>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/clawr.stl"/>
         </geometry>
        </visual>
        <collision>
         <geometry>
          <mesh filename="package://urdf_tutorial/meshes/clawr.stl"/>
         </geometry>
        </collision>
  </link>

  <joint name="joint1" type="revolute">
    <axis xyz="0 0 1" />
    <limit effort="1000.0" lower="-1.708" upper="1.708" velocity="1.0" />
    <parent link="base_cylinder"/>
    <child link="platform"/>
  </joint>

  <joint name="joint2" type="revolute">
    <axis xyz="-1 0 0" />
    <limit effort="1000.0" lower="-1.708" upper="1.708" velocity="1.0" />
    <origin xyz="0 0 0.093" rpy="0 0 0" />
    <parent link="platform"/>
    <child link="lower_arm"/>
  </joint>

  <joint name="joint3" type="revolute">
    <axis xyz="1 0 0" />
    <limit effort="1000.0" lower="-1.708" upper="1.708" velocity="1.0" />
    <origin xyz="0 0 0.121" rpy="0 0 0" />
    <parent link="lower_arm"/>
    <child link="upper_arm"/>
  </joint>

  <joint name="joint4" type="revolute">
    <axis xyz="-1 0 0" />
    <limit effort="1000.0" lower="-1.708" upper="1.708" velocity="1.0" />
    <origin xyz="0 0 0.112" rpy="0 0 0" />
    <parent link="upper_arm"/>
    <child link="wrist"/>
  </joint>

  <joint name="joint5" type="fixed">
    <axis xyz="-1 0 0" />
    <origin xyz="0 0 0.112" rpy="0 0 0" />
    <parent link="wrist"/>
    <child link="claw_base"/>
  </joint>

  <joint name="joint6" type="revolute">
    <axis xyz="0 1 0" />
    <limit effort="1000.0" lower="-0.15" upper="0.30" velocity="1.0" />
    <origin xyz="-0.027 0 0" rpy="0 0 0" />
    <parent link="claw_base"/>
    <child link="claw_l"/>
  </joint>

  <joint name="joint7" type="revolute">
    <axis xyz="0 -1 0" />
    <limit effort="1000.0" lower="-0.15" upper="0.30" velocity="1.0" />
    <origin xyz="-0.027 0 0" rpy="0 0 0" />
    <parent link="claw_base"/>
    <child link="claw_r"/>
  </joint>

</robot>
```
SRDF file generated with MoveIt setup assistant
```

> <robot name="test_robot">
>     <!--GROUPS: Representation of a set of joints and links. This can be useful for specifying DOF to plan for, defining arms, end effectors, etc-->
>     <!--LINKS: When a link is specified, the parent joint of that link (if it exists) is automatically included-->
>     <!--JOINTS: When a joint is specified, the child link of that joint (which will always exist) is automatically included-->
>     <!--CHAINS: When a chain is specified, all the links along the chain (including endpoints) are included in the group. Additionally, all the joints that are parents to included links are also included. This means that joints along the chain and the parent joint of the base link are included in the group-->
>     <!--SUBGROUPS: Groups can also be formed by referencing to already defined group names-->
>     <group name="gripper">
>         <link name="claw_l" />
>         <link name="claw_r" />
>         <joint name="joint6" />
>         <joint name="joint7" />
>     </group>
>     <group name="arm">
>         <chain base_link="base_cylinder" tip_link="claw_base" />
>     </group>
>     <!--GROUP STATES: Purpose: Define a named state for a particular group, in terms of joint values. This is useful to define states like 'folded arms'-->
>     <group_state name="open" group="gripper">
>         <joint name="joint6" value="0.3" />
>         <joint name="joint7" value="0.3" />
>     </group_state>
>     <group_state name="default" group="arm">
>         <joint name="joint1" value="0" />
>         <joint name="joint2" value="0" />
>         <joint name="joint3" value="0" />
>         <joint name="joint4" value="0" />
>     </group_state>
>     <!--END EFFECTOR: Purpose: Represent information about an end effector.-->
>     <end_effector name="gripper" parent_link="claw_base" group="gripper" parent_group="arm" />
>     <!--VIRTUAL JOINT: Purpose: this element defines a virtual joint between a robot link and an external frame of reference (considered fixed with respect to the robot)-->
>     <virtual_joint name="virtual_joint" type="fixed" parent_frame="fixed_frame" child_link="base_cylinder" />
>     <!--DISABLE COLLISIONS: By default it is assumed that any link of the robot could potentially come into collision with any other link in the robot. This tag disables collision checking between a specified pair of links. -->
>     <disable_collisions link1="base_cylinder" link2="lower_arm" reason="Never" />
>     <disable_collisions link1="base_cylinder" link2="platform" reason="Adjacent" />
>     <disable_collisions link1="claw_base" link2="claw_l" reason="Adjacent" />
>     <disable_collisions link1="claw_base" link2="claw_r" reason="Adjacent" />
>     <disable_collisions link1="claw_base" link2="lower_arm" reason="Never" />
>     <disable_collisions link1="claw_base" link2="platform" reason="Never" />
>     <disable_collisions link1="claw_base" link2="upper_arm" reason="Never" />
>     <disable_collisions link1="claw_base" link2="wrist" reason="Adjacent" />
>     <disable_collisions link1="claw_l" link2="claw_r" reason="Default" />
>     <disable_collisions link1="claw_l" link2="lower_arm" reason="Never" />
>     <disable_collisions link1="claw_l" link2="platform" reason="Never" />
>     <disable_collisions link1="claw_l" link2="upper_arm" reason="Never" />
>     <disable_collisions link1="claw_l" link2="wrist" reason="Never" />
>     <disable_collisions link1="claw_r" link2="lower_arm" reason="Never" />
>     <disable_collisions link1="claw_r" link2="platform" reason="Never" />
>     <disable_collisions link1="claw_r" link2="upper_arm" reason="Never" />
>     <disable_collisions link1="claw_r" link2="wrist" reason="Never" />
>     <disable_collisions link1="lower_arm" link2="platform" reason="Adjacent" />
>     <disable_collisions link1="lower_arm" link2="upper_arm" reason="Adjacent" />
>     <disable_collisions link1="lower_arm" link2="wrist" reason="Never" />
>     <disable_collisions link1="platform" link2="upper_arm" reason="Never" />
>     <disable_collisions link1="platform" link2="wrist" reason="Never" />
>     <disable_collisions link1="upper_arm" link2="wrist" reason="Adjacent" />
> </robot>
```

Python code for pick operation 
```
import rospy, sys
import moveit_commander
from geometry_msgs.msg import PoseStamped, Pose
from moveit_commander import MoveGroupCommander, PlanningSceneInterface
from moveit_msgs.msg import PlanningScene, ObjectColor
from moveit_msgs.msg import Grasp, GripperTranslation, MoveItErrorCodes

from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from tf.transformations import quaternion_from_euler
from copy import deepcopy

GROUP_NAME_ARM = 'arm'
GROUP_NAME_GRIPPER = 'gripper'

GRIPPER_FRAME = 'claw_base'

GRIPPER_OPEN = [0.3,0.3]
GRIPPER_CLOSED = [0.0,0.0]
GRIPPER_NEUTRAL = [0.009,0.009]
GRIPPER_GRASP = [0.017,0.017]

GRIPPER_JOINT_NAMES = ['joint6','joint7']

GRIPPER_EFFORT = [1.0]

REFERENCE_FRAME = 'base_cylinder'

class MoveItDemo:
    def __init__(self):
        # Initialize the move_group API
        moveit_commander.roscpp_initialize(sys.argv)
        
        rospy.init_node('moveit_demo')
        
        # Use the planning scene object to add or remove objects
        scene = PlanningSceneInterface()
        
        # Create a scene publisher to push changes to the scene
        self.scene_pub = rospy.Publisher('planning_scene', PlanningScene, queue_size=5)
        
        # Create a publisher for displaying gripper poses
        self.gripper_pose_pub = rospy.Publisher('gripper_pose', PoseStamped, queue_size=5)
        
        # Create a dictionary to hold object colors
        self.colors = dict()
                        
        # Initialize the move group for the right arm
        right_arm = MoveGroupCommander(GROUP_NAME_ARM)
        
        # Initialize the move group for the right gripper
        right_gripper = MoveGroupCommander(GROUP_NAME_GRIPPER)
        
        # Get the name of the end-effector link
        end_effector_link = right_arm.get_end_effector_link()
 
        # Allow some leeway in position (meters) and orientation (radians)
        #right_arm.set_goal_position_tolerance(0.05)
        #right_arm.set_goal_orientation_tolerance(0.1)

        # Allow replanning to increase the odds of a solution
        right_arm.allow_replanning(True)
        
        # Set the right arm reference frame
        #right_arm.set_pose_reference_frame(REFERENCE_FRAME)
        
        # Allow 5 seconds per planning attempt
        right_arm.set_planning_time(3)
        
        # Set a limit on the number of pick attempts before bailing
        max_pick_attempts = 5
        
        # Set a limit on the number of place attempts
        max_place_attempts = 5
                
        # Give the scene a chance to catch up
        rospy.sleep(2)



   
        # clean the scene
        scene.remove_world_object("table")
        scene.remove_world_object("part")
        
        # Remove any attached objects from a previous session
        scene.remove_attached_object(GRIPPER_FRAME, "part")
        
        # Give the scene a chance to catch up    
        rospy.sleep(1)
        
        # Start the arm in the "grasp" pose stored in the SRDF file
        right_arm.set_named_target('default')
        right_arm.go()
        
        # Open the gripper to the neutral position
        right_gripper.set_joint_value_target(GRIPPER_OPEN)
        right_gripper.go()
       
        rospy.sleep(1)


        place_pose = PoseStamped()
        place_pose.header.frame_id = REFERENCE_FRAME
        place_pose.pose.position.x = 0.170
        place_pose.pose.position.y = 0.045
        place_pose.pose.position.z = 0.3
        scene.add_box("part", place_pose, (0.07, 0.01, 0.2))
        
        # Specify a pose to place the target after being picked up
        target_pose = PoseStamped()
        target_pose.header.frame_id = REFERENCE_FRAME
        # start the gripper in a neutral pose part way to the target
        target_pose.pose.position.x = 0.0733923763037
        target_pose.pose.position.y = 0.0129100652412
        target_pose.pose.position.z = 0.3097191751
        target_pose.pose.orientation.x = -0.524236500263
        target_pose.pose.orientation.y = 0.440069645643
        target_pose.pose.orientation.z = -0.468739062548
        target_pose.pose.orientation.w = 0.558389186859


        # Initialize the grasp pose to the target pose
        grasp_pose = target_pose
	print("going to start pose")
	right_arm.set_pose_target(target_pose)
        right_arm.go()

        rospy.sleep(2)

        
        # Shift the grasp pose by half the width of the target to center it
        #grasp_pose.pose.position.y -= target_size[1] / 2.0
        #grasp_pose.pose.position.x = 0.12792118579
        #grasp_pose.pose.position.y = -0.285290879999
        #grasp_pose.pose.position.z = 0.120301181892
                
        # Generate a list of grasps
        grasps = self.make_grasps(grasp_pose, 'part')

        # Publish the grasp poses so they can be viewed in RViz
        print "Publishing grasps"
        for grasp in grasps:
            self.gripper_pose_pub.publish(grasp.grasp_pose)
            rospy.sleep(0.2)

        # Track success/failure and number of attempts for pick operation
        result = None
        n_attempts = 0
        
        # Repeat until we succeed or run out of attempts
        while result != MoveItErrorCodes.SUCCESS and n_attempts < max_pick_attempts:
            n_attempts += 1
            rospy.loginfo("Pick attempt: " +  str(n_attempts))
            result = right_arm.pick('part', grasps)
            rospy.sleep(0.2)
        
        # If the pick was successful, attempt the place operation   
        if result == MoveItErrorCodes.SUCCESS:
            result = None
            n_attempts = 0
            
            # Generate valid place poses
            places = self.make_places(place_pose)
            
            # Repeat until we succeed or run out of attempts
            while result != MoveItErrorCodes.SUCCESS and n_attempts < max_place_attempts:
                n_attempts += 1
                rospy.loginfo("Place attempt: " +  str(n_attempts))
                for place in places:
                    result = right_arm.place('part', place)
                    if result == MoveItErrorCodes.SUCCESS:
                        break
                rospy.sleep(0.2)
                
            if result != MoveItErrorCodes.SUCCESS:
                rospy.loginfo("Place operation failed after " + str(n_attempts) + " attempts.")
            else:
                # Return the arm to the "resting" pose stored in the SRDF file
                right_arm.set_named_target('right_arm_rest')
                right_arm.go()
                
                # Open the gripper to the open position
                right_gripper.set_joint_value_target(GRIPPER_OPEN)
                right_gripper.go()
        else:
            rospy.loginfo("Pick operation failed after " + str(n_attempts) + " attempts.")

        rospy.sleep(1)

        # Shut down MoveIt cleanly
        moveit_commander.roscpp_shutdown()
        
        # Exit the script
        moveit_commander.os._exit(0)
        
    # Get the gripper posture as a JointTrajectory
    def make_gripper_posture(self, joint_positions):
        # Initialize the joint trajectory for the gripper joints
        t = JointTrajectory()
        
        # Set the joint names to the gripper joint names
        t.joint_names = GRIPPER_JOINT_NAMES
        
        # Initialize a joint trajectory point to represent the goal
        tp = JointTrajectoryPoint()
        
        # Assign the trajectory joint positions to the input positions
        tp.positions = joint_positions
        
        # Set the gripper effort
        tp.effort = GRIPPER_EFFORT
        
        tp.time_from_start = rospy.Duration(1.0)
        
        # Append the goal point to the trajectory points
        t.points.append(tp)
        
        # Return the joint trajectory
        return t
    
    # Generate a gripper translation in the direction given by vector
    def make_gripper_translation(self, min_dist, desired, vector):
        # Initialize the gripper translation object
        g = GripperTranslation()
        
        # Set the direction vector components to the input
        g.direction.vector.x = vector[0]
        g.direction.vector.y = vector[1]
        g.direction.vector.z = vector[2]
        
        # The vector is relative to the gripper frame
        g.direction.header.frame_id = GRIPPER_FRAME
        
        # Assign the min and desired distances from the input
        g.min_distance = min_dist
        g.desired_distance = desired
        
        return g

    # Generate a list of possible grasps
    def make_grasps(self, initial_pose_stamped, allowed_touch_objects):
        # Initialize the grasp object
        g = Grasp()
        
        # Set the pre-grasp and grasp postures appropriately
        g.pre_grasp_posture = self.make_gripper_posture(GRIPPER_OPEN)
        g.grasp_posture = self.make_gripper_posture(GRIPPER_GRASP)
                
        # Set the approach and retreat parameters as desired
        g.pre_grasp_approach = self.make_gripper_translation(0.01, 0.1, [0, 0, -1.0])
        g.post_grasp_retreat = self.make_gripper_translation(0.1, 0.15, [0, 0, 1.0])
        
        # Set the first grasp pose to the input pose
        g.grasp_pose = initial_pose_stamped
    
        ideal_roll = 0
        ideal_pitch = 0
        ideal_yaw = -1.57
        
        step_size = 0.1
        idx = 0.1
        idx_roll = ideal_roll + idx
        idx_pitch = ideal_pitch + idx
        idx_yaw = ideal_yaw + idx
        roll_vals = []
        pitch_vals = []
        yaw_vals = []
        while idx >= -0.1:
            roll_vals.append(idx_roll)
            pitch_vals.append(idx_pitch)
            yaw_vals.append(idx_yaw)
            idx -= step_size
            idx_roll -= step_size
            idx_pitch -= step_size
            idx_yaw -= step_size

        # A list to hold the grasps
        grasps = []
        
        print "Generating Poses"
        
        # Generate a grasp for each roll pitch and yaw angle
        for r in roll_vals:
            for y in yaw_vals:
                for p in pitch_vals:
                    # Create a quaternion from the Euler angles
                    q = quaternion_from_euler(r, p, y)
                    
                    # Set the grasp pose orientation accordingly
                    g.grasp_pose.pose.orientation.x = q[0]
                    g.grasp_pose.pose.orientation.y = q[1]
                    g.grasp_pose.pose.orientation.z = q[2]
                    g.grasp_pose.pose.orientation.w = q[3]
                    
                    # Set and id for this grasp (simply needs to be unique)
                    g.id = str(len(grasps))
                    
                    # Set the allowed touch objects to the input list
                    g.allowed_touch_objects = allowed_touch_objects
                    
                    # Don't restrict contact force
                    g.max_contact_force = 0
                    
                    # Degrade grasp quality for increasing pitch angles
                    g.grasp_quality = 1.0 - abs(p)
                    
                    # Append the grasp to the list
                    grasps.append(deepcopy(g))
                    
        print "Generated " + g.id + " poses"
        # Return the list
        return grasps
    
    # Generate a list of possible place poses
    def make_places(self, init_pose):
        # Initialize the place location as a PoseStamped message
        place = PoseStamped()
        
        # Start with the input place pose
        place = init_pose
        
        # A list of x shifts (meters) to try
        x_vals = [0, 0.005, 0.01, 0.015, -0.005, -0.01, -0.015]
        
        # A list of y shifts (meters) to try
        y_vals = [0, 0.005, 0.01, 0.015, -0.005, -0.01, -0.015]
        
        pitch_vals = [0, 0.1, -0.1, 0.2, -0.2, 0.3, -0.3]
        
        # A list of yaw angles to try
        yaw_vals = [0, 0.1, -0.1, 0.2, -0.2, 0.3, -0.3]

        # A list to hold the places
        places = []
        
        # Generate a place pose for each angle and translation
        for y in yaw_vals:
            for p in pitch_vals:
                for y in y_vals:
                    for x in x_vals:
                        place.pose.position.x = init_pose.pose.position.x + x
                        place.pose.position.y = init_pose.pose.position.y + y
                        
                        # Create a quaternion from the Euler angles
                        q = quaternion_from_euler(0, p, y)
                        
                        # Set the place pose orientation accordingly
                        place.pose.orientation.x = q[0]
                        place.pose.orientation.y = q[1]
                        place.pose.orientation.z = q[2]
                        place.pose.orientation.w = q[3]
                        
                        # Append this place pose to the list
                        places.append(deepcopy(place))
        
        # Return the list
        return places
    
    # Set the color of an object
    def setColor(self, name, r, g, b, a = 0.9):
        # Initialize a MoveIt color object
        color = ObjectColor()
        
        # Set the id to the name given as an argument
        color.id = name
        
        # Set the rgb and alpha values given as input
        color.color.r = r
        color.color.g = g
        color.color.b = b
        color.color.a = a
        
        # Update the global color dictionary
        self.colors[name] = color

    # Actually send the colors to MoveIt!
    def sendColors(self):
        # Initialize a planning scene object
        p = PlanningScene()

        # Need to publish a planning scene diff        
        p.is_diff = True
        
        # Append the colors from the global color dictionary 
        for color in self.colors.values():
            p.object_colors.append(color)
        
        # Publish the scene diff
        self.scene_pub.publish(p)

if __name__ == "__main__":
    MoveItDemo()
```
### Expected behaviour
Robot arm going to pre-grasp pose and then grasping an object

### Actual behaviour
Arm going to pre-grasp pose and then failing to execute all the grasps provided by grasp generator. 
A few guesses:
1)I saw people having issues with less than 6-DOF arms using KDL kinematics solver. I've tried Trac-IK with the same results. I also want to pay attention that my arm can move to different poses using RVIZ interactive markers, but the strange thing is, after joint2 or joint3 moved from the default angle I cannot rotate the robot platform(base_cylinder) with interactive markers anymore without swtiching on the "Allow approximate IK solutions" option.
2)There's no IK solver for gripper which is two revolute type joints. Can that be an issue? 

I would appreciate any help, that could move me in the right direction.

### Backtrace or Console output

[ WARN] [1537283456.419090736]: All supplied grasps failed. Retrying last grasp in verbose mode.
[ INFO] [1537283456.419349063]: Re-added last failed plan for pipeline 'pick'. Queue is now of size 1
[ INFO] [1537283456.425039540]: IK failed
[ INFO] [1537283456.432710067]: IK failed
[ INFO] [1537283456.441817085]: IK failed
[ INFO] [1537283456.441934449]: Sampler failed to produce a state
[ INFO] [1537283456.442002976]: Manipulation plan 8 failed at stage 'reachable & valid pose filter' on thread 0

**Comment by v4hn** [comment]
(1) You don't have to go to a pre-grasp pose yourself with the pick-pipeline, it should take care of that

(2) Inverse kinematics for your grasp failed, so the grasp you specify cannot be reached by your gripper - or your IK solver at least thinks so

(3) The Pipeline expects to be able to do Cartesian movements along the retreat and approach directions. This might be a problem with only 4DOF (it depends on your request and the arm kinematics of course)

**Comment by AIWintermuteAI** [comment]
1) Okay. I saw it in the tutorial and many people seem to specify the pre-grasp pose, so I assumed it's necessary. If not, even better.
2) Any way to check the location of grasps? Maybe with markers in RVIZ?
3)That might be an issue, because as I mentioned arm kinematics does seem to be a little weird with KDL and TracIK plugins. I guess I'll have to generate IKfast plugin... Any idea which kinematics solver to use with 4 DOF? 

    Transform6D - end effector reaches desired 6D transformation
    Rotation3D - end effector reaches desired 3D rotation
    Translation3D - end effector origin reaches desired 3D translation
    Direction3D - direction on end effector coordinate system reaches desired direction
    Ray4D - ray on end effector coordinate system reaches desired global ray
    Lookat3D - direction on end effector coordinate system points to desired 3D position
    TranslationDirection5D - end effector origin and direction reaches desired 3D translation and direction. Can be thought of as Ray IK where the origin of the ray must coincide.
    TranslationXY2D - end effector origin reaches desired XY translation position, Z is ignored. The coordinate system with relative to the base link.
    TranslationLocalGlobal6D - local point on end effector origin reaches desired 3D global point. Because both local point and global point can be specified, there are 6 values.
    TranslationXAxisAngle4D, TranslationYAxisAngle4D, TranslationZAxisAngle4D - end effector origin reaches desired 3D translation, manipulator direction makes a specific angle with x/y/z-axis (defined in the manipulator base link’s coordinate system)

I've tried Transform6D and it says my arm is < 6 DOF....

**Comment by v4hn** [comment]
1. You have to *specify* it implicitly in the Grasp message, but you don't have to move the robot there before grasping.

2. We are currently working on [a replacement for this pipeline](https://github.com/ros-planning/moveit_task_constructor). It's not as straight-forward to use as the pick function yet, but visualizes a lot of useful feedback ootb. There will be a talk about it in two weeks at ROSCon (recording will be made available afterwards).

3. This is not a problem in MoveIt anymore, so I will close this issue. Please post a question on [ros answers](https://answers.ros.org) that also includes a picture/kinematic schema of your robot and hopefully someone can help you there.

**Comment by smarthhy** [comment]
@AIWintermuteAI 
Hi,
Have you solved this problem? Thanks

**Comment by AIWintermuteAI** [comment]
I went another way and used Grasp Pose Detection (GPD) package for obtaining the grasp pose from point cloud. I improved IK success rate by adding one more degree of freedom. But it still fails in about 20% of cases, which I solve iterating fast through the grasps and finding the one that works

**Comment by saitejaallam** [comment]
@AIWintermuteAI 
Hi,
I am using open manipulator mounted on the turtlebot3 waffle pi to perform the pick and place demo. I came across the same issue as you have faced. Here is my output from the console.

> [ WARN] [1594306947.954874050, 116.642000000]: All supplied grasps failed. Retrying last grasp in verbose mode.
[ INFO] [1594306947.955223575, 116.642000000]: Re-added last failed plan for pipeline 'pick'. Queue is now of size 1
[ INFO] [1594306947.963400818, 116.650000000]: IK failed
[ INFO] [1594306947.972309928, 116.654000000]: IK failed
[ INFO] [1594306947.979752280, 116.662000000]: IK failed
[ INFO] [1594306947.980016702, 116.662000000]: Sampler failed to produce a state
[ INFO] [1594306947.980154410, 116.662000000]: Manipulation plan 0 failed at stage 'reachable & valid pose filter' on thread 0
[ INFO] [1594306947.980542898, 116.662000000]: Pickup planning completed after 0.071445 seconds

I am very eager to know the issue and solve it. Here is my code to run this demo.
`#!/usr/bin/env python

import sys
import rospy
from math import pi,radians, sqrt
from tf import transformations
from tf.transformations import quaternion_from_euler, euler_from_quaternion
from moveit_commander import RobotCommander, MoveGroupCommander
from moveit_commander import PlanningSceneInterface, roscpp_initialize, roscpp_shutdown
from geometry_msgs.msg import PoseStamped, Quaternion, Pose
import actionlib
from math import pi, radians, sqrt
from moveit_msgs.msg import Grasp, GripperTranslation, PlaceLocation, ExecuteTrajectoryGoal, ExecuteTrajectoryAction, ExecuteTrajectoryFeedback
from trajectory_msgs.msg import JointTrajectoryPoint

if __name__=='__main__':

    roscpp_initialize(sys.argv)
    rospy.init_node('demo', anonymous=True)
   
    #Use the planning scene object to add or remove objects
    scene = PlanningSceneInterface()
    robot = RobotCommander()

    arm = MoveGroupCommander("arm")
    gripper = MoveGroupCommander("gripper")
    #eef = arm.get_end_effector_link()
    #print "eef:",eef
    rospy.sleep(2)

    #started the action client to perform the action and wait for sometime to execute the subsequent operation
    #otherwise it throws a warning in the console

    arm_client = actionlib.SimpleActionClient('execute_trajectory',ExecuteTrajectoryAction)
    arm_client.wait_for_server()
    rospy.loginfo('Execute Trajectory server is available for arm')
  
    gripper_client = actionlib.SimpleActionClient('execute_trajectory',ExecuteTrajectoryAction)
    gripper_client.wait_for_server()
    rospy.loginfo('Execute Trajectory server is available for gripper')

    gripper_joint_values = gripper.get_current_joint_values()
    gripper_joint_values[0] = 0.018
    gripper_joint_values[1] = 0.0179
    gripper.set_joint_value_target(gripper_joint_values)
    plan = gripper.plan()
    print("plan executed")
    rospy.sleep(1)
    gripper.go(wait=True)
    rospy.sleep(1)

    # clean the scene
    scene.remove_world_object("table")
    scene.remove_world_object("part")

    arm.set_named_target("home")
    #arm.go()
    #arm.plan()
    arm_goal = ExecuteTrajectoryGoal()
    arm_goal.trajectory = arm.plan()
    #arm.execute(wait=True)

    #rospy.loginfo("reaching home position")

    arm_client.send_goal(arm_goal)
    arm_client.wait_for_result()

    #arm.set_planner_id("RRTConnectkConfigDefault")  #we can set the planning id here for motion planning
   
    # gripper.set_named_target("open")
    # gripper.go()
    # gripper.plan()
    #gripper.execute()

    #rospy.loginfo("gripper opened")
   
    rospy.sleep(1)

    # publish a demo scene
    p = PoseStamped()
    p.header.frame_id = robot.get_planning_frame()

    print("plannin frame:", p.header.frame_id)
    #p.header.frame_id = "base_link"

    # add a table
    p.pose.position.x = 0.2 #0.42
    p.pose.position.y = 0 # -0.2
    p.pose.position.z = 0
    scene.add_box("table", p, (0.1, 0.5, 0.1))   #(name, pose, dimensions)

    # add an object to be grasped
    p.pose.position.x = 0.2 #0.205
    p.pose.position.y = 0   #-0.12
    p.pose.position.z = 0.1   #0.7
    scene.add_box("part", p, (0.07, 0.01, 0.1))

    print "table and obj added"
   
    rospy.sleep(1)
   
    grasps = []
   
    g = Grasp()
    g.id = "pick_place"
    grasp_pose = PoseStamped()
    #print("grasp_pose", grasp_pose)
    grasp_pose.header.frame_id = "base_footprint"
    grasp_pose.pose.position.x = 0.2 #0.148554
    grasp_pose.pose.position.y = 0   #-0.116075
    grasp_pose.pose.position.z = 0.1 #0.70493

    # angle = radians(80) # angles are expressed in radians
    # quat = quaternion_from_euler(-angle/2, -angle/2, -angle/4) # roll, pitch, yaw
    # grasp_pose.pose.orientation = Quaternion(quat)

    ##The orientation/quaternion values shoudl be normalised for moveit
    grasp_pose.pose.orientation.x = -0.37232056 #-0.709103
    grasp_pose.pose.orientation.y = -0.26070166 #0.0137777
    grasp_pose.pose.orientation.z = -0.26853582 #0.0164031
    grasp_pose.pose.orientation.w = 0.84929415 #0.704779
   
    arm.set_pose_target(grasp_pose)    #Set the pose of the end-effector, if one is available. The expected input is a Pose message, a PoseStamped message or a list of 6 floats:
    #arm.go()

    arm_goal1 = ExecuteTrajectoryGoal()
    arm_goal1.trajectory = arm.plan()
    #arm.execute(wait=True)

    #rospy.loginfo("reaching home position")

    arm_client.send_goal(arm_goal1)
    arm_client.wait_for_result()
    #arm.plan()

    rospy.sleep(2)
   
    # set the grasp pose
    g.grasp_pose = grasp_pose
   
    # define the pre-grasp approach
    g.pre_grasp_approach.direction.header.frame_id = "base_footprint"  #This should be your gripper tool frame, since you usually want the
                                                                       #approach to happen along a specific axis of the gripper, not the base.

    g.pre_grasp_approach.direction.vector.x = 1.0
    g.pre_grasp_approach.direction.vector.y = 0.0
    g.pre_grasp_approach.direction.vector.z = 0.0
    g.pre_grasp_approach.min_distance = 0.05 #0.001
    g.pre_grasp_approach.desired_distance = 0.1
   
    g.pre_grasp_posture.header.frame_id = "base_footprint"
    g.pre_grasp_posture.joint_names = ["gripper"]
   
    pos = JointTrajectoryPoint()
    pos.positions.append(0.018)
   
    g.pre_grasp_posture.points.append(pos)
   
    # set the grasp posture
    g.grasp_posture.header.frame_id = "base_footprint"
    g.grasp_posture.joint_names = ["gripper"]

    pos = JointTrajectoryPoint()
    pos.positions.append(0.0)
    pos.effort.append(0.0)
   
    g.grasp_posture.points.append(pos)   ## needs clarification

    # set the post-grasp retreat
    g.post_grasp_retreat.direction.header.frame_id = "base_footprint"
    g.post_grasp_retreat.direction.vector.x = 0.0
    g.post_grasp_retreat.direction.vector.y = 0.0
    g.post_grasp_retreat.direction.vector.z = 1.0
    g.post_grasp_retreat.desired_distance = 0.25
    g.post_grasp_retreat.min_distance = 0.01

    #g.allowed_touch_objects = ["table"]
    g.allowed_touch_objects = ["part"]

    g.max_contact_force = 0
   
    # append the grasp to the list of grasps
    grasps.append(g)

    rospy.sleep(2)

    #interface = MoveGroupInterface("arm", "base_footprint", "move_group")
    #interface.setPlanningTime(45.0)
    result = False
    n_attempts = 0

    # pick the object
    while result == False:

        result = robot.arm.pick("part", grasps)
        n_attempts +=1
        print "Attempts:", n_attempts
        rospy.sleep(0.2)
    #print("gr:", grasps)
    rospy.loginfo("part found and picking")

    rospy.spin()
    roscpp_shutdown()
   `

Please help me in solving this issue. I am able to get the gripper open position and the arm moving to its home location specified in the code.
