### ISSUE TITLE
get_planning_scene with 0-component should return complete scene

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#1067]
Currently, the `/get_planning_scene` service returns an empty scene message when the request field has `components` set to 0. I believe it would be more useful if the service would return the *full* planning scene in this case.

It is cumbersome and error-prone to specify each and every bit (i.e. bitmask 1023) explicitly for each full call.

It should be validated throughout MoveIt whether we call the service like this in some context (although it does not make much sense...), because the ROS overhead would increase tremendously.

**Comment by gavanderhoorn** [comment]
> It is cumbersome and error-prone to specify each and every bit (i.e. bitmask 1023) explicitly for each full call.

`(~0) & 0x3FF`?

**Comment by j-petit** [comment]
I am taking this up.

**Comment by rhaschke** [comment]
Addressed in #1424
