### ISSUE TITLE
select planning group in planning tab

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#1069]
For a few years now, it frustrates me that the MotionPlanning display property is the only way to change the active planning group.
The user has to expand the properties of the display, expand the properties of "Planning Request" only to change the planning group property.

With multi-arm setups or setups that model the gripper as a planning group, this is very annoying.

I propose to add a drop-down menu to the "Query" box in the "Planning" tab of the panel right above "Select Start State:".
This should always have the value of the mentioned property, exposing it for easy access.

This issue requires previous insight into RViz programming to finish it in one day.

**Comment by felixvd** [comment]
I would even go as far as putting radio buttons underneath the "Plan&Execute" button instead of a dropdown menu. It could be a dropdown when 5+ groups exist, but I believe this is the exception. Radio buttons would save hundreds of clicks.

**Comment by v4hn** [comment]
The panel should remain compact and @davetcoleman spent some time in the past making it smaller.
So I'm not a big fan of radio buttons; it might make sense for up to 4 groups.

But then, I work with a robot with 12 planning groups, and thus apparently I'm the exception. :)
I believe your current robot setup should have at least 6 planning groups for your three arms+grippers,
possibly more to use multiple arms at once...
