### ISSUE TITLE
Eigen::Affine3d and SVD

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#1073]
As @Levi-Armstrong and @Jmeyer1292  just pointed out in their presentation at ROSCon, there is a nonsensical performance bottleneck in MoveIt at the moment because we use Affine3d (wrongly?).

Specifically, I just verified that calling [`Affine3d::rotation() const`](http://eigen.tuxfamily.org/dox/classEigen_1_1Transform.html#title59) actually computes SVD in the background.

We clearly want to change this.

Levi argued for `Eigen::Isometry3d` instead of `Eigen::Affine3d`. I agree that this makes sense in melodic.
Because we want to keep kinetic api stable though, can we get rid of `rotation()` in favor of `linear()` throughout the code base?

**Comment by skohlbr** [comment]
Oh, that's pretty ..interesting. Just came across https://github.com/dartsim/dart/issues/767 and https://github.com/flexible-collision-library/fcl/issues/317, which also contain related discussion (and same conclusion).

**Comment by rhaschke** [comment]
Fix provided in #1091.

**Comment by davetcoleman** [comment]
Glad you are pushing on this! Out of curiosity can we benchmark the performance difference?

**Comment by rhaschke** [comment]
> Out of curiosity can we benchmark the performance difference?

@Levi-Armstrong reported on some benchmarks as ROSCon, didn't he?

**Comment by v4hn** [comment]
I believe this has been resolved for a while now.
