### ISSUE TITLE
Save trajectory to file

### ISSUE THREAD

**Issue by grafoteka** [ros-planning/moveit#1077]
### Description

I would like to save the path that my end effector follows into a file.

![Path generated](https://user-images.githubusercontent.com/7115092/46549400-79919100-c897-11e8-9212-42e9e4694564.png)

As you can see in the picture, my intention is to save all the points that are drawn in RViz.

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04
* Source

### Steps to reproduce
[Here is the repo of the project.](https://github.com/grafoteka/Fotokite_arm)
The file that generates the path is in `moveit_tutorials/move_group_interface/src/fotokite_move_path.cpp`

For testing:
1.- `roslaunch fotokite_moveit demo.launch`
2.- `roslaunch moveit_tutorials fotokite_move_path.launch `

### Expected behaviour
It should save in a file (txt, for example) all the positions (transform from x, y, z) that has been calculated for the last link (link [6], finger).

### Actual behaviour
With: 
```
moveit_msgs::RobotTrajectory path_points;
path_points = trajectory;
std::stringstream ss;

for (unsigned i=0; i<size_trajectory; i++)
      {
        ss << "point_index: " << i << std::endl
           << "positions: "
           << "[" << path_points.joint_trajectory.points[i].positions[6]
           << "]" << std::endl;
      }
std::ofstream outfile ("/home/crasar/points.txt",std::ios::app);
if(!outfile.is_open())
{
    ROS_INFO("open failed");
}
else
{
     ROS_INFO("File open");
     outfile<<"trajectory"<<count<<std::endl;
     outfile<<path_points.joint_trajectory.joint_names[6]<<std::endl;
     outfile<<ss.str()<<std::endl;
     outfile.close();
}
```
I get all the points calculated, but I don't know what correspond to the value obtained:
point_index: 762
positions: [0.843665]

Also, I have try to get the values as:

`float variable = trajectory.multi_dof_joint_trajectory.points.at(0).transforms[0].translation.z;`

But when I execute it fails.

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
```

Thank you, 
Jorge

**Comment by BryceStevenWilley** [comment]
Hey Jorge. Looks like found the answer to this in your ROS Answers post (https://answers.ros.org/question/305133/trajectory-multidof-to-file/), so I'm going to close this issue as resolved.
