### ISSUE TITLE
Switch Sphinx Documentation Visual Theme

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#11]
Current one is visually outdated, would be nice to use something similar to how ReadTheDocs appears. A great starting point would be to copy Fetch's version of the ReadTheDocs theme https://github.com/fetchrobotics/docs/tree/master/source/_themes/sphinx_rtd_theme

The MoveIt! logo uses color #2ab2e6 so would be nice to sprinkle that in.

A huge bonus is that it would give us the "Edit On Github" button for free (top right [here](http://docs.fetchrobotics.com/))

**Comment by IanTheEngineer** [comment]
+1 for ReadTheDocs theme. It's modern, clean, and easy to navigate.

**Comment by davetcoleman** [comment]
I completed this, see http://docs.ros.org/kinetic/api/moveit_tutorials/html/
