### ISSUE TITLE
Test Tutorials and add more visuals / screenshots

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#111]
The consolidated the [moveit_tutorials](https://github.com/ros-planning/moveit_tutorials) have many pages without any images - currently only the Rviz Plugin tutorial and Setup Assistant really have visuals. It would be great if someone could run through the tutorials and take more screen shots of progress for tutorials that have no images.

**Comment by uwesterh** [comment]
I've already found some broken links in the tutorial pages. So I pick up this issue and will provide some screen shots for the tutorials in addition to the link fixes.

**Comment by uwesterh** [comment]
Most of the links are fixed now. For details, see my pull request at https://github.com/ros-planning/moveit_tutorials/pull/1

**Comment by davetcoleman** [comment]
Great! Did you find any good use cases for additional images?

**Comment by v4hn** [comment]
@uwesterh you showed me some pictures you embedded into the docs on Tuesday.
Why didn't you file a request to add them?

**Comment by v4hn** [comment]
The issue as posted for WMD is now deprecated. Closing.
testing tutorials is *always* welcome even without an issue.
