### ISSUE TITLE
Update README.md for Melodic

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#1112]
The root README.md needs updated CI build badges for Melodic, and lunar needs to be removed as its no longer supported. Easy task for World MoveIt! Day:

![image](https://user-images.githubusercontent.com/561060/47328153-2bb5b080-d62d-11e8-9676-96bf2f738487.png)

I've updated it in the past using this script:
https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit/scripts/create_maintainer_table.py

Feel free to rename the python script to be more relevant and make other tweaks to it. You'll want to use ``create_travis_badge`` in that script I think.

**Comment by Unemyr** [comment]
Starting to look into this...
