### ISSUE TITLE
[moveit_tutorials] Minor Cleanup

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#114]
Trivial laundry list of nice-to-haves that I wasn't able to get to today when refactoring moveit_tutorials:

- Edit on Github button is off center - bad css
- Warnings are generated when running ``rosdoc_lite .``
- Would be nice to move all ``pr2_tutorials`` from ``src/doc`` to just ``doc``
- Other cleanup items

**Comment by v4hn** [comment]
@davetcoleman could you update the state of this issue please? I believe you improved some of this already.

**Comment by davetcoleman** [comment]
I was think I'd just close this issue since it didn't get address on WMD and none of it is a big deal
