### ISSUE TITLE
Moving computeCartesianPath out of robot_state

### ISSUE THREAD

**Issue by mlautman** [ros-planning/moveit#1142]
I would like to (finally) move the Cartesian planner out of robot_state. Ideally it would live in it's own package at `moveit/moveit_planners/cartesian_planner` but as @davetcoleman pointed out, this may cause a circular dependencies. If we keep it in MoveIt! core, then we don't have the issues but it really doesn't belong there either.

**Comment by davetcoleman** [comment]
+1 to this cleanup

moving it into moveit_planners will be a very big effort that I don't think you want to do yet

**Comment by rhaschke** [comment]
Addressed in #1149.
