### ISSUE TITLE
Way of managing large octomap?

### ISSUE THREAD

**Issue by atyshka** [ros-planning/moveit#1184]
I'm experimenting with octomapping in moveit and I'm running into a problem: the octomap gets way too big, way too quickly. It's fine on the machine it's running on, but forget about trying to use a remote RViz for control. Everything is ridiculously slow and I'm wondering if there's any way to cut down on this data. As of now the only solution I have is clearing the octomap every five seconds which is pretty ridiculous. Subsampling doesn't help much, it cuts down on the data being added but the complete octomap is still enormous. Is there a way we could increase the voxel size in the octomap? Honestly it's a lot more resolution than I need. Also, for mobile robots, would it be possible to add partial clearing functionality that clears the parts of the octomap that are no longer near the robot?

**Comment by simonschmeisser** [comment]
There is a configuration option for voxel size. Also Octomaps can be "compressed", ie if all subcells of a cell are occupied then the whole cell can be marked as occupied (and thus the memory usage goes down). I'm not sure if that needs to be triggered manually (in octomap updater plugin)?

**Comment by atyshka** [comment]
@simonschmeisser I know moveit does compression, but it's very minimal. Flat surfaces usually only have one layer of cells in the octomap so it's rarely compressed. I know octomap offers a configuration for voxel size, but can this be adjusted in moveit through params or dynamic reconfigure or do I need to build from source? I haven't found anything yet.
