### ISSUE TITLE
Jacobian for PRISMATIC joint is wrong

### ISSUE THREAD

**Issue by ajsmilutin** [ros-planning/moveit#1191]
I've been trying to get Jacoiban matrix for a robot that has a `PRISMATIC` joint in the kinematic chain. When I've printed out the matrix obtained, I've seen  for a prismatic joint is `[-0.1133; -0.003852;  1.49086 ; 0; 0; 0]`
According to the theory, that can't be the case, since the norm of the top half ( -0.1133; -0.003852;  1.49086), has to be 1.  I've digged deeper into the code and found an issue here:
https://github.com/ros-planning/moveit/blob/1e7023ba1ea7733df2dc1229df022f770de96858/moveit_core/robot_state/src/robot_state.cpp#L1175
Where `Eigen::Affine3d` is multiplied by axis vector. In fact, axis should be multiplied only by rotation matrix as multiplied here:
https://github.com/ros-planning/moveit/blob/1e7023ba1ea7733df2dc1229df022f770de96858/moveit_core/robot_state/src/robot_state.cpp#L1167
So, my resolution to this bug is:
This line:
https://github.com/ros-planning/moveit/blob/1e7023ba1ea7733df2dc1229df022f770de96858/moveit_core/robot_state/src/robot_state.cpp#L1175
Should be:
`joint_axis = joint_transform.rotation() * static_cast<const robot_model::PrismaticJointModel*>(pjm)->getAxis();`

**Comment by rhaschke** [comment]
Resolved by #1192. Thanks for your efforts!
