### ISSUE TITLE
Auto check for deadlinks on moveit website using Travis CI

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#126]
Today @mintar found *a lot* of [dead links](https://github.com/ros-planning/moveit.ros.org/pull/43) that I think we can avoid in the future by using a simple travis script that is explained here:

https://www.jacobtomlinson.co.uk/jekyll/2015/02/18/test-you-jekyll-blog-with-travis-ci/

**Comment by mintar** [comment]
+1, that's what I was thinking should be next!

BTW, I also used a tool (called "linkchecker") to find those dead links. That script you found looks really good!

**Comment by mintar** [comment]
Here you go: ros-planning/moveit.ros.org#47

**Comment by v4hn** [comment]
continued in https://github.com/ros-planning/moveit.ros.org/pull/47
