### ISSUE TITLE
RobotState RViz crashes when sending joints that are not in the description

### ISSUE THREAD

**Issue by christian-rauch** [ros-planning/moveit#1266]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: melodic
* OS Version: Ubuntu 18.04
* Binary build: 0.10.5

### Steps to reproduce
Activate the `RobotState` RViz plugin and send a `DisplayRobotState` message which contains joints that are not available in the robot description. E.g. "fubar"

Btw, the `Robot State Topic` field gives as hint: `The topic on which the moveit_msgs::RobotState messages are received`, which is wrong since the topic expects a `moveit_msgs::DisplayRobotState`.

### Expected behaviour
The plugin should show the robot articulated with the set of available joints.

### Actual behaviour
The plugin is ignoring the exception and lets RViz crash. The plugin should show a warning once, if it wants to notify the user, but it should definitely not crash the whole RViz session.

### Backtrace or Console output

```
[ERROR] [1544796166.730999500]: Variable 'fubar' is not known to model 'lwr'
Exception thrown.
terminate called after throwing an instance of 'moveit::Exception'
  what():  Variable 'fubar' is not known to model 'lwr'
```

**Comment by rhaschke** [comment]
Closed via #1267. Thanks a lot for reporting and initial fix!
