### ISSUE TITLE
Potential out-of-bounds access at moveit setup assistant

### ISSUE THREAD

**Issue by sharronliu** [ros-planning/moveit#1273]
### Description
1. moveit/moveit_setup_assistant/src/widgets/robot_poses_widget.cpp:
RobotPosesWidget::loadJointSlider()
"&init_value" is passed to "getVariableDefaultPositions()" which uses it as an array, potential out-of-bounds access.

2. moveit/moveit_setup_assistant/src/widgets/robot_poses_widget.cpp:
RobotPosesWidget::showDefaultPose()
"&init_value" is passed to "getVariableDefaultPositions()" which uses it as an array, potential out-of-bounds access.

### Your environment
* ROS Distro: [Kinetic]
* OS Version: Ubuntu 16.04

### Steps to reproduce
code review

**Comment by davetcoleman** [comment]
Good catch! Do you have a suggested solution?

**Comment by rhaschke** [comment]
> `RobotPosesWidget::loadJointSlider()` passes `&init_value` to `getVariableDefaultPositions()`

It's [checked in advance, that the joint uses only a single variable](https://github.com/ros-planning/moveit/blob/4d25c3a8e9de614afa28b234dcc6c83648bc47f4/moveit_setup_assistant/src/widgets/robot_poses_widget.cpp#L519), i.e. a one-element array. 

> `RobotPosesWidget::showDefaultPose()` passes `&init_value` to `getVariableDefaultPositions()`

[Same here](https://github.com/ros-planning/moveit/blob/4d25c3a8e9de614afa28b234dcc6c83648bc47f4/moveit_setup_assistant/src/widgets/robot_poses_widget.cpp#L367).
