### ISSUE TITLE
Potential out-of-bounds access at moveit core

### ISSUE THREAD

**Issue by sharronliu** [ros-planning/moveit#1274]
### Description
moveit/moveit_core/robot_trajectory/src/robot_trajectory.cpp:
RobotTrajectory::unwind()
"&reference_value" is passed to function "enforcePositionBounds()" which uses it as an array, potential out-of-bounds access.

### Your environment
* ROS Distro: [Kinetic]
* OS Version: Ubuntu 16.04

### Steps to reproduce
code review

**Comment by rhaschke** [comment]
This function works on continuous (rotational) joints, that only use a _single_ joint variable.
