### ISSUE TITLE
Potential out-of-bounds access at moveit ros trajectory execution manager

### ISSUE THREAD

**Issue by sharronliu** [ros-planning/moveit#1275]
### Description
moveit/moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp:
TrajectoryExecutionManager::validate()
1, "&cur_position" passed to function "enforcePositionBounds()" which uses it as an array, potential out-of-bounds access

2, "&traj_position" passed to function "enforcePositionBounds()" which uses it as an array, potential out-of-bounds access

### Your environment
* ROS Distro: [Kinetic]
* OS Version: Ubuntu 16.04

### Steps to reproduce
code review

**Comment by rhaschke** [comment]
This method only checks the single-dof trajectory. Hence, there is only a single joint variable.
