### ISSUE TITLE
Potential memory leak at moveit planner

### ISSUE THREAD

**Issue by sharronliu** [ros-planning/moveit#1276]
### Description
moveit/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:
ChompPlanner::solve()
"optimizer" was created but not freed before return.

optimizer = new ChompOptimizer(&trajectory, planning_scene, req.group_name, &params_nonconst, start_state);
if (!optimizer->isInitialized())
{
...
return false;
}

### Your environment
* ROS Distro: [Kinetic]
* OS Version: Ubuntu 16.04

### Steps to reproduce
code review

**Comment by rhaschke** [comment]
This one was fixed in e658cafaf8f0e88c4ca6ad499f05753f36e30878 /  106e7782875fd75bba41002ef6816d942c1d91e8. Potentially there are more leaks in this new code.
