### ISSUE TITLE
Potential memory leak at moveit setup assistant

### ISSUE THREAD

**Issue by sharronliu** [ros-planning/moveit#1277]
### Description
1. moveit/moveit_setup_assistant/src/widgets/robot_poses_widget.cpp:
RobotPosesWidget::doneEditing()
"searched_data" was created, and its contents copied and pushed to "onfig_data_->srdf_->group_states_", but not freed before return.

searched_data = new srdf::Model::GroupState();
if (isNew)
{
config_data_->srdf_->group_states_.push_back(*searched_data);
}
...
_EMIT isModal(false);

2. moveit/moveit_setup_assistant/src/widgets/virtual_joints_widget.cpp
VirtualJointsWidget::doneEditing()
"searched_data" was created, and its contents copied and pushed to "onfig_data_->srdf_->virtual_joints_", but not freed before return.

### Your environment
* ROS Distro: [Kinetic]
* OS Version: Ubuntu 16.04

### Steps to reproduce
code review

**Comment by rhaschke** [comment]
There are potentially many leaks in MSA. Best option to track them down is using [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer):
`LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.4 rosrun moveit_setup_assistant moveit_setup_assistant`.
As MSA is only called once in a while, we didn't care too much about these leaks in the past.
