### ISSUE TITLE
What IDE can I use to open the MoveIt repository as a whole project?

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [ros-planning/moveit#1280]
I'm curious as to what IDEs are in use within the community who are working on MoveIt, and if there are any project definitions already in existence that would enable me to open the MoveIt code in a meaningful and organised manner?

I know CMake can generate projects for various IDEs and Make systems, but I haven't had much luck with this option thus far.  If this is a viable approach, a succinct tutorial showing how to do this would be just fine.

For C++ work, I use Xcode on MacOS and Code::Blocks on linux, but I do have Eclipse and Netbeans installed.

**Comment by rhaschke** [comment]
Please ask such questions on ROS answers. Here, we should focus on real issues only.

Regarding your question: This is primarily a matter of taste, isn't it?
I am using qtcreator with a generic project and catkin tools for building.
I also looked into Microsoft's Visual Studio Code, which comes with plugins for ROS.
The java-based Eclipse/Netbeans is - for me - way to slow to process a code base like MoveIt.
