### ISSUE TITLE
no motion plan found

### ISSUE THREAD

**Issue by C-monC** [ros-planning/moveit#1302]
I am trying this tutorial [https://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/move_group_python_interface/move_group_python_interface_tutorial.html](url) with a different robot. The planning works and displays in Rviz but I cannot get any of the planned paths to execute.

* ROS Distro: melodic
* OS Version: Ubuntu 18.04

rviz console output

`[ERROR] [1547123777.426484348]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1547123777.426564093]: RRTConnect: Created 1 states (1 start + 0 goal)
[ INFO] [1547123777.426598929]: No solution found after 0.040688 seconds
[ INFO] [1547123777.426647393]: Unable to solve the planning problem
[ INFO] [1547123876.184405449]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1547123876.184581598]: Planning attempt 1 of at most 1
[ INFO] [1547123876.185324057]: Planner configuration 'arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1547123876.185693967]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1547123876.198492593]: RRTConnect: Created 4 states (2 start + 2 goal)
[ INFO] [1547123876.198651041]: Solution found in 0.013047 seconds
[ INFO] [1547123876.209667728]: SimpleSetup: Path simplification took 0.010899 seconds and changed from 3 to 2 states
[ INFO] [1547123876.284230017]: Fake execution of trajectory
[ INFO] [1547123878.683883080]: Completed trajectory execution with status SUCCEEDED ...
^C[rviz_cmon_11545_2385174472520968209-5] killing on exit
[move_group-4] killing on exit
`

Here is the src file if someone can help. The python file is in scripts in bamba_pkg.

[src.zip](https://github.com/ros-planning/moveit/files/2745327/src.zip)

The goal is just to execute a path via python, so any other method is also welcome. This is the code im trying without moveit but the final goal is to have it work through moveit.

`  def go_to_joint_state(self):
    move_group = self.move_group

    joint_goal = move_group.get_current_joint_values()
    joint_goal[0] = random.randrange(-10,10,1)/10
    joint_goal[1] = random.randrange(-10,10,1)/10
    joint_goal[2] = random.randrange(-10,10,1)/10
    joint_goal[3] = random.randrange(-10,10,1)/10

    move_group.go(joint_goal, wait=True)
    move_group.execute(joint_goal, wait=True)

    move_group.stop()

    current_joints = move_group.get_current_joint_values()
    return all_close(joint_goal, current_joints, 0.01)`

**Comment by rhaschke** [comment]
According to your console output, a solution is found and successfully executed using the fake controller:
```
[ INFO] [1547123876.198651041]: Solution found in 0.013047 seconds 
[ INFO] [1547123876.209667728]: SimpleSetup: Path simplification took 0.010899 seconds and changed from 3 to 2 states 
[ INFO] [1547123876.284230017]: Fake execution of trajectory 
[ INFO] [1547123878.683883080]: Completed trajectory execution with status SUCCEEDED
```
What is the actual problem?

**Comment by C-monC** [comment]
I can plan useing set joint states but I can't execute the path in Rviz.
I can't plan using pose goal or execute using pose goal. `^[[ INFO] [1547187664.749495665]: ABORTED: No motion plan found. No execution attempted.
`
I used get current pose to get `position: 
  x: 0.102592509978
  y: 3.56171850966e-05
  z: 0.156007748445
orientation: 
  x: -0.603189755716
  y: -0.369006495064
  z: -0.368769278832
  w: 0.603328719845
`
but setting the pose using ` pose_goal = []
    pose_goal = [0.4, 3, 0.1]
    move_group.set_position_target(pose_goal)`

gives TypeError: 'Pose' object does not support indexing

**Comment by C-monC** [comment]
If in the docs it says the function wants xyz is that a list?

**Comment by rhaschke** [comment]
You should read the MoveIt tutorial: pose goals with Python are explained [here](https://ros-planning.github.io/moveit_tutorials/doc/move_group_python_interface/move_group_python_interface_tutorial.html#planning-to-a-pose-goal). Please raise such usage questions on https://answers.ros.org.
Closing this, as it's obviously not an issue, but a usage question.
