### ISSUE TITLE
How to display robot motion plan found while using moveit_ros_benchmarks::BenchmarkExecutor class ?

### ISSUE THREAD

**Issue by moucrob** [ros-planning/moveit#1309]
### Description
Hi let's say I'm doing some simulations relying on [this BenchmarkExecutor.cpp file](https://github.com/ros-planning/moveit/blob/abc4f4070e300352c851f84fb53fa6d06c9eacbb/moveit_ros/benchmarks/src/BenchmarkExecutor.cpp#L792), and through the iterations I get different [`planning_interface::MotionPlanDetailedResponse mp_res`](http://docs.ros.org/kinetic/api/moveit_core/html/structplanning__interface_1_1MotionPlanDetailedResponse.html). 
* How could I charge RViz/MoveIt! to display the found trajectory (with the current launched robot within it) from that same BenchmarkExecutor.cpp file please?

### Environment
* Kinetic
* Ubuntu 16.04

### Already tried
dumbly to : 
* `rosparam set /moveit_run_benchmark/planning_scene_monitor/publish_geometry_updates true`
* `rosparam set /moveit_run_benchmark/planning_scene_monitor/publish_planning_scene true`
* `rosparam set /moveit_run_benchmark/planning_scene_monitor/publish_planning_scene_hz true`
* `rosparam set /moveit_run_benchmark/planning_scene_monitor/publish_states_updates true`
* `rosparam set /moveit_run_benchmark/planning_scene_monitor/publish_transform_updates true`
* `rosparam set /moveit_run_benchmark/planning_scene_monitor/publish_geometry_updates true`

But it turned out not being as simple as this...

@rhaschke @zkingston @ryanluna @gavanderhoorn Can I bother you guys for enlightening me with some ideas please?
By thanking you in advance.

**Comment by rhaschke** [comment]
Use a debugger to track down the segfault.

> What if I actually wanted (sorry for expressing myself wrongly all this time) to display the robot moves mainly, and optionally the path~line of its end effector ? Should I use publishIKSolutions, publishRobotState, or Path would do the job?

* publishIKSolutions probably publishes a set of fixed robot states - the ik solutions
* publishRobotState publishes a single robot pose
* publishTrajectoryPath probably publishes the found path to be shown as an animated solution in rviz.

But @davetcoleman as the original author of this package might provide more insight.

**Comment by moucrob** [comment]
Solved! 

Among other moveit_visual_tools' methods to be added to one's own class, 
- even though we never provide it as an argument, 
- the **different possibilities for calling [`MoveItVisualTools::publishTrajectoryPath` (see here on ROS docs,](http://docs.ros.org/kinetic/api/moveit_visual_tools/html/moveit__visual__tools_8cpp_source.html#l01151) [or here for a github permalink)](https://github.com/ros-planning/moveit_visual_tools/blob/b8e40d0e7b91c78e03a26f0bd33c6403f1bbceb6/src/moveit_visual_tools.cpp#L1127) were**, 
- while nesting in cascade the calls between them, 

**trying to fetch a [`shared_robot_state_`](https://github.com/ros-planning/moveit_visual_tools/blob/b8e40d0e7b91c78e03a26f0bd33c6403f1bbceb6/src/moveit_visual_tools.cpp#L1145),**
- which not only has to be defined in one's own class header in order to become a global variable, 
- but also has its loader ([http://docs.ros.org/kinetic/api/moveit_visual_tools/html/moveit__visual__tools_8h_source.html#l00674](http://docs.ros.org/kinetic/api/moveit_visual_tools/html/moveit__visual__tools_8h_source.html#l00674)) to be called in one's own class

And so you were right, Line plots the 3D path of the end effector with spheres showing the interpolation, and Path makes the robot move. :+1:
