### ISSUE TITLE
Change joint values

### ISSUE THREAD

**Issue by labarea** [ros-planning/moveit#1328]
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04

Hi,
we have to change the initial value of joint in the current state. We use this code with ros

  moveit::core::RobotStatePtr current_state = move_group.getCurrentState();

  std::vector<double> joint_group_positions;
  current_state->setJointGroupPositions(joint_model_group, joint_group_positions);

  joint_group_positions[0] = 3.14/2;
  joint_group_positions[1] = 0.0;
  joint_group_positions[2] = 0.0;
  joint_group_positions[3] = 0.0;
  joint_group_positions[4] = 0.0;
  joint_group_positions[5] = 0.0;
  joint_group_positions[6] = 0.0;
  joint_group_positions[7] = 0.0;
  move_group.setJointValueTarget(joint_group_positions);

  After that we print values, and these are still
    0
    -0.785
    0
    -2.356
    0
    1.571
    0.785
  (that are the initial values)
so nothing is changed. Can you help us?

**Comment by rhaschke** [comment]
`move_group.setJointValueTarget()` sets a _target_ (joint) pose. It's not intended to change initial values. To this end, there is a `move_group.setStartState()`.
