### ISSUE TITLE
additionnal saved rviz motion planning plugin not ok at re-launch

### ISSUE THREAD

**Issue by moucrob** [ros-planning/moveit#1339]
### Description

In order to display two different `trajectoryPath`s (movements) simultaneously, I added a second motion planning plugin to RViz. 
After this, I saved the moveit.rviz settings so that for next launches of RViz the pannel will already be there, and it won't need the user to manually add the right topic name where the trajectory msgs are published.

The thing is that it works (I see my 2 simultaneous traj) only when I launch RViz and manually add a motion planning display. Otherwise, the additionnal one already provided never has its status set to ok :heavy_check_mark: like the native one: 
![plugin](https://user-images.githubusercontent.com/33000071/52268471-84d2f700-2933-11e9-9d5d-fb29925cce18.png)

I said click on 'add' and not 'duplicate', because I can't duplicate the second one which doesn't have that `status ok`...

Except from this `status : ok`, as accurately as I checked, the additionnal loaded plugin and the one I create have the same settings, as I actually look into the additionnaly loaded to create the new one everytime.

### Environment
* Kinetic
* Ubuntu 16.04

### Code
I know nothing, but here is a detail that may be useful : in the c++ code where the movements are generated, I think I do have loaded the planning scene as the native motion planning plugin does:
```
visual_tools2_->loadTrajectoryPub(DISPLAY_PLANNED_PATH_PARALLEL);
visual_tools2_->loadPlanningSceneMonitor();
```
Unfortunately it seems that the native motion planning plugin loads the scene at RViz launch, which is done before I even launch my c++ node. So I don't really know where to know how to set a status ok of an rviz plugin through c++ dommands...

### People to bother

@rhaschke @davetcoleman sorry guys

**Comment by rhaschke** [comment]
Generally, it's not a good idea to load two MotionPlanning plugins simultaneously, as these two plugins seem to use the same interactive marker names for the end effector.
However, what you want to achieve is to display multiple trajectories. To this end, there is another display plugin, called "moveit_ros_visualization/Trajectory".
There is no way to directly influence the status of a display from outside. Rather this status reflects internal errors of the given plugin and you should fix errors by fixing the configuration of the plugin in rviz. As you didn't report the actual error message in case the status is not ok, it's hard to help further than this.

**Comment by rhaschke** [comment]
@moucrob I hope I interpret your :tada: correctly and this can be closed. If not, feel free to reopen.
