### ISSUE TITLE
Remove signals from find_package() in CMakeLists

### ISSUE THREAD

**Issue by jwhendy** [ros-planning/moveit#1350]
Is [this issue](https://github.com/ros/ros_comm/pull/1580) also relevant here?

I had to remove `signals` from the `find_package()` calls in these `CMakeLists.txt`  files to build successfully:
- [moveit_ros/perception](https://github.com/ros-planning/moveit/blob/8075221e76fa78f014b7c69c60035c9ed216d180/moveit_ros/perception/CMakeLists.txt)
- [moveit_ros/planning](https://github.com/ros-planning/moveit/blob/8075221e76fa78f014b7c69c60035c9ed216d180/moveit_ros/planning/CMakeLists.txt)
- [moveit_ros/move_group](https://github.com/ros-planning/moveit/blob/8075221e76fa78f014b7c69c60035c9ed216d180/moveit_ros/move_group/CMakeLists.txt)

This is on arch linux with cmake 3.13 and boost 1.69.

**Comment by rhaschke** [comment]
Closed via #1353.
