### ISSUE TITLE
generateEnvironmentDistanceField in WorldCollisionDistanceField has no source

### ISSUE THREAD

**Issue by tsijs** [ros-planning/moveit#1383]
### Description

generateEnvironmentDistanceField in WorldCollisionDistanceField has no source.

### Your environment
* ROS Distro: [Kinetic]
* OS Version: Ubuntu 16.04
* Source or Binary build? Source
* If source, which git commit or tag? devel/all

### Expected behaviour
Probably just get rid of the declaration in the header?

**Comment by BryceStevenWilley** [comment]
Just linking this to #1392, so this can be closed when that is merged.
