### ISSUE TITLE
add "<previous>" robot state to RViz motion display

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#14]
In some situations it would be nice to have a "<previous>" entry in the Update Start/Goal State drop-down list, to set the start/goal state of the display to the previous pose the robot was in (before the latest motion). This can be used e.g. to look for alternative paths for the latest robot motion.

This could be implemented by adding a new `robot_state::RobotState previous_state_` member to the `MotionPlanningDisplay` that is updated after each successful execution (as well as plan&execute) and might be used by `MotionPlanningFrame::updateQueryStateHelper` to set a query state.

**Comment by takarakasai** [comment]
I am trying for this issue at moveit day 2019.

**Comment by rhaschke** [comment]
Addressed in #1742.
