### ISSUE TITLE
IKFast plugin not initialized correctly

### ISSUE THREAD

**Issue by martiniil** [ros-planning/moveit#1448]
### Description

We have a test failing sporadically after an IKfast update.
https://github.com/PilzDE/pilz_robots/blob/kinetic-devel/prbt_ikfast_manipulator_plugin/test/unittests/tst_prbt_ikfast_manipulator_plugin.cpp

My guess is that `IKFastKinematicsPlugin::computeRelativeTransform` does use an uninitialized RobotState, which can lead to errors.

An issue is also that above function returns true even if the computed transform is not well-defined.

**Comment by rhaschke** [comment]
Fixed via #1449.
