### ISSUE TITLE
some confuse of the function "set_position_target()" 

### ISSUE THREAD

**Issue by minglianghou** [ros-planning/moveit#1486]
### Description

I'm trying moveit with the urdf i designed。it has 5 joint。
at the beginning，i use the set_position_target() to control my robot，but it doesn't work，“RRTConnect: Unable to sample any valid states for goal tree”;
then i change the Kinematics Configuration :"position_only_ik: True",and it goes well.
Was it necessary，because the declaration say like this“Specify a target position for the end-effector. Any orientation of the end-effector is acceptable.”

### Your environment
* ROS Distro: [Kinetic]
* OS Version: e.g. Ubuntu 16.04
* /rosversion: 1.12.14

**Comment by BryceStevenWilley** [comment]
Without more information (the exact URDF you are using, the targets you are setting), this is intended. Since robots with < 6 DOF will not able able to reach any arbitrary target pose, the documentation that you referenced assumes that your robot is >= 6 DOF.
