### ISSUE TITLE
Travis fails because of outdated GPG keys

### ISSUE THREAD

**Issue by felixvd** [ros-planning/moveit#1496]
All Travis builds are failing because the GPG key `F42ED6FBAB17C654` is outdated and needs to be replaced. See [here](https://discourse.ros.org/t/new-gpg-keys-deployed-for-packages-ros-org/9454/1).

It looks like waiting for the ROS docker images to be updated will be enough. I am not sure if a manual change is necessary.

**Comment by rhaschke** [comment]
docker images should be fixed now.
