### ISSUE TITLE
Moveit building from source fails

### ISSUE THREAD

**Issue by kalyanvasudev** [ros-planning/moveit#1524]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04
* Source or Binary build? Ans: Source 

### Steps to reproduce
Followed instructions here to download source code - 
https://moveit.ros.org/install/source/
then ran "catkin build" in the catkin work space "ws_moveit"

After doing so, the build fails with the following error.
![image](https://user-images.githubusercontent.com/12800032/60210697-78403400-982b-11e9-915a-447b3db93097.png)

Can someone please help me on how to fix this?

**Comment by rhaschke** [comment]
Looks like you are missing the package `python-numpy`. Did you run the `rosdep install` command to install all required dependencies? This [works on Travis...](https://travis-ci.org/ros-planning/moveit/builds/548781867)

**Comment by knorth55** [comment]
I have exact same issue on my kinetic pc.
I'm looking into this issue.

**Comment by knorth55** [comment]
This issue occurs when you install upper version `numpy` via `pip` (i.e. `sudo pip install numpy -U`)
I installed `1.16.3` numpy, so I uninstall it (`sudo pip uninstall numpy`) and reinstall debian numpy `sudo apt install python-numpy --reinstall`.
Now I can correctly build `moveit_ros_planning_interface`.
