### ISSUE TITLE
Errors installing on Kinetic 

### ISSUE THREAD

**Issue by bmgatten** [ros-planning/moveit#1545]
### Description

Overview of your issue here.
Not able to fetch packages when installing moveit for ros kinetic.  The installation fails when typing the command: sudo apt install ros-kinetic-moveit

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04 
* Source or Binary build?
Binary
* If binary, which release version?
Not sure.  I'm just following the installation instructions per https://github.com/ros-planning/moveit_tutorials/blob/kinetic-devel/doc/getting_started/getting_started.rst

### Steps to reproduce
Follow the installation instructions in the github moveit tutorials for ros kinetic.

### Expected behaviour
Should install packages.

### Actual behaviour
Doesn't seem to be able to find most packages. I'm getting errors saying the i.p. address is not found (see Backtrace or Console output section).

### Backtrace or Console output
https://gist.github.com/bmgatten/d3d8e38adad7658c10342c4e837fb2c7

**Comment by gavanderhoorn** [comment]
I'm almost 100% certain that you are running into [ros/answers#325039](https://answers.ros.org/question/325039).

As such, I'm going to close this issue.

Feel free to keep commenting of course and if it turns out it's not that issue, we can re-open.
