### ISSUE TITLE
rviz display should default to `move_group/monitored_planning_scene`

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#156]
Another rather common problem of new users to MoveIt is that they do not realize that they should
change the topic of the display from `planning_scene` to `move_group/monitored_planning_scene` to see the internal state of the `move_group` (including a maintained octomap).
This definitely confused me a lot two years ago and I just noticed that this issue still exists (https://github.com/ros-planning/moveit/pull/128#issue-172791297).

I propose to change the default to `move_group/monitored_planning_scene`

Note that for example [the pr2 default rviz config already sets it to the monitored topic on startup](https://github.com/ros-planning/moveit_pr2/blob/indigo-devel/pr2_moveit_config/launch/moveit.rviz#L520)

**Comment by mikeferguson** [comment]
+1
