### ISSUE TITLE
jog_arm_server relies on move_group action server (moveit_experimental)

### ISSUE THREAD

**Issue by Dale-Koenig** [ros-planning/moveit#1563]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: [Melodic]
* OS Version: Ubuntu 18.04
* Source or Binary build?
* source (master)

### Steps to reproduce
Try to use jog_arm_server to move a robot without move_group action server node running

### Expected behaviour
Jog commands should still work even without action server

### Actual behaviour
If there is no move_group action server, the JogCalcs thread crashes upon trying to initialize the MoveGroupInterface

### Fix possibility
At the moment the MoveGroupInterface is used only once, to call `move_group_.getJointNames()`.  Removing `move_group_` as a member variable and getting joint names with another method, such as calling `joint_model_group_->getJointModelNames()` allows jog_arm_server to work without the move_group action server running.

**Comment by rhaschke** [comment]
Please feel free to file a pull request to fetch the groups joint names by other means.
