### ISSUE TITLE
Validate full start state before executing a trajectory

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit#1564]
As pointed out in https://github.com/ros-planning/moveit/issues/705#issuecomment-350374849, currently, start-state validation only considers group joints (that are part of the trajectory).
This might result in unexpected collisions when running multiple move_group nodes in parallel (for separate robots).

**Comment by v4hn** [comment]
I don't think we have a problem here.

Start-state validation is only meant to entail the controllers of the JointModelGroup do not get targets too far away from their current position (leading to high-jerk motions for unsafe controllers).

[Online trajectory collision checking](https://github.com/ros-planning/moveit/blob/master/moveit_ros/planning/plan_execution/src/plan_execution.cpp#L264) is supposed to ensure we do not get unwanted collisions.
