### ISSUE TITLE
Invalid iterator

### ISSUE THREAD

**Issue by danielwangksu** [ros-planning/moveit#1578]
Inside the loop iterator is erased, which invalid the iteration
https://github.com/ros-planning/moveit/blob/6c7e84c4c5185cf86c4b1daa1bdf898fd9a1e3fc/moveit_setup_assistant/src/tools/moveit_config_data.cpp#L742-L780

**Comment by rhaschke** [comment]
Thanks for pointing this out. Would you mind filing a PR?
