### ISSUE TITLE
Python GIL not released before entering the C++ library

### ISSUE THREAD

**Issue by Rayman** [ros-planning/moveit#1580]
### Description
Python GIL not released before entering the C++ library. The effect is that all rospy subscribers, publishers, transform listeners etc. are not updated. Effectively all communications with that python node are not possible anymore.

This issue was raised a few years back in this issue: https://github.com/ros-planning/moveit_commander/issues/28

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04
* Source or Binary build: The normal debian release
```
moveit_version 
0.9.17-Alpha
```

### Steps to reproduce
Execute a plan with moveit_commander that takes multiple seconds.

### Expected behaviour
A subscriber should be able to receive messages from other ros nodes while the plan is executing.

### Actual behaviour
The GIL is locked an the node is not able to execute any python code at all while the plan is executing.

**Comment by rhaschke** [comment]
We would be grateful, if you could file a pull request to fix this issue.
