### ISSUE TITLE
Consider using #pragma once, instead of include guards

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#1597]
While reviewing the [pending TrajOpt PR](https://github.com/ros-planning/moveit/pull/1593/files) I noticed some copied code from [trajopt_ros](https://github.com/ros-industrial-consortium/trajopt_ros) used ``#pragama once``. I was about to request its removal, but really, why bother? 

I did some research and found a very useful rational from the Drake Motion Planning project in this [issue](https://github.com/RobotLocomotion/drake/issues/2104). After very informed debate, they decided to break away from the Google Style guide here. Please review that rational so we don't have to reiterate the exact same discussion.

Overall, Drake and TrajOpt use ``pragma once`` to simplify the code and reduce user error. I think MoveIt should too.

Other references:
- [Drake style guide change](https://github.com/RobotLocomotion/drake/pull/2120/files)
- [Example PR to remote ``#ifndef``](https://github.com/RobotLocomotion/drake/pull/2125/files)

**Comment by davetcoleman** [comment]
@rhaschke @mlautman @henningkayser thoughts?

**Comment by rhaschke** [comment]
I'm advocating `#pragma once` for long time already...

**Comment by v4hn** [comment]
:+1: Feel free to add a pull-request for it.

**Comment by jonbinney** [comment]
I used this tool to convert Iron Ox's code base over to pragma once: https://github.com/marcusmueller/include-guard-convert

I went ahead and used it to convert moveit over; PR here: https://github.com/ros-planning/moveit/pull/1615

**Comment by davetcoleman** [comment]
Whoot thanks!
