### ISSUE TITLE
moveit_setup_assistant should require author details

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#16]
catkin requires a maintainer and mail address to be specified in each package.xml.
Up to now the setup assistant does not ask for that information during setup, but just adds "assistant@moveit.ros.org" there. This is clearly wrong and people forget to change that value later on.
An issue for this was filed [here](https://github.com/ros-planning/moveit_setup_assistant/issues/110).

[This commit](https://github.com/v4hn/moveit_setup_assistant/commit/3181604e8bf203fe49efd5e02f653006b232b841) implements basic support for configuration of the contact details in the GUI, but it is not yet ready for merging.

- [x] Check for valid mail address
- [x] Make sure the setup assistant can load the new parameters from a config already generated
- [x] Prohibit generation of the config when the contact details are not (yet) filled in

**Comment by jan0e** [comment]
I started working on this and implemented functionality for bullet point 1 and 3. Will also look into point 2.

**Comment by davetcoleman** [comment]
This has been completed
