### ISSUE TITLE
rename jog_arm to moveit_jog_arm

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#1612]
See https://github.com/ros-planning/moveit/pull/1606#discussion_r312545808 .

If anyone is not happy with the request to rename it, we can discuss here.

**Comment by AndyZe** [comment]
I'm slightly not-in-favor of this change. `jog_arm` is so much easier to remember/type than `moveit_jog_arm`.

Also, are we going to rename the other packages in moveit_experimental? Those names will be really long.

moveit_collision_distance_field_ros
moveit_kinematics_constraint_aware
etc

**Comment by rhaschke** [comment]
That's the way it is. We also have `moveit_ros_planning_interface`...

**Comment by v4hn** [comment]
> moveit_collision_distance_field_ros
> moveit_kinematics_constraint_aware
> etc

Actually, all the "catkinized" packages in there already include the `moveit_` prefix.
There is
- `set(MOVEIT_LIB_NAME moveit_kinematics_cache)`
- `set(MOVEIT_LIB_NAME moveit_kinematics_constraint_aware)`
