### ISSUE TITLE
Merging two or more trajectories in real time 

### ISSUE THREAD

**Issue by pulkit123tak** [ros-planning/moveit#1613]
Hi 

I am working on Ubuntu 16.04, with ROS Kinetic. I am trying to add new trajectory to the **_FollowJointTrajectoryAction_** without preempting the current trajectory, such that the two trajectories get merged. Can someone help me with that ??

**Comment by v4hn** [comment]
Sorry, but this is out of scope here.

Whether or not this is possible depends only on the implementation of the action server (which is provided independent of MoveIt).
See http://wiki.ros.org/joint_trajectory_controller/UnderstandingTrajectoryReplacement for more details on how drivers can implement this.
