### ISSUE TITLE
Octomap not properly refreshing Intel Realsense SR300 MoveIt

### ISSUE THREAD

**Issue by MarcoT11** [ros-planning/moveit#1628]
### Your environment
* ROS Kinetic
* Ubuntu 16.04
* Sensor: Intel Realsense SR300
* sr300_config.yaml
sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/depth/color/points
    max_range: 1.7                                      #Points further than this will not be used
    point_subsample: 1                                #One=choose every point
    padding_offset: 0.04                               #Size of  padding in cm
    padding_scale: 1.0                                 #Scale of the padding
    max_update_rate: 100                            #Update of Octomap: Less than or equal to this value
    filtered_cloud_topic: filtered_cloud_topic

### Steps to reproduce
* Intel SR300 needed
* Camera is positioned 1 meter above the robot arm

### Expected behaviour
Refreshing of the OctoMap after the obstacle is removed.

### Actual behaviour
Voxels still remain in the position where the obstacle was. 

RQT_graph:
![24RViz_commander_translation_pointcloud_without_command](https://user-images.githubusercontent.com/48487398/63173836-0329f780-c041-11e9-81b1-5be7e69a04cc.png)

Workspace:
![RViz1](https://user-images.githubusercontent.com/48487398/63170991-e4c0fd80-c03a-11e9-921c-bdc794302d9d.png)
Put in an obstacle:
![RViz2](https://user-images.githubusercontent.com/48487398/63171080-189c2300-c03b-11e9-95fb-ca5d98fffce1.png)
Remove obstacle:
![RViz3](https://user-images.githubusercontent.com/48487398/63171092-1df96d80-c03b-11e9-9484-be6b07a45f1a.png)
Voxels stay even obstacle is removed and pointcoud is not detecting. Same again:
![RViz4](https://user-images.githubusercontent.com/48487398/63171110-2b165c80-c03b-11e9-9b7b-40357c8511d2.png)
![RViz5](https://user-images.githubusercontent.com/48487398/63171116-2ce02000-c03b-11e9-9638-cdea220be7d0.png)
When putting in an obstacle below the previous one the voxels disappear:
![RViz6](https://user-images.githubusercontent.com/48487398/63171164-4719fe00-c03b-11e9-82da-2debfac1155f.png)
When pulling an obstacle upwards it creates a pillar: 
![RViz7](https://user-images.githubusercontent.com/48487398/63171181-4e410c00-c03b-11e9-8b9f-d0333cb9f359.png)
![RViz8](https://user-images.githubusercontent.com/48487398/63171227-657ff980-c03b-11e9-9ed2-179890cc2bbe.png)
which can be removed again by putting in an obstacle below it:
![RViz9](https://user-images.githubusercontent.com/48487398/63171232-687aea00-c03b-11e9-940a-886038e43ca5.png)

This causes lots of voxels left in the workspace limiting the motion ability of the robot arm. The voxels especially stay on the edge of the sensor
![RViz10](https://user-images.githubusercontent.com/48487398/63171285-89dbd600-c03b-11e9-8d33-f771ae7b0878.png)

When restarting MoveIt the Octomap builds up fresh.

### Backtrace or Console output
`[ WARN] [1565962011.410588435]: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)`
`[ WARN] [1565962011.490164733]: No stream match for pointcloud chosen texture Process - Color`
`[ERROR] [1565962011.628675414]: Region-of-interest is not implemented for this device!`
 
What influences the update of the Octomap in MoveIt?
Why do some Voxels remain even though no pointcloud data is received for that position?

**Comment by v4hn** [comment]
As far as I understood your post, you observe that voxels are not cleared unless points *behind* the voxel (a perceived from the camera's point of view) are detected.
This is actually intended. The system performs [ray tracing](https://github.com/ros-planning/moveit/blob/master/moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp#L300) to avoid just that.
This is usually done in depth-based perception (also for simple 2d laser scans) to account for measurement errors where no distance is perceived for a ray or something else suddenly blocks the view of a previously perceived obstacle.

Of course, you can hack the plugin to free *all* cells that are not occupied and you will not see the "tower" artifacts anymore.
I believe such an updater might even be welcome upstream.
However, it would throw away information about potential collisions in valid scenarios too.
E.g., just because a robot arm moved over the table, that does not mean there is no table anymore.
So it will never become the default behavior.

PS: If applicable, you should use the [depth_image_octomap_update](https://github.com/ros-planning/moveit/tree/master/moveit_ros/perception/depth_image_octomap_updater) instead of the pointcloud-based updater.

**Comment by MarcoT11** [comment]
Hello v4hn, thanks for the answer. What are the advantages of the depth image over the point cloud? 
As far as I know the depth image has a way smoother and more complete stream since it takes more time to optimize the stream of points into an image. The raw point cloud on the other hand is less visual smooth but offers a very quick input of data. 
Wouldn't be a quick data input more important for the field of obstacle avoidance? The faster an obstacle is detected the better? 
Or is the time difference between an depth image and the point cloud so small making the discussion irrelevant?

**Comment by ChangcongWang** [comment]
Hello Marco, I want to ask you how you solve this problem finally. I face the same problem but I don't know how to hack the plugin.

**Comment by ChangcongWang** [comment]
I figure out how to solve this problem, just need to add "tree_->clear()" to [here](https://github.com/ros-planning/moveit/blob/39f592037576d5fada0e0b64c27370222c7c286c/moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp#L332) to clear the tree created before. I hope it's helpful for who have the same problem.

**Comment by dbdxnuliba** [comment]
@ChangcongWang  dou you mean the code should be modified as:
  for (const octomap::OcTreeKey& free_cell : free_cells)
{
     tree_->clear();
      tree_->updateNode(free_cell, false);
}

**Comment by ChangcongWang** [comment]
> @ChangcongWang dou you mean the code should be modified as: for (const octomap::OcTreeKey& free_cell : free_cells) { tree_->clear(); tree_->updateNode(free_cell, false); }

No. I mean 
```
try
  {
    tree_->clear();
    /* mark free cells only if not seen occupied in this cloud */
    for (const octomap::OcTreeKey& free_cell : free_cells)
      tree_->updateNode(free_cell, false);
```
However, this refresh method is very inefficient, and the tree must be refreshed every time the tree is updated. At present, I can't find a better way to solve the refresh problem of octomap.

**Comment by dbdxnuliba** [comment]
yes it is, we need find a efficient way
and ideas @rojkov @rhaschke
