### ISSUE TITLE
[WARN]: Kinematics solver doesn't support #attempts anymore, but only a timeout.

### ISSUE THREAD

**Issue by anubhav1772** [ros-planning/moveit#1642]
I am fairly new to ROS. Initially, on adding `ur_kinematics/UR5KinematicsPlugin` Kinematic Solver to the planning group `manipulator`, I was getting error same as [issue#306](https://github.com/ros-industrial/universal_robot/issues/306), but when I tried the solution proposed in the [comment](https://github.com/ros-industrial/universal_robot/issues/306#issuecomment-380366259) by LuserBen, I was able to get rid of the above error but now I am getting warning messages:
```
[WARN] [1566548603.759182091]: Kinematics solver doesn't support #attempts anymore, but only a timeout.
Please remove the parameter '/rviz_predator_helios300_10772_3827859127693552409/manipulator/kinematics_solver_attempts' from your configuration.
[WARN] [1566548603.764627321]: IK plugin for group 'manipulator' relies on deprecated API. Please implement initialize(RobotModel, ...).
```

* ROS Distro: Melodic
* OS Version: Ubuntu 18.04

I don't know, why I am getting the above warning messages. It looks like a deprecation problem. But, if it is so, how can I correct this. Please guide me. Thanks.

**Comment by rhaschke** [comment]
This is a deprecation warning, which you as a user can ignore for now. The maintainers of https://github.com/ros-industrial/universal_robot should fix this warning by adapting to the new MoveIt API as indicated in the [migration notes](https://github.com/ros-planning/moveit/blob/melodic-devel/MIGRATION.md).
