### ISSUE TITLE
Class default_planner_request_adapters/ResolveConstraintFrames does not exist

### ISSUE THREAD

**Issue by rickstaa** [ros-planning/moveit#1655]
### Description

While following the [moveit_tutorials](https://ros-planning.github.io/moveit_tutorials/doc/quickstart_in_rviz/quickstart_in_rviz_tutorial.html) I get an error while trying to run the `roslaunch panda_moveit_config demo.launch` command.

### Your environment
* ROS Distro: Melodic
* OS Version: e.g. Ubuntu 18.04
* Source or Binary build: Binary
* If binary, which release version?:  1.0.2-1bionic.20190808.234100 amd64

### Steps to reproduce
Install moveit and perform the steps in the [moveit_tutorials](https://ros-planning.github.io/moveit_tutorials/doc/quickstart_in_rviz/quickstart_in_rviz_tutorial.html).

### Expected behaviour
No error.

### Actual behaviour
Error:

```

[ERROR] [1567265168.348453066]: Exception while loading planning adapter plugin 'default_planner_request_adapters/ResolveConstraintFrames': According to the loaded plugin descriptions the class default_planner_request_adapters/ResolveConstraintFrames with base class type planning_request_adapter::PlanningRequestAdapter does not exist. Declared types are  chomp/OptimizerAdapter default_planner_request_adapters/AddIterativeSplineParameterization default_planner_request_adapters/AddTimeOptimalParameterization default_planner_request_adapters/AddTimeParameterization default_planner_request_adapters/Empty default_planner_request_adapters/FixStartStateBounds default_planner_request_adapters/FixStartStateCollision default_planner_request_adapters/FixStartStatePathConstraints default_planner_request_adapters/FixWorkspaceBounds

```

I suspect this error is due to an incompatibility between the[panda_moveit_config ](https://github.com/rickstaa/panda_moveit_config)which I build from source and the moveit packages for which I installed the binaries. I'm not testing this by building everything from source.

## Solution 

Building all packages from source solved it so I think my theory was alright. Unfortunately, now my robot is not linked.

![image](https://user-images.githubusercontent.com/17570430/64066742-e6cfb280-cc1d-11e9-9e77-208ef538cec1.png)

This can be solved by changing the `LC_NUMERIC` format using the `export LC_NUMERIC="en_US.UTF-8` command.

## Additional question

As I want to use a gazebo simulation of the panda robot I use a fork provided by @erdalpekel for the [panda_moveit_config](https://github.com/erdalpekel/panda_moveit_config) and [ros_franka](https://github.com/erdalpekel/franka_ros) packages. Does this automatically mean that I have to build the whole moveit package from source? Or is there a better way?

**Comment by rhaschke** [comment]
> Class `default_planner_request_adapters/ResolveConstraintFrames` does not exist

This plugin was added to the `master` branch of MoveIt, which is not released as binary debs.
Hence, you need to build from source.

The tutorials you referenced correspond to the master branch.
When running against stock Melodic MoveIt you should use the [Melodic tutorials](http://docs.ros.org/melodic/api/moveit_tutorials/html/index.html).

> As I want to use a gazebo simulation of the panda robot I use a fork of the panda_moveit_config and ros_franka packages. Does this automatically mean that I have to build the whole moveit package from source?

Usually not. However, on issues first compare the config and launch files in `panda_moveit_config`.

**Comment by huiwenzhang** [comment]
@rhaschke Hi, even I follow the tutorials of the melodic version, I still encounter this error. However, according to the melodic version tutorial, a binary installation of the moveit is ok. To solve this issue, I can install the master branch of moveit from source, But I am doubting  whether the source install will corrupt somewhere else of tutorial.

**Comment by rhaschke** [comment]
You can safely ignore this "error" on a Melodic binary release. As said before, the corresponding plugin is only available in master (to be built from source) and it will become available in Noetic. The corresponding [_subframes_ tutorial](https://ros-planning.github.io/moveit_tutorials/doc/subframes/subframes_tutorial.html) is only available in the master version of the tutorials.
