### ISSUE TITLE
Understand end effector setup

### ISSUE THREAD

**Issue by rickstaa** [ros-planning/moveit#1694]
### Description

In order to control the gripper of the `panda_emika_franka robot`, I added an extra virtual link to my the robot `srdf` and `urdf` files (See [/rickstaa/panda_moveit_config/tree/melodic-devel-panda_autograsp](https://github.com/rickstaa/panda_moveit_config/tree/melodic-devel-panda_autograsp) and [/rickstaa/franka_ros/tree/melodic-devel-panda_autograsp](https://github.com/rickstaa/franka_ros/tree/melodic-devel-panda_autograsp)). This will create the following model:

![image](https://user-images.githubusercontent.com/17570430/66929197-e60aa880-f032-11e9-91b8-b637b2c6b952.png)

When trying to control the robot however, I noticed that the `panda_gripper_center` is not automatically set as the end effector of the `panda_arm` move group. As a result I have to set it using the `self.moveit_commander.robot.get_group("panda_arm").set_end_effector_link("panda_gripper_center". After playing around with the `moveit_setup_assistant` I came to the following conclusions about using end effectors. Please correct me if I'm wrong.

**My conclusion:**
1. An end effector can only be set for a move group that consists of a chain of links.
2. When in your `srdf` you set a link as an end effector that is part of the move group itself it gets is set as the end effector by the moveit_commander.
3. When in the `srdf` you set a link as the end effector that is not part of the move_group but part of a move_group higher in the chain it is not automatically set. You can, however, control it with the specified link as the end effector after setting it manually in the code using the `self.move_group.set_end_effector_link("<YOUR_SPECIFIED_EEF_LINK>")`.
4. For move groups containing only links and or joints, you can not set and thus plan w.r.t. an end effector.

### Your environment
* **ROS Distro:** Melodic
* **OS Version:** ubuntu 18.03
* **Source:** v1.0.2

### Steps to reproduce
* Clone the [ros-planning/panda_moveit_config](https://github.com/ros-planning/panda_moveit_config) and [frankaemika/franka_ros](https://github.com/frankaemika/franka_ros) repositories.
* Build and source your `catkin_ws`.
* Run the `roslaunch panda_moveit_config demo.launch`.
* Run the moveit_commander script below and check the output.

```
import rospy
import moveit_commander
import sys

# Init service node
rospy.init_node("moveit_planner_server")

# initialize moveit_commander and robot commander
moveit_commander.roscpp_initialize(sys.argv)

# Get robot commander
robot = moveit_commander.RobotCommander(robot_description="robot_description", ns="/")

# Get move_group
move_group = robot.get_group("panda_arm")
print(move_group.get_end_effector_link())
move_group.set_end_effector_link("panda_gripper_center")
print(move_group.get_end_effector_link())

```

### Expected behaviour

For the `panda_arm` group the `panda_gripper_center` joint should be set as the end effector. Thus manually setting it using `move_group.set_end_effector_link("panda_gripper_center") is not needed.

### Actual behaviour
For the `panda_arm` group the `panda_gripper_center` link is not set as the end effector (see print statement 1). I therefore need to manually set it using `move_group.set_end_effector_link("panda_gripper_center"). After this is done, the end effector is set to be the `panda_gripper_center` (see print statement 2). Further, I can now successfully control the robot w.r.t. the `panda_gripepr_center`.

## Backtrace or Console output
- [Console log](https://gist.github.com/rickstaa/0b51642e68a40aa6d1d30e88f67524a4).

**Comment by rhaschke** [comment]
> 1. An end effector can only be set for a move group that consists of a chain of links.

That's true: Currently the `MoveGroupInterface` doesn't support Cartesian targets for kinematic trees that have several tips, because we can only set a single `PoseTarget`.

> 3. When in the srdf you set a link as the end effector that is not part of the move_group but part of a move_group higher in the chain it is not automatically set. 

The end-effector link should usually be part of the group you are controlling (and if not, it should be rigidly connected to it). If the group is a chain, the end effector link is [set automatically to the last link of the chain](https://github.com/ros-planning/moveit/blob/b1b1b98f3e93880e3bcf3b3d109acee5a5cb9edc/moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp#L131-L132). 

> You can, however, control it with the specified link as the end effector after setting it manually in the code using the self.move_group.set_end_effector_link("<YOUR_SPECIFIED_EEF_LINK>").

That's the expected behavior.

If you want panda_gripper_center to become your end effector link by default, you should extend the chain up to this link.

**Comment by rickstaa** [comment]
@rhaschke Thanks a lot for elaborating on my observations. I now have a clear understanding of the moveit_commander.
