### ISSUE TITLE
Consolidate moveit_resources for integration tests

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit#17]
According to the discussion in https://github.com/ros-planning/moveit_ros/pull/729, we should:

- [x] Rename `test` folder in `moveit_resources` to `pr2`
- [x] Add a simple robot arm (e.g. test_robot alias Fanuc), including a `moveit_config`, for testing
- [x] Add integration tests in `moveit_ros/test`

The existing PR stuff is used in several locations:
```
./moveit_core/robot_state/test/test_kinematic_complex.cpp
./moveit_core/kinematic_constraints/test/test_constraints.cpp
./moveit_core/planning_scene/test/test_planning_scene.cpp
./moveit_core/constraint_samplers/test/test_constraint_samplers.cpp
./moveit_core/collision_detection_fcl/test/test_fcl_collision_detection.cpp
./moveit_core/robot_model/test/test.cpp
```

UPDATE:

Opened PRs
- [x] https://github.com/ros-planning/moveit_resources/issues/7
- [x] https://github.com/ros-planning/moveit/issues/83

**Comment by davetcoleman** [comment]
+1!

**Comment by davetcoleman** [comment]
Ready for the second step - adding integration tests
