### ISSUE TITLE
Can not find subframe member from moveit_msgs::CollisionObject

### ISSUE THREAD

**Issue by kctoayo88** [ros-planning/moveit#1702]
### Description

I created a CollisionObject object and want to use subframe member of it, but I can't find subframe option.
Here is my includes:
```
#include <moveit_msgs/CollisionObject.h>
#include <moveit/move_group_interface/move_group_interface.h>
#include <moveit/planning_scene_interface/planning_scene_interface.h>
```
![擷取選取區域_001](https://user-images.githubusercontent.com/33343560/67561271-18ad5300-f74f-11e9-8ecb-2dca74d9fca7.jpg)

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04
* Binary build
* ros-kinetic-moveit:amd64/xenial 0.9.17-1xenial-20190914-001720+0000 uptodate

### Expected behaviour

Refer to this [tutorial](https://ros-planning.github.io/moveit_tutorials/doc/subframes/subframes_tutorial.html).

```
box.subframe_names.resize(5);
box.subframe_poses.resize(5);

box.subframe_names[0] = "bottom";
box.subframe_poses[0].position.y = -.05;
box.subframe_poses[0].position.z = 0.0 + z_offset_box;

tf2::Quaternion orientation;
orientation.setRPY((90.0 / 180.0 * M_PI), 0, 0);
box.subframe_poses[0].orientation = tf2::toMsg(orientation);
```

**Comment by rhaschke** [comment]
Subframes support was added into the master branch of MoveIt, but you are running on ROS Kinetic.
Thus, in order to use this feature, you need to build MoveIt from source.
