### ISSUE TITLE
Trajectory smoothness

### ISSUE THREAD

**Issue by janisa9** [ros-planning/moveit#1711]
### Description

Actually I don't know where to start and which package makes the issue, but I will try my best to express this issue as best as I can. In a few words I would describe this- trajectory produced by MoveIt! is not as smooth as it should be.

I am using UR5, with UrSim 3.9 version and the new Universal_Robots_ROS_Driver https://github.com/UniversalRobots/Universal_Robots_ROS_Driver , I think no problems in this package.

To show the issue I am moving robot between 2 predefined positions without any objects between them, using Move Group C++ Interface and plotting joint velocities. 

After going into details in several similar issues #416 #167 , I have tried all the Time Parameterization Algorithms and different motions planners. There was no difference between OMPL (RRTConnect) and STOMP in terms of trajectory smoothness.  Here you can see the plots:

Using Time optimal trajectory generation
![TOTG](https://user-images.githubusercontent.com/29726718/68205948-32169080-ffd4-11e9-9b0d-57173a88c562.png)

Using Iterative Parabolic Time Parameterization
![IPTP](https://user-images.githubusercontent.com/29726718/68205958-393d9e80-ffd4-11e9-9ebf-a8a4a4227423.png)

Using Iterative Spline Parameterization
![ISP](https://user-images.githubusercontent.com/29726718/68205969-4064ac80-ffd4-11e9-8982-17b660a35942.png)

As you can see TOTG seems to give the best results in trajectory, but anyway there are some velocity spikes which causes jiggle and sometimes trigger safety on the real robot. As in the next picture

![totg1](https://user-images.githubusercontent.com/29726718/68207325-5a53be80-ffd7-11e9-8d9f-3b96235d181c.png)

I have tried this on two separate pcs both running on kinetic, I've reinstalled and checked most of the packages, but could not find the solution. Maby I am missing something on this? 

If any additional information is needed please inform me.

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04
* Source build Melodic version on Kinetic
* melodic-devel 5344c09 [origin/melodic-devel] depth_image_octomap_updater: reset depth transfer function to standard values (#1661)

**Comment by gavanderhoorn** [comment]
Although I recognise the issue with the various time parameterisation algorithms, the fact that you're looking at the `joint_states` topic implies that this is state coming back from the robot, after execution.

As the `joint_trajectory_controller` is the entity that ultimately resamples the trajectory that MoveIt sends it, I would suggest to take a look there.

The problem could be due to resampling artefacts (the JTC must resample, as the `JointTrajectory` message is much too sparse (in time) to be executed on the UR controller directly).

I would also suggest to make sure you are running a real-time kernel -- as recommended by the setup instructions of the new driver -- as hickups in the execution of the JTC could also cause this (so called 'catch up' behaviour).

**Comment by janisa9** [comment]
Thank you for the quick response.

Yes indeed, I am not running a real-time kernel. In fact, I am already preparing another work-station with a clean install, where I will use a real-time kernel. Will make tests and see if it resolves "catch up" behaviour.

In the meantime to ensure that this is the problem would comparison between trajectory published on `/scaled_pos_traj_controller/follow_joint_trajectory/goal` and state coming back from the robot on `joint_state` topic be able to prove this on some level?

**Comment by gavanderhoorn** [comment]
Comparison between the incoming trajectory and the way it is eventually executed would certainly be a good thing to do, yes.

I would perhaps also see what the `state` of the controller is. This is published by the JTC on a topic.

That would show you the difference between what the controller outputs and what the robot actually executes.

**Comment by janisa9** [comment]
Yes, I think this pretty much shows the problem and using a real-time kernel should solve this. Thank you! 

![comparision](https://user-images.githubusercontent.com/29726718/68277776-94c16800-0078-11ea-99be-7c123ea0b91d.png)

Anyway, do you have ant idea why Iterative Spline Parameterization makes this weird trajectory?

**Comment by janisa9** [comment]
Installed fresh ubuntu 18.04 with real-time kernel and ROS-melodic, the problem is gone. So probably this can be closed.

But I am still curious about Iterative Parabolic Time Parameterization and Iterative Spline Parameterization why the trajectory differs so much from TOTG and the fact why IPTP is used by default in MoveIt!?

**Comment by v4hn** [comment]
> why IPTP is used by default in MoveIt!?

For historic reasons. You are free to create a pull-request to change the default.

TOTG can move the waypoints returned by sampling. This is not a very nice characteristic with the current pipeline and some additional collision checking would have to be added.

ISP was meant to be a sane replacement for IPTP, but somehow didn't make it to the default yet.

IPTP usually isn't the best, but was claimed to be the fastest at some point (never benchmarked myself and I'm not convinced the difference, if any, is relevant these days).

**Comment by felixvd** [comment]
Related: https://github.com/ros-planning/moveit/issues/2183
