### ISSUE TITLE
WMD19 - Prepare issues

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#1721]
World MoveIt Day is around the corner and almost all open issues with the `moveit day candidate` label are older than a year (or were added by me).

If you have *any* unresolved issue in or around MoveIt in mind that you would like to see resolved/ improved, but that is not yet documented as an issue here, please take the time to write down the essential information required to reproduce it and have someone write a patch for it!

If the issue can be resolved within a day, add the `moveit day candidate` label so people can tackle the issue next week.

This goes especially to all official maintainers
@davetcoleman @rhaschke @130s @IanTheEngineer @gavanderhoorn @jrgnicho @bmagyar @mlautman @jonbinney @henningkayser @BryceStevenWilley @mamoll 

- Edit -

Also ping @felixvd and @k-okada.

**Comment by felixvd** [comment]
Could you add the label to #1730 , #1556 and #1065 ? I can't do it myself. Thanks!

**Comment by rhaschke** [comment]
> Could you add the label to #1730 , #1556 and #1065 ?

Done.

**Comment by v4hn** [comment]
over for this year.
