### ISSUE TITLE
Write tests for subframes

### ISSUE THREAD

**Issue by felixvd** [ros-planning/moveit#1733]
As we might be changing the collision environment soon, and I haven't gotten around to doing this after #1439, tests for the subframe functionality will be very helpful.

This issue can teach you how to write tests and should be easy enough to implement with the help of [this tutorial](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html). The motions and commands in [the subframe tutorial](https://ros-planning.github.io/moveit_tutorials/doc/subframes/subframes_tutorial.html) make some good test cases.

Related to #643, which is also still a great WMD issue.

Also I know this is my unfinished business, but that's how I know it's not hard, so 🙇‍♂️

**Comment by tylerjw** [comment]
We are on it!
