### ISSUE TITLE
setup assistant: split command line and gui tools

### ISSUE THREAD

**Issue by mikeferguson** [ros-planning/moveit#176]
Ported from https://github.com/ros-planning/moveit_setup_assistant/issues/113

It would be great have standalone tools library and command line tool without QT dependencies.
I suggest to move the moveit_setup_assistant into a sub-directory and to factor out the non-GUI code into a moveit_setup_tools package.

**Comment by mikeferguson** [comment]
Might also be good to add additional command-line arguments as mentioned in https://github.com/ros-planning/moveit_setup_assistant/issues/87

**Comment by v4hn** [comment]
@ipa-mdl Why? you never gave a reason why this would make sense.

**Comment by ipa-mdl** [comment]
> @ipa-mdl Why? you never gave a reason why this would make sense.

The key is "without QT dependencies". I have written the command line tools (ros-planning/moveit_setup_assistant#108) for headless creation and maintenance of SRDFs. With extensive automated testing (Travis etc.) and container-based deployment (Docker etc.) clean dependencies get more important again.

`moveit_ros_visualization` adds 100 debian packages and 350 MB of disk usage which are not needed for headless operation.

@mikeferguson: I think ros-planning/moveit_setup_assistant#87 is already addressed by `collisions_updater`

**Comment by v4hn** [comment]
Oh, I haven't seen the `collision_updater` before. Sounds like it's pretty useful!
@ipa-mdl: Could you maybe add a short description of this tool to [the setup_assistant tutorial](http://docs.ros.org/indigo/api/moveit_tutorials/html/doc/setup_assistant/setup_assistant_tutorial.html#additional-reading)?
That would be awesome!
Note the "Edit on Github" link on top of the page :)

**Comment by davetcoleman** [comment]
+1 to adding to the tutorial

**Comment by davetcoleman** [comment]
Given this issue is 3 years old, I will close this until someone with a strong use case presents a prototype...
