### ISSUE TITLE
More coverage in .travis.yaml

### ISSUE THREAD

**Issue by 130s** [ros-planning/moveit#181]
I noticed that we might also want to test Debs on Travis now that the Debs of dependent packages are available. Once `moveit` is released into all IJK, we can update .travis.yaml.

Advantage of more coverage (source, Debs): Obviously we can be more sure about the stability.

Drawback: Longer runtime of CI jobs. CI job can inevitably fail if only a part of the change that traverses over multiple packages is available (e.g. #180).

**Comment by davetcoleman** [comment]
What do you mean by test debs? How would you implement this?

I don't think it needs to increase the CI runtime if you just add a new job to the [matrix](https://github.com/ros-planning/moveit/blob/indigo-devel/.travis.yml#L15)
