### ISSUE TITLE
ImportError: cannot import name MoveGroupCommander?

### ISSUE THREAD

**Issue by Musyue** [ros-planning/moveit#1819]
### Description

Hi, guys,
When I use moveit to simulate our robot, It was ok at first.
But when I compiling OMPL from source code and make install, then I go back to use ros moveit to control our robot. It throws an error. like this:
Traceback (most recent call last):
    from moveit_commander import MoveGroupCommander, PlanningSceneInterface
ImportError: cannot import name MoveGroupCommander
And then I skip this code,just run moveit_commander.roscpp_initialize(sys.argv)
I got this error:
    moveit_commander.roscpp_initialize(sys.argv)
AttributeError: 'module' object has no attribute 'roscpp_initialize'
I try to uninstall the ros-melodic-moveit-commander, and reinstall, however, it still had the error.
I have no idea about this, and I guess it may be because I install the OMPL.
could you help me?
Thank you
### My environment
* ROS Distro: [Melodic]
* OS Version: Ubuntu 18.04
* Moveit version, I just reinstall today

**Comment by rhaschke** [comment]
The python error is probably unrelated to your OMPL source build. I guess you screwed your ROS workspace somehow. Did you correctly define your underlay? Did you correctly source your new workspace? Have a look at your environment, particularly `ROS_PACKAGE_PATH`, `PYTHONPATH`, and `LD_LIBRARY_PATH`. They all should list your local workspace pathes before `/opt/ros` pathes.

**Comment by Musyue** [comment]
@rhaschke Thanks for your reply. I solved it by deleting the workspace's build and devel folder. And Everything is fine. Thank you very much. I will close this bug. Sorry to bother you.

**Comment by thebirdgr** [comment]
yes deleting the build and devel folders and rebuilding the workspace with catkin_make helped.
