### ISSUE TITLE
Since #1760, RobotTrajectory's (shallow) copy constructor deletes all waypoints

### ISSUE THREAD

**Issue by beiju** [ros-planning/moveit#1833]
I believe this issue (currently) only affects `master`, which I was using to test out `moveit_jog_arm`.

The copy constructor for `RobotTrajectory` that was added in #1760 always clears the `waypoints_` list ([L59](https://github.com/ros-planning/moveit/blob/a6c173f3fbd6a3433908c370b0178ef8c6e9d6e8/moveit_core/robot_trajectory/src/robot_trajectory.cpp#L59)). This makes sense during a deep copy, because they're then replaced by copied `RobotStates`, but during a shallow copy the waypoints are just lost. I assume that line was meant to be inside the if statement.

The effect of this is that waypoints are deleted when returning a trajectory from a function, when passing a trajectory to a function by value, as part of aggregate initialization, and probably at least a dozen other situations.

**Comment by rhaschke** [comment]
Thanks for reporting this issue. Next time, please consider filing a PR fixing the issue directly.
