### ISSUE TITLE
Fast FK computation for move group python interface

### ISSUE THREAD

**Issue by vvanirudh** [ros-planning/moveit#1848]
I am trying to compute FK of PR2 7D arm for a project I am working on, and I will be computing FK for a wide range of joint values. So, I need the FK computation to be fast. So far, I have been using the movegroup python interface for my motion planning and would like to continue using python. 

My current solution for FK is to use the rosservice '/compute_fk'. But I have noticed that this is slow (even with a persistent service, it takes 1ms on average to return the fk solution). I need the computation to be around 0.1ms. 

What do you suggest? How should I go about this? One solution I could think of is to write a C++ node that has a subscriber and publisher, that listen to my python node for the joint angles and upon receiving computes FK solution in C++ (using getGlobalLinkTransform) and publishes it to the python node. I am not sure if this will be any faster than the service.

**Comment by rhaschke** [comment]
Currently, we don't yet have an API for this. But there is a pending PR: https://github.com/ros-planning/moveit/pull/1622.
Please test and review it, thus increasing the chances that it will be merged soon...
