### ISSUE TITLE
Flaky unit test in jog_arm

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit#1858]
As pointed out [here](https://github.com/ros-planning/moveit/pull/1854#issuecomment-577555883), there is a flaky unit test in moveit_jog_arm: [Travis failure](https://travis-ci.org/ros-planning/moveit/jobs/640614191#L1552).
The culprit is this code snippet:
https://github.com/ros-planning/moveit/blob/e582953c8c7a92f19674479f9986fd45d44d4f92/moveit_experimental/moveit_jog_arm/test/integration/test_jog_arm_integration.py#L103-L106

The same code repeats here (consider to unify):
https://github.com/ros-planning/moveit/blob/e582953c8c7a92f19674479f9986fd45d44d4f92/moveit_experimental/moveit_jog_arm/test/integration/test_jog_arm_integration.py#L79-L82

**Comment by AndyZe** [comment]
OK, I'll take a look. It could also be that the "settling time" was reduced in this commit:

https://github.com/ros-planning/moveit/commit/e0b4f854edd3a792ec124bc3d1af816dc3cc190a#diff-23ab07d8dbd5935900be742c099b4b4d
