### ISSUE TITLE
prefer `moveit::core` over `robot_state` namespace

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#1878]
Confusingly, [robot_model/robot_model.h](https://github.com/ros-planning/moveit/blob/master/moveit_core/robot_model/include/moveit/robot_model/robot_model.h#L621) creates alias namespaces for `moveit::core`. Ioan added this long ago to stay backward compatible with old usage.

However, as a result the namespaces where not aligned throughout the codebase (grep for `robot_state::RobotState`, for example) and the alias is still there.

I believe we should deprecate the old names and align our codebases not to use the old names.

@davetcoleman

**Comment by davetcoleman** [comment]
This duplicate namespacing has always bothered me. @v4hn why did you close this? How about we make the change now in MoveIt 2? @henningkayser

**Comment by rhaschke** [comment]
Actually, most of these namespace instances were removed in #1924. But there are still a few left...

**Comment by v4hn** [comment]
I was under the impression the linked pr fixed it, but @rhaschke is right, apparently there are still some places left..

**Comment by v4hn** [comment]
pr will be ready in 5 :-)
