### ISSUE TITLE
$CATKIN_WS is not defined in the docker container

### ISSUE THREAD

**Issue by felixvd** [ros-planning/moveit#1891]
It is awkward that the [clang-tidy commands from our style guide](https://moveit.ros.org/documentation/contributing/code/) do not work in the official docker container, because the environment variable CATKIN_WS isn't set. Should it be set? Is there a different convention that should be followed?

If it is supposed be set, I'll file a PR to add `ENV CATKIN_WS /root/ws_moveit` to [this Dockerfile](https://github.com/ros-planning/moveit/blob/master/.docker/source/Dockerfile).

edit: I don't know that I'd label this a bug, but I guess that happens automatically now.

**Comment by rhaschke** [comment]
We changed this variable to `ROS_WS` to become catkin-agnostic (ROS2 uses colcon):
https://github.com/ros-planning/moveit_ci/blob/f243457dd3340a76b0c44b9a9fc8f57096b94fe1/travis.sh#L353

Please file a PR to fix the style guide docs. Thanks.
