### ISSUE TITLE
Disable codecov triggering red 'X' for pull-request CI status

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit#1896]
Dear @tylerjw, @davetcoleman,
while having the codecov report shown in github is great, can we relax the requirement to not decrease coverage with PRs? This creates lots of spurious "not-mergable" flags, I one always needs to inspect the details, why a particular PR is not mergable.
As we currently have extremely low coverage, I suggest to invert the messaging and provide extra positive feedback if the coverage is significantly increased, because a new test case was added.
Is that possible?

**Comment by rhaschke** [comment]
Ping @tylerjw. We should discuss our strategy in the next maintainer meeting.
Could you, @tylerjw, figure out the technical possibilities until then?

**Comment by felixvd** [comment]
Cross-referencing the [discourse post](https://discourse.ros.org/t/moveit-maintainer-meeting-feb-27th/12812/5?u=felixvd) for the meeting.

**Comment by jschleicher** [comment]
See PR #1917

**Comment by v4hn** [comment]
The remaining issue, as discussed at the last maintainer meeting is the red 'x' in every pull-request that fails codecov.

This is not wanted right now and makes the maintainers' job harder looking through all open requests.

**Comment by jschleicher** [comment]
@v4hn I think, this was fixed in #1917, see current PR #2027 for a working example: coverage decreases and it is still green. Suggesting to close here.
