### ISSUE TITLE
‘ Unable to locate package ros-melodic-moveit’

### ISSUE THREAD

**Issue by xu-ye** [ros-planning/moveit#1910]
### Description
I wanna to use moveit to learn to how to control the robotics arms.But while i am installing ,problems occurred..
![图片](https://user-images.githubusercontent.com/55088275/75023306-889bd200-54d2-11ea-988b-723794ebd416.png)

### My environment
* ROS Distro: [Melodic]
* OS Version:  Ubuntu 18.04

**Comment by rhaschke** [comment]
Did you follow the install steps for ROS?
http://wiki.ros.org/melodic/Installation/Ubuntu

This looks like, you didn't configure the ROS package repository.

**Comment by felixvd** [comment]
Also, please consider posting your question here instead: https://answers.ros.org/questions/
