### ISSUE TITLE
Connect Moveit with KUKA

### ISSUE THREAD

**Issue by CesMak** [ros-planning/moveit#1913]
Hey there,

I successfully connected my 30HA-KUKA robot using [kuka_eki_hw_interface](https://github.com/ros-industrial/kuka_experimental/tree/indigo-devel/kuka_eki_hw_interface) to my Ubuntu 18.04 melodic ROS PC. 

I am now able to control the robot using
` rosrun rqt_joint_trajectory_controller rqt_joint_trajectory_controller`

**Goal**
I would like to control the EE of the real Robot using MoveIt Plugin in Rviz.

**Progress**
I read in [Low-Level-Controllers-MOVEIT](https://ros-planning.github.io/moveit_tutorials/doc/controller_configuration/controller_configuration_tutorial.html) that a FollowJointTrajectory action service is required. 

If I do rostopic echo (when connected to the real Robot with kuka_eki_hw_interface) I get:

```
/joint_states
/position_trajectory_controller/command
/position_trajectory_controller/follow_joint_trajectory/cancel
/position_trajectory_controller/follow_joint_trajectory/feedback
/position_trajectory_controller/follow_joint_trajectory/goal
/position_trajectory_controller/follow_joint_trajectory/result
/position_trajectory_controller/follow_joint_trajectory/status
/position_trajectory_controller/state
/rosout
/rosout_agg
/tf
/tf_static
```

-> So this means I have an action server as required already right?

Next I created this launch file:
```
<?xml version="1.0" encoding="utf-8"?>
<launch>

 <!-- Load the URDF, SRDF and other .yaml configuration files on the param server -->
 <include file="$(find panda_moveit_config)/launch/planning_context.launch">
   <arg name="load_robot_description" value="true"/>
 </include>

 <!-- If needed, broadcast static tf for robot root -->
 <node pkg="tf2_ros" type="static_transform_publisher" name="virtual_joint_broadcaster_1" args="0 0 0 0 0 0 world panda_link0" />

 <!-- Set the param that trajectory_execution_manager needs to find the controller plugin -->
 <arg name="moveit_controller_manager" default="moveit_simple_controller_manager/MoveItSimpleControllerManager" />
 <param name="moveit_controller_manager" value="$(arg moveit_controller_manager)"/>

 <!-- load controller_list -->
 <rosparam file="$(find kuka_eki_hw_interface)/config/moveit_controller.yaml"/>

  <node type="rviz" name="rviz" pkg="rviz" args="-d $(find kuka_eki_hw_interface)/config/config_file.rviz" />

</launch>
```
And I have this moveit_controller.yaml:
```
controller_list:
 - name: panda_arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - joint_a1
     - joint_a2
     - joint_a3
     - joint_a4
     - joint_a5
     - joint_a6
```

However when I launch this launch file I get as topics:
```
/attached_collision_object
/clicked_point
/initialpose
/move_base_simple/goal
/move_group/cancel
/move_group/display_planned_path
/move_group/feedback
/move_group/goal
/move_group/monitored_planning_scene
/move_group/result
/move_group/status
/planning_scene
/planning_scene_world
/recognized_object_array
/rosout
/rosout_agg
/rviz/motionplanning_planning_scene_monitor/parameter_descriptions
/rviz/motionplanning_planning_scene_monitor/parameter_updates
/rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic/feedback
/rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic/update
/rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic/update_full
/tf
/tf_static
/trajectory_execution_event
```
which looks different from the one I should have when following the above tutorial on a low level controller:
```
        /panda_arm_controller/follow_joint_trajectory/goal
        /panda_arm_controller/follow_joint_trajectory/feedback
        /panda_arm_controller/follow_joint_trajectory/result
        /hand_controller/gripper_action/goal
        /hand_controller/gripper_action/feedback
        /hand_controller/gripper_action/result
```

**Comment by felixvd** [comment]
This question would be better suited for and probably get more views on [ROS answers](https://answers.ros.org/questions/).

To give a stub of a response: I am confused why you start up the panda's moveit config although you are using a KUKA robot. You should probably start your troubleshooting there. Do take it over to ROS answers though. You will get better responses.

**Comment by gavanderhoorn** [comment]
Unfortunately the response to MoveIt related questions on ROS Answers has been really low. It makes little sense to direct people to ROS Answers when none of the MoveIt maintainers actually monitor that forum.

I can understand why users start posting these sort of questions here because of that.

I realise it's not just the maintainers that should answer questions there, but it would seem the reality is that either MoveIt users with sufficient experience to answer these types of questions do not frequent ROS Answers, or there are no MoveIt users on ROS Answers, period.

**Comment by felixvd** [comment]
I also don't judge anyone for it, and it's not certain every answer will get a better response over there, but at least it is better to put it in a central place to search.

**Comment by CesMak** [comment]
moved and **updated** Qustion to:

https://answers.ros.org/question/345728/connect-real-kuka-to-moveit/

**Comment by tylerjw** [comment]
@CesMak was your issue solved?  Should this be closed?

**Comment by CesMak** [comment]
Yes can be closed

Tyler Weaver <notifications@github.com> schrieb am Do., 9. Apr. 2020, 22:38:
