### ISSUE TITLE
Fail: RECALLED: This goal was canceled because another goal was recieved by the simple action server

### ISSUE THREAD

**Issue by lusu8892** [ros-planning/moveit#1916]
### Description

I am running my code, Moveit and Rviz on the remote PC (Master PC), this PC is running roscore also. The hardware is paired with another PC (aka Hardware PC). My code will use move_group to call pick function to plan a object picking planning. However I got the warning, **Fail: RECALLED: This goal was canceled because another goal was recieved by the simple action server.**

But if I run my code, Moveit and Rviz on Hardware PC, but keeping roscore on the Master PC, everything works fine.

### Your environment
* ROS Distro: [Kinetic|]
* OS Version: All PCs running Ubuntu 16.04
* Source or Binary build?
* If binary, which release version?
* If source, which branch?

**Comment by v4hn** [comment]
Your code calls the action twice for some reason, while one call is still processed.
`rostopic echo /pickup/goal` to monitor the requests you send.

Almost surely, this is a bug in your setup.

**Comment by lusu8892** [comment]
Hi v4hn

I checked the topic, I can not target where did I send the same message to the action server.

I tried running debug mode. the pick_action_client_ only sendGoal once, I do not know where I sent it twice.

**Comment by v4hn** [comment]
Sorry but this seems to be close to impossible to debug or resolve without access to your specific setup.
