### ISSUE TITLE
Can't run specific tests with rostest

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit#1918]
Even after sourcing the setup.bash rostest can't find individual tests.

if you type `rostest moveit_ros_planning_interface` there are no tests found in it to run.

**Comment by Dale-Koenig** [comment]
catkin compiles to install rather than normal build, ros tools seem to try to take you to the install directory instead.  so `rostest` will look in the install directory and find no tests.

**Comment by rhaschke** [comment]
That's correct. If you want to be able to run tests, you need to source the devel space, not the install space. Closing the issue.
