### ISSUE TITLE
moveit_setup_assistant file dialog should start from current directory

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit#1922]
When browsing to an existing package, the setup assistant used to start from the current working directory. It would be nice to restore that behavior because it's a good time saver.

![browse_to_package](https://user-images.githubusercontent.com/11284393/75683836-6dad2880-5c5d-11ea-820d-3f2c736ce616.png)

**Comment by rhaschke** [comment]
This was changed in #1618 by @JafarAbdi. Obviously, the "security fix" suggested in #1497, doesn't yield the correct path. Actually, `QDir::currentPath()` yields the current application path, i.e. the last path explicitly set. While we don't explicitly set a path, ROS internally does when searching for packages. But even fetching the path directly after start, just yields the ROS default path (~/.ros).
Hence, my suggestion is to revert #1618.

**Comment by felixvd** [comment]
Just want to add that `roslaunch X_moveit_config setup_assistant.launch` fills in the path for that package and is a great timesaver as well.

**Comment by jschleicher** [comment]
Fixed in #1932. Please Close.
