### ISSUE TITLE
Do you have example code for collision_detection?

### ISSUE THREAD

**Issue by Hubert51** [ros-planning/moveit#1929]
I want to calculate the distance between the robotic arm and closest point in the environment to avoid the collision. I also want to the corresponding points on the arm and environment. 

But now I do not know how to use Moveit functionality to do that. 

Would you like to provide some simple examples to teach me to do that?

Thank you very much

**Comment by felixvd** [comment]
MoveIt uses libraries like FCL and Bullet to do the collision checking. You can see the integration [here](https://github.com/ros-planning/moveit/tree/master/moveit_core) in the folders `collision_detection`, `collision_detection_fcl` and `collision_detection_bullet`. There is no ready-made example for checking the distance between two collision objects, but [this function](https://github.com/ros-planning/moveit/blob/master/moveit_core/collision_detection_fcl/src/collision_common.cpp#L403) does it in FCL. 

I can imagine some use cases for checking the distance between two objects in MoveIt during "normal" use, but I don't think it is a very pressing issue, and it also seems like a functionality that can easily confuse users if the collision results are not intuitive. If you want to implement it for your own purposes, extending the PlanningSceneInterface would make sense.

**Comment by Hubert51** [comment]
Thank you!
