### ISSUE TITLE
class RobotTrajectory bug with getDuration() melodic

### ISSUE THREAD

**Issue by edetleon** [ros-planning/moveit#1989]
### Description

When the function getDuration() from the class robot_trajectory::RobotTrajectory is called it throws an error "getDuration()".error).

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04
* Binary, no version

### Steps to reproduce
* Create a C++ node, or open an existing one.
* create a RobotTrajectory object with constructor : `robot_trajectory::RobotTrajectory::RobotTrajectory(const robot_model::RobotModelPtr & robot_model, const std::string & group);`

+ Compile your code with` catkin_make`

### Expected behaviour
catkin_make doesn't throw an error.

### Actual behaviour
An error is thrown.

### Backtrace or Console output

Extract from my code :
  ```
    robot_model_loader::RobotModelLoader robot_model_loader("robot_description");
      robot_model::RobotModelConstPtr robot_model1 = robot_model_loader.getModel();
      const robot_model::RobotModelConstPtr& ptrmod = robot_model1;
      const string str = "Leg";
      const string& strptr = str;
      robot_trajectory::RobotTrajectory traj(ptrmod, strptr);
      const double dur = traj.getDuration();

```

Console output :
```
/home/edith/catkin_ws/src/cpp_move_patte/src/move_patte.cpp: In function ‘int main(int, char**)’:
/home/edith/catkin_ws/src/cpp_move_patte/src/move_patte.cpp:197:31: error: ‘class robot_trajectory::RobotTrajectory’ has no member named ‘getDuration’
       const double dur = traj.getDuration();
                               ^~~~~~~~~~~
cpp_move_patte/CMakeFiles/move_patte.dir/build.make:62: recipe for target 'cpp_move_patte/CMakeFiles/move_patte.dir/src/move_patte.cpp.o' failed
make[2]: *** [cpp_move_patte/CMakeFiles/move_patte.dir/src/move_patte.cpp.o] Error 1
CMakeFiles/Makefile2:5376: recipe for target 'cpp_move_patte/CMakeFiles/move_patte.dir/all' failed
make[1]: *** [cpp_move_patte/CMakeFiles/move_patte.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
```

C++ class :
http://docs.ros.org/melodic/api/moveit_core/html/classrobot__trajectory_1_1RobotTrajectory.html#af827ef5d4a1a30176f2599c701683f27

**Comment by v4hn** [comment]
The method is new and was added in https://github.com/ros-planning/moveit/pull/1554 (backported to melodic in d99e47bdf2af7864e99617f414ddd8016965917b).

There has not been a melodic release since then, so you have to compile from source if you want to use the method.
Note that this is just a convenience wrapper you can easily replace by iterating over the individual durations.
