### ISSUE TITLE
Cleanup old HTML in markdown-based website

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#2]
The MoveIt! website was migrated from a Wordpress site, and much of the formatting is still in HTML blocks that are not ideally formatted. We would like to convert this information to cleaner markdown, and move images to the proper locations. For example the [install page](https://raw.githubusercontent.com/julienking/julienking.github.io/master/install/index.markdown).

**Comment by dbolkensteyn** [comment]
The site's repo is here: https://github.com/julienking/julienking.github.io

**Comment by davetcoleman** [comment]
This has largely been accomplished, closing
