### ISSUE TITLE
support path constraints in computeCartesianPath of MoveGroup interface

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#20]
[This request](https://github.com/ros-planning/moveit_ros/pull/414) has been around for quite a while and it is still relevant.
However, it fails to merge at the moment and needs a helping hand to merge it into our `kinetic-devel` branch.

This is a special case of https://github.com/ros-planning/moveit/issues/6 .

**Comment by dbolkensteyn** [comment]
I'll give this one a try

**Comment by davetcoleman** [comment]
great!

**Comment by dbolkensteyn** [comment]
I've migrated the old PR

Note that it didn't change the Python bindings, so this feature is only available from C++. I'm not really comfortable with Python - so I won't add it there.
