### ISSUE TITLE
Error compiling on Ubuntu 20.04

### ISSUE THREAD

**Issue by emmanuelkring** [ros-planning/moveit#2005]
### Description
I am trying to compile the master branch on Ubuntu 20.04 with noetic and I get this error:
>Make Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
abs_lib_eigenpy
    linked by target "moveit_move_group_interface_python" in directory /home/emmanuel/moveit_ws/src/moveit/moveit_ros/planning_interface/move_group_interface

When I recompile the error goes away.

**Comment by rhaschke** [comment]
This is an open issue with the release of eigenpy: https://github.com/ros/rosdistro/pull/24287.
I suggest reverting eigenpy to the previous release (1.6.9).
