### ISSUE TITLE
Codecov needs login

### ISSUE THREAD

**Issue by gleichdick** [ros-planning/moveit#2006]
### Description

Login to Codecov is required to analyze the codecov report generated by the pipeline.
Otherwise, HTTP 403 occurs.

### Steps to reproduce

Open a private browser window and click on any link in one of the latest [codecov reports](https://github.com/ros-planning/moveit/pull/1983#issuecomment-607150995).

**Comment by gleichdick** [comment]
Tested it again, seems to work again

**Comment by gleichdick** [comment]
Nope, broken again :thinking: 
![image](https://user-images.githubusercontent.com/43565432/78247246-d56bc300-74ea-11ea-9101-3ea67fd65f53.png)

**Comment by gavanderhoorn** [comment]
It's always been like this for me, at least here in `ros-planning`.

**Comment by tylerjw** [comment]
This seems like an issue with how the codecov website is trying to get you to sign up using your github more than an issue with how we are using it.  Would you suggest an alternative to codecov.io that doesn't gate viewing details of the reports?  Atleast codecov.io is free for open source projects like ours and makes nicely formatted comments on PRs that you can view without signing in to their site.

**Comment by gleichdick** [comment]
Ah, thanks, I didn't know that codecov does that in general.
