### ISSUE TITLE
Meta: Allow labeling for core contributors

### ISSUE THREAD

**Issue by simonschmeisser** [ros-planning/moveit#2039]
I'm not sure if this is actually possible with github but I would really like to put labels on stuff! (Who doesn't? ;) )

My main motivation currently is to put "MoveItDay" on some of the doc-issues I opened so I don't have to do it myself ...

@davetcoleman

**Comment by gavanderhoorn** [comment]
The [Triage access level](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level) should allow this.

**Comment by rhaschke** [comment]
@davetcoleman, are you the only one with access rights at the ros-planning organization level?
I just wanted to grant this right to contributors (which, I think makes absolutely sense), but I don't see the settings tab at the organization level.

**Comment by felixvd** [comment]
Would be great if this worked, has been an issue for a while.

**Comment by v4hn** [comment]
> I just wanted to grant this right to contributors (which, I think makes absolutely sense), but I don't see the settings tab at the organization level.

I believe the only MoveIt developers with Owner access to ros-planning (outside the general OSRF/OR crowd) are Dave and Mike Ferguson.

**Comment by simonschmeisser** [comment]
@davetcoleman friendly ping before adding it to tomorrows list

**Comment by davetcoleman** [comment]
"Apply labels" is now available via "Triage" access. I've just changed the "Core Contributors" access to "Triage" for all MoveIt packages.

Sorry for my delay in seeing this, Felix just emailed me the link to this issue!

**Comment by davetcoleman** [comment]
Documented: https://github.com/ros-planning/moveit.ros.org/pull/453
