### ISSUE TITLE
RViz panel: parameters list can move right without scrollbar

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#2062]
I guess the picture says it all:

![clipped_parameters](https://user-images.githubusercontent.com/680358/81281955-d3050780-905a-11ea-8501-b979e1be2841.png)

This is on ROS melodic in Ubuntu 18.04.

I believe there is a similar issue, possibly the same, with RViz parameter edits.
Edit: the latter one might be related to my very custom system and I can't force it in Ubuntu right now...

**Comment by felixvd** [comment]
Fixed in #2310
