### ISSUE TITLE
Bug: unable to warn user when the service is not available.

### ISSUE THREAD

**Issue by yeshwanths88** [ros-planning/moveit#2064]
https://github.com/ros-planning/moveit/blob/efa7fdca8a6999dbfcc28171b83deb67b258438a/moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp#L719

Since the check is for the srvice client object and not for the service itself, eventhough a service is not available, it is not caught here. And the user gets wrong error message: "Grasp planning failed. Unable to pick."
But in reality the service itself is not available.
Alternatively we could check for the service:
`if (!plan_grasps_service_.waitForExistence(ros::Duration(2)))`

**Comment by v4hn** [comment]
I proposed https://github.com/ros-planning/moveit_msgs/pull/73 to be able to differentiate between service failure and planning failure in this code.
