### ISSUE TITLE
memroy leaks for days

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit#2075]
I called out the first chunk of memory leaks found using this PR: #2057

This is to track the fact that there are more and I didn't continue to copy and paste from the logs from them.  Once the others are fixed or resolved some other way we should re-run the test to see what memory leaks persist.

**Comment by jliukkonen** [comment]
I'll take a look into those leaks today as my World MoveIt Day task. Hopefully manage to squash at least couple of them.
