### ISSUE TITLE
JogArm -> Servo and API migration giude

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit#2175]
I'm not sure where to put this but here are my notes about the recent changes in `jog_arm/servo`:

https://gist.github.com/tylerjw/e6443adaff45490f35932fd280af10a5

**Comment by rhaschke** [comment]
As we didn't release jog_arm before, we don't need to advertise this guide, do we?

**Comment by tylerjw** [comment]
Yes, and no.  People may have been using jog_arm from master and would be surprised their code doesn't build any more.

**Comment by v4hn** [comment]
> People may have been using jog_arm from master and would be surprised their code doesn't build any more.

:+1: There was a lot of advertisement for the old name, so some notes somewhere make sense. Maybe just create a discourse post? You could also add a quick mention in MIGRATION.md even if it's no breaking change between distributions.

**Comment by tylerjw** [comment]
I'll take a second pass at making this guide more complete and then I'll post it to discourse today.
