### ISSUE TITLE
No header for OMPLPlannerManager

### ISSUE THREAD

**Issue by gchabert** [ros-planning/moveit#2176]
Maybe a newbie question.
I'm trying to develop a plugin which brings some modifications to the OMPL planner. 
I would like my planner manager to inherit from OMPLPlannerManager but there is no header for this class.
Is there any reason why? If not, could it be possible to create such header?

Gilles

**Comment by v4hn** [comment]
> Is there any reason why?

Probably nobody expected someone to inherit from it.

> If not, could it be possible to create such header?

Sure, feel free to create a pull-request. Make sure to test the plugin you develop on top of it before. Off the top of my head, I'm not sure pluginlib plugins can inherit from other plugins.

**Comment by gchabert** [comment]
Thanks for the quick answer, I will make a pull request.
I will not try to make the enter plugin inherit, just the c++ classes inside.
