### ISSUE TITLE
CHOMP HMC is commented

### ISSUE THREAD

**Issue by iskandersauma** [ros-planning/moveit#2192]
### Description

I am trying to uncomment the HMC part of CHOMP but I cannot seem to make it work. It fails because it calls to something called collisionProximitySpace which is not implemented. Has anyone managed to uncomment HMC and make it work? For me it seems that the code was left incomplete.

### Your environment
* ROS Distro: [Melodic]
* OS Version: Ubuntu 18.04
* Source build master bransch

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by simonschmeisser** [comment]
I haven't actually checked, but maybe you can find the missing modules in https://github.com/ros-planning/moveit_experimental ?
