### ISSUE TITLE
Point cloud topic has data, but NO Octomap in Rviz!!!

### ISSUE THREAD

**Issue by yiyinglai** [ros-planning/moveit#2208]
### Description
On hardware, point clouds are provided by RealSense D415. PointCloud2 exists, but no Octomap appears.

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04

### Setup
Content of `niryo_one_moveit_config/config/sensors_3d.yaml` :

    sensors:
      - filtered_cloud_topic: filtered_cloud
        max_range: 5.0
        max_update_rate: 1.0
        padding_offset: 0.1
        padding_scale: 1.0
        point_cloud_topic: /camera/depth/points
        point_subsample: 1
        sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater

Content of `niryo_one_moveit_config/launch/sensor_manager.launch.xml`:

    <launch>
    
      
    
      
      <rosparam command="load" file="$(find niryo_one_moveit_config)/config/sensors_3d.yaml" />
    
      
      
      <param name="octomap_resolution" type="double" value="0.025" />
      <param name="max_range" type="double" value="5.0" />
    
      
      <arg name="moveit_sensor_manager" default="niryo_one" />
      <include file="$(find niryo_one_moveit_config)/launch/$(arg moveit_sensor_manager)_moveit_sensor_manager.launch.xml" />
    
    </launch>

### Expected behaviour
Octomap shows up as in simulation.
It works for me, as shown in the following figure (I used [RealSense plugin](https://github.com/pal-robotics/realsense_gazebo_plugin/tree/kinetic-devel) to simulate the camera).
![sim octomap](https://user-images.githubusercontent.com/57045546/87477835-cb338780-c5f6-11ea-882f-51561ff523cc.png)
And in `/move_group/monitored_planning_scene`, I had actual content in `octomap`:

    name: "(noname)+"
    robot_state: 
      joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 428
            nsecs: 194000000
          frame_id: "/world"
        name: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6, gripper_joint, left_clamp_joint,
      left_rod_joint, right_gear_joint, right_clamp_joint, right_rod_joint]
        position: [0.0002741740361669187, -0.005544641035825748, -0.0047824728172924935, -0.004096483894079128, -0.009302052764738278, -0.0036276511038133563, 2.7370436193052683e-06, -4.863704734958674e-06, 3.8067452639012345e-06, 3.5276141945317363e-06, -4.115511588409504e-06, -4.813747795928691e-06]
        velocity: []
        effort: []
      multi_dof_joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs:         0
          frame_id: "/world"
        joint_names: []
        transforms: []
        twist: []
        wrench: []
      attached_collision_objects: []
      is_diff: False
    robot_model_name: "niryo_one"
    fixed_frame_transforms: 
      - 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs:         0
          frame_id: "/world"
        child_frame_id: "/world"
        transform: 
          translation: 
            x: 0.0
            y: 0.0
            z: 0.0
          rotation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 1.0
    allowed_collision_matrix: 
      entry_names: []
      entry_values: []
      default_entry_names: []
      default_entry_values: []
    link_padding: []
    link_scale: []
    object_colors: []
    world: 
      collision_objects: []
      octomap: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs:         0
          frame_id: "/world"
        origin: 
          position: 
            x: 0.0
            y: 0.0
            z: 0.0
          orientation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 1.0
        octomap: 
          header: 
            seq: 0
            stamp: 
              secs: 0
              nsecs:         0
            frame_id: ''
          binary: False
          id: "OcTree"
          resolution: 0.025
          data: [-70, -76, 96, 64, -86, -70, -76, 96, 64, 64, -70, -76, 96, 64, 64, -70, -76, 96, 64, 64, -70, -76, 96, 64, 64, -70, -76, 96, 64, 64, -70, -76, 96, 64, 64, -70, -76, 96, 64, 64, -70, -76, 96, 64, -32, 117, 0, 0, -64, -128, 117, 0, 0, -64, 64, 117, 0, 0, -64, 64, 117, 0, 0, -64, -64, 117, 0, 0, -64, -128, 117, 0, 0, -64, -32, ...]
          is_diff: True

### Actual behaviour
No Octomap in Rviz.
![no octomap](https://user-images.githubusercontent.com/57045546/87477993-0c2b9c00-c5f7-11ea-9362-49c2f35bd409.png)
In `/move_group/monitored_planning_scene`, `octomap` is empty. 

    name: "(noname)+"
    robot_state: 
      joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 1594703183
            nsecs: 943662321
          frame_id: "/world"
        name: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6, gripper_joint, left_clamp_joint,
      left_rod_joint, right_gear_joint, right_clamp_joint, right_rod_joint]
        position: [-0.0, -0.0, -0.0004986655005698084, 0.01689478715930511, -0.00153588974175501, -0.030368728984701332, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        velocity: []
        effort: []
      multi_dof_joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs:         0
          frame_id: "/world"
        joint_names: []
        transforms: []
        twist: []
        wrench: []
      attached_collision_objects: []
      is_diff: False
    robot_model_name: "niryo_one"
    fixed_frame_transforms: []
    allowed_collision_matrix: 
      entry_names: []
      entry_values: []
      default_entry_names: []
      default_entry_values: []
    link_padding: []
    link_scale: []
    object_colors: []
    world: 
      collision_objects: []
      octomap: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs:         0
          frame_id: ''
        origin: 
          position: 
            x: 0.0
            y: 0.0
            z: 0.0
          orientation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 0.0
        octomap: 
          header: 
            seq: 0
            stamp: 
              secs: 0
              nsecs:         0
            frame_id: ''
          binary: False
          id: ''
          resolution: 0.0
          data: []
    is_diff: True

### Excluded causes

1. No `octomap` or `octomap_rviz_plugin`
I have `ros-kinetic-octomap` and `octomap_rviz_plugins` installed.
2. No data in point cloud topic.
There is data in the point cloud topic.
3. Inccorect topic name in config file.
The config file has the correct point cloud topic name. For simulation, topic name is `/camera/depth/points`, and on hardware, topic name is `/camera/depth/color/points`. When tested, `niryo_one_moveit_config/config/sensors_3d.yaml` is updated accordingly.

### Alternative?
I tried explicitly launching octomap_server by adding `niryo_one_moveit_config/launch/octomap_server.launch`.
```
<launch>
  <node pkg="octomap_server" type="octomap_server_node" name="octomap_server">
    <param name="resolution" value="0.01" />
    <param name="frame_id" type="string" value="world" />
    <!-- maximum range to integrate (speedup!) -->
    <param name="sensor_model/max_range" value="5.0" />
    <!-- data source to integrate (PointCloud2) -->
    <remap from="cloud_in" to="/camera/depth/color/points" />
  </node>
</launch>
```
and it does show Octomap in Rviz, but this Octomap is not in `/move_group/monitored_planning_scene`, so MoveIt will not consider this Octomap for obstacle avoidance.
![octomap server](https://user-images.githubusercontent.com/57045546/87479141-f28b5400-c5f8-11ea-8ed6-6589741fca60.png)

**Comment by simonschmeisser** [comment]
Since it seems to work with simulated data you need to check what's different between your simulated data and the real data. Candidates are:

- tf (where is the point cloud located)
- topics (is the octomap updater listening to the correct topic)
- message format

Please also note that support questions should be asked on answers.ros.org

If there is actually a bug please provide a github repo with the configuration and a rosbag with sensor data as a minimally working example (MWE)

ps: please try keep your issue titles "calmer"

**Comment by yiyinglai** [comment]
@simonschmeisser First off, my apology for the exclamation marks and asking questions here. In my experience, answer.ros.org has not been useful (I have asked several questions there, some for discussion, some for a specific problem, and got zero answer from other users).

Thanks for your suggestion. I don't think they are the real reasons. Under the secontion **Alternative?**, I explicitly launched the `octmap_server_node` and if any of those three candidates is the cause, there wouldn't be an Octomap in Rviz, right?

The topic names are definetly correct. I changed the config before switching between simulation and hardware and verified the publication/subscription relationship using `rqt_graph`.
Point cloud topic `/camera/depth/points` goes to `/move_group` in the simulation node graph:
![sim graph](https://user-images.githubusercontent.com/57045546/87713755-b8e15700-c778-11ea-872d-2cb8616dc20f.png)
Point cloud topic `/camera/depth/color/points` goes to `/move_group` in hardware node graph:
![hw graph](https://user-images.githubusercontent.com/57045546/87713761-bb43b100-c778-11ea-8777-dd28e3672e5e.png)

And message format is also the same. Again, when explicitly launching `octomap_server_node`, it worked.

**Comment by yiyinglai** [comment]
I made a [repo](https://github.com/yiyinglai/mwe-ros-planning-moveit-issues-2208) of a mwe. Two rosbags are provided, one from hardware, one from Gazebo simulator.

When the rosbag file from Gazeb simulator was played, the Octomap showed up.
![ss](https://user-images.githubusercontent.com/57045546/88251436-d0d54100-cc78-11ea-8018-aa7856d91e57.png)

When the rosbag file from hardware was played, no Octomap is present and the following showed up:
` Transform error: "right_gear" passed to lookupTransform argument source_frame does not exist.`

I thought the tf complaint is not relevant because `right_gear` has nothing to do with camera frames, as shown in [frames.pdf](https://github.com/ros-planning/moveit/files/4963811/frames.pdf). 

Is it because the tf (even though it seems `right_gear` or any other child links of `mainsupport` will not affect `camera_bottom_screw_frame` and its children)?

**Comment by simonschmeisser** [comment]
I guess you need all transforms defined for self-filtering to work? Best have a look at the code yourself here https://github.com/ros-planning/moveit/blob/master/moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp

**Comment by yiyinglai** [comment]
With all the transforms available, the Octomap is up now. Thanks!
