### ISSUE TITLE
Full robot model not showing in MoveIt Setup Assistant

### ISSUE THREAD

**Issue by HarshilNaikk** [ros-planning/moveit#2220]
I imported a solidworks model into a urdf file using the sw_urdf_exporter. But when i open the urdf file in Moveit Setup Assistant, i can only see the base_link of the robot model in the preview pane on the right side. What could be the issue?

I'm using ROS-Melodic with Ubuntu 18.04

**Comment by felixvd** [comment]
Did you check that the URDF is correct? I assume the problem is with the URDF exporter.

**Comment by HarshilNaikk** [comment]
The URDF exporter was broken. i had to do it on a different computer altogether
