### ISSUE TITLE
#"Unable to find a random collision free configuration after 100 attempts"    MoveIt! Motion Planning 

### ISSUE THREAD

**Issue by HarshilNaikk** [ros-planning/moveit#2230]
I'm trying to get MoveIt to work for my custom robot. The robot successfully launches in Gazebo and in RViz. When i try to plan the arm motion to a random valid goal state, the RViz simulation shows the arm executing the trajectory successfully. But the same does not happen in Gazebo. I followed  http://gkueh.org/ros/Gazebo%20+%20MoveIt!/  and https://github.com/AS4SR/general_info/wiki/Basic-ROS-MoveIt!-and-Gazebo-Integration   tutorials. 

I get the following output in my terminal:

........

>You can start planning now!

>[ INFO] [1596263892.914606581, 3375.873000000]: Ready to take commands for planning group arm.
[ INFO] [1596263892.914687019, 3375.873000000]: Looking around: no
[ INFO] [1596263892.914732120, 3375.873000000]: Replanning: no
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
[ WARN] [1596263905.382602436, 3388.121000000]: Unable to find a random collision free configuration after 100 attempts
[ WARN] [1596263907.594309116, 3390.257000000]: Unable to find a random collision free configuration after 100 attempts
[ INFO] [1596263908.919498881, 3391.558000000]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1596263908.919705045, 3391.558000000]: Planning attempt 1 of at most 1
[ WARN] [1596263908.920972140, 3391.558000000]: arm[RRTConnect]: Ignoring joint 'j1' in projection since it has 0 DOF
[ INFO] [1596263908.921109738, 3391.558000000]: Planner configuration 'arm[RRTConnect]' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1596263908.922163156, 3391.560000000]: arm[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1596263908.922228521, 3391.560000000]: arm[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1596263908.922364859, 3391.560000000]: arm[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1596263908.923906988, 3391.560000000]: arm[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1596263908.924310060, 3391.560000000]: arm[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1596263908.924404269, 3391.560000000]: arm[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1596263908.925414613, 3391.560000000]: arm[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1596263908.926083052, 3391.560000000]: arm[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1596263908.926276149, 3391.560000000]: ParallelPlan::solve(): Solution found by one or more threads in 0.004426 seconds
[ INFO] [1596263908.926996340, 3391.565000000]: arm[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1596263908.927137086, 3391.565000000]: arm[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1596263908.927306315, 3391.565000000]: arm[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1596263908.927608457, 3391.565000000]: arm[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1596263908.929511753, 3391.566000000]: arm[RRTConnect]: Created 5 states (2 start + 3 goal)
[ INFO] [1596263908.931467628, 3391.568000000]: arm[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1596263908.936136974, 3391.571000000]: arm[RRTConnect]: Created 5 states (2 start + 3 goal)
[ INFO] [1596263908.936399555, 3391.572000000]: arm[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1596263908.936928457, 3391.573000000]: ParallelPlan::solve(): Solution found by one or more threads in 0.009977 seconds
[ INFO] [1596263908.937501003, 3391.573000000]: arm[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1596263908.937962202, 3391.574000000]: arm[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1596263908.941169409, 3391.576000000]: arm[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1596263908.941459515, 3391.576000000]: arm[RRTConnect]: Created 5 states (2 start + 3 goal)
[ INFO] [1596263908.942272185, 3391.578000000]: ParallelPlan::solve(): Solution found by one or more threads in 0.004955 seconds
[ INFO] [1596263908.954971456, 3391.590000000]: SimpleSetup: Path simplification took 0.012511 seconds and changed from 3 to 2 states
[ INFO] [1596263908.957797067, 3391.593000000]: Disabling trajectory recording
[ INFO] [1596263910.289561302, 3392.899000000]: Controller arm_controller successfully finished
[ INFO] [1596263910.328846883, 3392.938000000]: Completed trajectory execution with status SUCCEEDED ...

I dont know where I'm going wrong please help!

**Comment by v4hn** [comment]
The name of this issue apparently has nothing to do with the issue.

The console output you show says everything succeeds and works as expected.

I'm afraid we cannot help you and the problem is likely a misunderstanding on your part.
