### ISSUE TITLE
When would moveit be available in the Ubuntu package repositories for Noetic?

### ISSUE THREAD

**Issue by saihv** [ros-planning/moveit#2308]
According to https://github.com/ros-planning/moveit/pull/2304, it looks like moveit was officially released for noetic. When can we expect the binaries to be available in the Ubuntu package repositories?

**Comment by VictoriaBentell** [comment]
The binaries are available using [ros-testing](http://wiki.ros.org/TestingRepository)

**Comment by rhaschke** [comment]
The packages will become available with the next sync. See the above link for more details on this.
