### ISSUE TITLE
errors occur after putting MFC and kinova controling code together

### ISSUE THREAD

**Issue by 207900368** [ros-planning/moveit#2316]
### Description
Before I put the MFC  application and kinova controlling application together,I have generated the kinova controlling application sucessfully,and it can control the robot sucessfully.In the VS MFC appliction,I cited the generated kinova controlling application. Then many errors occur.Most of them are error 3254 and error 2838
![微信图片_20200915111330](https://user-images.githubusercontent.com/69491379/93161242-bb463a00-f744-11ea-9e08-bd96cbc2baba.png)

my environment
windows10 vs2017 cmake conan

### Expected behaviour
I don't know why these errors occur and how to debug

**Comment by felixvd** [comment]
I fail to see the connection to MoveIt. Maybe you should take this question to a Kinova support platform or to ROS Answers, with more detail.

**Comment by felixvd** [comment]
This doesn't look like a MoveIt problem. Please reopen and add more detail if you think it is.
