### ISSUE TITLE
Setup Assistant not visualizing URDF in start screen

### ISSUE THREAD

**Issue by JeroenDM** [ros-planning/moveit#2329]
### Description
The MoveIt Setup Assistant does not visualize a loaded URDF by default anymore. I seem to remember it did a couple of months ago. I went through the latest changes in the source code on Github, but cannot find the cause for this.

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04
* Binary install version `1.0.6-1bionic.20200828.222638`

### Steps to reproduce
Launch the setup assistant in a sourced workspace with a robot description package (so it can find the meshes).
```bash
roslaunch moveit_setup_assistant setup_assistant.launch
```
Click "Create new MoveIt configuration package" and select the urdf file of the robot.

### Expected behaviour
I would expect to see a visual of the robot in the right pane.

### Actual behaviour
The pane is empty, like this:
![setup_assistent_before](https://user-images.githubusercontent.com/11537861/94653006-2b36f180-02fb-11eb-98d8-7ad41166a712.png)

If you go to the "Robot Poses" tap and click "show default pose", you do see the robot:
![setup_assistent_after](https://user-images.githubusercontent.com/11537861/94653129-5de0ea00-02fb-11eb-87e5-7162694973d9.png)

### Backtrace or Console output
[Console output](https://gist.github.com/JeroenDM/39edf650d98788513a5703f471b0c643).

**Comment by rhaschke** [comment]
This was already fixed in #2245, but not yet released.

**Comment by JeroenDM** [comment]
Ah, ok. Thank you!
