### ISSUE TITLE
[moveit_setup_assistant] larger default window size

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit#2339]
Here is a minor UI tweak that would be nice.  The `Default Planning Groups` needs to be adjusted to have more vertical space.  This is easy enough to resize the window by dragging the bottom of the window, but if the default size of the window was slightly taller it would make this look nicer.

Another page that could help with a larger default size is the `Define Robot Poses` when you are editing a pose, at the current default size it has awkward scrollbars in the center column.  To make it nicer for that window a wider default would also help.

![default_planning_groups_layout](https://user-images.githubusercontent.com/2490389/94956587-aa6a2800-04a9-11eb-997c-f4a9b51d464a.png)

**Comment by rhaschke** [comment]
I noticed this issue as well, but I'm not sure why the minimal widget size is not correctly propagated up the window hierarchy.

**Comment by felixvd** [comment]
I wouldn't mind taking a look if someone can tell me how to open this in QtCreator. I don't see a .ui file.

**Comment by rhaschke** [comment]
Unfortunately, Dave didn't use .ui files when programming this, but manually coded all the gui elements.
It's a long-standing task to migrate to .ui files...

**Comment by lyh458** [comment]
Hi there, thanks for the good issue and commits.
But I still have the similar problem under high DPI screen, while everything is good under a normal DPI screen.
Here is my device info:
- system: Ubuntu 18.04, ROS Melodic, and Moveit! is up-to-date
- screen info: resolution 3840*2160, scale 200%

---

- Some items are overlapping in the first default windows, and the font size is small, unfriendly.
![the-default-windows](https://cdn.jsdelivr.net/gh/lyh458/ImageRepo@main/image/1626252059780-1626252059767.png)

- The **Robot Pose** window: totally can't see and change the value of each joints
![the-robot-pose-window](https://cdn.jsdelivr.net/gh/lyh458/ImageRepo@main/image/1626252199109-1626252199104.png)
