### ISSUE TITLE
CHOMP planner documentation

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#237]
@ksatyaki remaining TODOs post https://github.com/ros-planning/moveit/pull/155:
- [x] Open PRs for jade and kinetic
- [x] Create moveit_tutorial page for using CHOMP

**Comment by davetcoleman** [comment]
@ksatyaki do you mind finishing up the CHOMP integration by documenting how to use what you've done so far?

**Comment by davetcoleman** [comment]
fyi I created a very basic page for you to expand upon: https://github.com/ros-planning/moveit_tutorials/pull/33

**Comment by ksatyaki** [comment]
I have just completed the tutorial and issued a pull request. Sorry for the delay.

**Comment by 130s** [comment]
I'm interested in looking into this for WMD2017, although I'm very new to CHOMP/STOMP. Let's see how far a langsam learner :turtle: can go within a day.

@ksatyaki wrote:

> I have just completed the tutorial and issued a pull request. Sorry for the delay.

Where can we find it?

**Comment by ksatyaki** [comment]
I think this issue should be closed. The tutorial is available at http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/chomp_interface_tutorial.html

**Comment by davetcoleman** [comment]
I think the tutorial would be great to be reviewed and expanded upon

**Comment by ksatyaki** [comment]
I will probably resurrect this planner in the near future and make sure it works reliably. At that time I shall also build upon the tutorial (unless someone wants to do it sooner, of course).

**Comment by davetcoleman** [comment]
Closing because @mlautman recently reviewed this tutorial after @ksatyaki's original version
