### ISSUE TITLE
Jump in moveit_servo velocity command

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit#2386]
[servo_config.yaml.txt](https://github.com/ros-planning/moveit/files/5425782/servo_config.yaml.txt)

### Description

When moveit_servo is configured to publish velocity commands, we occasionally see a jump in the outgoing command (from moveit_servo to the ros_control velocity command topic). It's not 100% clear if this is a moveit_servo problem but I figured I will create the issue and see if anybody else has a similar problem.

### Your environment
* ROS Distro: Melodic
* Ubuntu 18.04
* Building master branch from source

### Steps to reproduce
Servo config file is attached.

### Plots
This first plot (from top to bottom) shows:  

- Outgoing command, from Servo to the ros_control controller. The jump is obvious
- The hardware's velocity state. It reports the jump correctly, seems OK
- The hardware's position state. It seems OK
- The hardware's position command (not really relevant, since the arm was in velocity control mode at the time)

![jump_plots](https://user-images.githubusercontent.com/11284393/96929456-c432d580-147f-11eb-9010-91b08413f050.png)

I didn't capture the /joint_states topic but it seemed steady, too.

Second plot, zoomed in to show one joint clearly:

![shoulder_jump](https://user-images.githubusercontent.com/11284393/96929475-cd23a700-147f-11eb-9a98-ee7b7590a291.png)

Possibly it's a discrete differentiation problem. Internally, moveit_servo filters joint positions then does discrete differentiation to calculate velocity.

**Comment by v4hn** [comment]
Is this still relevant? I believe you solved a number of issues w.r.t. velocity commands in the recent past.

**Comment by AndyZe** [comment]
I haven't seen it recently or heard any complaints   :+1:
