### ISSUE TITLE
Improve MoveIt! Quick Start guide

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#24]
Would like to expand upon our current Rviz Motion Planning plugin tutorial with the PR2 to make it streamlined for new users:
- Improve ordering of tutorials so that they are cohesive for new users
- Should new users first learn the [PR2 with Setup Assistant](http://docs.ros.org/indigo/api/moveit_setup_assistant/html/doc/tutorial.html) or do we want them to be able to immediatly plan in Rviz with the PR2?
- There are some broken links

There is now a link at the button of the [install](http://moveit.ros.org/install/) page for the Quick Start

**Comment by dornhege** [comment]
Definitely +1 for expanding the Rviz motion plugin tutorial. I was quite confused, when I used that the first time, but it all makes sense!

I'd remove the setup assistant from the basic tutorials. It's not necessary for using MoveIt! and ideally that's already done for the robots of new users. New MoveIt! users with their own robot can still refer to that tutorial, but also learn, how to use MoveIt! with a properly set up robot.

**Comment by v4hn** [comment]
I somewhat agree with @dornhege. The assistant shouldn't be the first thing to learn about.
Still, it *is* important and "ideally that's already done" is simply not the usual use-case of MoveIt...

**Comment by davetcoleman** [comment]
Another benefit of the SA is that, even if you already have a config package for your robot, it teaches you about some of the components and how they are configured and it gives you a sense of ownership over the setup.

**Comment by dornhege** [comment]
I agree that the SA is relevant, but I don't think that this is something that beginners should face first.

**Comment by davetcoleman** [comment]
This has been addressed in this code sprint last year:
https://moveit.ros.org/moveit!/ros/2018/02/26/tutorials-documentation-codesprint.html
