### ISSUE TITLE
Retiming trajectory after compute cartesian path

### ISSUE THREAD

**Issue by wlawler45** [ros-planning/moveit#2400]
### Description

I have been having trouble getting the move group interface to replan trajectory with time optimal parameterization. Im using compute cartesian path in the python interface and the plan that results has inconsistent velocity at the end effector and I'm trying to then replan the trajectory using the generated waypoints so that it will then have the time parameterization I want from that but I don't know how I should do that in python, are there any suggestions on how I can do that? Please let me know.

### Your environment
Kinetic, source build

**Comment by felixvd** [comment]
Why not use [retime_trajectory](http://docs.ros.org/en/api/moveit_commander/html/classmoveit__commander_1_1move__group_1_1MoveGroupCommander.html#a5fb1d772b6d248a6c4113412eacb4330)?

**Comment by wlawler45** [comment]
I tried, it didn't change the behavior of the robot or the timing of the trajectory at all.

**Comment by felixvd** [comment]
Can you paste how you are using it in your code?

**Comment by wlawler45** [comment]
for i in range(len(dxf_points)):
            pose_goal = Pose()
            rpy=[math.pi,0.0,sines[i]-math.pi/2]
            print(rpy)
            R_result=rox.rpy2R(rpy)
            quat=rox.R2q(R_result)
            print(quat)
            pose_goal.orientation.w=0.0
            pose_goal.orientation.x=quat[1]
            pose_goal.orientation.y=quat[2]
            pose_goal.orientation.z=0.0
            
            x_val=(20-dxf_points[i][0]) *0.0254
            y_val=dxf_points[i][1]*0.0254
            pose_goal.position.x=0.8+y_val
            pose_goal.position.y=x_val
            pose_goal.position.z=0.3
            print(pose_goal)
            
            waypoints.append(pose_goal)

        
        (plan, fraction) = self.move_group.compute_cartesian_path(
                                       waypoints,   # waypoints to follow
                                       0.01,        # eef_step
                                       0.0)
plan=self.move_group.retime_trajectory(moveit_robot_state,plan,1.0)


Is this what you needed?

**Comment by gavanderhoorn** [comment]
@wlawler45: where do you request MoveIt to use a different time-parameterisation from its default?

**Comment by wlawler45** [comment]
I tried changing the retime line to this but it gave me an error for too many arguments
plan=self.move_group.retime_trajectory(moveit_robot_state,plan,1.0,1.0,"iterative_spline_parameterization") did I do that wrong?

**Comment by wlawler45** [comment]
Is that version of retime_trajectory not in the branch I'm using? If so is there a moveit branch for kinetic that would use that version of retime_trajectory?

**Comment by gavanderhoorn** [comment]
If you are on Kinetic it's likely that functionality is not available to you.

I haven't checked in which version that first appeared. I'd recommend using a more up-to-date version of MoveIt in any case. There have been *many* improvements added to MoveIt since the last Kinetic release.

**Comment by AndyZe** [comment]
The best time parameterization algorithm right now is `time_optimal_trajectory_generation`. It looks like it is not available on Kinetic. Sorry.

If you do upgrade to, say, Melodic, here are some slides about using TOTG:  https://picknik.ai/docs/moveit_workshop_macau_2019/TOTG.pdf

**Comment by AndyZe** [comment]
Once you specify the use of TOTG in the yaml file, you shouldn't need to manually re-time anything.

**Comment by gavanderhoorn** [comment]
@AndyZe: does `computeCartesianPath(..)` use the planning request adapter? Afaik it's hard-coded to use the IPTP?

**Comment by AndyZe** [comment]
I guess I don't know. OK, disregard -- it may be necessary to retime the path.

I stand by TOTG being the best available, though.

**Comment by wlawler45** [comment]
I did update my workspace to melodic and now I can't use the retime trajectory command because it gives the error Validation failed: Missing valid timestamp data for trajectory pt 1. What should I do about that?

**Comment by felixvd** [comment]
Did your plan succeed? It sounds like the plan failed and the trajectory you're trying to retime is empty.

**Comment by felixvd** [comment]
Friendly ping @wlawler45

**Comment by felixvd** [comment]
I'll close this for lack of activity. Feel free to reopen if this is a bug.

**Comment by luiz0897** [comment]
Hey guys,

I'm working with ROS Noetic and MoveIt.

I'm interested in parameterizing my trajectories with **TOTG** after using the cartesian path. 
Using **retime_trajectory** I can parameterize the trajectory with a delta time (dt) of 0.1 seconds. Is there any way to change this time parameter?

I tried modifying **time_optimal_trajectory_generation.h** but it didn't work.

**Comment by AndyZe** [comment]
Unfortunately it looks like the time step parameter is hard-coded in time_optimal_trajectory_generation.cpp:

`constexpr double DEFAULT_TIMESTEP = 1e-3;`

A PR to turn that into an optional parameter would probably be welcome!

**Comment by luiz0897** [comment]
Thanks for the answer!

After checking my MoveIt installation files, I found that I didn't have the **time_optimal_trajectory_generation.cpp** file (I used MoveIt binary installation). In my trajectory_processing folder I only had the .h files.

I tried adding the files manually, but it still didn't work.
The strange thing is that even deleting the folder, I can still use the **retime_trajectory** with dt = 0.1s (TOTG).

Any idea how I can resolve this?

Thanks.

**Comment by hassan-shehawy** [comment]
Hi, can you please share how you use it in c++? I can't seem to find a `retime_trajectory` function in the `MoveGroupInterface` class [here](http://docs.ros.org/lunar/api/moveit_ros_planning_interface/html/classmoveit_1_1planning__interface_1_1MoveGroupInterface.html)

**Comment by v4hn** [comment]
There is no need for it in c++ because you can directly instantiate and use the respective classes in moveit_core/trajectory_processing (notably TOTG).

**Comment by AndyZe** [comment]
Here's a link:  https://github.com/ros-planning/moveit/blob/326e9b5fe76bdf856f9c4a2be56ce7e136651ff2/moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h#L170

**Comment by hassan-shehawy** [comment]
Thanks!
