### ISSUE TITLE
Add support for master-source docker container running clang-tidy commands from the instructions

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit#2409]
## Background

Make the environment variables like CATKIN_WS work in the [master-source docker container](https://github.com/ros-planning/moveit/blob/master/.docker/source/Dockerfile) so clang-tidy commands can be copy-pasted directly [from the instructions](https://moveit.ros.org/documentation/contributing/code/#clang-tidy-linting).

@felixvd you gave me the idea for this issue.  Could you edit the description to include context for the workflow where this is useful in developing?

## Instructions
Hi, this is a `first-timer-only` issue. This means we've worked to make it more legible to people who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

We're interested in helping you take the first step, and can answer questions and help you out along the way. Note that we're especially interested in contributions from underrepresented groups!

We know that creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this PR for someone new**, and looking through our general [bug](https://github.com/ros-planning/moveit/labels/bug) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [x] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 🗄️**Create a local workspace** for making your changes and testing [follwing these instructions](https://moveit.ros.org/install/source/)

- [ ] 📝 **Update** the file `.docker/source/Dockerfile`by applying the change shown in the diff below.

```diff
diff --git a/.docker/source/Dockerfile b/.docker/source/Dockerfile
index 1cfeb73e8..a18b2fefe 100644
--- a/.docker/source/Dockerfile
+++ b/.docker/source/Dockerfile
@@ -24,7 +24,11 @@ RUN \
 
 ENV PYTHONIOENCODING UTF-8
 RUN cd .. && \
-    catkin config --extend /opt/ros/$ROS_DISTRO --install --cmake-args -DCMAKE_BUILD_TYPE=Release && \
+    catkin config --extend /opt/ros/$ROS_DISTRO --install --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON && \
     # Status rate is limited so that just enough info is shown to keep Docker from timing out,
     # but not too much such that the Docker log gets too long (another form of timeout)
     catkin build --limit-status-rate 0.001 --no-notify
+
+# Environment variable used in instructions on moveit.ros.org website for running clang-tidy
+ENV CATKIN_WS /root/ws_moveit
+
```

- [ ] 🤖 Test the changes by building the docker image locally and testing that you can run clang-tidy per the instructions linked above.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:
1. If you are not familiar with GitHub or how to create a pull request, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!**

### 🤔❓ Questions?

Don’t hesitate to ask questions or to get help if you feel like you are getting stuck. For example leave a comment below!
Furthermore, you find helpful resources here:
* [MoveIt FAQ](https://moveit.ros.org/documentation/faqs/)
* [MoveIt Tutorials](https://ros-planning.github.io/moveit_tutorials/)
* [MoveIt contribution guide](https://moveit.ros.org/documentation/contributing/)
* [ROS Tutorials](https://wiki.ros.org/ROS/Tutorials)
* [ROS Answers](https://answers.ros.org/questions/)

**Good luck with your first issue!**

**Comment by archonixX** [comment]
i got this
