### ISSUE TITLE
CollisionRequest min_cost_density arg isn't used

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit#2410]
I grepped for `min_cost_density` and it only appears in a [header file](https://github.com/ros-planning/moveit/blob/master/moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h). So I think the data member could be deleted.

Here's the description from (http://docs.ros.org/en/melodic/api/moveit_core/html/structcollision__detection_1_1CollisionRequest.html):

`When costs are computed, this is the minimum cost density for a CostSource to be included in the results.`

**Comment by JafarAbdi** [comment]
Close by https://github.com/ros-planning/moveit/pull/2411
