### ISSUE TITLE
Auto-format code base with clang-format

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#242]
I'd like to run [clang-format](https://github.com/davetcoleman/roscpp_code_format) on this entire repo right after the indigo and kinetic releases are finished, as I am expecting that the fewest number of pull request will be open at that moment. The code formatter is pretty amazing - in one line of code:

```
find . -name '*.h' -or -name '*.hpp' -or -name '*.cpp' | xargs clang-format-3.6 -i -style=file $1
```

We can make all our code comply to the roscpp style guidelines and then, in the future, include this as a check for CI. This change does have the tendency to break open PRs though - rebasing will likely have lots of merge conflicts (there are ways to mitigate this) so that is why I suggest we wait until the moveit releases.

I've already run this formatter on the entire [ompl codebase](https://github.com/ompl/ompl/pull/81) successfully, and its been used by many ROS users for a while via the link on [rosccp style guidelines](http://wiki.ros.org/CppStyleGuide#Autoformatting_of_ROS_Code)

I'm announcing this intention now so that we can discuss it and, when the moment is right, make the merge quickly.

**Comment by de-vri-es** [comment]
I'm very much in favor of this idea. It would allow me to work with my regular editor settings without worrying about style, and then apply the same formatting in one go before committing.

**Comment by v4hn** [comment]
I don't really like syntactic rewriting like this but I see the advantages in this case. so +1 from my side.

**Comment by jonbinney** [comment]
+1

**Comment by rhaschke** [comment]
It's a huge rewrite of the whole repo. But I can see the benefits too. +1 if we enforce compliance afterwards as suggested.

**Comment by davetcoleman** [comment]
The automated test has been created: https://github.com/ros-planning/moveit_ci/pull/19

**Comment by davetcoleman** [comment]
code formatting is complete!
