### ISSUE TITLE
Speed up motion planning time using GPU

### ISSUE THREAD

**Issue by impet14** [ros-planning/moveit#2435]
Hi, 
Is there a way to speed up motion planning using GPU or parallel computing? 
I would like to speed up my planning time. Please suggest to me.

Thank you.

**Comment by simonschmeisser** [comment]
Please ask questions on https://answers.ros.org/ :smile: This issue tracker is more for discussing concrete bugs, tasks and sometimes ideas.

Short answer: Motion planning uses all cores of your CPU but there is no support for GPU yet (possibly via bullet collision checking but I don't think this has been tried yet)
