### ISSUE TITLE
RobotState::setJointGroupPositions: Check for matching size of JointModelGroup and passed vector

### ISSUE THREAD

**Issue by simonschmeisser** [ros-planning/moveit#2442]
https://github.com/ros-planning/moveit/blob/bdd4bde4938c7bdac3a57a791cf738146c8834e0/moveit_core/robot_state/include/moveit/robot_state/robot_state.h#L625

would be nice to have an assert here and might have hinted to https://github.com/ros-planning/moveit_visual_tools/issues/82  and/or similar bugs in our products code

Will open PR

**Comment by pawanw17** [comment]
Hey I'd like to work on this issue, can you guide me for the same?

**Comment by simonschmeisser** [comment]
A small improvement would be to have an `assert` just like you can find it in a few places in the file I linked already.

The real solution would be to create a new function `setActiveJointGroupPositions` that takes the values for only the active joints as this would make the API a lot less error-prone.

**Comment by pawanw17** [comment]
Hey @simonschmeisser should I add both the assertions?  
i.e from the link you provided
``
if (ee_jmg == nullptr)
`` if (!ee_joint_pos.empty())
and
``
 if (!ee_joint_pos.empty())
``
and should I make the pull request to melodic-devel?
