### ISSUE TITLE
No interpolation is made in RViz

### ISSUE THREAD

**Issue by awied1404** [ros-planning/moveit#2446]
Hello guys,

I have a little problem. I am using the Kuka YouBot and want to calculate a trajectory.
I created a catkin package with MoveIt setup assistant and after setting a goal pose via RViz GUI and 
calculating the trajectory I look at the path and see the following:
![collision_detection_failed](https://user-images.githubusercontent.com/67168322/101253485-bfb83880-371e-11eb-9043-8e293abafda0.gif)

In my opinion a interpolation made when executing this trajectory would detect this collision but somehow it doesn't. 

My environment
* Ubuntu 18.04
* ROS Distro: Melodic
* RViz, MoveIt
* Planner: RRTstar

The only console output I get when starting the move_group node is the following:
`[ INFO] [1607212921.861570503]: Loading robot model 'youbot'...
[ WARN] [1607212921.951508475]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1607212923.157338499]: Ready to take commands for planning group youbot_arm.
[ INFO] [1607212925.143674089]: Replanning: yes`

But in fact I use the LMA kinematics plugin so I also don't understand why I get this warning from moveit. 

My fake_controllers.yaml file:
rate: 20
controller_list:
  - name: fake_youbot_arm_controller
    type: via points
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
  - name: fake_gripper_controller
    joints:
      - gripper_finger_joint_l
      - gripper_finger_joint_r
initial:  # Define initial robot poses.
  - group: youbot_arm
    pose: home
  - group: gripper
    pose: home

I also tried the default type for the controllers (interpolate) but it doesn't work either. 
In my urdf file I have as collision the same mesh as I have for visualisation. 
According to http://docs.ros.org/en/melodic/api/moveit_tutorials/html/doc/fake_controller_manager/fake_controller_manager_tutorial.html the fake controllers should interpolate between my trajectory points. 

Maybe someone can help me. I would be very grateful!

Best regards

**Comment by simonschmeisser** [comment]
Sorry, I don't understand your issue and cannot deduce from the gif. Could you provide some more details?

**Comment by awied1404** [comment]
Thank you for answering but I now understand a little better how moveit/RViz is working. My problem was that moveit in my setup only has a discrete collision detection and I need a continuous to detect collision between two trajectory points. 
I solved it by validating my motion plan in gazebo. As it is no issue I will close this now.
