### ISSUE TITLE
RViz moveit getting stuck in initializing window | VMware

### ISSUE THREAD

**Issue by Kiwigamer** [ros-planning/moveit#2536]
I followed the tutorial from The Construct Morpheus Chair. Everything looks good even the start protocol (https://pastebin.com/esX1RU9B). But after that the RViz initializing windows opens up nothing happens anymore.

RViz is running without any issues.
But the demo.launch file is causing the above described error.

Environment:
VMware Workstation 16 Player with Ubuntu 16.04 LTS
PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.17

**Comment by Kiwigamer** [comment]
rebooting the machine a zillion times helped

**Comment by Jiajie-Ye** [comment]
reboot worked！
