### ISSUE TITLE
[Docker Container] Moveit workspace is not source from the start

### ISSUE THREAD

**Issue by cambel** [ros-planning/moveit#2543]
### Description

When using `gui-docker` the workspace is not already sourced from the beginning. This leads to confusion on how to get started with the docker since how to properly source the workspace is also not mentioned in the tutorial.

### Your environment
* ROS Distro: [Noetic]
* OS Version: Docker

### Steps to reproduce
Run the docker container:
`./gui-docker`

Execute the moveit tutorial's first script:
`roslaunch moveit_tutorials robot_model_and_robot_state_tutorial.launch`

It should ideally just work but instead, I get the error:

> RLException: [robot_model_and_robot_state_tutorial.launch] is neither a launch file in package [moveit_tutorials] nor is [moveit_tutorials] a launch file name
> The traceback for the exception was written to the log file

Potential solution:
Add the sourcing of the workspace to the Dockerfile
`RUN echo 'source /opt/ros/noetic/setup.bash' >> ~/.bashrc`
`RUN echo 'source ~/ws_moveit/iinstall/setup.bash' >> ~/.bashrc`

**Comment by zark-zeugan** [comment]
Hello! I would like to contribute to this. I have experience adding environment variable in melodic and am familiar with ROS. 
However, I am new to contributing can you suggest to how to get started ?

**Comment by felixvd** [comment]
I don't really know what information you need, but does [this Google result help](https://www.dataschool.io/how-to-contribute-on-github/)?

**Comment by zark-zeugan** [comment]
Yes ! Thanks a lot @felixvd

**Comment by zark-zeugan** [comment]
Isn't that supposed to be `install` in `RUN echo 'source ~/ws_moveit/iinstall/setup.bash' >> ~/.bashrc`

Also, this should be added to the dockerfile in the source file right?

**Comment by cambel** [comment]
@zark-zeugan  Yes, that's right, it was a typo on my side. And yes, I think it should go in the Dockerfile

**Comment by zark-zeugan** [comment]
Adding the sourcing to the Docker File doesn't seem to work. 
Is it possible for you to send me they way you build these docker files? Like, the command to build these Docker files.

**Comment by zark-zeugan** [comment]
@cambel  could you please help me out with this issue?

**Comment by cambel** [comment]
@zark-zeugan Sorry about that, I forgot:

Here is the docker file as I built it, including the changes in @rhaschke PR

```
# moveit/moveit:noetic-source
# Downloads the moveit source code and install remaining debian dependencies

FROM moveit/moveit:noetic-ci-shadow-fixed
MAINTAINER Dave Coleman dave@picknik.ai

ENV ROS_UNDERLAY /root/ws_moveit/install
WORKDIR $ROS_UNDERLAY/../src

# Commands are combined in single RUN statement with "apt/lists" folder removal to reduce image size
# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers
RUN \
    # Download moveit source so that we can get necessary dependencies
    wstool init . https://raw.githubusercontent.com/ros-planning/moveit/${ROS_DISTRO}-devel/moveit.rosinstall && \
    #
    # Update apt package list as cache is cleared in previous container
    # Usually upgrading involves a few packages only (if container builds became out-of-sync)
    apt-get -qq update && \
    apt-get -qq dist-upgrade && \
    #
    rosdep update && \
    rosdep install -y --from-paths . --ignore-src --rosdistro ${ROS_DISTRO} --as-root=apt:false && \
    rm -rf /var/lib/apt/lists/*

ENV PYTHONIOENCODING UTF-8
RUN cd .. && \
    catkin config --extend /opt/ros/$ROS_DISTRO --install --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON && \
    # Status rate is limited so that just enough info is shown to keep Docker from timing out,
    # but not too much such that the Docker log gets too long (another form of timeout)
    catkin build --limit-status-rate 0.001 --no-notify

RUN echo 'source '$ROS_UNDERLAY'/setup.bash' >> ~/.bashrc
# Environment variable used in instructions on moveit.ros.org website for running clang-tidy
ENV CATKIN_WS $(realpath $ROS_UNDERLAY/..)
```
