### ISSUE TITLE
Problem with retime_trajectory() function

### ISSUE THREAD

**Issue by TGSP1997** [ros-planning/moveit#2552]
### Description

Hello,
while executing the retime_trajectory function in my Python Code i get this error and couldn't find a similar error.  

`

move_group = self.move_group

    scale = 1
    waypoints = []

    wpose = move_group.get_current_pose().pose
    if type_of_approach == "LEFT":
      wpose.position.x -= scale * 5  # First move sideways (x)
      wpose.position.z -= scale * 2  # then down (z)
      waypoints.append(copy.deepcopy(wpose))
      # waypoints to follow,eef_step,jump_threshold,avoid_collision

      (plan, fraction) = move_group.compute_cartesian_path(waypoints, 0.0001, 0.0, avoid_collisions=False)
      self.plan=plan

      move_group.retime_trajectory(move_group.get_current_pose().pose,plan,0.2,0.2,1)
      move_group.execute(plan, wait=False)`

This is the Code im executing. And this the error im getting:

`Traceback (most recent call last):
  File "/home/tgsp/ws_moveit/src/my_package/scripts/move_ur10.py", line 848, in <module>
    main()
  File "/home/tgsp/ws_moveit/src/my_package/scripts/move_ur10.py", line 810, in main
    tutorial.velocity_change(tutorial,pressure_s_value)
  File "/home/tgsp/ws_moveit/src/my_package/scripts/move_ur10.py", line 637, in velocity_change
    tutorial.move_sideways(type_of_approach)
  File "/home/tgsp/ws_moveit/src/my_package/scripts/move_ur10.py", line 704, in move_sideways
    move_group.retime_trajectory(move_group.get_current_pose().pose,plan,0.2,0.2,1)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/moveit_commander/move_group.py", line 605, in retime_trajectory
    ser_traj_out = self._g.retime_trajectory(ser_ref_state_in, ser_traj_in, velocity_scaling_factor, acceleration_scaling_factor, algorithm)
Boost.Python.ArgumentError: Python argument types in
    MoveGroupInterface.retime_trajectory(MoveGroupInterface, str, str, float, float, int)
did not match C++ signature:
    retime_trajectory(moveit::planning_interface::MoveGroupInterfaceWrapper {lvalue}, moveit::py_bindings_tools::ByteString, moveit::py_bindings_tools::ByteString, double, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
`

Via Definition the arguments shoud look like follow:

`
def` moveit_commander.move_group.MoveGroupCommander.retime_trajectory 	( 	  	self,
		  	ref_state_in,
		  	traj_in,
		  	velocity_scaling_factor = 1.0,
		  	acceleration_scaling_factor = 1.0,
		  	algorithm = "iterative_time_parameterization" 
	) 	`
Everything works if i delete the retime_trajectory() function. 
Am i doing something wrong, or is this a bug?

EDIT:
My first implementation was this:
`move_group.retime_trajectory(move_group.get_current_pose().pose,plan,1.0,1.0,algorithm = "iterative_time_parameterization")`
instead of 
`move_group.retime_trajectory(move_group.get_current_pose().pose,plan,0.2,0.2,1)`

but still this error occured:

`Traceback (most recent call last):
  File "/home/tgsp/ws_moveit/src/my_package/scripts/move_ur10.py", line 848, in <module>
    main()
  File "/home/tgsp/ws_moveit/src/my_package/scripts/move_ur10.py", line 810, in main
    tutorial.velocity_change(tutorial,pressure_s_value)
  File "/home/tgsp/ws_moveit/src/my_package/scripts/move_ur10.py", line 637, in velocity_change
    tutorial.move_sideways(type_of_approach)
  File "/home/tgsp/ws_moveit/src/my_package/scripts/move_ur10.py", line 704, in move_sideways
    move_group.retime_trajectory(move_group.get_current_pose().pose,plan,1.0,1.0, "iterative_time_parameterization")
  File "/opt/ros/melodic/lib/python2.7/dist-packages/moveit_commander/move_group.py", line 605, in retime_trajectory
    ser_traj_out = self._g.retime_trajectory(ser_ref_state_in, ser_traj_in, velocity_scaling_factor, acceleration_scaling_factor, algorithm)
RuntimeError: Buffer Overrun

`
As for the Path Computing:

[ INFO] [1615741544.352049840, 17.508000000]: Received request to compute Cartesian path
[ INFO] [1615741544.352276079, 17.508000000]: Attempting to follow 1 waypoints for link 'sensor' using a step of 0.010000 m and jump threshold 0.000000 (in global reference frame)
[ INFO] [1615741544.388658511, 17.535000000]: Computed Cartesian path with 215 points (followed 39.703154% of requested trajectory)

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04

### Steps to reproduce
I took the Code from the Python Move Group Interface Tutorial and added the retime Function.
[https://github.com/ros-planning/moveit_tutorials/blob/kinetic-devel/doc/move_group_python_interface/scripts/move_group_python_interface_tutorial.py](url)

### Expected behaviour
The robot should do the same movement as without this function but slower.

**Comment by Jiaxunn** [comment]
I have the same issue.
