### ISSUE TITLE
moveit_msgs::MotionPlanRequest has no member named ‘pipeline_id'

### ISSUE THREAD

**Issue by Sunny478** [ros-planning/moveit#2558]
### Description
While building MoveIt from source (I have done so multiple times successfully), 'moveit_ros_planning_interface' packages poses an error while building viz. 
`‘moveit_msgs::MotionPlanRequest {aka struct Moveit_msgs::MotionPlanRequest_<std::allocator<void> >}’ has no member named ‘pipeline_id’`
Since I had previously built all the packages, so I narrowed it down to the particular commit as in from which commit does the error starts and here are the results...
The build runs fine till this particular commit - 

![build_ok_commit](https://user-images.githubusercontent.com/39979141/111952999-fcf8d880-8b0b-11eb-9fe5-6f4fe2c2bee2.png)
gives : 
![build_ok_summary](https://user-images.githubusercontent.com/39979141/111953145-3a5d6600-8b0c-11eb-9aa0-40eee756fc07.png)

but the right next commit i.e.
![build_fail_commit](https://user-images.githubusercontent.com/39979141/111953252-5eb94280-8b0c-11eb-9001-3ef6f761520c.png)
gives : 
![build_fail_summary](https://user-images.githubusercontent.com/39979141/111953279-67117d80-8b0c-11eb-9940-355a9c0c3d32.png)

On inspecting this particular commit, it does add the line `request.pipeline_id = planning_pipeline_id_;` and in  http://docs.ros.org/en/jade/api/moveit_msgs/html/msg/MotionPlanRequest.html , there is no reference about `planning_id`. 

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04
* Source build

### Steps to reproduce
Build MoveIt from source.

### Expected behaviour
MoveIt successfully built

### Actual behaviour
Error while building 'moveit_ros_planning_interface' package

### Backtrace or Console output
../src/moveit/moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp:1085:13: error: ‘moveit_msgs::MotionPlanRequest {aka struct moveit_msgs::MotionPlanRequest_<std::allocator<void> >}’ has no member named ‘pipeline_id’
     request.pipeline_id = planning_pipeline_id_;
             ^~~~~~~~~~~
make[2]: *** [move_group_interface/CMakeFiles/moveit_move_group_interface.dir/src/move_group_interface.cpp.o] Error 1
make[1]: *** [move_group_interface/CMakeFiles/moveit_move_group_interface.dir/all] Error 2
make: *** [all] Error 2

Failed     << moveit_ros_planning_interface:make                             [ Exited with code 2 ]                                                  
Failed    <<< moveit_ros_planning_interface                                  [ 39.4 seconds ]

**Comment by felixvd** [comment]
1. You are looking at outdated API documentation for Jade (Google results tricked you) instead of the [master branch](http://docs.ros.org/en/api/moveit_msgs/html/msg/MotionPlanRequest.html).
2. It looks like you didn't follow the [build instructions](https://moveit.ros.org/install/source/), specifically these steps:

```
wstool merge -t src https://raw.githubusercontent.com/ros-planning/moveit/master/moveit.rosinstall
wstool update -t src
rosdep install -y --from-paths src --ignore-src --rosdistro ${ROS_DISTRO}
```

**Comment by Sunny478** [comment]
Thanks, this solved the issue. I thought it won't be necessary to download the source code every time I build moveit.

**Comment by felixvd** [comment]
When you build from source, you generally need the full source code, yes. I assume this was meant to be closed.
