### ISSUE TITLE
Quick question about fake_execution flag

### ISSUE THREAD

**Issue by ranjitkathiriya** [ros-planning/moveit#2570]
Hello there,

Just a quick question, if we are configuring a real robot with moveit what will be the flag of `fake_execution` flag? it will be true or false?

```
<include file="$(find kuka_moveit_roof)/launch/move_group.launch">
      <arg name="publish_monitored_planning_scene" value="true" />
       <arg name="allow_trajectory_execution" value="true"/>
      <arg name="fake_execution" value="true"/>
    <arg name="info" value="true"/>
    <arg name="debug" value="$(arg debug)"/>
    <arg name="pipeline" value="$(arg pipeline)"/>
    <arg name="load_robot_description" value="$(arg load_robot_description)"/>
  </include>
```

and what args is important when we are configuring a real robot? In repository, I only find 'publish_monitored_planning_scene' in [kuka configuration tutorials](https://github.com/gavanderhoorn/kuka_experimental/blob/kr6r900sixx_moveit_rsi_convenience/kuka_kr6r900sixx_moveit_config/launch/moveit_planning_execution_rsi.launch). Can you please put a light on this question?

If I am making the `fake_execution` flag as false I am getting an error as unused args.

```
(ros1_envs) kuka-ai@kukaai-ROG-Zephyrus-G15-GA502IU-GA502IU:~/ai_catkin$ roslaunch kuka_moveit_roof moveit_planning_execution_rsi3.launch sim:=true
... logging to /home/kuka-ai/.ros/log/1a851b26-9074-11eb-9c65-9da7670cc46f/roslaunch-kukaai-ROG-Zephyrus-G15-GA502IU-GA502IU-115220.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

WARN: unrecognized 'param' tag in <include> tag
WARN: unrecognized 'param' tag in <include> tag
RLException: unused args [execution_type] for include of [/home/kuka-ai/ai_catkin/src/kuka_moveit_roof/launch/kuka_kr16_2_moveit_controller_manager.launch.xml]
The traceback for the exception was written to the log file

```

Overview of your issue here.

### Your environment
* ROS Distro: Noetic
* OS Version: e.g. Ubuntu 20.04

**Comment by ranjitkathiriya** [comment]
Finally, Solve this issue:

> if we are configuring a real robot with moveit what will be the flag of `fake_execution` flag? it will be true or false?

Answer: It should be always set to false. You can set it by making false here as below or ignore writing this fake_execution line by default it is set to false. It is very important to set `publish_monitored_planning_scene` as true.

```
<include file="$(find kuka_moveit_roof)/launch/move_group.launch">
      <arg name="publish_monitored_planning_scene" value="true" />
       <arg name="allow_trajectory_execution" value="true"/>
      <arg name="fake_execution" value="true"/>
    <arg name="info" value="true"/>
    <arg name="debug" value="$(arg debug)"/>
    <arg name="pipeline" value="$(arg pipeline)"/>
    <arg name="load_robot_description" value="$(arg load_robot_description)"/>
  </include>
```
> If I am making the fake_execution flag as false I am getting an error as unused args.

Answer: In `trajectory_execution.launch.xml` uncomment below line. The reason of this bug was the `moveit_controller_manager.launch.xml` file has no argument name `execution_type`.

```
<include file="$(find kuka_moveit_roof)/launch/$(arg moveit_controller_manager)_moveit_controller_manager.launch.xml">
<!--    <arg name="execution_type" value="$(arg execution_type)" />-->
  </include>
```

**Comment by valmil2000** [comment]
Hey how exactly did you solve this bug?

**Comment by ranjitkathiriya** [comment]
I have provided my solution over here. 

https://github.com/ros-planning/moveit/issues/2570#issuecomment-810305129 (Just above your comment)

**Comment by ranjitkathiriya** [comment]
Or you can remove all args and keep this: 

```
<include file="$(find kuka_kr20_movit_config)/launch/move_group.launch">
      <arg name="publish_monitored_planning_scene" value="true" />
  </include>
```


Dont forget to do this: Answer: In trajectory_execution.launch.xml uncomment below line. The reason of this bug was the moveit_controller_manager.launch.xml file has no argument name execution_type.

as in above https://github.com/ros-planning/moveit/issues/2570#issuecomment-810305129 comment.

I think it should work.

**Comment by valmil2000** [comment]
Thanks for your help. I actually had to comment the line instead of uncommenting it.
