### ISSUE TITLE
Path optimization to minimize unnecessary movement

### ISSUE THREAD

**Issue by sdfzz** [ros-planning/moveit#2608]
Ubuntu 18.04
ROS Melodic

Hi,

I'm trying to use Moveit for a machine tending project. My environment consists of many obstacles and I'm impressed that Moveit can create a collision-free trajectory in such environment.

However, the generated path seems "exaggerated" as the robot tends to wonder unnecessary far from an obstacle to avoid it. 

I've tried "PathLengthOptimizationObjective", which improved the path, but not much.

Is there an option to further optimize the generated path? I'm willing to increase computation time if I can get more optimized path. 

Any help would be appreciated

Steve

**Comment by jschleicher** [comment]
Please take a look at https://answers.ros.org/question/342461/wrong-extremely-non-optimal-moveit-trajectories-on-scene-with-collision-objects/ with a nice answer from v4hn about RRT and please use https://answers.ros.org for future questions.
