### ISSUE TITLE
moveit kinetic build problem 

### ISSUE THREAD

**Issue by arpit15** [ros-planning/moveit#265]
https://gist.github.com/arpit15/0e83c83e8fe260e6441cfb395d7e6681
I was using the instructions from http://moveit.ros.org/install/source/ for kinetic ros on 16.04
fcl is compiling % . When I catkin build there is the error as listed in the attached file.

**Comment by davetcoleman** [comment]
please use https://gist.github.com/

**Comment by davetcoleman** [comment]
do you have ``libfcl-0.5.-dev`` and ``libfcl0.5`` installed via debian? have you run ``rosdep update``? did you run the ``rosdep install`` command?

**Comment by arpit15** [comment]
I installed from source using the commands from http://moveit.ros.org/install/source/dependencies/. 
I ran `rosdep update`. I didn't use `rosdep install`

**Comment by davetcoleman** [comment]
Ah, those are not official build instructions but rather experimental. Please specify that next time. Let us know if you find improvements in those instructions.

**Comment by arpit15** [comment]
Thank you @davetcoleman. I was able to successful build moveit with fcl-0.5 for kinetic on 16.04.

**Comment by davetcoleman** [comment]
Did you find any mistakes in my FCL instructions that could be fixed?

**Comment by arpit15** [comment]
@davetcoleman I used `git checkout fcl-0.5` instead of your command `git checkout -b tags/0.5.0` and everything build perfectly.

**Comment by davetcoleman** [comment]
i just confirmed your fix (i wrote those instructions after the fact of setting up FCL locally, sorry).

do you mind making a quick PR to the moveit website to fix the instructions? 
https://github.com/ros-planning/moveit.ros.org

**Comment by arpit15** [comment]
[@88](https://github.com/ros-planning/moveit.ros.org/pull/88) created PR with corrected instructions
