### ISSUE TITLE
MotionPlanning Display re-enables when rviz is reset

### ISSUE THREAD

**Issue by PeterMitrano** [ros-planning/moveit#2656]
### Description

If the MotionPlanning Display is turned off, and you hit reset, it enables itself and shows the MotionPlanning Panel. 

### Your environment
* ROS Distro: [Noetic]
* OS Version: Ubuntu 20.04
* Binary
* 1.1.2

### Steps to reproduce
 - Uncheck MPD
 - hit reset

### Expected behaviour
It should stay off

### Actual behaviour
MPD is renabled and MPP shows up

**Comment by rhaschke** [comment]
This should have been fixed recently in #2588, which was released with 1.1.2.
It's interesting that this issue popped up twice in very short time, while nobody cared about it in the past.
