### ISSUE TITLE
Lie on Pickup/Place actions comment? 

### ISSUE THREAD

**Issue by corot** [ros-planning/moveit#2667]
### Description

I'm trying to allow touching other collision objects when picking/placing. Following [this comment](https://github.com/ros-planning/moveit_msgs/blob/master/action/Pickup.action#L43), seems that adding "all" to the list of allowed_touch_objects will disable checks for all known objects, but this doesn't happen. And looking at [moveit code](https://github.com/ros-planning/moveit/blob/master/moveit_core/collision_detection/src/collision_matrix.cpp#L193), I cannot see where is this implemented, so I suppose is an error on the Pick/Place action comments.

Can anyone confirm, so I can open a PR removing the misguiding comment?

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04
* Source build from master branch

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by v4hn** [comment]
> Following [this comment](https://github.com/ros-planning/moveit_msgs/blob/master/action/Pickup.action#L43), seems that adding "all" to the list of allowed_touch_objects will disable checks for all known objects, but this doesn't happen. And looking at [moveit code](https://github.com/ros-planning/moveit/blob/master/moveit_core/collision_detection/src/collision_matrix.cpp#L193), I cannot see where is this implemented, so I suppose is an error on the Pick/Place action comments.
> 
> Can anyone confirm, so I can open a PR removing the misguiding comment?

You are right, this might have been removed during some cleanup years ago without updating the comment.
Feel free to remove the comment, I don't think we should add the described behavior back. :+1:
