### ISSUE TITLE
<function has no name member >

### ISSUE THREAD

**Issue by LEZHOU26** [ros-planning/moveit#2679]
### Description
When I catkin_make the work space, I received error below, and not for sure it is a ros problem or C++ problem, can some give me a hand?
/Desktop/catkinws/src/moveit/moveit_core/robot_state/src/conversions.cpp: In function ‘void moveit::core::{anonymous}::_attachedBodyToMsg(const moveit::core::AttachedBody&, moveit_msgs::AttachedCollisionObject&)’:
/home/le/Desktop/catkinws/src/moveit/moveit_core/robot_state/src/conversions.cpp:220:14: error: ‘moveit_msgs::AttachedCollisionObject_<std::allocator<void> >::_object_type {aka struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_names’
   aco.object.subframe_names.clear();
              ^~~~~~~~~~~~~~
/home/le/Desktop/catkinws/src/moveit/moveit_core/robot_state/src/conversions.cpp:221:14: error: ‘moveit_msgs::AttachedCollisionObject_<std::allocator<void> >::_object_type {aka struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_poses’; did you mean ‘plane_poses’?
   aco.object.subframe_poses.clear();
              ^~~~~~~~~~~~~~
              plane_poses
/home/le/Desktop/catkinws/src/moveit/moveit_core/robot_state/src/conversions.cpp:224:16: error: ‘moveit_msgs::AttachedCollisionObject_<std::allocator<void> >::_object_type {aka struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_names’
     aco.object.subframe_names.push_back(frame_pair.first);
                ^~~~~~~~~~~~~~
/home/le/Desktop/catkinws/src/moveit/moveit_core/robot_state/src/conversions.cpp:227:16: error: ‘moveit_msgs::AttachedCollisionObject_<std::allocator<void> >::_object_type {aka struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_poses’; did you mean ‘plane_poses’?
     aco.object.subframe_poses.push_back(pose);
                ^~~~~~~~~~~~~~
                plane_poses
/home/le/Desktop/catkinws/src/moveit/moveit_core/robot_state/src/conversions.cpp: In function ‘void moveit::core::{anonymous}::_msgToAttachedBody(const moveit::core::Transforms*, const AttachedCollisionObject&, moveit::core::RobotState&)’:
/home/le/Desktop/catkinws/src/moveit/moveit_core/robot_state/src/conversions.cpp:256:22: error: ‘const _object_type {aka const struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_poses’; did you mean ‘plane_poses’?
       if (aco.object.subframe_poses.size() != aco.object.subframe_names.size())
                      ^~~~~~~~~~~~~~
                      plane_poses
/home/le/Desktop/catkinws/src/moveit/moveit_core/robot_state/src/conversions.cpp:256:58: error: ‘const _object_type {aka const struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_names’
       if (aco.object.subframe_poses.size() != aco.object.subframe_names.size())
                                                          ^~~~~~~~~~~~~~
/home/le/Desktop/catkinws/src/moveit/moveit_core/robot_state/src/conversions.cpp:304:48: error: ‘const _object_type {aka const struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_poses’; did you mean ‘plane_poses’?
         for (std::size_t i = 0; i < aco.object.subframe_poses.size(); ++i)
                                                ^~~~~~~~~~~~~~
                                                plane_poses
/home/le/Desktop/catkinws/src/moveit/moveit_core/robot_state/src/conversions.cpp:307:35: error: ‘const _object_type {aka const struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_poses’; did you mean ‘plane_poses’?
           tf2::fromMsg(aco.object.subframe_poses[i], p);
                                   ^~~~~~~~~~~~~~
                                   plane_poses
/home/le/Desktop/catkinws/src/moveit/moveit_core/robot_state/src/conversions.cpp:308:41: error: ‘const _object_type {aka const struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_names’
           std::string name = aco.object.subframe_names[i];
                                         ^~~~~~~~~~~~~~
moveit/moveit_core/robot_state/CMakeFiles/moveit_robot_state.dir/build.make:86: recipe for target 'moveit/moveit_core/robot_state/CMakeFiles/moveit_robot_state.dir/src/conversions.cpp.o' failed
make[2]: *** [moveit/moveit_core/robot_state/CMakeFiles/moveit_robot_state.dir/src/conversions.cpp.o] Error 1
CMakeFiles/Makefile2:9666: recipe for target 'moveit/moveit_core/robot_state/CMakeFiles/moveit_robot_state.dir/all' failed
make[1]: *** [moveit/moveit_core/robot_state/CMakeFiles/moveit_robot_state.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04
* Source or Binary build? clone from  https://github.com/ros-planning/moveit.git

**Comment by rhaschke** [comment]
If you build from source you also need to use the latest source for the dependencies. Here, particularly, moveit_msgs needs to be updated as well.
