### ISSUE TITLE
CI needs to build MoveIt without MoveIt around

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#2689]
https://github.com/ros-planning/moveit/pull/2688 illustrates the problem.

With @rhaschke's freshly merged [split workspaces patch](https://github.com/ros-planning/moveit/pull/2654) it seems to work for most CI jobs now, but the melodic job still fails for the wrong reasons.

**Comment by rhaschke** [comment]
I think this can be closed due to https://github.com/ros-planning/moveit/pull/2688#issuecomment-856287819.
