### ISSUE TITLE
[noetic] Descartes Capability - Symbol lookup error with moveit 1.1.2 or newer, moveit 1.1.0 works fine

### ISSUE THREAD

**Issue by Hawxxer** [ros-planning/moveit#2733]
### Description

I try using descartes_capability with a moveit versionen newer than 1.1.1. While Moveit 1.1.1 works fine under ros noetic, since Moveit 1.1.2 I always get a symbol lookup error. I also opened a Issue at descartes_capability https://github.com/PickNikRobotics/descartes_capability/issues/11 but I can't really tell if it's a problem with moveit or descartes capability.

Edit 
To clear that up:
1.1.0 and 1.1.1 works fine, but since version 1.1.2 it stops working

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04.2
* 1.1.2, 1.1.3 and 1.1.0 from source, 1.1.5 binary 

### Steps to reproduce
start gazebo
start moveit
set new robot position
enable cartesian path
plan & execute

### Expected behaviour
descartes starts calculating new path

### Actual behaviour
moveit gets stuck

### Backtrace or Console output

![image](https://user-images.githubusercontent.com/46371370/123065959-ec5c4500-d40f-11eb-84cf-91f81be3685a.png)

How do I link the console output as a gist here?

```
[ INFO] [1624397880.308366634, 863.551000000]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[ INFO] [1624397880.308388435, 863.551000000]: MoveGroup context initialization complete

You can start planning now!

[ INFO] [1624397881.319000126, 864.562000000]: Ready to take commands for planning group helene_arm.
[ INFO] [1624397881.319065229, 864.562000000]: Looking around: no
[ INFO] [1624397881.319090266, 864.562000000]: Replanning: no
[ INFO] [1624397885.824363451, 869.064000000]: Received request to compute Descartes path
/home/eric/rviz/moveit3/devel/lib/moveit_ros_move_group/move_group: symbol lookup error: /home/eric/habc/devel/lib/libdescartes_capability.so: undefined symbol: _ZN2tf14poseMsgToEigenERKN13geometry_msgs5Pose_ISaIvEEERN5Eigen9TransformIdLi3ELi1ELi0EEE
[move_group-3] process has died [pid 88747, exit code 127, cmd /home/eric/rviz/moveit3/devel/lib/moveit_ros_move_group/move_group --debug __name:=move_group __log:=/home/eric/.ros/log/190b5764-d3a0-11eb-b24b-335eae1200a5/move_group-3.log].
log file: /home/eric/.ros/log/190b5764-d3a0-11eb-b24b-335eae1200a5/move_group-3*.log
[ INFO] [1624397891.555577313, 874.791000000]: Stopping planning scene monitor
[rviz_eric_88728_9101102882021071447-4] process has finished cleanly
log file: /home/eric/.ros/log/190b5764-d3a0-11eb-b24b-335eae1200a5/rviz_eric_88728_9101102882021071447-4*.log
```

**Comment by felixvd** [comment]
Did you try to clean and rebuild your workspace?

**Comment by Hawxxer** [comment]
> Did you try to clean and rebuild your workspace?

Yes I always do
catkin clean
catkin build

**Comment by JafarAbdi** [comment]
This's a bug in [descartes_capability](https://github.com/PickNikRobotics/descartes_capability) not moveit, this [commit](https://github.com/ros-planning/moveit/commit/b7711c134a8a1e173c9bf956f68ad8bbe27796c4) removed the dependency on `tf` but descartes_capability doesn't find/export it explicitly which should be the case (see [CMakeLists.txt](https://github.com/PickNikRobotics/descartes_capability/blob/master/CMakeLists.txt))

Do you mind adding `tf_eigen` to these lines [1](https://github.com/PickNikRobotics/descartes_capability/blob/master/CMakeLists.txt#L14) [2](https://github.com/PickNikRobotics/descartes_capability/blob/master/CMakeLists.txt#L36) [3](https://github.com/PickNikRobotics/descartes_capability/blob/master/package.xml) and see if it fixes the error you're seeing .?

**Comment by Hawxxer** [comment]
Do you mean `eigen_conversions` ? I think there is no package `tf_eigen`. If yes, that works thank you very much!

**Comment by JafarAbdi** [comment]
Sorry, yes, I think it was called `eigen_conversions` not `tf_eigen`

**Comment by JafarAbdi** [comment]
Could you please open a PR the fixes it upstream .? thanks!

**Comment by Hawxxer** [comment]
Will do, I will close the issue here.
