### ISSUE TITLE
Servo server JointTrajectory output incorrect when `use_gazebo` is true

### ISSUE THREAD

**Issue by turniphead** [ros-planning/moveit#2739]
### Description

Servo server trajectory output is incorrect when `use_gazebo` is set to true

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04
* Source or Binary build? binary
* If binary, which release version? apt list info: `ros-melodic-moveit-servo/bionic,now 1.0.8-1bionic.20210601.174208 amd64 [installed]`
* If source, which branch?

### Steps to reproduce
Launch servo server, configure `use_gazebo: true` and `command_out_type: trajectory_msgs/JointTrajectory`. 

### Expected behaviour
Output Trajectory should be useable with a ros controller

### Actual behaviour
I get this error from the controller: `Trajectory message contains waypoints that are not strictly increasing in time.`. Specifically, the second point of the trajectory is completely empty.

### Backtrace or Console output

**look at the second point of the following trajectory**
trajectory message output from servo server: https://gist.github.com/turniphead/046a5ec9282820ac4013aab71cc1e5a7

console output: https://gist.github.com/turniphead/fe2d375848cddcea69ab2e02ec091bae

**Comment by luisrayas3** [comment]
Suggested fix: https://github.com/ros-planning/moveit/pull/2740

**Comment by JafarAbdi** [comment]
Fıxed by https://github.com/ros-planning/moveit/pull/2740
