### ISSUE TITLE
MSA creates broken sensors_3d.yaml

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#2750]
If no sensor plugin is specified, the generated `sensors_3d.yaml` looks like this:
```
# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it
sensors:
  - {}
  - {}
```
Instead, the file should be *empty* to avoid error messages when parsing the configuration later.

**Comment by gavanderhoorn** [comment]
Is this a new version of #1680?

**Comment by v4hn** [comment]
Indeed. duplicate of #1680 - though I'll have to reopen the issue there...
