### ISSUE TITLE
use std::make_shared where applicable

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#2757]
MoveIt is sprinkled with `...SharedPtr::reset(new ...)` code and `SharedPtr(new ...)` constructors.
It is slightly (though in most cases not noticeably) faster and cleaner to use `std::shared_ptr<...>()` instead.

Anyone is welcome to help clean this up and create a pull-request along the lines of #2756 for wider parts of the code base. :muscle:

**Comment by pvanlaar** [comment]
I like to help! @v4hn, could you assign me? regards Patrick

**Comment by jaskiratsingh2000** [comment]
Hey  I am quite beginner and super interested to begin my contribution towards this repo and this issue seems interesting to me. Can you please let me know that where exactly do I have to make changes or add functionalities?
Any examples corresponding to this would be highly appreciable. Thanks!

**Comment by jaskiratsingh2000** [comment]
Is this still open?

**Comment by rhaschke** [comment]
As you can see a few lines above, this issue was tackled in #2762. However, because that PR is not yet merged (due to some open issues), this issue is not yet closed yet as well.

**Comment by jaskiratsingh2000** [comment]
So @rhaschke Do you think that I should work on this?

**Comment by jaskiratsingh2000** [comment]
@rhaschke Can you please assign this to me?

**Comment by rhaschke** [comment]
I don't think there is anything you can do. I'm looking into the open issues right now.

**Comment by jaskiratsingh2000** [comment]
@rhaschke Yes, please redirect me to super beginner friendly issue as I am supper interested to work under this repo. So I am looking forward to hearing from you

**Comment by pvanlaar** [comment]
The PR is merged, so this issue can be closed.

**Comment by rhaschke** [comment]
Closed via #2762.
