### ISSUE TITLE
avoid `boost`/`std::bind`

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#2766]
Similar in spirit to #2757, here is another nagging detail scattered throughout the code base:

Scott Meyer's "Effective Modern C++" Item 34 as well as [TOTW 108](https://abseil.io/tips/108) state:

> Avoid `boost`/`std::bind` [in favor of lambdas where applicable]

MoveIt uses `bind` in various places and readability suffers from it.
We should update the definitions to use lambdas with properly named arguments instead!

**Comment by tylerjw** [comment]
All the lambdas!

**Comment by rhaschke** [comment]
There is clang-tidy modernize-avoid-bind: https://github.com/ros-planning/moveit/commit/29d2de102e47c5ab88207a624f91b2b6c8752ed6 :smile: I will prepare a PR if clang-tidy is done...

**Comment by v4hn** [comment]
> There is clang-tidy modernize-avoid-bind

:open_mouth:  Cool!

**Comment by rhaschke** [comment]
Unfortunately, it doesn't translate placeholders into arguments :disappointed:  I'm trying clang-tidy-12 now...
