### ISSUE TITLE
how do I use compute_cartesian_path function?

### ISSUE THREAD

**Issue by haixuanwo** [ros-planning/moveit#277]
when I use compute_cartesian_path , I often get erorr.
the value of fraction is 89%,32%,50% etc.
I try to give long time and more tempt to  IK . It is not good, I will get strange trajectory.
I get waypoints in RVIZ using commander of "current". I doubt that I make mistake in here.

I want know how can I get correct waypoints?and how do I use compute_cartesian_path function?

**Comment by haixuanwo** [comment]
I have other question whether the compute_cartesian_path is used in two arms.

**Comment by v4hn** [comment]
This belongs on ROS answers and is not a direct issue of the framework.
You cross-posted at http://answers.ros.org/question/245476/how-do-i-use-compute_cartesian_path-function/
