### ISSUE TITLE
Node or topic that shows robot input

### ISSUE THREAD

**Issue by GitNzino** [ros-planning/moveit#2784]
# Summary

I want to known if there is any node or topic that shows the input given to the robot in terms of joint position and joint velocity.

# Use case

I am using moveit planner to obtain some advanced feature in robot movement and collision avoiding, but i do not known what is the input that the planner give to the robot. I can also obtain the feedback that in the case of velocity is with some noise.

Having a topic with input velocities and position is better to recognize the type of input that the joint is following

**Comment by simonschmeisser** [comment]
You can listen to the goal topic of the http://docs.ros.org/en/api/control_msgs/html/action/FollowJointTrajectory.html action

Please also note that questions like this should best be asked at answers.ros.org  (and please close this if your question has been answered)

**Comment by GitNzino** [comment]
Thank you for the response, next time I will surely go to the ros site to ask the question.

I tried to see the topic that you suggested, but i obtain only a sequence of point that in my opinion should be the waypoints of the trajectory. However nothing of them is printable continuatively using rqt_plot or plotjuggler, how should i do?

![image](https://user-images.githubusercontent.com/64754955/127137546-22246822-3ff1-4bf4-acd3-8010cb5aa7bd.png)


Thank you for help, kind regards

**Comment by felixvd** [comment]
This package should help: http://wiki.ros.org/rqt_joint_trajectory_plot

**Comment by GitNzino** [comment]
Thank you, it works properly!

But sometimes, the planner crash (I'm using Pilz) and put as output this error:
![image](https://user-images.githubusercontent.com/64754955/127178325-b89e5f8e-2b09-492a-abbc-f4f5d41d69f4.png)

Can You help me to understand what is not going on?
The robot is in pre-imposted position, but non works.
I tried to launch moveit and rviz with the robot in other position but it continues to not work

**Comment by simonschmeisser** [comment]
Are you sure that your robots position is within the joint limits? Those can be set both in URDF and in joint_limits.yaml. The yaml file wins if in doubt.

**Comment by GitNzino** [comment]
Yes, it was a similar issue! Thank you!
