### ISSUE TITLE
Add test for (#2824)

### ISSUE THREAD

**Issue by felixvd** [ros-planning/moveit#2843]
https://github.com/ros-planning/moveit/pull/2824 fixed a bug with the pilz industrial motion planner, where attached objects were not considered during plans. 

It would be very helpful if this bug was covered by a test, for example with a motion like in [this tutorial](https://ros-planning.github.io/moveit_tutorials/doc/move_group_interface/move_group_interface_tutorial.html):

![image](https://user-images.githubusercontent.com/4535737/130881794-323e673f-9f6b-4b09-b5c1-aeece179802b.png)

This is a good issue for someone new. You only need to add a test, e.g. in one of [these files](https://github.com/ros-planning/moveit/tree/master/moveit_ros/planning_interface/test) or a new one, which fails before the PR and succeeds after.

You can run your test with `catkin run_tests -iv` or `rostest your_package your_test_file` as described [here](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html). If you are a new contributor, feel free to ask for help in this thread.

**Comment by saurabh-1-1** [comment]
hey felix i am new to ros learned about moveit through sense think and act podcast really intrested in doing some open source work can you guide me how can i help solve this issue.

**Comment by felixvd** [comment]
Hi,

I would suggest to start by following the tutorials, asking on ROS Answers if you have trouble with anything, then move on to read and understand the code as much as possible, try to build it from source, then write some new tests and check if they succeed.

**Comment by gquey** [comment]
Hello, is this issue still open?  I am looking to make my first contribution and this looks like a good place to start. Thanks

**Comment by rhaschke** [comment]
As you can see from the latest linked PR, this issue was already fixed in #2878.
