### ISSUE TITLE
TypeError occured in MoveGroupCommander.plan() at use list to joints

### ISSUE THREAD

**Issue by ghost** [ros-planning/moveit#2869]
### Description

I use `MoveGroupCommander.plan()` in ROS melodic with a list of arguments `joints` that work fine.
But in ROS noetic rises `TypeError`.

It is probably due to the fact that MoveItCommanderException is used instead of TypeError at `except`.

melodic: except any exceptions
https://github.com/ros-planning/moveit/blob/melodic-devel/moveit_commander/src/moveit_commander/move_group.py#L613

noetic: except only MoveItCommanderException
https://github.com/ros-planning/moveit/blob/noetic-devel/moveit_commander/src/moveit_commander/move_group.py#L626

It may be the same problem as https://github.com/ros-planning/moveit/pull/1459.

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04.2
* Binary build: 1.0.8-1bionic.20210720.003319

### Steps to reproduce

```py
move_group = moveit_commander.MoveGroupCommander()
goal = [0.7976906570653386,
        0.0782906421639883,
        1.9223913621679352,
        1.1664013898767458,
        1.1357409385690191,
        -1.836251315695872]

succeeded, plan, _, error_code = move_group.plan(goal)
```

### Expected behaviour

```py
    succeeded, plan, _, error_code = move_group.plan(goal)
  File "/opt/ros/noetic/lib/python3/dist-packages/moveit_commander/move_group.py", line 625, in plan
    self.set_joint_value_target(self.get_remembered_joint_values()[joints])
TypeError: unhashable type: 'list'
```

### Actual behaviour

Handle TypeError and return plan.

**Comment by rhaschke** [comment]
Thanks for pinging us on this old issue. I filed a fix in https://github.com/ros-planning/moveit/pull/3302 now. Please review.
