### ISSUE TITLE
rviz createDisplay moveit_rviz_plugin/MotionPlanning collapsed

### ISSUE THREAD

**Issue by GuavaL** [ros-planning/moveit#2885]
### Description

can't create display moveit_rviz_plugin/MotionPlanning when you run code like 

`rviz::VisualizationManager* manager_;`
`rviz::Display* robot_;`
`robot_ = manager_->createDisplay("moveit_rviz_plugin/MotionPlanning", "robot", true);`

add MotionPlanning is normal in rviz.
### Your environment
* ROS Distro: [Melodic]
* OS Version: e.g. Win 10
* Source
* release

**Comment by v4hn** [comment]
please add more details. what actually happens and does that code work for other displays?
