### ISSUE TITLE
pilz_industrial_motion_planner/MoveGroupSequenceAction having issue with planning multi waypoints

### ISSUE THREAD

**Issue by PingHsunTsai** [ros-planning/moveit#2900]
### Description

By reproducing @cambel 's really useful python [sample](https://github.com/ros-planning/moveit/issues/2789#issuecomment-889650783), pilz_industrial_motion_planner/MoveGroupSequenceAction
can successfully plan and execute one or two simple waypoints but with the following error.
 ```
[ INFO] [1633881533.141877000, 9682.866000000]: Combined planning and execution request received for MoveGroupSequenceAction.
[ INFO] [1633881533.142027700, 9682.866000000]: Planning attempt 1 of at most 1
[ INFO] [1633881533.142317400, 9682.866000000]: Initialized Point-to-Point Trajectory Generator.
[ INFO] [1633881533.142450600, 9682.867000000]: Generating PTP trajectory...
[ INFO] [1633881533.142641900, 9682.867000000]: Goal already reached, set one goal point explicitly.
[ INFO] [1633881533.142883000, 9682.867000000]: Initialized Point-to-Point Trajectory Generator.
[ INFO] [1633881533.142962300, 9682.867000000]: Generating PTP trajectory...
[ INFO] [1633881537.172426000, 9686.886000000]: Controller 'scaled_pos_joint_traj_controller' successfully finished
[ INFO] [1633881537.177050500, 9686.890000000]: Completed trajectory execution with status SUCCEEDED ...
[ INFO] [1633881537.186955700, 9686.900000000]: Execution request received
[ERROR] [1633881537.193105000, 9686.906000000]:
Invalid Trajectory: start point deviates from current robot state more than 0.01
joint 'elbow_joint': expected: 2.85075e-05, current: 1.97222
[ INFO] [1633881537.193336700, 9686.906000000]: Execution completed: ABORTED
``` 

Once the waypoints are more than that this error will come up.
```

[ INFO] [1633881631.926094200, 9781.402000000]: Combined planning and execution request received for MoveGroupSequenceAction.
[ INFO] [1633881631.926279500, 9781.403000000]: Planning attempt 1 of at most 1
[ INFO] [1633881631.926537400, 9781.403000000]: Initialized Point-to-Point Trajectory Generator.
[ INFO] [1633881631.926645200, 9781.403000000]: Generating PTP trajectory...
[ INFO] [1633881631.926764700, 9781.403000000]: Goal already reached, set one goal point explicitly.
[ INFO] [1633881631.927004100, 9781.403000000]: Initialized Point-to-Point Trajectory Generator.
[ INFO] [1633881631.927101100, 9781.403000000]: Generating PTP trajectory...
[ INFO] [1633881631.927224200, 9781.404000000]: Goal already reached, set one goal point explicitly.
[ INFO] [1633881631.927418100, 9781.404000000]: Initialized Point-to-Point Trajectory Generator.
[ INFO] [1633881631.927494100, 9781.404000000]: Generating PTP trajectory...
[ INFO] [1633881631.928244600, 9781.405000000]: Initialized Point-to-Point Trajectory Generator.
[ INFO] [1633881631.928332900, 9781.405000000]: Generating PTP trajectory...
[ WARN] [1633881631.934653900, 9781.411000000]: Controller 'scaled_pos_joint_traj_controller' failed with error INVALID_GOAL: Trajectory message contains waypoints that are not strictly increasing in time.
[ WARN] [1633881631.934815300, 9781.411000000]: Controller handle scaled_pos_joint_traj_controller reports status FAILED
[ INFO] [1633881631.934992700, 9781.411000000]: Completed trajectory execution with status FAILED ...
```
Wondering if is robot start state having some issues, therefore I tried to follow the solution [here ](https://answers.ros.org/question/253004/moveit-problem-error-trajectory-message-contains-waypoints-that-are-not-strictly-increasing-in-time/)not adding the start point into waypoints, but still couldn't remove the error.

Thanks for your help in advance!
### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04
* Source 
* Robot: UR5

### Steps to reproduce
 Start the service with the [Universal_Robots_ROS_Driver](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver), gazebo simulation and moveit with roslaunch.

### Expected behaviour
plan and execute the trajactory

### Actual behaviour
`[ WARN] [1633881771.314513300, 9920.467000000]: Controller 'scaled_pos_joint_traj_controller' failed with error INVALID_GOAL: Trajectory message contains waypoints that are not strictly increasing in time.
[ WARN] [1633881771.314654100, 9920.467000000]: Controller handle scaled_pos_joint_traj_controller reports status FAILED`

**Comment by Joinjiang** [comment]
would you mind give more details on how to use  pilz_industrial_motion_planner in ros melodic env, if sample code can be provided, that may be prefect. Any help will be appreciated

**Comment by Joinjiang** [comment]
would you mind give more details on how to use  pilz_industrial_motion_planner in ros melodic env, if sample code can be provided, that may be prefect. Any help will be appreciated
