### ISSUE TITLE
trajoptConfig.cmake

### ISSUE THREAD

**Issue by posshe** [ros-planning/moveit#2933]
### Description
I have installed the trajopt, but it does't generate the trajoptConfig.cmake. Do you have some suggestion about the install about trajopt? Thank you!

Could not find a package configuration file provided by "trajopt" with any
  of the following names:

    trajoptConfig.cmake
    trajopt-config.cmake

  Add the installation prefix of "trajopt" to CMAKE_PREFIX_PATH or set
  "trajopt_DIR" to a directory containing one of the above files.  If
  "trajopt" provides a separate development package or SDK, be sure it has
  been installed.

### Your environment
* ROS Distro: [Melodic]
* OS Version:Ubuntu 18.04
* Source or Binary build? Source
* If binary, which release version? 
* If source, which branch? master

**Comment by simonschmeisser** [comment]
What do you mean by "installed the trajopt"?

**Comment by posshe** [comment]
Thank you for the reply. I have solved this question by installing the trajopt_ros package rather than the origin trajopt. I'll close the issue. Thank you.

**Comment by HaosUtopia** [comment]
> trajopt_ros

Hello, how did you solve this problem? I have tried to install trajopt_ros package and the dependencies inside its dependencies.rosinstall. But still miss trajoptConfig.cmake when compiling with moveit. Thanks in advance!

**Comment by Noah-Lau** [comment]
Have you solved the problem? I got the same issue. @HaosUtopia

**Comment by simonschmeisser** [comment]
You need to clone trajopt to your workspace: https://github.com/tesseract-robotics/trajopt
