### ISSUE TITLE
Weird semantics of default collision entries in ACM

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit#2936]
**Background:** franka_description introduced coarse collision models to mimic the behavior of self-collision checking of the real robot controller. Thus, planned trajectories will be executable without surprising new collisions.
**Problem:** collision model of hand is huge and doesn't allow to approach objects for grasping
**Solution proposal:** Use the coarse collision models for self-collision checking (only) and introduce smaller models for collision checking with the environment. 

This would require defining fallback defaults:
- `NEVER` collide coarse collision models with environment objects, but specify some self-collision pairs
- `ALWAYS` collide accurate collision models with environment objects, but disable self-collision via specific pairs

I knew that MoveIt provides a default value for collision objects. However, surprisingly this default is not considered as a _fallback_, but as an `override` taking precedence over explicitly declared collision pairs:
https://github.com/ros-planning/moveit/blob/f69a324617a14dc5f90b897d8bf6ae9c995960fd/moveit_core/collision_detection/src/collision_matrix.cpp#L281-L286

The corresponding ACM method `setDefaultEntry()` is only used once in the code base, namely to establish a custom collision function for the kinematic visibility constraint:
https://github.com/ros-planning/moveit/blob/779b7c8b019f70898d4de3189f9261c9697d9b9f/moveit_core/kinematic_constraints/src/kinematic_constraint.cpp#L1115

For this reason, I'm tempted to change the semantics, such that the default is considered a _fallback_ again.
Interestingly, the original implementation was intended to serve as a fallback as well, but [@isucan changed it 10 years ago](https://github.com/ros-planning/moveit/commit/c72a8570d420a23a9fe4715705ed617f18836634#diff-7cfe15079e95e5c372aceae894c1d6e373d52f247fdd2e112f8fa047be1919d7R261).
I'm curious what other maintainers think about this idea?
@v4hn, @simonschmeisser, @tylerjw, @henningkayser, @davetcoleman

**Comment by v4hn** [comment]
> I think we should keep interpreting the disable_collisions tags as default entries which I believe is what the current semantic https://github.com/ros-planning/moveit/blob/master/moveit_core/planning_scene/src/planning_scene.cpp#L162

You lost me there. Of course `disable_collisions` sets defaults for *pairs*.
But that cannot be used at this point to define a default *for a single link*, but that's relevant to decide the default for a link w.r.t. new objects. This is at least what Robert and I talked about in a recent phone call.
