### ISSUE TITLE
Add path_constraints to moveit_cpp interface

### ISSUE THREAD

**Issue by Colin-Kohler** [ros-planning/moveit#2958]
There is no current way to set the path_constraints field of a MotionPlanRequest when using the moveit_cpp interface. Recently, this feature was added to moveit2: https://github.com/ros-planning/moveit2/pull/752. Should be simple enough to port those changes over to moveit with minor changes. I have a forked version of moveit, that does exactly this and will submit a PR to incorporate these changes.

**Comment by JafarAbdi** [comment]
Fixed by https://github.com/ros-planning/moveit/pull/2959
