### ISSUE TITLE
sync-noetic-devel can break when two PRs are merged close to each other

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#2989]
I just received [a failed action run](https://github.com/ros-planning/moveit/actions/runs/1563785198) for the sync action and was wondering for a while what went wrong.
Turns out I merged 9d78be4705fad661a9cd2ef90b0f9d933d60b325 and 9bfb2c73cf70acef7ba9d127698831d3fe14bd04 very close to each other and the wrong one pushed first:

```
To https://github.com/ros-planning/moveit
 ! [rejected]        master -> noetic-devel (non-fast-forward)
error: failed to push some refs to 'https://github.com/ros-planning/moveit'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I don't want to experiment with this right now, but I guess
https://github.com/ros-planning/moveit/blob/master/.github/workflows/ci.yaml#L169
can be replaced by something like
```
git switch noetic-devel
git merge --ff-only master
git push origin noetic-devel
```
?
@rhaschke

**Comment by rhaschke** [comment]
The key problem was probably that the wrong `noetic-devel` branch was fetched from remote. I'm not convinced that your proposal will help for this. Rather, we would need to fetch again...
Did you manually forwarded noetic-devel now? Maybe just re-triggering the CI job would have helped?
I'm not sure it's worth to put effort into fixing this...

**Comment by v4hn** [comment]
no, I did not push by hand. 
I expect the job of the second mentioned commit (which suceeded) did the trick. 

On December 10, 2021 8:52:02 PM GMT+01:00, Robert Haschke ***@***.***> wrote:
>The key problem was probably that the wrong `noetic-devel` branch was
>fetched from remote. I'm not convinced that your proposal will help for
>this. Rather, we would need to fetch again...
>Did you manually forwarded noetic-devel now? Maybe just re-triggering
>the CI job would have helped?
>I'm not sure it's worth to put effort into fixing this...
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ros-planning/moveit/issues/2989#issuecomment-991251523

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
