### ISSUE TITLE
Duration is out of dual 32-bit range 

### ISSUE THREAD

**Issue by fzoric8** [ros-planning/moveit#2994]
### Problem Description
I'm sometimes having issue during path planning. After executing moveGroup->execute(), during execution I get following error: 
```
[ERROR] [1639416096.145879252]: Dynamic exception type: std::runtime_error
std::exception::what: Duration is out of dual 32-bit range

```

### My environment
* ROS Distro: Noetic
* OS Version: e.g. Ubuntu 20.04
* Source 
* Branch: `noetic-devel`, log `a27e5d1a1e9f18389d3cb5fe444d39814da6a043` 
* Schunk lwa4p robot (CAN communication)

### Steps to reproduce
I'm currently not able to provide scripts for reproducing error, however this error happens sometimes, not always. It's quite hard to determine when and why it happens. I've tried rebuilding whole ROS workspace and I'm sure I'm using ROS `noetic` and  have adequate environment. Interesting thing is that it happens only occasionaly, and it's probably related to time duration of certain trajectory (shorter planning time, easier fail). 

Any help would be much appreciated. Even how te get verbose output to be able to better locate source of the error. 
Thank you

**Comment by rhaschke** [comment]
This usually occurs when using an uninitialized duration or calculating a negative duration. Please try to narrow the issue down.

**Comment by fzoric8** [comment]
Closing this up because it's not related to `moveit`. 

I was looking how to get better outputs and found [this](http://wiki.ros.org/rosconsole#Console_Output_Formatting). 
I set up rosconsole output formatting environment variable as follows: 

```
export ROSCONSOLE_FORMAT='[${severity}] [${time}] [${node}]: ${message}'
```
Maybe helps someone. 
Thank you!
