### ISSUE TITLE
Provide version check macro

### ISSUE THREAD

**Issue by simonschmeisser** [ros-planning/moveit#2996]
Qt has a very convenient macro for version checks:
https://doc.qt.io/qt-5/qtglobal.html#QT_VERSION_CHECK

We should have that too

relates to #2995

**Comment by v4hn** [comment]
I wrote [a related macro for MTC before](https://github.com/ros-planning/moveit_task_constructor/blob/master/core/include/moveit/task_constructor/moveit_compat.h#L43-L45).
