### ISSUE TITLE
no robot seen when i run the moveit tutorial

### ISSUE THREAD

**Issue by mashuai191** [ros-planning/moveit#3006]
### Description
i start to learn by going through this link https://ros-planning.github.io/moveit_tutorials/doc/quickstart_in_rviz/quickstart_in_rviz_tutorial.html, but cannot see the robot mentioned here - "You should now see the Panda robot in RViz:"

### Your environment
* ROS Distro: [Noetic]
* OS Version: e.g. Ubuntu 20.04 on WSL2
* Source or Binary build?
* If binary, which release version?
* If source, which branch? source as the link suggested

### Steps to reproduce
first go through this: https://ros-planning.github.io/moveit_tutorials/doc/getting_started/getting_started.html
then go through this: https://ros-planning.github.io/moveit_tutorials/doc/quickstart_in_rviz/quickstart_in_rviz_tutorial.html

### Expected behaviour
cannot see the robot
then i check the 'Show Robot Collision' under 'Motion Planning folder', a red pipe-like robot appear but it looks not a real robot, quite abstract.

### Actual behaviour
Tell us what happens instead

### Backtrace or Console output

You can start planning now!

[ INFO] [1640013940.964509939]: rviz version 1.14.13
[ INFO] [1640013940.964564902]: compiled against Qt version 5.12.8
[ INFO] [1640013940.964572580]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1640013940.971327842]: Forcing OpenGl version 0.
[ INFO] [1640013943.931013498]: Stereo is NOT SUPPORTED
[ INFO] [1640013943.931108535]: OpenGL device: D3D12 (NVIDIA GeForce MX450)
[ INFO] [1640013943.931163572]: OpenGl version: 3.1 (GLSL 1.4).
[ INFO] [1640013965.344652355]: Loading robot model 'panda'...
[ WARN] [1640013965.344969704]: Link panda_leftfinger has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[ WARN] [1640013965.345053534]: Link panda_rightfinger has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[ INFO] [1640013965.423813077]: Starting planning scene monitor
[ INFO] [1640013965.427060119]: Listening to '/move_group/monitored_planning_scene'
[ INFO] [1640013965.892332548]: No active joints or end effectors found for group 'hand'. Make sure that kinematics.yaml is loaded in this node's namespace.
[ INFO] [1640013965.894481227]: No active joints or end effectors found for group 'hand'. Make sure that kinematics.yaml is loaded in this node's namespace.
[ INFO] [1640013965.904558469]: Constructing new MoveGroup connection for group 'hand' in namespace ''
[ INFO] [1640013967.048063098]: Ready to take commands for planning group hand.

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

add the screenshot:
![screen](https://user-images.githubusercontent.com/40193779/146853809-8cf50ae6-04ed-40ba-9dfc-774bea67217d.png)
![Screenshot 2021-12-21 091134](https://user-images.githubusercontent.com/40193779/146853923-6b07f286-5ab9-43ab-8a5e-babbec0be29d.png)

**Comment by rhaschke** [comment]
Typically such display issues are due to the OpenGL in use. Please, could you provide more details about your specific setup?
Can you get any standard OpenGL output or generic output in rviz?

**Comment by mashuai191** [comment]
Thanks for quick response! Everything looks ok (there is a empty grid chart) except the robot not seen. 
For setup I copied some logs there, hope that useful.

**Comment by rhaschke** [comment]
The logs don't indicate an issue. I suspect issues with WSL2 and OpenGL.

**Comment by mashuai191** [comment]
@rhaschke, today i fresh-installed a VM(Ubuntu20.04) in VirtualBox and go through the same steps, and the robot can be shown properly, so as you said that may be an issue in my WSL2 and OpenGL. For now i can use my VirtualBox VM to go forward. Thanks for your help!

**Comment by IsolatedMeasure** [comment]
I run into this problem either, it was the same as the issue in [wslg issue 554](https://github.com/microsoft/wslg/issues/554) ,  seems that ogre3d  in wslg can't work very well. Like the advice given in that issue, by temporary set `export LIBGL_ALWAYS_SOFTWARE=1` , the problem can be solved temporary. Maybe this information is a little bit helpful.
