### ISSUE TITLE
No model showing up in moveit setup assistant

### ISSUE THREAD

**Issue by pratsc7117** [ros-planning/moveit#3029]
Hi, I'm using ROS Noetic on Ubuntu 20.04. I created a urdf file from solidworks that I wish to configure using MSA.
I confirmed that the urdf file works and has the meshes and child/parent info.

The MSA says that the file was loaded sucessfully, but the model doesnt show up on the right. Moreover, if i go ahead and try to generate the collision matrix, no links are found.. Not sure what the problem is.

Only error I get after uploading the model is: Ros was unable to find the package name "XXX" within the ROS workspace, This may cause issues later.

**Comment by rhaschke** [comment]
Obviously, you need to setup your ROS workspace such that meshes from the URDF are found. So, please fix the "only" error you get.
