### ISSUE TITLE
Joint 'panda_joint1' declared as part of group 'panda_arm' is not known to the URDF (Not solved)

### ISSUE THREAD

**Issue by sm3304love** [ros-planning/moveit#3032]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04
* Source or Binary build?
* If binary, which release version?
* If source, which branch?

### Steps to reproduce
The Xacro file is defined as below code, and the config file is created through moveit setup assistance.
![Screenshot from 2022-01-21 22-15-10](https://user-images.githubusercontent.com/57741032/150536739-20b9779a-eb25-4926-b9d8-16c17574148d.png)

In the moveit setup assistance, I confirmed that the shape of the xacro file appears correctly.
![Screenshot from 2022-01-21 22-44-00](https://user-images.githubusercontent.com/57741032/150537523-b14fc32a-eef6-4bf9-b9ce-2257890c8456.png)

### Expected behaviour
I created a config file using setup assistance using the xacro file that Franka panda emika above the box named "base". However, when I run demo gazebo.launch, the following error occurs. What is wrong?

### Actual behaviour

[ERROR] [1642689202.858111809]: Joint 'panda_joint1' declared as part of group 'panda_arm' is not known to the URDF
[ERROR] [1642689202.858741291]: Joint 'panda_joint2' declared as part of group 'panda_arm' is not known to the URDF
[ERROR] [1642689202.858754184]: Joint 'panda_joint3' declared as part of group 'panda_arm' is not known to the URDF
[ERROR] [1642689202.858760998]: Joint 'panda_joint4' declared as part of group 'panda_arm' is not known to the URDF
[ERROR] [1642689202.858766978]: Joint 'panda_joint5' declared as part of group 'panda_arm' is not known to the URDF
[ERROR] [1642689202.858772792]: Joint 'panda_joint6' declared as part of group 'panda_arm' is not known to the URDF
[ERROR] [1642689202.858781150]: Joint 'panda_joint7' declared as part of group 'panda_arm' is not known to the URDF
[ERROR] [1642689202.858790417]: Joint 'panda_joint8' declared as part of group 'panda_arm' is not known to the URDF
[ERROR] [1642689202.858809454]: Link 'panda_hand' declared as part of group 'hand' is not known to the URDF
[ERROR] [1642689202.858820333]: Link 'panda_leftfinger' declared as part of group 'hand' is not known to the URDF
[ERROR] [1642689202.858829936]: Link 'panda_rightfinger' declared as part of group 'hand' is not known to the URDF
[ WARN] [1642689202.858840067]: Group 'hand' is empty.
[ERROR] [1642689202.858857214]: Joint 'panda_finger_joint1' declared as part of group state 'home' is not known to the URDF
[ERROR] [1642689202.858867837]: Joint 'panda_finger_joint2' declared as part of group state 'home' is not known to the URDF
[ERROR] [1642689202.858885177]: Link 'panda_link8' specified as parent for end effector 'hand' is not known to the URDF
[ WARN] [1642689202.858903007]: Link 'panda_hand' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.858913799]: Link 'panda_leftfinger' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.858923375]: Link 'panda_link0' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.858932473]: Link 'panda_link1' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.858941610]: Link 'panda_link2' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.858950714]: Link 'panda_link3' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.858959836]: Link 'panda_link4' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.858968619]: Link 'panda_link5' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.858977694]: Link 'panda_link6' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.858986775]: Link 'panda_link7' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.858995748]: Link 'panda_link8' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859004658]: Link 'panda_rightfinger' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859013860]: Link 'panda_hand' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859022829]: Link 'panda_hand' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859032031]: Link 'panda_hand' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859040940]: Link 'panda_hand' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859049900]: Link 'panda_hand' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859058792]: Link 'panda_hand' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859068049]: Link 'panda_hand' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859076829]: Link 'panda_leftfinger' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859085883]: Link 'panda_leftfinger' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859094924]: Link 'panda_leftfinger' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859103998]: Link 'panda_leftfinger' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859112693]: Link 'panda_leftfinger' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859121865]: Link 'panda_leftfinger' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859131228]: Link 'panda_link0' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859140752]: Link 'panda_link0' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859149354]: Link 'panda_link0' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859158359]: Link 'panda_link0' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859167270]: Link 'panda_link1' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859176383]: Link 'panda_link1' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859198962]: Link 'panda_link1' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859209005]: Link 'panda_link2' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859219379]: Link 'panda_link2' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859228967]: Link 'panda_link3' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859238854]: Link 'panda_link3' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859248797]: Link 'panda_link4' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859259508]: Link 'panda_link4' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859269435]: Link 'panda_link4' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859278895]: Link 'panda_link4' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859287964]: Link 'panda_link4' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859297172]: Link 'panda_link5' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859305841]: Link 'panda_link5' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859315047]: Link 'panda_link5' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859324401]: Link 'panda_link6' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859333874]: Link 'panda_link6' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859342637]: Link 'panda_link7' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859351829]: Link 'panda_link7' is not known to URDF. Cannot disable collisons.
[ WARN] [1642689202.859361100]: Link 'panda_link8' is not known to URDF. Cannot disable collisons.

![Screenshot from 2022-01-20 23-38-55](https://user-images.githubusercontent.com/57741032/150360554-c9b4d0ec-3efd-4c9e-a55c-d7f69aa108f8.png)

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by sm3304love** [comment]
> urdf를 다양하게 구성하고 있습니까? 이전 파일을 공유하고 있습니까?
You mean demo_gazebo.launch file?
`<launch>

  
  <arg name="db" default="false" />
  
  <arg name="db_path" default="$(find capston_moveit_config)/default_warehouse_mongo_db" />

  
  <arg name="debug" default="false" />

  
  <arg name="load_robot_description" default="false"/>

  
  <arg name="use_gui" default="false" />

  
  <arg name="gazebo_gui" default="true"/>
  <arg name="paused" default="false"/>
  
  <arg name="urdf_path" default="$(find franka_description)/robots/panda_arm_hand.urdf.xacro"/>

  
  <include file="$(find capston_moveit_config)/launch/gazebo.launch" >
    <arg name="paused" value="$(arg paused)"/>
    <arg name="gazebo_gui" value="$(arg gazebo_gui)"/>
    <arg name="urdf_path" value="$(arg urdf_path)"/>
  </include>

  
  

  
  <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher" unless="$(arg use_gui)">
    <rosparam param="source_list">[move_group/fake_controller_joint_states]</rosparam>
    <rosparam param="source_list">[/joint_states]</rosparam>
  </node>
  <node name="joint_state_publisher" pkg="joint_state_publisher_gui" type="joint_state_publisher_gui" if="$(arg use_gui)">
    <rosparam param="source_list">[move_group/fake_controller_joint_states]</rosparam>
    <rosparam param="source_list">[/joint_states]</rosparam>
  </node>

  
  <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher" respawn="true" output="screen" />

  
  <include file="$(find capston_moveit_config)/launch/move_group.launch">
    <arg name="allow_trajectory_execution" value="true"/>
    <arg name="fake_execution" value="false"/>
    <arg name="info" value="true"/>
    <arg name="debug" value="$(arg debug)"/>
    <arg name="load_robot_description" value="$(arg load_robot_description)"/>
  </include>

  
  <include file="$(find capston_moveit_config)/launch/moveit_rviz.launch">
    <arg name="rviz_config" value="$(find capston_moveit_config)/launch/moveit.rviz"/>
    <arg name="debug" value="$(arg debug)"/>
  </include>

  
  <include file="$(find capston_moveit_config)/launch/default_warehouse_db.launch" if="$(arg db)">
    <arg name="moveit_warehouse_database_path" value="$(arg db_path)"/>
  </include>

</launch>`

**Comment by sm3304love** [comment]
> How are you loading the urdf to the parameter server ? do you mind sharing the launch file ?

You mean demo_gazebo.launch file?

 
I accidentally clicked the close button. Can you reopen it?

**Comment by armanarnautovic** [comment]
I have the same problem: 'joint  declared is not known to the URDF', after customizing the manipulator via setup assistant

**Comment by rhaschke** [comment]
@armanarnautovic, please open a new issue and provide detailed information about your robot's moveit_config.
I don't face any issues running [panda_moveit_config's](https://github.com/ros-planning/panda_moveit_config) demo.launch.
A gazebo.launch file is not part of its melodic-devel branch. So what is your actual command and environment?
