### ISSUE TITLE
No kinematics plugins defined. Fill and load kinematics.yaml!

### ISSUE THREAD

**Issue by mduz22** [ros-planning/moveit#3042]
I try to start moveit_planning_execution.launch file for fanuc_m10ia robot. However, I have this error when I start. 

[ INFO] [1643356674.864498473]: Loading robot model 'fanuc_m10ia'...
[ WARN] [1643356674.917474783]: No kinematics plugins defined. Fill and load kinematics.yaml!
...
The launch is working but this warning is blocking me.

Actually I added kinematics.yaml into moveit_planning_execution.launch with the following command :

<rosparam command="load" file="$(find fanuc_m10ia_moveit_config)/config/kinematics.yaml"/>

And my kinematics.yaml is :

manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005

Also, I added IKsolver (KDLKinematicsPlugin) while creating a group in setup assistant by following the path below.
planning group -> manipilator -> kinematics solver 

But it has not changed. 

Is there anyone who can help ? Thanks !

**Comment by rhaschke** [comment]
Check on the ROS parameter server that your kinematics config was actually loaded.
As each joint model group has its own kinematics config, ensure that you selected the correct group.

**Comment by mduz22** [comment]
I have just joint group named "manipulator" and I checked if it has kinematics solver. I loaded the ROS parameter server like this:
< rosparam command="load" file="$(find fanuc_m10ia_moveit_config)/config/kinematics.yaml" >
Is that false?

**Comment by rhaschke** [comment]
See [`moveit_resources`](https://github.com/ros-planning/moveit_resources/tree/master/panda_moveit_config) for an example config or create a new config for your robot from scratch using MoveIt Setup Assistant and compare this with your current config.

**Comment by mduz22** [comment]
My rosparam command was not right. I took a look at your advice and fixed it. Thank you!

**Comment by Mustafaalam99** [comment]
Hello,
I am facing the same issue. I have my robot launch file which launches the robot in rviz as well as gazebo. I am calling the launch files created by moveit2 in my launch file to launch different nodes (rsp, move_group, rviz, spawn_controllers). I am following the [panda pick and place tutorial ](https://moveit.picknik.ai/main/doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.html). In that I have updated the file as per my robot and I am trying to run it. I am able to setup the planning scene but once I start creating task it gives me an error 
[WARN] [1713160664.150421854] [moveit_ros.robot_model_loader]: No kinematics plugins defined. Fill and load kinematics.yaml!
[ERROR] [1713161573.374594726] [moveit_robot_state.robot_state]: No kinematics solver instantiated for group 'arm'

**Comment by rhaschke** [comment]
@Mustafaalam99, this is the MoveIt repository for ROS1. As you are using ROS2, switch to https://github.com/ros-planning/moveit2. But in general the same advice holds: check that the parameters are loaded correctly.

**Comment by Mustafaalam99** [comment]
Okay will post there. Thanks for the reply.

**Comment by Wangbaiyue007** [comment]
Hi! Just to make sure that you don't make the same mistake as I do, after launching the moveit server, you do need to run your client node by launching it, similar to [this](https://github.com/moveit/moveit2_tutorials/blob/main/doc/examples/move_group_interface/launch/move_group_interface_tutorial.launch.py). 

Using `ros2 run your_package your_client_node` directly will cause `No kinematics plugins defined. Fill and load kinematics.yaml!`.
