### ISSUE TITLE
NO PLANNING LIBRARY LOADED in CHOMP PLANNER tutorial

### ISSUE THREAD

**Issue by QNXLQ** [ros-planning/moveit#3072]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: [Kinetic|Melodic|Noetic]
* OS Version: e.g. Ubuntu 18.04
* Source
* If source, which branch?    melodic-devel

### Steps to reproduce
Follow the tutorial and `roslaunch panda_moveit_config demo.launch pipeline:=chomp`

### Actual behaviour
in the ternimal show error: [move_group-6] process has died
in the MotionPlanning of Display, Status:Warn, PlanningScene warnning that "Requesting initial scene failed"
In the Context section of MotionPlanning, it reports that "NO PLANNING LIBRARY LOADED" in red color.

if i run the code `roslaunch panda_moveit_config demo.launch` without set the pipeline, no error 

### Backtrace or Console output

`[ INFO] [1646126213.343504300]: Loading planning pipeline ''`
`[ INFO] [1646126213.363768890]: rviz version 1.13.23`
`[ INFO] [1646126213.363830162]: compiled against Qt version 5.9.5`
`[ INFO] [1646126213.363840460]: compiled against OGRE version 1.9.0 (Ghadamon)
move_group: malloc.c:2401: sysmalloc: Assertion` `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.`
`[ INFO] [1646126213.372873630]: Forcing OpenGl version 0.`
`[move_group-6] process has died [pid 62195, exit code -6, cmd /home/nielei/catkin_ws/devel/lib/moveit_ros_move_group/move_group --debug /joint_states:=/joint_states_desired __name:=move_group __log:=/home/nielei/.ros/log/53eb682c-9940-11ec-b113-000c29873124/move_group-6.log].`
`log file: /home/nielei/.ros/log/53eb682c-9940-11ec-b113-000c29873124/move_group-6*.log`
`[ INFO] [1646126215.076711393]: Stereo is NOT SUPPORTED`
`[ INFO] [1646126215.076864865]: OpenGL device: SVGA3D; build: RELEASE;  LLVM;`
`[ INFO] [1646126215.076926252]: OpenGl version: 3.3 (GLSL 3.3) limited to GLSL 1.4 on Mesa system.`
`[ INFO] [1646126215.207829556]: Loading robot model 'panda'...`
`[ WARN] [1646126215.208308013]: Link panda_leftfinger has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.`
`[ WARN] [1646126215.208505761]: Link panda_rightfinger has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.`
`[ INFO] [1646126215.783294139]: Loading robot model 'panda'...`
`[ WARN] [1646126215.783466465]: Link panda_leftfinger has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.`
`[ WARN] [1646126215.783519853]: Link panda_rightfinger has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.`

**Comment by rhaschke** [comment]
I just tested the command `roslaunch panda_moveit_config demo.launch pipeline:=chomp` and it works fine with latest MoveIt release 1.0.9 and `melodic-devel` branch of [`panda_moveit_config`](https://github.com/ros-planning/panda_moveit_config).

According to your log, the `move_group` process dies due to some `malloc` assertion failure. Try to reboot your machine and check that you have enough memory.

**Comment by QNXLQ** [comment]
> I just tested the command `roslaunch panda_moveit_config demo.launch pipeline:=chomp` and it works fine with latest MoveIt release 1.0.9 and `melodic-devel` branch of [`panda_moveit_config`](https://github.com/ros-planning/panda_moveit_config).
> 
> According to your log, the `move_group` process dies due to some `malloc` assertion failure. Try to reboot your machine and check that you have enough memory.

thanks, i tried to reboot my virtual machine and check the memory: 8G total and 6G available, and 20G swap when i run the command, but the process still has died

By the way, i tried to tested the command on Ubuntu 16.04 + ROS kinetic, it works fine

**Comment by QNXLQ** [comment]
> You wrote, you are using a MoveIt source build from `melodic-devel` branch. Could you try with a released version of MoveIt, please?

Thanks, i solved this
