### ISSUE TITLE
collisions_updater not generating a complete matrix

### ISSUE THREAD

**Issue by LoyVanBeek** [ros-planning/moveit#3073]
### Description

A colleague of mine noticed that when using `rosrun moveit_setup_assistant collisions_updater ...  --default --always --keep --verbose ...` the allowed collisions matrix would lose almost all of it's entries, even ones that should obviously be there. 

### Your environment
* ROS Distro: [Noetic]
* OS Version: e.g. Ubuntu 20.04
* Source build: `tag/1.1.8` or rather my debug branch: https://github.com/ros-planning/moveit/compare/1.1.8...LoyVanBeek:debug/collision_updater with some extra logging

### Steps to reproduce
0. `cd ~/moveit_ws/src`
1. `git clone git@github.com:ros-industrial/universal_robot.git`
2. `cd ur10_e_moveit_config`  # and check content of `config/ur10e.srdf`
3. `catkin build --this`
4. Delete all the `<disable_collisions ...>` tags
5. `rosrun moveit_setup_assistant collisions_updater --config-pkg ur10_e_moveit_config --default --always --keep --trials 100000`
6. `git diff -w` to ignore changes to whitespace
7. Observe the diff to the collision matrix. Each link appears only once as `link1`, instead of some multiple times as it were before.

### Expected behaviour
The collision matrix should be unchanged, give or take some formatting. 

### Actual behaviour
Only a few pairs remain, in this case
```xml
<disable_collisions link1="base_link" link2="shoulder_link" reason="Adjacent"/>
<disable_collisions link1="ee_link" link2="wrist_1_link" reason="Never"/>
<disable_collisions link1="shoulder_link" link2="wrist_2_link" reason="Never"/>
<disable_collisions link1="wrist_1_link" link2="wrist_3_link" reason="Never"/>
```
Notice that all the `link1`s are unique while this was not the case before. 

### Backtrace or Console output
Console output using my debug branch: 
https://gist.github.com/LoyVanBeek/d782e4fadf2fa1d88f0ab4aaa064e43e

Notice the occurrences of [`filtered.insert`](https://github.com/ros-planning/moveit/compare/1.1.8...LoyVanBeek:debug/collision_updater#diff-afd5f8e1ad86bce85a80043828f0b90044790924e39d7ba7527a2a4fb99c29a7R172). Only 4 of those while there are much more pairs that should be disabled. 
All other cases it reports [`filtered cont. `](https://github.com/ros-planning/moveit/compare/1.1.8...LoyVanBeek:debug/collision_updater#diff-afd5f8e1ad86bce85a80043828f0b90044790924e39d7ba7527a2a4fb99c29a7R176) meaning the item is not inserted (because the set 'thinks' it already contains the pair ie. is not 'unique' according to the specified equivalency operator). 

`filtered` is a `set` that I think should only include unique pairs. But judging by the logging, it only allows uniqueness of `pair.first`, so only the first pair including some link is included.

This made me think the [set comparison operation here](https://github.com/ros-planning/moveit/blob/1.1.8/moveit_setup_assistant/src/collisions_updater.cpp#L123) is the culprit

**Comment by rhaschke** [comment]
Fixed via #3076.
