### ISSUE TITLE
High octomap_resolution causes Transform Error.

### ISSUE THREAD

**Issue by sm3304love** [ros-planning/moveit#3083]
### Description
By default, octomap_resolution is set to 0.05, but should be set to 0.02 if necessary. However, if I set octomap_resolution to 0.02, I get a Transform Error that didn't happen before.

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04

### Steps to reproduce
When `octomap_resolution` in sensor_manager.launch.xml was set to 0.02, a Transform Error occurs

### Expected behaviour
High resolution octomap implementation without Transform Error

### Actual behaviour
Transform Error occurs
![Screenshot from 2022-03-08 21-53-36](https://user-images.githubusercontent.com/57741032/157243523-976ec170-b4e0-48f7-b45b-50464a642ade.png)

**Comment by v4hn** [comment]
you will have to compensate to either restrict the number of messages (or points per message) your updater receives or run on a faster machine. There is a natural trade-off here between resolution and computational load. If computation falls behind too much TF has dropped the relevant transforms already.

If you are using the `pointcloud_octomap_updater` with a depth camera, consider switching to the `depth_image_octomap_updater` which is much faster in general.
