### ISSUE TITLE
When using octomap mapping for an actual robot, is self-filtering applied to the robot?

### ISSUE THREAD

**Issue by sm3304love** [ros-planning/moveit#3089]
In the simulation environment, if the camera was added to the urdf, we could see that the octomap ignores the urdf of the robot. However, I'm wondering if this can equally disregard a real robot in a real world environment.
As a student, I have not yet applied it to a real robot. Can you tell me if self-filtering is possible for real robots as well? And if possible, can you tell me if the implementation way  is the same as the simulation or different?

(simulation world)
![image](https://user-images.githubusercontent.com/57741032/158052300-3e4e4609-6383-4a55-bc37-bc19781bcc14.png)

(real world)
![image](https://user-images.githubusercontent.com/57741032/158052346-1829ad7e-70d8-442c-99ad-c7f7d05ab754.png)

**Comment by simonschmeisser** [comment]
The so called "self-filtering" should work with the real robot as well
