### ISSUE TITLE
When i try to launch the robot model, getting this issue

### ISSUE THREAD

**Issue by LOKAKSHAI** [ros-planning/moveit#3101]
[ INFO] [1648117589.991587820]: Ready to take commands for planning group manip.
[ INFO] [1648117591.010270653]: Didn't receive robot state (joint angles) with recent timestamp within 1 seconds.

* ROS Distro: Melodic
Ubuntu version : 18.04

**Comment by v4hn** [comment]
The error message tells you `/joint_states` is not published (or not with correct time stamps) by anyone. Either a simulation or the real hardware has to publish them. This is not an issue in the framework.
