### ISSUE TITLE
The problem of planning the movement of the manipulator and the gripper at the same time in rviz using moveit

### ISSUE THREAD

**Issue by ksjz** [ros-planning/moveit#3115]
I am using moviet in rviz to drive the motion of the robotic arm and the gripper at the same time, but I can't find the relevant API. Have you ever done a similar operation?  Thank you!

**Comment by rhaschke** [comment]
Just define a planning group comprising both, the arm and the end-effector. Then you can easily define and plan for a common target.

**Comment by ksjz** [comment]
> 

i get it, thank you!
