### ISSUE TITLE
chomp_motion_planner build failure

### ISSUE THREAD

**Issue by xlla** [ros-planning/moveit#3157]
### Description

failure to build chomp_motion_planner with ros melodic/noetic

### Your environment
* ROS Distro: Melodic|Noetic
* OS Version: macOS 10.13.6
* Source  build
 origin/noetic-devel

### Steps to reproduce
` catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release -DCMAKE_MACOSX_RPATH=ON -DCMAKE_INSTALL_RPATH=$HOME/ros_catkin_ws/install_isolated/lib  -DPYTHON_EXECUTABLE=/usr/local/bin/python3 --pkg chomp_motion_planner`

### Expected behaviour
success build

### Actual behaviour
 exception raised

### Backtrace or Console output

<pre>
-- Build files have been written to: /Users/xlla/ros_catkin_ws/build_isolated/chomp_motion_planner
==> make -j8 -l8 in '/Users/xlla/ros_catkin_ws/build_isolated/chomp_motion_planner'
[ 33%] Building CXX object CMakeFiles/chomp_motion_planner.dir/src/chomp_parameters.cpp.o
[ 33%] Building CXX object CMakeFiles/chomp_motion_planner.dir/src/chomp_optimizer.cpp.o
[ 50%] Building CXX object CMakeFiles/chomp_motion_planner.dir/src/chomp_planner.cpp.o
[ 66%] Building CXX object CMakeFiles/chomp_motion_planner.dir/src/chomp_cost.cpp.o
[ 83%] Building CXX object CMakeFiles/chomp_motion_planner.dir/src/chomp_trajectory.cpp.o
In file included from /Users/xlla/ros_catkin_ws/src/ros_planning/moveit/moveit_planners/chomp/chomp_motion_planner/src/chomp_trajectory.cpp:37:
In file included from /Users/xlla/ros_catkin_ws/install_isolated/include/ros/ros.h:38:
In file included from /Users/xlla/ros_catkin_ws/install_isolated/include/ros/time.h:53:
In file included from /Users/xlla/ros_catkin_ws/install_isolated/include/ros/platform.h:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:500:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string_view:176:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string:56:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/algorithm:644:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1880:61: error: object expression of non-scalar type 'double [6]' cannot be used in a
      pseudo-destructor expression
    _LIBCPP_INLINE_VISIBILITY void destroy(pointer __p) {__p->~_Tp();}
                                                         ~~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1742:18: note: in instantiation of member function 'std::__1::allocator<double [6]>::destroy'
      requested here
            {__a.destroy(__p);}
                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1595:14: note: in instantiation of function template specialization
      'std::__1::allocator_traits<std::__1::allocator<double [6]> >::__destroy<double [6]>' requested here
            {__destroy(__has_destroy<allocator_type, _Tp*>(), __a, __p);}
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:421:25: note: in instantiation of function template specialization
      'std::__1::allocator_traits<std::__1::allocator<double [6]> >::destroy<double [6]>' requested here
        __alloc_traits::destroy(__alloc(), _VSTD::__to_raw_pointer(--__soon_to_be_end));
                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:364:29: note: in instantiation of member function 'std::__1::__vector_base<double [6],
      std::__1::allocator<double [6]> >::__destruct_at_end' requested here
    void clear() _NOEXCEPT {__destruct_at_end(__begin_);}
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:458:9: note: in instantiation of member function 'std::__1::__vector_base<double [6],
      std::__1::allocator<double [6]> >::clear' requested here
        clear();
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iterator:1427:74: note: in instantiation of member function 'std::__1::__vector_base<double [6],
      std::__1::allocator<double [6]> >::~__vector_base' requested here
    template <class _Tp, class _Alloc> friend class _LIBCPP_TEMPLATE_VIS vector;
                                                                         ^

</pre>

Then I deep in to the source try to find the cause,  I found there have a variable defined in chomp_trajectory.h but do not got initialized in some case.

std::vector<size_t> full_trajectory_index_;

**Comment by rhaschke** [comment]
This looks more like a bug in the implementation of the C++ standard library (vector<T> here) in your OSX.
In which cases, do you think, is the vector `full_trajectory_index_` not initialized?

**Comment by xlla** [comment]
It is seems related to compiler, I'v test apple clang 10.0.1 and llvm clang 13.0.0, both raise errors as I post above.
while switch to gcc-11,  it pass all obj files compile but failure to link, maybe moveit_core's libs I'v built before using clang does not ABI compatible with gcc-11.

<pre>
catkin_make_isolated  --install -DCMAKE_BUILD_TYPE=Release -DCMAKE_MACOSX_RPATH=ON -DCMAKE_INSTALL_RPATH=$HOME/ros_catkin_ws/install_isolated/lib --pkg chomp_motion_planner -DCMAKE_C_COMPILER=/usr/local/bin/gcc-11 -DCMAKE_CXX_COMPILER=/usr/local/bin/g++-11

...

[100%] Linking CXX shared library /Users/xlla/ros_catkin_ws/devel_isolated/chomp_motion_planner/lib/libchomp_motion_planner.dylib
Undefined symbols for architecture x86_64:
  "__ZN16robot_trajectory15RobotTrajectoryC1ERKSt10shared_ptrIKN6moveit4core10RobotModelEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE", referenced from:
      __ZNK5chomp12ChompPlanner5solveERKSt10shared_ptrIKN14planning_scene13PlanningSceneEERKN11moveit_msgs18MotionPlanRequest_ISaIvEEERKNS_15ChompParametersERN18planning_interface26MotionPlanDetailedResponseE in chomp_planner.cpp.o
  "__ZN21kinematic_constraints15JointConstraint9configureERKN11moveit_msgs16JointConstraint_ISaIvEEE", referenced from:
      __ZNK5chomp12ChompPlanner5solveERKSt10shared_ptrIKN14planning_scene13PlanningSceneEERKN11moveit_msgs18MotionPlanRequest_ISaIvEEERKNS_15ChompParametersERN18planning_interface26MotionPlanDetailedResponseE in chomp_planner.cpp.o
  "__ZN21kinematic_constraints19KinematicConstraintC2ERKSt10shared_ptrIKN6moveit4core10RobotModelEE", referenced from:
      __ZNK5chomp12ChompPlanner5solveERKSt10shared_ptrIKN14planning_scene13PlanningSceneEERKN11moveit_msgs18MotionPlanRequest_ISaIvEEERKNS_15ChompParametersERN18planning_interface26MotionPlanDetailedResponseE in chomp_planner.cpp.o
  "__ZN3ros7console21initializeLogLocationEPNS0_11LogLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_6levels5LevelE", referenced from:
      __ZN5chomp14ChompOptimizer15registerParentsEPKN6moveit4core10JointModelE in chomp_optimizer.cpp.o
      __ZN5chomp14ChompOptimizer10initializeEv in chomp_optimizer.cpp.o
      __ZN5chomp14ChompOptimizerC1EPNS_15ChompTrajectoryERKSt10shared_ptrIKN14planning_scene13PlanningSceneEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKNS_15ChompParametersERKN6moveit4core10RobotStateE in chomp_optimizer.cpp.o
      __ZN5chomp14ChompOptimizer8optimizeEv in chomp_optimizer.cpp.o
      __ZNK5chomp12ChompPlanner5solveERKSt10shared_ptrIKN14planning_scene13PlanningSceneEERKN11moveit_msgs18MotionPlanRequest_ISaIvEEERKNS_15ChompParametersERN18planning_interface26MotionPlanDetailedResponseE in chomp_planner.cpp.o
  "__ZN3ros7console5printEPNS0_10FilterBaseEPvNS0_6levels5LevelERKNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEEPKciSF_", referenced from:
      __ZN5chomp14ChompOptimizer15registerParentsEPKN6moveit4core10JointModelE in chomp_optimizer.cpp.o
      __ZN5chomp14ChompOptimizer10initializeEv in chomp_optimizer.cpp.o
      __ZN5chomp14ChompOptimizerC1EPNS_15ChompTrajectoryERKSt10shared_ptrIKN14planning_scene13PlanningSceneEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKNS_15ChompParametersERKN6moveit4core10RobotStateE in chomp_optimizer.cpp.o
      __ZN5chomp14ChompOptimizer8optimizeEv in chomp_optimizer.cpp.o
      __ZNK5chomp12ChompPlanner5solveERKSt10shared_ptrIKN14planning_scene13PlanningSceneEERKN11moveit_msgs18MotionPlanRequest_ISaIvEEERKNS_15ChompParametersERN18planning_interface26MotionPlanDetailedResponseE in chomp_planner.cpp.o
  "__ZN3roslsERSoRKNS_12WallDurationE", referenced from:
      __ZN5chomp14ChompOptimizer10initializeEv in chomp_optimizer.cpp.o
      __ZN5chomp14ChompOptimizer8optimizeEv in chomp_optimizer.cpp.o
  "__ZN6moveit4core10RobotStateC1ERKSt10shared_ptrIKNS0_10RobotModelEE", referenced from:
      __ZN5chomp15ChompTrajectory20fillInFromTrajectoryERKN16robot_trajectory15RobotTrajectoryE in chomp_trajectory.cpp.o
  "__ZN6moveit4core25robotStateMsgToRobotStateERKNS0_10TransformsERKN11moveit_msgs11RobotState_ISaIvEEERNS0_10RobotStateEb", referenced from:
      __ZNK5chomp12ChompPlanner5solveERKSt10shared_ptrIKN14planning_scene13PlanningSceneEERKN11moveit_msgs18MotionPlanRequest_ISaIvEEERKNS_15ChompParametersERN18planning_interface26MotionPlanDetailedResponseE in chomp_planner.cpp.o
  "__ZN6moveit4core25robotStateToRobotStateMsgERKNS0_10RobotStateERN11moveit_msgs11RobotState_ISaIvEEEb", referenced from:
      __ZNK5chomp14ChompOptimizer42isCurrentTrajectoryMeshToMeshCollisionFreeEv in chomp_optimizer.cpp.o
  "__ZNK14planning_scene13PlanningScene11isPathValidERKN11moveit_msgs11RobotState_ISaIvEEERKNS1_16RobotTrajectory_IS3_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbPSt6vectorImSaImEE", referenced from:
      __ZNK5chomp14ChompOptimizer42isCurrentTrajectoryMeshToMeshCollisionFreeEv in chomp_optimizer.cpp.o
  "__ZNK14planning_scene13PlanningScene15getCollisionEnvERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE", referenced from:
      __ZN5chomp14ChompOptimizerC1EPNS_15ChompTrajectoryERKSt10shared_ptrIKN14planning_scene13PlanningSceneEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKNS_15ChompParametersERKN6moveit4core10RobotStateE in chomp_optimizer.cpp.o
  "__ZNK14planning_scene13PlanningScene25getCollisionDetectorNamesERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE", referenced from:
      __ZN5chomp14ChompOptimizerC1EPNS_15ChompTrajectoryERKSt10shared_ptrIKN14planning_scene13PlanningSceneEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKNS_15ChompParametersERKN6moveit4core10RobotStateE in chomp_optimizer.cpp.o
  "__ZNK19collision_detection18CollisionEnvHybrid21getCollisionGradientsERKNS_16CollisionRequestERNS_15CollisionResultERKN6moveit4core10RobotStateEPKNS_22AllowedCollisionMatrixERSt10shared_ptrINS_24GroupStateRepresentationEE", referenced from:
      __ZN5chomp14ChompOptimizer24performForwardKinematicsEv in chomp_optimizer.cpp.o
      __ZN5chomp14ChompOptimizer10initializeEv in chomp_optimizer.cpp.o
  "__ZNK6moveit4core10RobotModel12getLinkModelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPb", referenced from:
      __ZN5chomp14ChompOptimizer22computeJointPropertiesEi in chomp_optimizer.cpp.o
  "__ZNK6moveit4core10RobotModel13getJointModelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE", referenced from:
      __ZN5chomp14ChompOptimizer22computeJointPropertiesEi in chomp_optimizer.cpp.o
  "__ZNK6moveit4core10RobotModel16getVariableIndexERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE", referenced from:
      __ZNK5chomp12ChompPlanner5solveERKSt10shared_ptrIKN14planning_scene13PlanningSceneEERKN11moveit_msgs18MotionPlanRequest_ISaIvEEERKNS_15ChompParametersERN18planning_interface26MotionPlanDetailedResponseE in chomp_planner.cpp.o
  "__ZNK6moveit4core10RobotModel18getJointModelGroupERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE", referenced from:
      __ZN5chomp15ChompTrajectoryC2ERKSt10shared_ptrIKN6moveit4core10RobotModelEEddRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE in chomp_trajectory.cpp.o
      __ZN5chomp15ChompTrajectoryC1ERKSt10shared_ptrIKN6moveit4core10RobotModelEEddRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE in chomp_trajectory.cpp.o
      __ZN5chomp15ChompTrajectoryC2ERKSt10shared_ptrIKN6moveit4core10RobotModelEEmdRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE in chomp_trajectory.cpp.o
      __ZN5chomp15ChompTrajectoryC1ERKSt10shared_ptrIKN6moveit4core10RobotModelEEmdRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE in chomp_trajectory.cpp.o
      __ZN5chomp14ChompOptimizer17perturbTrajectoryEv in chomp_optimizer.cpp.o
      __ZN5chomp14ChompOptimizer22setRobotStateFromPointERNS_15ChompTrajectoryEi in chomp_optimizer.cpp.o
      __ZN5chomp14ChompOptimizer10initializeEv in chomp_optimizer.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
CMakeFiles/chomp_motion_planner.dir/build.make:234: recipe for target '/Users/xlla/ros_catkin_ws/devel_isolated/chomp_motion_planner/lib/libchomp_motion_planner.1.1.9.dylib' failed
make[2]: *** [/Users/xlla/ros_catkin_ws/devel_isolated/chomp_motion_planner/lib/libchomp_motion_planner.1.1.9.dylib] Error 1
CMakeFiles/Makefile2:2107: recipe for target 'CMakeFiles/chomp_motion_planner.dir/all' failed
make[1]: *** [CMakeFiles/chomp_motion_planner.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
<== Failed to process package 'chomp_motion_planner': 

</pre>
 



> In which cases, do you think, is the vector `full_trajectory_index_` not initialized?

I found the vector 'full_trajectory_index_' only initialized at copy constructor, if ChompTrajectory initialized via another two constructor, the vector will not be initialized,  if getFullTrajectoryIndex() happen to be invoke.
however, I am not know the call logic at all, maybe this case never occurred.

**Comment by rhaschke** [comment]
My assumption that this is a clang issue turns out to be true. Try to compile everything with GCC.  File a bug report with clang. (Try to find a minimal test case first)

**Comment by xlla** [comment]
> Try to compile everything with GCC.

I have build thousands packages by apple clang, so I can't re-compile everything with GCC.

I found it is a clang issue which does not report the real cause of the error, it does not  caused by ros.h, if I comment out ros.h, it is still complain the same error.

finally, I found the reason, 

` std::vector<double[6]> coeff(num_joints_);`

libc++ complains about the destruction part; the default implementation uses an explicit/pseudo dtor call, which is not valid for an array type.

Fortunately,  that is just a fixed 2-demension array,  I can manage to amend it.

**Comment by light-tech** [comment]
Got the same problem. Thank to @xlla's explanation

> finally, I found the reason,
> 
> ` std::vector<double[6]> coeff(num_joints_);`
> 
> libc++ complains about the destruction part; the default implementation uses an explicit/pseudo dtor call, which is not valid for an array type.

the fix is really simple: Changing `double[6]` to `std::array<double, 6>` should make clang happy.

**Comment by rhaschke** [comment]
Interestingly we don't face that problem in [our CI build using clang 10.0](https://github.com/ros-planning/moveit/actions/runs/3203007786/jobs/5232599965) from Ubuntu. I guess you use a newer version, @light-tech?

**Comment by light-tech** [comment]
@rhaschke Yes, I am using Apple clang version 13.1.6.

> Do you mind filing a PR?

Just now I realize that I commented on the wrong repo: I was actually compiling MoveIt2 on ROS2 Humble!? So I feel I should refrain from making the PR given I did not have ROS1 installed to confirm if this was an issue.

**Comment by rhaschke** [comment]
Please file a PR against MoveIt2 then, please :wink:

**Comment by light-tech** [comment]
@rhaschke Sure, I just did it.
