### ISSUE TITLE
How to compile and use the trajopt planner?  

### ISSUE THREAD

**Issue by cgdsss** [ros-planning/moveit#3184]
### Description
How to **compile** and use the **trajopt** planner?  
My system is Ubuntu20.04, ros noetic, thanks a lot

**Comment by simonschmeisser** [comment]
You need to remove the file `CATKIN_IGNORE` in moveit/planners/trajopt and then it will try to compile it

However this has not been maintained for a while and will likely not compile at all. PRs welcome!
