### ISSUE TITLE
Calling `moveit_commander` function `set_joint_value_target` crashes without warnings if `len(position) < len(name)`

### ISSUE THREAD

**Issue by FSund** [ros-planning/moveit#3186]
### Description

Calling `set_joint_value_target` ([link to source](https://github.com/ros-planning/moveit/blob/noetic-devel/moveit_commander/src/moveit_commander/move_group.py#L199)) with `arg1` of type `JointState` and `len(arg1.name) > len(arg1.position)` leads to moveit_commander crashing without any error messages (except `process has died` -- the logs contain nothing of interest).

Is this the expected outcome, or should the length of these fields be verified somewhere?

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04
* Latest version from apt

### Steps to reproduce
```
#!/usr/bin/env python
import rospy
import moveit_commander
from sensor_msgs.msg import JointState

if __name__ == "__main__":
    rospy.init_node("test_moveit_commander")

    move_group = moveit_commander.MoveGroupCommander(
        name="shoulders",  # change this to fit whatever robot you are using
        robot_description="robot_description",
    )

    joints = move_group.get_active_joints()
    js = JointState()
    js.name = [joints[0]]
    js.position = []

    move_group.set_joint_value_target(js)
```

**Comment by rhaschke** [comment]
It is definitely asserted that these arrays have same length. Please file a PR adding a corresponding python assertion. Thanks.

**Comment by FSund** [comment]
@rhaschke I've added a draft PR with a suggestion of how to fix the issue, with some questions in a comment.
