### ISSUE TITLE
Symbol lookup error with Descartes and IKFast

### ISSUE THREAD

**Issue by vivekcdavid** [ros-planning/moveit#3194]
While trying to use Descartes with the IKFast solver I am getting a symbol lookup error. The exact error can be seen below, Do you know why I am getting this error? Any help is much appreciated. Thanks in advance.

_[ INFO] [1661352051.910503611]: Received request to compute Descartes path
[ INFO] [1661352051.931343040]: Stopping planning scene monitor
[ INFO] [1661352051.935125394]: Starting planning scene monitor
[ INFO] [1661352051.956399368]: Listening to '/planning_scene'
/home/sawyer/ws_moveit/devel/lib/moveit_ros_move_group/move_group**: symbol lookup error: /home/sawyer/ws_moveit/devel/lib/libdescartes_capability.so: undefined symbol: _ZN2tf14poseMsgToEigenERKN13geometry_msgs5Pose_ISaIvEEERN5Eigen9TransformIdLi3ELi1ELi0EEE**
[move_group-1] process has died [pid 79283, exit code 127, cmd /home/sawyer/ws_moveit/devel/lib/moveit_ros_move_group/move_group joint_states:=/robot/joint_states __name:=move_group _log:=/home/sawyer/.ros/log/7b9e47e2-2381-11ed-8e16-64006a6cd200/move_group-1.log].
log file: /home/sawyer/.ros/log/7b9e47e2-2381-11ed-8e16-64006a6cd200/move_group-1*.log

**Comment by rhaschke** [comment]
As Descartes is not part of MoveIt, this question should be better asked at https://answers.ros.org. Please, post real MoveIt issues and bug reports here only.
Looking at the error message, you can [easily figure out](https://sourceware.org/binutils/docs/binutils/c_002b_002bfilt.html) that `tf::poseMsgToEigen(geometry_msgs::Pose&)` is missing here. Did you link against [`tf_conversions`](http://wiki.ros.org/tf_conversions)?
