### ISSUE TITLE
Why does group.computeCartesianPath create optimal straight line paths, my group.plan does not?

### ISSUE THREAD

**Issue by ericdusel77** [ros-planning/moveit#3195]
I am using ROS Noetic with MoveIt and a kinova jaco arm IRL and in simulation. When I am trying to plan I am getting drastically different solutions using two methods suggested by the move group interface tutorial. I am wondering why one is so much better than the other, and if there are some configuration steps I may be missing that will make them both be more optimal.

I have written the following code which gives me two options of planning to a certain point. One using the computeCartesianPath, and one that uses the traditional planning method from the tutorial.

```
    if (compute_cart){
        // CREATE TRAJECTORY
        std::vector<geometry_msgs::Pose> waypoints;
        waypoints.push_back(approach_pose);  // APPROACH
        waypoints.push_back(pose);  // GOAL (BUTTON)
        waypoints.push_back(approach_pose);  // APPROACH
        waypoints.push_back(home_pose);  // HOME
        moveit_msgs::RobotTrajectory trajectory;
        double fraction = group_->computeCartesianPath(waypoints,
                                                        0.01,  // eef_step - path to be interpolated at this resolution
                                                        10.0,   // jump_threshold
                                                        trajectory);

        // EXECUTE TRAJECTORY IF FULL PATH IS FOUND
        if (fraction == 1){
            group_->execute(trajectory);
        }

    } else {
        group_->setPoseTarget(approach_pose);
        evaluate_plan(*group_);
        group_->setPoseTarget(pose);
        evaluate_plan(*group_);
        group_->setPoseTarget(approach_pose);
        evaluate_plan(*group_);
        group_->setJointValueTarget(home);
        evaluate_plan(*group_);
    }

void evaluate_plan(moveit::planning_interface::MoveGroupInterface &group)
{
    moveit::planning_interface::MoveGroupInterface::Plan my_plan;
    bool result = (group.plan(my_plan) == moveit_msgs::MoveItErrorCodes::SUCCESS);
    if (result)
    {
        group.execute(my_plan);
    }
    ros::WallDuration(1.0).sleep();
}

```
However, as shown in the simulation gifs below, only the first method (computeCartesianPath) actually finds a good straight line path. 
![computeCart](https://user-images.githubusercontent.com/67301707/186725842-957fb0ed-284a-4261-ae74-af77617565a5.gif)
**THIS WORKS GREAT**

Attempting to follow the same four waypoints using the plan and execute commands yields the following results. 
![regular_move_group](https://user-images.githubusercontent.com/67301707/186725976-fe940f6a-3f52-439f-bae7-c53fd4844228.gif)
**THIS IS NOT A STRAIGHT LINE PATH**

Is anyone able to help me to determine what I am missing here in order to make the second option plan more closely to the first option?

**Comment by rhaschke** [comment]
The two approaches are fundamentally different: `computeCartesianPath()` just performs Cartesian interpolation with _collision checking_ (but no planning), `plan()` performs sampling-based planning and _obstacle avoidance_ (resulting in random trajectories).
Have a look [here](https://picknik.ai/cartesian%20planners/moveit/motion%20planning/2021/01/07/guide-to-cartesian-planners-in-moveit.html) for an overview of these and alternative approaches.
You need to answer the question how to handle obstacles in the straight-line Cartesian path? Do you want to move around them and deviate from the Cartesian path?

**Comment by ericdusel77** [comment]
Oh, that makes so much sense.  Thank you for the response!
