### ISSUE TITLE
Link 'panda_link(0-7)_sc' and 'panda_hand_sc' are not known to URDF. Cannot disable/enable collisons

### ISSUE THREAD

**Issue by WangHonghui123** [ros-planning/moveit#3206]
### Description

When I try to input "roslaunch panda_moveit_config demo.launch" in the terminal, it shows:
[ WARN] [1662286780.413483924]: Link 'panda_link0_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1662286780.413686723]: Link 'panda_link1_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1662286780.413777536]: Link 'panda_link2_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1662286780.413939808]: Link 'panda_link3_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1662286780.414784335]: Link 'panda_link4_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1662286780.414912294]: Link 'panda_link5_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1662286780.415584525]: Link 'panda_link6_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1662286780.415716295]: Link 'panda_link7_sc' is not known to URDF. Cannot disable/enable collisons.
....
[ WARN] [1662286780.422768697]: Link 'panda_hand_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1662286780.422782740]: Link 'panda_hand_sc' is not known to URDF. Cannot disable/enable collisons.
.....

When I use "Plan" Command to run, the error happens, shown as follows:

![Screenshot from 2022-09-04 20-56-37](https://user-images.githubusercontent.com/54740543/188309898-230ef119-7b5c-4de3-b0ea-de4d3d7197e0.png)

I would like to know how to fix it. Thanks.

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04
* Source Build
* Moveit 1 - Noetic

**Comment by rhaschke** [comment]
Please update [franka_description](https://github.com/frankaemika/franka_ros/tree/develop/franka_description) to version 0.9.1 - either using the [`ros-testing` repo](http://wiki.ros.org/TestingRepository) or building it from source. This package was released into Noetic, but not yet synced.

**Comment by WangHonghui123** [comment]
Thank you for your help. It can work.

**Comment by WangHonghui123** [comment]
Thank you for your help. @rhaschke. It is able to work.

**Comment by OoooL19** [comment]
Hi, I have the same issue when I use Moveit1 - melodic. Do you know what can I fix this issue?
Thank you

**Comment by rhaschke** [comment]
For Melodic you need to use franka_description from source. Unfortunately, its Melodic release was reverted.

**Comment by OoooL19** [comment]
> For Melodic you need to use franka_description from source. Unfortunately, its Melodic release was reverted.

Thanks. it works now.
