### ISSUE TITLE
Issue #11 from #2741

### ISSUE THREAD

**Issue by mralderman** [ros-planning/moveit#3220]
## Background

Overview of your issue here.
As stated on issue #2741, it says to make a separate issue request if you want to ask about one of them separately. I was just wondering if I could help with the new number 11, which was updating the progress bar to show units. @rhaschke I was wondering if you could help get me started on that issue as I am a new programmer and new to Github in general. 

### 📋 Step by Step

- [ ] 🗄️ **Create a local workspace** for making your changes and testing [following these instructions](https://moveit.ros.org/install/source/)

- [ ] 🍴 **Fork the repository** using the handy button at the top of the repository page and **clone** it into `~/ws_moveit/src/moveit`, [here is a guide that you can follow](https://guides.github.com/activities/forking/) (You will have to remove or empty the existing `moveit` folder before cloning your own fork)

- [ ] 🤖 **Apply `clang-format-10`** auto formatting, [following these instructions](https://moveit.ros.org//documentation/contributing/code/?#clang-format-auto-code-formatting)

- [ ] 💾 **Commit and Push** your changes

- [ ] 🔀 **Start a Pull Request** to request to merge your code into `master`. There are two ways that you can start a pull request:
1. If you are not familiar with GitHub or how to create a pull request, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.
2. If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

You will find helpful resources here:
* [MoveIt FAQ](https://moveit.ros.org/documentation/faqs/)
* [MoveIt Tutorials](https://ros-planning.github.io/moveit_tutorials/)
* [MoveIt contribution guide](https://moveit.ros.org/documentation/contributing/)
* [ROS Tutorials](https://wiki.ros.org/ROS/Tutorials)
* [ROS Answers](https://answers.ros.org/questions/)

**Comment by rhaschke** [comment]
To show units also in the `ProgressBarEditor`, you need to adapt the editor's [`paint()`](https://github.com/ros-planning/moveit/blob/327b5b09cc48b97ba3f2a9ac2acf1edcd1bb0650/moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_joints_widget.cpp#L497) method to also print units as done in [`ProgressBarDelegate::paint()`](https://github.com/ros-planning/moveit/blob/327b5b09cc48b97ba3f2a9ac2acf1edcd1bb0650/moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_joints_widget.cpp#L384).
To avoid code duplication, I suggest to have a free `paint()` function shared by both class methods.

**Comment by rhaschke** [comment]
I implemented a fix in #3227. Thanks anyway for trying to help!
