### ISSUE TITLE
How can I improve positioning system

### ISSUE THREAD

**Issue by xav12358** [ros-planning/moveit#3229]
### Your environment
* ROS Distro: [Noetic]
* OS Version: e.g. Ubuntu 20.04

I try to improve the goal position accuracy. Is there a way to modify the controller strategy to avoid static error between the target and the real position.

Edit : in fact I use the robot arm without the gripper. When I remove the gripper I have repeatability troubles. 
How can I solve it ?

**Comment by JafarAbdi** [comment]
Hi @xav12358, I don't see a bug in the issue description, I think https://answers.ros.org is more suitable for this kind of queries, please feel free to link your question here once you post it on that forum, and I will try to answer you when get a chance
