### ISSUE TITLE
How to change end_effectors or tools of arm dynamiclly?

### ISSUE THREAD

**Issue by dbdxnuliba** [ros-planning/moveit#3267]
how can we change end_effectors or tools of arm dynamiclly  in  moveit ROS1, is there method  or services,thanks a lot

**Comment by rhaschke** [comment]
If you just want to switch between different end-effector frames defined for your robot, you can call the methods
`setEndEffectorLink()` or `setEndEffector()` of `MoveGroupInterface`.
However, this will not change the actual tool mounted to an arm. This is not easily possible as this would require changing the robot's URDF on the fly, which is not supported throughout ROS1.

**Comment by dbdxnuliba** [comment]
can we do it in the following way :
`    def attach_end_effector(
        self,
        name: str,
        filename: str = "/dev_ws/src/trajectory_tools/end_effector/ur_ee.stl",
    ) -> bool:

        pose = PoseStamped()
        pose.header = Header()
        pose.header.frame_id = self.move_group.get_end_effector_link()
        pose.pose = Pose(position=Point(0, 0, 0), orientation=Quaternion(0, 0, 0, 1))

        ac = AttachedCollisionObject()
        ac.object = make_mesh(name, pose, filename=filename)

        ac.link_name = self.move_group.get_end_effector_link()
        ac.object.subframe_names = ["tcp"]
        ori = tf.transformations.quaternion_from_euler(0, pi / 2, 0)
        ac.object.subframe_poses = [
            Pose(
                position=Point(0.184935, 0.0, 0.06),
                orientation=Quaternion(ori[0], ori[1], ori[2], ori[3]),
            )
        ]

        self.scene.attach_object(ac)

        return self.wait_for_state_update(name, object_is_attached=True)

from https://github.com/vinceHuyghe/trajectory_tools/blob/dev/src/trajectory_tools/trajectory_handler.py#:~:text=def%20attach_end_effector(,%3DTrue)
`

**Comment by rhaschke** [comment]
Sure, if your end effector is a rigid tool, you can just add it as an attached collision object.
However, most end effector are actuated, e.g. involving finger joints. Changing these would require modifying the URDF, which is not possible.

**Comment by dbdxnuliba** [comment]
> Sure, if your end effector is a rigid tool, you can just add it as an attached collision object.
> However, most end effector are actuated, e.g. involving finger joints. Changing these would require modifying the URDF, which is not possible. 

OK，I see, but for now,attach the tools can meet my jobs

**Comment by rhaschke** [comment]
If this resolves your issue, please close it.

**Comment by dbdxnuliba** [comment]
ok

**Comment by rhaschke** [comment]
> how can I close the issue, I can't find the option to close it

Just pushing the corresponding button right below the comment field:
![image](https://user-images.githubusercontent.com/5376030/203717974-b7583639-de2d-4eed-889b-f39e92d90935.png)

**Comment by dbdxnuliba** [comment]
![image](https://user-images.githubusercontent.com/13350158/204117808-138d2f4a-695a-4226-a42c-0a2f6af39f23.png)
It seems that there is no such buttion

**Comment by rhaschke** [comment]
Sure, because I closed it already!

**Comment by dbdxnuliba** [comment]
OK
