### ISSUE TITLE
The MoveIt Planning Scene Interface confuses me

### ISSUE THREAD

**Issue by julianmueller** [ros-planning/moveit#3291]
Hi, im using the `moveit_commander.PlanningSceneInterface()` with python to spawn/despawn scene objects. have written two scripts to load/import a `.scene` file, and also to export it. For this, I needed to reverse engineer the `.scene` file format, which I haven't found any documentation to.
My import-script basically reads the file, parses it and then spawns the objects and shapes with the `moveit_commander`. My export script gets all objects and shapes from the `moveit_commander`, parses them and writes them into a scene file.

The scripts are mostly working, but MoveIt is really inconsistent about its shapes and objects. I have the following issues with it:

1. Why is there not a provided MoveIt interface/api to import/export a `.scene` file?

2. The implementation ([here](http://docs.ros.org/en/api/shape_msgs/html/msg/SolidPrimitive.html) and [here](https://docs.ros.org/en/noetic/api/moveit_commander/html/classmoveit__commander_1_1planning__scene__interface_1_1PlanningSceneInterface.html)) suggests that there are objects in a scene. One object can have multiple shapes inside it. An object has a pose, and every shape inside of it also has its own "sub"pose, color and shape specific propertiy (eg sphere has a radius). If I spawn several objects with the same name, they all get merged into one object with multiple shapes. But their poses are not recalculated correctly, as they all simply match the pose of the last object, and keep the same subpose of the shape, resulting in overlapping shapes. eg:

   - first object "Box_0" with pose (1,0,0) and one shape with the subpose (0,0,0)
   - second object "Box_0" with the pose (-1,0,0) with one shape with the subpose (0,0,0)
   - merged into "Box_0" with the pose (-1,0,0) with two shapes, both with the subposes (0,0,0) - instead of one subpose (2,0,0) and one subpose (0,0,0) to represent the original position of the first shape in the world with respect to the now merged parents pose

   For now I think, I will just spawn all my objects with a pose of (0,0,0) and modify the subposes of the shapes to get the result I expect.

3. Even though you can spawn a "cone" shape with the rviz plugin and can save it in the scene file, there is no provided function to actually spawn a cone object with the `moveit_commander`. There also exists a plane shape, but it cannot be spawned by the rviz plugin and is not visible in rviz. Furthermore its (a,b,c,d) way of saving it differs from the (normals, offset) way of spawning it. And dont get me started with the octree shape (no documentation whatsoever).

4. When an object with multiple shapes, I need to iterate over all the shapes and spawn them individually (eg with `add_box`). As they all belong to the same object, they have the same name and therefore override eachother, leaving only the last added shape. When loading a file with many objects, each having multiple shapes, and they all share the same name, they get joined to one object with all the shapes.

My efforts on this can be found in [my repo](https://github.com/julianmueller/moveit_planning_scene_interface) (will update it continuously).

Id be thankful for any help or explaination on this matter.

### My environment

* ROS Distro: Noetic
* OS Version: Ubuntu 20.04
* Source
* Language: Python

**Comment by julianmueller** [comment]
Hi, thanks for the extensive reply. 
I don't have any experience with using/wrapping C++ in Python, so I don't think, I'm much of a help. But I am willing to learn and help!

> If you ADD another object with the same name, the old object is removed and the new one added.

That's unfortunately not the case. I only tested this behavior with the RViz Buttons for Importing/Exporting .scene files, but I observe the following behavior:
I ADD a box to the scene, and then export it (without deleting it). If I then move the box to a different location in RViz (and publish it), and then ADD the same box (with the same name) that I exported right beforehand, the two objects get merged into one, with two box shapes. The location is also reset to the newly imported shape. This results in two shapes at the exact same location.

This is really inconsistent. Either it should replace the old object entirely, or if it adds a new shape to the old object, the old shape should keep its pose. If this gets messed with, why even bother and give each shape its own pose inside the object?

> Add functionality to create cones and planes from python / rviz.

I added the functionalities to add and attach a cone in python. The package built successfully, but I don't know how to test the code really. Could you provide any help with that?

**Comment by julianmueller** [comment]
Furthermore, I found [this](https://answers.ros.org/question/287394/moveit-import-scene-from-text-automatically/) thread, where [this](https://docs.ros.org/en/lunar/api/moveit_ros_planning/html/publish__scene__from__text_8cpp.html) script for importing a scene from a text file is referenced. Is there an equivalent for exporting a scene into a text file?

**Comment by julianmueller** [comment]
It gets even stranger:
- When I have a `.scene` file and import it from RViz, move one of the objects, and import the same file again, all the objects in RViz get reset to the position from the file, but now have two shapes attached to them! (With an object that has two shapes inside the `.scene` file, after importing twice, there are four shapes inside the object)
- When I do the same in code - using `add_box` with the same name twice - the position gets reset, but only one shape is in the object!
- And finally (as already metioned in a previous comment), when I import a file, where two/many objects share the same name, they get merged into one object that has all the shapes from the two/many original objects, but the pose is the one from the last object that got merged.

Rviz also has its problems with the PlanningScene:
- The InteractiveMarker for moving objects in the scene cannot really handle objects with multiple shapes. It does not show the InteractiveMarker or if it shows it, its not on the selected object.
- Also if an object with multiple shapes and a pose different then (0,0,0) gets loaded, its shown in the correct location in the gui, but the pose dialboxes in moveit show a pose of (0,0,0).

I have the feeling, that there are several implementations that all behave slightly different...

**Comment by rhaschke** [comment]
> > If you ADD another object with the same name, the old object is removed and the new one added.
> 
> That's unfortunately not the case.

Thanks for the more detailed explanation. Now I was able to reproduce (and fix) the issue. See #3296. 

> * The InteractiveMarker for moving objects in the scene cannot really handle objects with multiple shapes. It does not show the InteractiveMarker

That's because we don't know how to determine the size of the marker in that case. We could show a marker on the first shape though...

> ... or if it shows it, it's not on the selected object.

This is unexpected! Please describe a procedure to reliably reproduce that issue, i.e. a marker is shown but not on the selected object. 

> * If an object with multiple shapes is imported, and the shapes all have their own separate color, they are all shown with the color of the last shape.

I never have seen anything else than the default green color for scene objects. Could you provide an example `.scene` file, please?

**Comment by rhaschke** [comment]
> > * If an object with multiple shapes is imported, and the shapes all have their own separate color, they are all shown with the color of the last shape.
> 
> I never have seen anything else than the default green color for scene objects. Could you provide an example `.scene` file, please?

I checked the code: There is only one color stored per collision object. So, all shapes will have the same color.
The (private!) `.scene` file format is misleading here (and redundant).

**Comment by julianmueller** [comment]
> This is unexpected! Please describe a procedure to reliably reproduce that issue, i.e. a marker is shown but not on the selected object.
Thats simple, import a `.scene` file, select an object from the list and import the same scene file again. This will make all the objects have two shapes inside them. If you now select a different object from the list, the marker is still shown at the firstly selected object and wont update. If you then move the marker in the gui, the newly selected object jumps to the location of the marker (which is close to the location of the secondly selected object).

Do you also plan to expose the import/export functionality to python? That would be very helpful, as I currently coded my own workaround solely in python, making no use of the C++ methods.

Furthermore, do you plan on adding the support to distinguish between objects and shapes in python? Currently there is eg the method `add_box(...)` that adds a CollisionObject with a box shape to the scene, but there is no way to attach another shape (eg a cylinder) to the same CollisionObject.

One last note, do you by any means know, what the subframe option is? In every `.scene` file i have see, this value is set to zero. It also occurs in the msg definition `moveit_msgs/CollisionObject[] collision_objects` > `geometry_msgs/Pose[] subframe_poses`.

When will the changes youve already made be available to everyone?
Thank you very much for your help!

**Comment by rhaschke** [comment]
> Furthermore, do you plan on adding the support to distinguish between objects and shapes in python?

I was hoping you could continue the work on the python side. Obviously, you already (re)implemented loading and saving the scene in python, didn't you? Would be great to see a PR for this.

> there is no way to attach another shape (eg a cylinder) to the same CollisionObject

Not using the existing methods. But you can easily extend the API and add multiple shapes/poses to the lists `primitives` and `primitive_poses` of the [CollisionObject msg](https://docs.ros.org/en/noetic/api/moveit_msgs/html/msg/CollisionObject.html).

> One last note, do you by any means know, what the subframe option is?

Have a look at the tutorial: https://ros-planning.github.io/moveit_tutorials/doc/subframes/subframes_tutorial.html

> When will the changes youve already made be available to everyone?

I am preparing a new release, but there are several open issues to be resolved beforehand and time is very limited. So, I cannot promise anything.

**Comment by julianmueller** [comment]
> I checked the code: There is only one color stored per collision object. So, all shapes will have the same color.
The (private!) .scene file format is misleading here (and redundant).

As I'm looking through the definitions of `moveit_msgs/PlanningScene` and `PlanningSceneWorld` I noticed that the colors are part of the planning scene and not of the collision objects. For me this is also a bit misleading, but I guess changes to this would result in backwards incompatibility.

One could possibly just add a `moveit_msgs/ObjectColor[] object_colors` to the PSWorld msg that correspond to the `moveit_msgs/CollisionObject[] collision_objects` in there.

**Comment by julianmueller** [comment]
> I was hoping you could continue the work on the python side. Obviously, you already (re)implemented loading and saving the scene in python, didn't you? Would be great to see a PR for this.

I am working on the python side currently and the import/export works well. But I have some issus:
1. I dont know how to make a pull request to this repo, maybe you can help me out.
2. When I import a `.scene` file, I parse it with regex, and assembly everything in my own made objects (for convenience). The I go ahead and cycle through all the objects from the file and their shapes and use the python methods of `add_box()` etc to spawn the objects in the Moveit PS. BUT I need to rearrange the objects with multiple shapes, so that every shape has its own object, as I dont have any way of spawning multishape objects in moveit.
3. I can push my code to my repo and we can find a way together to fit my code into moveit.

> Not using the existing methods. But you can easily extend the API and add multiple shapes/poses to the lists primitives and primitive_poses of the [CollisionObject msg](https://docs.ros.org/en/noetic/api/moveit_msgs/html/msg/CollisionObject.html).

I'm also currently working on parsing my own made objectclasses to a `PlanningSceneWorld` msg. With this I can easily add multishape objects, meshes and even cones right now. Do you know how to give Moveit a PlanningSceneWorld and just override or add it to the current one?

> I am preparing a new release, but there are several open issues to be resolved beforehand and time is very limited. So, I cannot promise anything.

Okay, thanks! I think we can incorporate all the changes into it.

Furthermore, I'm also working on a way to add an Octomap to the PlanningScene by code, as I also need this for my research. I simply want to import/export `.bt` files by making use of the octomap_server nodes. There seems to be a way to add these into the `.scene` files as well, but I haven't seen an implementation of this yet. Maybe this could also be a feature for the RViz plugin? I will keep you updated on my progress.

**Comment by rhaschke** [comment]
> 1. I dont know how to make a pull request to this repo, maybe you can help me out.

Just follow the [official docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request): fork the repo, push to your fork, create a PR from there.

> 2\. I dont have any way of spawning multishape objects in moveit.

As I wrote before, just push multiple shapes into the corresponding list(s) of the `CollisionObject` msg. Yes, you will need to augment the existing API to do so (or create `CollisionObject` instances directly yourself).

> Do you know how to give Moveit a PlanningSceneWorld and just override or add it to the current one?

`PlanningSceneWorld` is part of the [`PlanningScene` msg](http://docs.ros.org/en/noetic/api/moveit_msgs/html/msg/PlanningScene.html) which you can use to communicate your PS changes. Have a look at [`__make_planning_scene_diff_req`](https://github.com/ros-planning/moveit/blob/f7b5f87d1d037de40c8d96f0ccb83d9d2e9fef83/moveit_commander/src/moveit_commander/planning_scene_interface.py#L354) and [its usage](https://github.com/ros-planning/moveit/blob/f7b5f87d1d037de40c8d96f0ccb83d9d2e9fef83/moveit_commander/src/moveit_commander/planning_scene_interface.py#L88-L89).

> I'm also working on a way to add an Octomap to the PlanningScene by code. Maybe this could also be a feature for the RViz plugin? 

Octomaps are usually updated dynamically from camera images. If you want to have a programmatic solution, just push a msg to the corresponding topic. See the [perception tutorial](https://ros-planning.github.io/moveit_tutorials/doc/perception_pipeline/perception_pipeline_tutorial.html) for more details.

**Comment by rhaschke** [comment]
> As I'm looking through the definitions of `moveit_msgs/PlanningScene` and `PlanningSceneWorld` I noticed that the colors are part of the planning scene and not of the collision objects. For me, this is also a bit misleading, but I guess changes to this would result in backwards incompatibility.

Colors are intended for semantic labeling of objects only. They don't have a meaning (obviously) for collision checking.
Historically, colors were introduced later than collision objects I guess. To maintain API compatibility, maintainers back then decided to add colors as a separate field in the PS instead of in objects...
