### ISSUE TITLE
get rid of "catkin_package() exports non-package include path"

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#33]
`moveit_core` currently exports the header file "devel/include/moveit/version.h".
Because this is not a path specifically for `moveit_core`, `catkin_lint .` in the `moveit_core` source folder (rightfully) complains:

> moveit_core: CMakeLists.txt(77): error: catkin_package() exports non-package include path

The file should probably be generated in "devel/include/moveit_core/moveit/version.h" (using appropriate catkin-variables for the prefix).

**Comment by davetcoleman** [comment]
+1

**Comment by toliver** [comment]
We can deal with this task for the WMD.

**Comment by AndriyPt** [comment]
working on it

**Comment by AndriyPt** [comment]
please review my pull request
