### ISSUE TITLE
Unable to find a random collision free configuration after 100 attempts

### ISSUE THREAD

**Issue by Akumar201** [ros-planning/moveit#3339]
### Description

I am trying to use [Moveit servoing tutorial](https://ros-planning.github.io/moveit_tutorials/doc/realtime_servo/realtime_servo_tutorial.html) with pose tracking example.launch. I am trying to move it randomly to  a point to avoid singularity using moveit.rviz . However I am getting the following error no matter how many times I try. 

`Unable to find a random collision free configuration after 100 attempts
`
### Your environment
* ROS Distro: Noetic
* OS Version: e.g. Ubuntu 20.04

### Steps to reproduce

roslaunch ur_gazebo ur5.launch

roslaunch ur5_moveit_config ur5_moveit_planning_execution.launch sim:=true

roslaunch ur5_moveit_config moveit_rviz.launch config:=true

### Expected behaviour
I understand it should avoid planning to be safe , however not taking any random valid path out of many tries is doubtful. There needs to be certain threshold that needs to be set high.

**Comment by AndyZe** [comment]
You could try increasing this parameter. Although increasing it too much can have safety ramifications.

`hard_stop_singularity_threshold: 30 # Stop when the condition number hits this`

If you were using MoveIt2, you could use a different IK solver like pick_ik. But that's not available in MoveIt1  :(

Here's the tutorial for MoveIt2 about a different Ik solver:  https://moveit.picknik.ai/main/doc/examples/realtime_servo/realtime_servo_tutorial.html#inverse-kinematics-in-servo

**Comment by Akumar201** [comment]
Thank You for the response. This issue has been solved
