### ISSUE TITLE
failed to   clear octomap  by using  rosservice call /clear_octomap

### ISSUE THREAD

**Issue by dbdxnuliba** [ros-planning/moveit#3342]
### Description
**Failed to   clear octomap  by using  **rosservice call /clear_octomap****
Overview of your issue here.

### Your environment
* ROS Distro**:[Noetic]**
* OS Version: e.g.**20.04**
* Source or Binary build? **source**
* If source, which branch? **1.1.10**

After I load a octomap map by **rosservice call /move_group/load_map**
I successfully see the octomap in rviz .
But when I  try to clear the map by **rosservice call /clear_octomap**, the octomap in the rviz doesn't disappear
like the gif shown:
![bb](https://user-images.githubusercontent.com/13350158/217782389-dbb31b26-18e8-47a8-bc93-1b28c9549784.gif)

and the terminal shown info :
![image](https://user-images.githubusercontent.com/13350158/217783707-acb525d8-e52f-430c-ba94-58d206f1f299.png)

**Comment by dbdxnuliba** [comment]
@rhaschke ,any ideas ,please

**Comment by rhaschke** [comment]
I don't have time to look into that right now. In any case, it would be helpful if you could provide data (rosbag or yaml) to populate the octomap as described.
