### ISSUE TITLE
Need default OMPL optimization objective

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#336]
Since optimization objects were added to our moveit_planners_ompl package in https://github.com/ros-planning/moveit_planners/pull/75 we now have a warning from MoveIt!

> No optimization objective specified, defaulting to PathLengthOptimizationObjective

@rbbg could you also specify a default so this warning is not output? The default should be path length. Thanks!

**Comment by rbbg** [comment]
Right now, the optimization objective is set separately for each planner, do you mean you want to be able to set a different default for _all_ optimizing planners? (much like the projection evaluator?) The path length is already selected in absence of a configuration setting so perhaps removing or changing the message to a debug message would also be sufficient?

**Comment by v4hn** [comment]
+1 to change it to debug.

**Comment by davetcoleman** [comment]
changing it to debug sounds good to me too, thanks!
