### ISSUE TITLE
move_group process immediately dies when executing the move_group.go() command.

### ISSUE THREAD

**Issue by juliusroschmann** [ros-planning/moveit#3374]
My environment

    ROS Distro: Noetic
    OS Version: Ubuntu 20.04
    MoveIt built following the official tutorial
  
Hello,

I was working through the python tutorial: 
        https://ros-planning.github.io/moveit_tutorials/doc/move_group_python_interface/move_group_python_interface_tutorial.html

After the second Enter: 
     2. The robot plans a path to a pose goal.

My move_group node immediately dies: 
`[move_group-1] process has died [pid 48400, exit code -11, cmd /opt/ros/noetic/lib/moveit_ros_move_group/move_group__name:=move_group __log:=/home/julius/.ros/log/418a76b8-c40b-11ed-834b-c58989f442f5/move_group-1.log].`

Without any specific error message and the referenced log-file does not exist either:
`julius@robb:~/.ros/log/418a76b8-c40b-11ed-834b-c58989f442f5$ ls -a`
`.  ..  roslaunch-robb-48012.log  roslaunch-robb-48164.log  roslaunch-robb-48376.log`

I then tried to reproduce the error using another setup found here: 
       https://gitlab.com/tracebot/tracebot_mockup/-/tree/main

Same issue, i can steer the robot using a python script sending joint targets, cartesian paths and also from RViz etc. but no pose_goal. The node also dies immediately without giving a specific error message. So the error occurs when the move_group.go() command is executed when a pose_goal has been supplied in advance. 

Either this is a problem with my local setup or there is somewhere a bug in the installation. I tried reinstalling moveit three times already but no success.

Is there a python workaround to access the inverse kinematic solution directly given 6d-poses, which could then be supplied as joint_value_targets which can be executed?

**Comment by juliusroschmann** [comment]
Update:

directly calling the `move_group.set_pose_target` leads to the described error. But calling `move_group.go(target_pose)` works as intended. I cannot explain why there should be any difference since the message `target_pose` is of type `PoseStamped` and that is a valid type for the `move_group.set_pose_target`  function.

**Comment by rhaschke** [comment]
Sorry, but I can't reproduce your issue. Please provide the exact commit hashes of your `moveit` and `moveit_tutorials` sources. Did you change anything?
