### ISSUE TITLE
in scene objects tab of MotionPlanning panel in rviz  when I want to add a box and move it to a specfied position  in rviz panel ,it can't work well ,like the gif shown

### ISSUE THREAD

**Issue by dbdxnuliba** [ros-planning/moveit#3378]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: Noetic]
* OS Version: 20.04
* Source or Binary build? source
* If binary, which release version?
* If source, which branch? 1.1.11

### Steps to reproduce
in scene objects tab of MotionPlanning panel in rviz 
when I want to add a box and move it to a specfied position  in rviz panel ,it can't work well ,like the gif shown
![cc](https://user-images.githubusercontent.com/13350158/226843101-ab06ab12-8322-4af0-a797-5fd31b90b76b.gif)

**Comment by rhaschke** [comment]
Indeed, publishing PS updates, I can confirm this behavior. Fixed in 0819713fb67e61ee6e4f3949a01f7922ae42aade

**Comment by dbdxnuliba** [comment]
Thank you for your prompt response and efficient handling,it works well now

**Comment by dbdxnuliba** [comment]
but could you please have a look at the issue :https://github.com/ros-planning/moveit/issues/3380
