### ISSUE TITLE
when I build octomap by input point_cloud produced by realsenseD435, I found the move_group node occupies too much cpu*

### ISSUE THREAD

**Issue by dbdxnuliba** [ros-planning/moveit#3379]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: [Kinetic|Melodic|Noetic]
* OS Version:Ubuntu 20.04
* Source or Binary build? source
* If binary, which release version?1.1.11
* If source, which branch?

### Steps to reproduce
**when I build octomap by input point_cloud produced by realsenseD435, I found the move_group node occupies too much cpu**,
and when I look into the node pid by  top -H -p <PID_move_group>
![image](https://user-images.githubusercontent.com/13350158/227088745-844cea8c-eb2f-459a-8ce6-8f85a24095e9.png)

**and we can find  as the fig shown ,the first thread occupies 99.9%cpu ,
but we can find there serveral threads running  in move_group node ,but the threads have  the same same "move_group",
so we cannot find which part code of move_group occupies the cpu most part**

SO my question is:
1.how can we find the code  occupied too much cpu in the move_group when building octomap ;Mabe   named  all the threads in the move_group node codes can help debug the problem
2. how can we reduce the cpu occupency of move_group when build octomap

Any answer is pleasured,thanks

**Comment by rhaschke** [comment]
`top` doesn't display thread names. The high CPU usage is due to the processing of the point cloud. This is expected.
If you want to reduce the load, reduce the update rate of your camera, point cloud, or planning scene update messages.
