### ISSUE TITLE
/clear_octomap can't clear octomap in moveit 

### ISSUE THREAD

**Issue by dbdxnuliba** [ros-planning/moveit#3380]
### Description

Overview of your issue here.

I have found a bug in MoveIt. When the point cloud topic stops publishing, clicking "clear octomap" in MotionPlanning Panel of rviz does not clear the map. However, if the point cloud topic continues to publish, the map will continue to update based on the point cloud and cannot be cleared completely. This means that once Map Building is turned on in MoveIt, the map cannot be cleared unless MoveIt is restarted.
![clear](https://user-images.githubusercontent.com/13350158/227117430-422be449-2bf7-49eb-9b61-5ca8f982cb29.gif)

### Your environment
* ROS Distro:Noetic
* OS Version: Ubuntu 20.04
* Source or Binary build?source
* If binary, which release version?
* If source, which branch?1.1.11
*

**Comment by rhaschke** [comment]
Looks like the scene update is not correctly received by rviz. In the move_group's PS, the octomap is correctly cleared. This can be easily verified by disabling and re-enabling the display in rviz, which re-creates everything. I'm looking into the issue in more depth...

**Comment by dbdxnuliba** [comment]
thanks for your prompt answer,did you mean the issue has been fixed and will pub in the next version ,

**Comment by rhaschke** [comment]
Yes, the issue will be fixed with the next release.

**Comment by dbdxnuliba** [comment]
ok ,thanks a lot
