### ISSUE TITLE
Pilz planner on windows

### ISSUE THREAD

**Issue by MarcM0** [ros-planning/moveit#3382]
**Is your feature request related to a problem? Please describe.**
The pilz planner is not available on windows

**Describe the solution you'd like**
A way to use the pilz planner on windows

**Describe alternatives you've considered**
I am using computeCartesianPath() but it fails often. The ompl planners work but don't give me straight paths, and they can't accept multiple goals

**Comment by rhaschke** [comment]
Windows is not officially supported. You need to build MoveIt from source on your own.
