### ISSUE TITLE
when I run the moveit plan and execute test code multiple time , the displayed path “/move_group/display_planned_path” in rviz is wrong and it seems like that the path of the previous path was cached in the current “/move_group/display_planned_path” topics ,which seems like a bug

### ISSUE THREAD

**Issue by dbdxnuliba** [ros-planning/moveit#3384]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: Noetic
* OS Version: e.g. Ubuntu 20.04
* Source or Binary build? source
* If binary, which release version?
* If source, which branch?1.1.11

### Steps to reproduce

when I run the code in the following multiple times,and 

Although the path executed by the robotic arm is correct, the displayed path “/move_group/display_planned_path” in rviz is wrong and it seems like that the path of the previous path was cached in the current “/move_group/display_planned_path” topics ,which seems like a bug:

and in details of the code 
    **waypoints.push_back(p1);
    p1.position.z += 0.1;  #first time run it is"p1.position.z += 0.1\",the next time run "p1.position.z -= 0.1"
    waypoints.push_back(p1);
    p1.position.y -= 0.1;** #first time run it is"p1.position.y -= 0.1\",the next time run "p1.position.y += 0.1"
    waypoints.push_back(p1);

you can reproduce this phenomenon by set different waypoints coord every time you run the test node again;
![path_plan](https://user-images.githubusercontent.com/13350158/227492092-0a70ff77-eee2-4f60-aa68-de4e70dfa2a9.gif)

![image](https://user-images.githubusercontent.com/13350158/227493133-5c57653c-0891-4af1-8e50-7671de0aa50e.png)

**the red trajectory is the right path ,but the blue path is unnecessary previous trajectories that should not appear,**

in detail of  Trajectory cfg in rviz  :
![image](https://user-images.githubusercontent.com/13350158/227492193-45c2a5ff-2e8c-4e21-87b1-56ff23e802d3.png)
![image](https://user-images.githubusercontent.com/13350158/227492274-0a0faf6d-3ce2-4b0a-9c8a-ec936b7b2d32.png)
``
#include <ros/ros.h>
#include <memory>

#include <moveit/move_group_interface/move_group_interface.h>
#include <moveit/planning_scene_interface/planning_scene_interface.h>

#include <geometry_msgs/PointStamped.h>
#include <moveit_msgs/RobotTrajectory.h>
#include <tf2_geometry_msgs/tf2_geometry_msgs.h>
#include <tf/transform_datatypes.h>
#include <moveit_visual_tools/moveit_visual_tools.h>

namespace rvt = rviz_visual_tools;

int main(int argc, char** argv)
{
    ros::init(argc, argv, "pilz_goal_controller");
    ros::NodeHandle nh("/pilz_goal_controller");
    ros::AsyncSpinner spinner(4);
    spinner.start();

    static const std::string PLANNING_GROUP = "right_arm";
    static const std::string LOGNAME = "pilz_goal_controller";

    ros::Duration(1.0).sleep();
    ROS_INFO_STREAM_NAMED(LOGNAME, "Starting MoveIt pilz right_arm Controller ...");
    
    moveit::planning_interface::MoveGroupInterface group(PLANNING_GROUP);
    moveit::planning_interface::PlanningSceneInterface planning_scene_interface;
    // Raw pointers are frequently used to refer to the planning group for improved performance.
    const moveit::core::JointModelGroup* joint_model_group =
        group.getCurrentState()->getJointModelGroup(PLANNING_GROUP);

    group.setPlanningPipelineId("pilz_industrial_motion_planner");
    group.setPlannerId("PTP");
    group.setMaxVelocityScalingFactor(0.05);
    group.setMaxAccelerationScalingFactor(0.1);

    const double pi = 3.141592653589793238;

    geometry_msgs::PoseStamped pose_cur = group.getCurrentPose();
    std::cout<<"pose_cur position:x,y,z"<<pose_cur.pose.position.x<<"\t"<<pose_cur.pose.position.y<<"\t"<<pose_cur.pose.position.z<<std::endl;
    std::cout<<"pose_cur orientation:qx,qy,qz,qw"<<pose_cur.pose.orientation.x<<"\t"<<pose_cur.pose.orientation.y<<"\t"<<pose_cur.pose.orientation.z<<"\t"<<pose_cur.pose.orientation.w<<std::endl;

    geometry_msgs::PoseStamped target;
    target= pose_cur;
    target.header.frame_id = group.getPoseReferenceFrame();
    target.header.stamp = ros::Time::now();
    std::vector<geometry_msgs::Pose> waypoints;
    geometry_msgs::Pose p1 = target.pose;
    **waypoints.push_back(p1);
    p1.position.z += 0.1;  #first time run it is"p1.position.z += 0.1\",the next time run "p1.position.z -= 0.1"
    waypoints.push_back(p1);
    p1.position.y -= 0.1;** #first time run it is"p1.position.y -= 0.1\",the next time run "p1.position.y += 0.1"
    waypoints.push_back(p1);

    moveit_msgs::RobotTrajectory trajectory;
    const double jump_threshold = 0.0;
    const double eef_step = 0.01;
    double fraction = group.computeCartesianPath(waypoints, eef_step, jump_threshold, trajectory);
    ROS_INFO_NAMED("tutorial", " (Cartesian path) (%.2f%% achieved)", fraction * 100.0);

    ros::Duration(5.0).sleep();

    group.execute(trajectory);
    return 0;
}
``

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by rhaschke** [comment]
Please provide clean and concise bug reports:
- The title should be a _short_ (i.e. one-line) description of the problem, not the full story
- Provide working code to reproduce your issue, including all required components, i.e. code, config files, etc.

In general, the TrajectoryDisplay always displays the last planned trajectory (which is cached then).
