### ISSUE TITLE
MoveIt Setup Assistant crashes when set 3D Perception

### ISSUE THREAD

**Issue by Siva552** [ros-planning/moveit#3398]
### Description

I Create New MoveIt Configuration Packag use MSA follow :

https://ros-planning.github.io/moveit_tutorials/doc/setup_assistant/setup_assistant_tutorial.html

when I set 3D Perception to "Point Cloud" or "Depth Map", then I click any option(author information or anyone else),MSA died

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04
* Binary build：noetic

### Steps to reproduce
1. launch MoveIt Setup Assistant : `roslaunch moveit_setup_assistant setup_assistant.launch`
2.load panda urdf on :  /opt/ros/noetic/share/franka_description/robots/panda/panda.urdf.xacro
3.set 3D Perception to "Point Cloud" or "Depth Map"
4.select any option (such "author information")
5.MSA crash !

### Backtrace or Console output
```
started core service [/rosout]
process[moveit_setup_assistant-2]: started with pid [39077]
[ INFO] [1681384916.234830124]: Loaded panda robot model.
[ INFO] [1681384916.235702915]: Setting Param Server with Robot Description
[ INFO] [1681384916.237171540]: Robot semantic model successfully loaded.
[ INFO] [1681384916.237184569]: Setting Param Server with Robot Semantic Description
[ INFO] [1681384916.242848416]: Loading robot model 'panda'...
[ INFO] [1681384916.242864711]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ INFO] [1681384916.347509163]: Stereo is NOT SUPPORTED
[ INFO] [1681384916.347568054]: OpenGL device: Mesa Intel(R) Graphics (ADL-S GT1)
[ INFO] [1681384916.347577363]: OpenGl version: 4.6 (GLSL 4.6) limited to GLSL 1.4 on Mesa system.
[ INFO] [1681384916.380395551]: Loading robot model 'panda'...
[ INFO] [1681384916.380411238]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ INFO] [1681384916.551439560]: Loading Setup Assistant Complete
================================================================================REQUIRED process [moveit_setup_assistant-2] has died!
process has died [pid 39077, exit code -11, cmd /home/cyk/ws_moveit/devel/lib/moveit_setup_assistant/moveit_setup_assistant __name:=moveit_setup_assistant __log:=/home/cyk/.ros/log/27fedc5a-d9ed-11ed-80d7-b1b1ae71f814/moveit_setup_assistant-2.log].
log file: /home/cyk/.ros/log/27fedc5a-d9ed-11ed-80d7-b1b1ae71f814/moveit_setup_assistant-2*.log
Initiating shutdown!
================================================================================
[moveit_setup_assistant-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by rhaschke** [comment]
The 3D perception config widget is designed incorrectly: while it is possible to register multiple octomap updaters (operating from different sources), the widget essentially only allows configuring a single one - the one selected in the combo box. However, the data structure to hold that information is already prepared to hold several configs...
I could go for a quick hack solution, allowing to correctly define a single updater. The correct solution will require a more thorough rework of the widget design...
