### ISSUE TITLE
Interactive marker not working for multiple robots

### ISSUE THREAD

**Issue by buswayne** [ros-planning/moveit#3401]
Hello there!

I'm simulating two robotic arms that share the same urdf. In gazebo and in Rviz, everything is coherent with the two namespaces that I gave the robots.

The behavior obtained with the MoveIt plugins for Rviz is as expected if the goal state is set modifying the joints (i.e, the trajectory is planned and executed correctly by the respective robot I want to control).

The issue is with the interactive marker that switches between one robot and the other, it cannot be moved and it "flickers". In short, apparently it is shared between the two robots (even though they have different namespaces!). My guess is that the problem is due to the fact that for both the robots the planning group is called "arm", and the moveit plugin code related to the interactive marker is not considering the namespace.

Do you have any suggestion to fix the issue?

Thanks in advance!

![image](https://user-images.githubusercontent.com/55987194/232122779-317ebce9-9bab-4b1a-b8e0-107553f10818.png)

**Comment by rhaschke** [comment]
I guess the problem stems from ambiguous TF names or do you have separate TF namespaces for the two robots as well?
(Note that this is different from the ROS parameter namespaces.)
To further study the issue, a full moveit and rviz config would be helpful.

**Comment by buswayne** [comment]
Hi Robert,

Thanks for the reply! Yep, the TF have separate namespaces, too! Here below the details of the configs. You can see from the graph that the only topics without namespace are the one pulished by rviz that containt "robot_interaction_interactive_marker_topic", that's why I believe this is the issue
 
GRAPH:
![rosgraph](https://user-images.githubusercontent.com/55987194/232197512-406c75dd-a324-4d93-80c3-d4613253523a.svg)

TF TREE:
![frames](https://user-images.githubusercontent.com/55987194/232198001-194de48e-6380-4a27-9c89-6d2b872c34e6.svg)

Thanks a lot for your support!

R

**Comment by rhaschke** [comment]
Please test #3403.

**Comment by buswayne** [comment]
It works like charm!! Thanks a lot Robert

![image](https://user-images.githubusercontent.com/55987194/232227521-d651600b-2766-4d3f-a907-e5ae76f138dd.png)
