### ISSUE TITLE
How to check which frame I'm on of a pose

### ISSUE THREAD

**Issue by TapleFlib** [ros-planning/moveit#3406]
I'm using ROS noetic and Techman robot tm5-700
1. I write a python code to read current pose, but I don't know if the pose is the pose of the base or end effector. And what is the unit ?

![image](https://user-images.githubusercontent.com/130976648/233122085-49925c03-9f1b-48fe-88ea-740f0f27c670.png)

2. I'm new to moveit and tf stuff, anyone know how to write a python code to convert x,y pixel from camera to end effector using tf?

**Comment by simonschmeisser** [comment]
Please consider reading the documentation for `get_current_pose` and if still unclear search or ask questions on answers.ros.org or robotics.stackexchange.com

This tracker is meant for bugs, enhancements and feature discussions.
