### ISSUE TITLE
Moveit Servo Restrict Joint Movement

### ISSUE THREAD

**Issue by nihalar** [ros-planning/moveit#3422]
### Description

Hello There. 
I am using an Ur5 robot with Moveit servo. I'm trying to figure out how to restrict movement on certain joints. In some instances (depending on the movement direction), only a subset of the joints needs to move, instead of the entire robot. That is, Movements of certain joints need to be restricted. The movements are done by sending twist velocity commands to the end effector.

Is there a way to assign weights or similar to the joints so that the movements happen on particular joints only? 

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04

**Comment by AndyZe** [comment]
Re-open if you have further issues, please.
