### ISSUE TITLE
Moveit servoing with roll, pitch and yaw 

### ISSUE THREAD

**Issue by Akumar201** [ros-planning/moveit#3447]
I am working with the [pose_tracking_example.cpp ](https://raw.githubusercontent.com/ros-planning/moveit/noetic-devel/moveit_ros/moveit_servo/src/cpp_interface_example/pose_tracking_example.cpp), I was trying to include orientation in the given example and was successful by adding 

```
  target_pose.pose.orientation.w = qw;
  target_pose.pose.orientation.x = qx;
  target_pose.pose.orientation.y = qy;
  target_pose.pose.orientation.z = qz;
  
```
But the arm is moving slow in terms of orientation, that is it's not changing it's orientation as fast as it does it's position. Any help will be much appreciated

**Comment by AndyZe** [comment]
If you can, try this MoveIt2 branch. It's leaps and bounds faster:  https://github.com/ros-planning/moveit2/pull/2224

The downside is, it's still a work in progress.

If you're stuck on ROS1, then you can increase the gains here:

https://github.com/ros-planning/moveit/blob/67121a31d8933a1ab109a2fbb4d33aa66672bfad/moveit_ros/moveit_servo/config/pose_tracking_settings.yaml#L19
