### ISSUE TITLE
Motion planning with the only position target

### ISSUE THREAD

**Issue by STAY-Melody** [ros-planning/moveit#3474]
Hi!

I'm curious about how the `move_group_interface` realizes the motion planning task with the only position target.

By browsing the source code of [move_group_interface.setPositionTarget](http://docs.ros.org/en/noetic/api/moveit_ros_planning_interface/html/move__group__interface_8cpp_source.html), I found that the orientation target is compensated with the default value (i.e., quaternion: 1, 0, 0, 0).

However, after some tests, the manipulator can finish the planning task without achieving the orientation goal. Is there a tolerance set somewhere in the program for the default orientation target?

Besides, with the pose (orientation and position) target, how does the `move_group_interface` transform the pose target to the joint value target in the configuration space and send the planning command to OMPL? 

Thanks!

**Comment by rhaschke** [comment]
If you use a position-only target, orientation constraints are removed:
https://github.com/ros-planning/moveit/blob/69ca441bc343c51544b19dde9c5a095481a3d906/moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp#L1127-L1128

OMPL planners are sampling-based, i.e. joint-space samples are drawn and validated against all the constraints. If any of them is violated, another sample is drawn and so on.
Some planners operate in Cartesian space as well, in which case the IK plugin is used that is defined for your planning group.

**Comment by rhaschke** [comment]
Such a question should be better asked at https://answers.ros.org. Please, post real issues and bug reports here only.
