### ISSUE TITLE
Could not find the package

### ISSUE THREAD

**Issue by zichunxx** [ros-planning/moveit#3476]
Hi!

I have built `moveit` from source in the `ws_moveit` package.

When I `find_package(moveit_visual_tools)` in another ROS workspace (`ws_A`), I met the `cmake` error that `cmake` could not find the package. 

```
By not providing "Findmoveit_visual_tools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "moveit_visual_tools", but CMake did not find one.

  Could not find a package configuration file provided by
  "moveit_visual_tools" with any of the following names:

    moveit_visual_toolsConfig.cmake
    moveit_visual_tools-config.cmake

  Add the installation prefix of "moveit_visual_tools" to CMAKE_PREFIX_PATH
  or set "moveit_visual_tools_DIR" to a directory containing one of the above
  files.  If "moveit_visual_tools" provides a separate development package or
  SDK, be sure it has been installed.
```

I am certain that I have made the following changes in my current workspace (`ws_A`)

* Add `~/ws_moveit/devel/setup.zsh` into `zshrc`
* Add `find_package(moveit_visual_tools REQUIRED)` in the `cmakelist.txt`
* Add  `<depend>moveit_visual_tools</depend>` in the `package.xml`

What else did I miss? 

Help would be appreciated! Thanks!

**Comment by rhaschke** [comment]
To answer the question: `moveit_visual_tools` is not part of the moveit repo, but a separate package.

**Comment by rhaschke** [comment]
After building your workspace, you need to source it to have those settings:
`source /path_to/ws_moveit/devel/setup.bash`

**Comment by gavanderhoorn** [comment]
Likely cross-post of [Could not find package after building moveit from source](https://answers.ros.org/question/417464). If it is, this shows exactly why that is not nice: we now have both me and @rhaschke trying to diagnose the same problem, and actually suggesting the exact same thing ..
