### ISSUE TITLE
Rate of fake controller 

### ISSUE THREAD

**Issue by yepw** [ros-planning/moveit#3480]
### Description

Hi, I have been trying to make the fake controller publish at a higher rate (the default seems to be 10 hz). 

In [this tutorial](https://ros-planning.github.io/moveit_tutorials/doc/controller_configuration/controller_configuration_tutorial.html#fake-controller-yaml-file), changing the `rate` parameter in the fake controller's yaml config file should work. However, it doesn't seem to make any difference. I wonder how to make `/move_group/fake_controller_joint_states` being published at a higher rate.

### Your environment
* ROS Distro: [Noetic]
* OS Version: e.g. Ubuntu 18.04
* Source or Binary build?   Binary
* If binary, which release version?   1.1.12 (from package.xml)
* If source, which branch?

### Steps to reproduce

1. Add the following line to `config/fake_controllers.yaml` in the repo `panda_moveit_config`
```
rate: 30
```
2. `roslaunch panda_moveit_config demo.launch`
3. `rosrun moveit_tutorials pick_place_tutorial`
4. `rostopic hz /move_group/fake_controller_joint_states`

### Expected behaviour

The rate of topic `/move_group/fake_controller_joint_states` should be ~30 hz.

### Actual behaviour

The rate of topic `/move_group/fake_controller_joint_states` is less than 10 hz.

**Comment by rhaschke** [comment]
Thanks for pointing out this issue. The parameter should be named: `fake_interpolating_controller_rate`.
I changed the tutorial accordingly.
