### ISSUE TITLE
MSA: move_group is always run in debug mode

### ISSUE THREAD

**Issue by VideoSystemsTech** [ros-planning/moveit#3491]
In the `demo.launch` file, the `info` argument passed to `move_group.launch` is set to `true`, thus forcing move_group to run in debug mode.

https://github.com/ros-planning/moveit/blob/1730d7b392a072bafaab37e6e3bb8ed11e58047e/moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch#L45-L50

https://github.com/ros-planning/moveit/blob/1730d7b392a072bafaab37e6e3bb8ed11e58047e/moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch#L9-L12

The `info` argument is useless anyway, I don't know if removing it would break things.

**Comment by rhaschke** [comment]
> The `info` argument is useless anyway, I don't know if removing it would break things.

Why do you think so?

The `info` argument enables debug-level logging (via the option `--debug` passed to `move_group` node):
https://github.com/ros-planning/moveit/blob/1730d7b392a072bafaab37e6e3bb8ed11e58047e/moveit_ros/move_group/src/move_group.cpp#L294-L298

The `debug` argument on the other hand runs move_group within the debugger:
https://github.com/ros-planning/moveit/blob/1730d7b392a072bafaab37e6e3bb8ed11e58047e/moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch#L6-L7

_Additionally_ it enables debug-mode, which perfectly makes sense to me.
Both options are independent, but `debug=true` implies `info=true`.
