### ISSUE TITLE
Robotic Arm on wall

### ISSUE THREAD

**Issue by Akumar201** [ros-planning/moveit#3496]
Hi, I would like to know how can I use MoveIt to control real Robotic arm fixed on Wall ! Currently, I am using moveit to control is (placing the arm on ground). What things I should take care of 
I am currently using it like 

![image](https://github.com/ros-planning/moveit/assets/108360879/c9cc3538-f3f6-4f50-a6fb-7a4799d83024)

I want to use it Something like 

![image](https://github.com/ros-planning/moveit/assets/108360879/534872dc-2abc-41a7-8631-011bc21f5c37)

**Comment by rhaschke** [comment]
MoveIt doesn't care about the mounting pose of the arm. However, your low-level robot-control might do. Check the docs of the manufacturer!

**Comment by rhaschke** [comment]
No, as I said, ROS and MoveIt work independently of the mounting pose. Just, change your URDF and mount the robot as you like.
