### ISSUE TITLE
collision_distance_field causes memory exhaustion to size 0 geometry

### ISSUE THREAD

**Issue by toru-kuga** [ros-planning/moveit#3502]
### Description
A fix idea on collision_distance_field, to prevent memory exhaustion & crash.

### Your environment
* ROS Distro: [Melodic]
* OS Version: Ubuntu 18.04
* Source build
* If source, which branch: melodic_devel

### Steps to reproduce
In the robot urdf file, in one of existing `<collision>`, add an element with geometry of size 0,
ex) 
```
    <collision name="link1">
      <geometry>
        <box size="0 0 0"/>
      </geometry>
    </collision>
```
select CHOMP as planner, which uses collision_distance_field collision checker. 

### Expected behaviour
It should throw an error, if size=0 is illegal.

### Actual behaviour
A rapid consumption of memory occurs, and finally the process gets killed, with a message like below.
> [move_group-3] process has died [pid 502666, exit code -9, cmd /home/ubuntu/catkin_ws/devel/lib/moveit_ros_move_group/move_group --debug __name:=move_group __log:=/home/ubuntu/.ros/log/ea5069cc-11b0-11ee-ac45-0242ac110002/move_group-3.log].
log file: /home/ubuntu/.ros/log/ea5069cc-11b0-11ee-ac45-0242ac110002/move_group-3*.log

### Backtrace or Console output
The trouble occurs at:
https://github.com/ros-planning/moveit/blob/1fbb2c4c555fe59cb316fea184760468aa702d66/moveit_core/collision_distance_field/src/collision_distance_field_types.cpp#L47
in lines
> L53 unsigned int num_points = ceil(cyl.length / (cyl.radius / 2.0));

and

> L57  for (unsigned int i = 1; i < num_points - 1; i++)

When size 0 box is passed, following calculation happened (may be environment-dependent) 
1) cyl.length / (cyl.radius / 2.0) = 0.0/0.0 = nan;
2) unsigned int num_points = ceil(nan) =0;
Then, in L57 loop limit becomes (num_points - 1)=0xffffffff , in the loop some memory consumption is made, that leads to exhaustion. 

### Fix idea
At least num_points =0 is illegal, and should be rejected. 
Whether it's better to throw exception or just ignore, I'm not sure.

### other information
Gazebo client also crashes with URDF with size 0 object, so maybe size 0 is widely illegal?

**Comment by rhaschke** [comment]
Thanks for pointing out and analyzing this issue. zero-sized bodies are not illegal per se, but they pose corner cases, which often require extra handling. I proposed a fix in #3504. Please review.
