### ISSUE TITLE
Is it possible to use moveit without a hardware interface or controller?

### ISSUE THREAD

**Issue by babbatem** [ros-planning/moveit#3511]
Hello, bit of a strange request -- is it possible to use moveit without a hardware interface or ros controllers? We are running our own controllers and trajectory execution stack and hoping to plan with moveit, then hand the trajectory off. Would this be possible, e.g. by publishing joint states from our controllers? 

Thanks for your time.

**Comment by rhaschke** [comment]
As input, MoveIt just needs the URDF/SRDF model and published `/joint_states`. To pass a planned trajectory to your non-standard controller, you will need to provide a `FollowJointTrajectory` action server:
https://ros-planning.github.io/moveit_tutorials/doc/controller_configuration/controller_configuration_tutorial.html

**Comment by babbatem** [comment]
Thanks for your reply.
