### ISSUE TITLE
Checkbox for joint slider to show joints in radians 

### ISSUE THREAD

**Issue by aaryanmurgunde** [ros-planning/moveit#3513]
This is a sub issue listed in #2741 

>14. In the "Joints" tab, joint values are given in degree. Some people think this is the correct way to show things to the user. But, in addition to this being a debatable choice, this makes it awful to set values from debugging output (in rad) to look at the robot state visually. As there are two clear opinions on this issue, I would propose to add a checkbox to switch units.

Suggested Change: To add a checkbox in the joints section of Motion Planning Rviz Plugin < [ ] Display joints in Radians > preferable in the bottom section of the window, so as to show the joints in radians.

@v4hn or @rhaschke  Any other suggestions?

**Comment by v4hn** [comment]
What suggestions do you want? Just needs to be done

**Comment by aaryanmurgunde** [comment]
![image](https://github.com/ros-planning/moveit/assets/44398228/6554c88b-a106-4882-9629-e4abe4164f02)
![image](https://github.com/ros-planning/moveit/assets/44398228/4859b11b-4143-45a6-9f2e-46323547f885)

Hi, I have added the checkbox and also found a way to display the joints in radians.
https://github.com/ros-planning/moveit/pull/3516/commits/994cdc5f563d3ac8e8d7230c107a31c545fea6a2

I require some help in connecting the checkbox to the flag. I tried a couple of things but the scope of the class seems to limit me access to the Qt checkbox.

**Comment by aaryanmurgunde** [comment]
Closing this Issue against PR #3516 

@rhaschke Thank you so much for helping me around this helps me a lot in building my skills. 
Do you want me to raise the same changes in the ROS 2 repo, or is there a way these changes are synchronised ?

**Comment by rhaschke** [comment]
We regularly cherry-pick from MoveIt1 to MoveIt2. Thanks.
