### ISSUE TITLE
Prefixed frame being considered as a subframe results in failure

### ISSUE THREAD

**Issue by mbusy** [ros-planning/moveit#3514]
### Description

When using the `plan` or the `compute_cartesian_path` method of a `moveit_commander.MoveGroupCommander` object, I get the following error:
```shell
Pose frame 'ur5_robot/wrist_3_link' does not exist.
```

To add more context, I work with a model containing links that can be prefixed (eg `ur5_robot/wrist_3_link` instead of `wrist_3_link`). 
This error arises when calling the `plan` method using a PoseStamped or `compute_cartesian_path`, in both cases after changing the end effector of the `MoveGroupCommander` (using `set_end_effector_link`) to a link within the group chain that is not the tip link.

I eventually tracked down what was responsible for that, and it has been brought by PR #2918 and #3388.

This [first check](https://github.com/ros-planning/moveit/blob/984a0ea2a00b4190cad9e08ea0d764c19dbf9975/moveit_core/robot_state/src/robot_state.cpp#L1706-L1709) is triggered when the end effector has been modified and now calls `getRigidlyConnectedParentLinkModel`, and fails [in here](https://github.com/ros-planning/moveit/blob/984a0ea2a00b4190cad9e08ea0d764c19dbf9975/moveit_core/robot_state/src/robot_state.cpp#L810-L825) as `ur5_robot/wrist_3_link` is assumed to be a [subframe](https://ros-planning.github.io/moveit_tutorials/doc/subframes/subframes_tutorial.html).

What would be the best way of updating this to be able to work with prefixed frames, without having them considered as subframes?

### Your environment
* ROS Distro: [Noetic]
* OS Version: e.g. Ubuntu 20.04
* Commit a6f8bb95b023a971f1ea20af971ff72324bea302
* Brought by PR #3388 and #2918

### Steps to reproduce
* Use a robot description containing prefixed frame (eg `ur5_robot/wrist_3_link` instead of `wrist_3_link`)
* Create a `moveit_commander.MoveGroupCommander` using a specific move group
* Set the end effector of the `moveit_commander.MoveGroupCommander` to a different link than the tip link of the group chain
* Call the `plan` method with a PoseStamped or the `compute_cartesian_path` method

### Expected behaviour
The methods should execute smoothly and consider the prefixed link as a standard link

### Actual behaviour
The methods fail, throwing
```shell
Pose frame 'ur5_robot/wrist_3_link' does not exist.
```
(When 'ur5_robot/wrist_3_link' has been selected as the end effector, through the `set_end_effector_link` link method)

**Comment by rhaschke** [comment]
Slashes are considered by MoveIt as a subframe separator. Thus, just use link names w/o slashes. Hence, you should use another last character for your prefix, e.g. replacing `/` with `\` or `:`.
