### ISSUE TITLE
Typo in MoveIt 1 documentation of moveit_commander.move_group.MoveGroupCommander

### ISSUE THREAD

**Issue by IrvingF7** [ros-planning/moveit#3573]
**Is your feature request related to a problem? Please describe.**

In the latest documentation updated on Feb 27, it says

"Compute a sequence of waypoints that make the end-effector move in straight line segments that follow the poses specified as waypoints. Configurations are computed for every eef_step meters; The jump_threshold specifies the maximum distance in configuration space between consecutive points in the resultingpath; Kinematic constraints for the path given by path_constraints will be met for every point along the trajectory, if they are not met, a partial solution will be returned. The return value is a tuple: a fraction of how much of the path was followed, the actual RobotTrajectory."

However, the actual returned values are (RobotTrajectory, Fraction). The order is reversed in the doc.

Also, this docstring has no line break, so it's very hard to read on PC.

**Describe the solution you'd like**
Fix the order and also add line breaks to it

**Describe alternatives you've considered**
I can also do the modification myself. Unfortunately, I don't know what would be the appropriate way to approach this.

**Additional context**
Thank you for your excellent work on this package.

**Comment by rhaschke** [comment]
A pull request is very welcome. You can directly edit the corresponding file here on github.
