### ISSUE TITLE
Starting MongoDB constraint database node with reset argument leads to class_loader::LibraryUnloadException

### ISSUE THREAD

**Issue by stevenoh2003** [ros-planning/moveit#3579]
### Your environment
* ROS Distro: [Noetic]
* OS Version: Ubuntu 20.04

### Steps to reproduce
Steps can be reproduced by simplying running the `default_warehouse_db.launch` file inside your moveit_config folder generated by moveit. One also must set the "reset" argument inside the launch file to be true.

In addition to this scenario, I found that after I launch the MongoDB warehouse server and use the constraint from the warehouse to plan trajectories in moveit commander the same error can be seen in my moveit commander terminal window after I finish the trajectories.

*Note that everything works (eg. warehouse server, moveit planning), but this error just appears at the end of 1)launching mongodb warehouse server and 2)moveit commander planning.

### Expected behaviour
It should just launch a warehouse database server using MongoDB without outputting any errors.

### Actual behaviour
It prints out error

`terminate called after throwing an instance of 'class_loader::LibraryUnloadException'
  what():  Attempt to unload library that class_loader is unaware of.`

**Comment by rhaschke** [comment]
I can run `roslaunch moveit_resources_panda_moveit_config default_warehouse_db.launch` w/o issues.
Please provide more details.

**Comment by stevenoh2003** [comment]
> I can run `roslaunch moveit_resources_panda_moveit_config default_warehouse_db.launch` w/o issues. Please provide more details.

Sorry, I just updated my post. You also have to set the "reset" argument to be "true". (it is false by default)

**Comment by rhaschke** [comment]
Yes, now I can reproduce the error message.

**Comment by rhaschke** [comment]
I shortly looked into this. You can safely ignore this error message. It occurs during the shutdown of the database initialization program while releasing a static resource, which should have been released earlier.
Nevertheless, I filed a PR to fix that issue: #3581

**Comment by stevenoh2003** [comment]
> I shortly looked into this. You can safely ignore this error message. It occurs during the shutdown of the database initialization program while releasing a static resource, which should have been released earlier.
> 
> Nevertheless, I filed a PR to fix that issue: #3581

Thank you for the PR!
