### ISSUE TITLE
Planning for moving the PR2 base with MoveIt!

### ISSUE THREAD

**Issue by Tenrampi** [ros-planning/moveit#375]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: [Indigo]
* OS Version: e.g. Ubuntu 14.04
* Source build
Hello,

I would like to use MoveIt for motion planning of the PR2 (only moving the base in a scene).
The example of controlling a mobile base given found in Internet are done with the move_base package using the navigation stack.

I followed the tutorial on moveit site to use the motion_planning_interface to plan the movement of an arm of pr2 but I can not figure out how to implement the planning of the base movement.
Can someone help me? There is an example of the entire robot motion planning using moveit?

I found this thread [planning move base](https://groups.google.com/forum/#!msg/moveit-users/eUdP2UHb1uM/p65UyJkrUZkJ) but I have many doubts about how this solution was implemented.

It is possible also extract the path generated by moveit through OMPL and not the entire trajectory?

Last question, there is a way to send moveit an already created octomap instead of PointCloud generated by the robot's sensors?

thank you

**Comment by gavanderhoorn** [comment]
Also: [Planning for moving the PR2 base with MoveIt!](https://groups.google.com/forum/#!topic/moveit-users/dC1MXhhje1s) on `moveit-users`.

**Comment by davetcoleman** [comment]
@Tenrampi please do not double post both here and on the mailing list, and try to keep questions separate: your octomap question is a very different topic of mobile base planning

There has not been much work with mobile base planning and MoveIt!. It is possible with customization and extra development, but not something that is easy to do out of the box AFAIK

**Comment by Tenrampi** [comment]
Sorry for the double post, I did not know that they were connected! I'm asking for the planning of the basic movement because running the demo of pr2 contained in the folder pr2_moveit_config you can make the planning of the movement of the base by selecting the base as a group, while I would like to conduct the planning of the base movement but using various interfaces like in tutorials on moveit site, so without having to use the present GUI rviz but using the scheduling parameters within the code. the problem is that from the tutorial I do not understand how to plan the movement of the base being the tutorial totally focused by the arm movements.

**Comment by 130s** [comment]
Also maybe relevant from moveit-users:
- [Integration of ROS Navigation stack](https://groups.google.com/forum/#!topic/moveit-users/W0iso6tJv94)
- [Moveit for non holonomic mobile base in 2D](https://groups.google.com/forum/#!topic/moveit-users/NNvRNHeiYrw)
- [Controlling a Mobile Base with MoveIt!](https://groups.google.com/forum/#!topic/ros-by-example/sEsmuVEPxjw)

**Comment by v4hn** [comment]
This is a broad topic and no specific issue with MoveIt.
I'll close this for now. If someone works on this and wants to have official support (including an example demo) for this in MoveIt, feel free to open this again.

**Comment by naveedhd** [comment]
Hi everybody! coming here after using the non-standard way of planning alongwith base (i.e. modelling with 2prismatic-1revolute joint) and thought this might be the place to put this. 

I am trying to sort out how would planning for base should be implemented. From my current understanding, I imagine it requires modifying/extending Robot Model, Robot State and Kinematic Base/Plugin interfaces for differential kinematics for a special group case that is the base.

If somebody has an idea, insights or ideally a rough roadmap of how things should be implemented within MoveIt, it would be good to have it somewhere. (in other words to know if I am able to attempt that).
