### ISSUE TITLE
make PlanningSceneInterface add/remove CollisionObjects synchronously

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#38]
I would very much like to adjust [`PlanningSceneInterface::{add/remove}CollisionObjects`](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_ros/planning_interface/planning_scene_interface/include/moveit/planning_scene_interface/planning_scene_interface.h#L86)
to use the new `ApplyPlanningScene` service such that it performs synchronous updates to the planning scene.
This is what most users expect and it is not even documented in the [tutorials](http://docs.ros.org/indigo/api/pr2_moveit_tutorials/html/planning/src/doc/move_group_interface_tutorial.html#adding-removing-objects-and-attaching-detaching-objects) that this is not the case.

At the moment these methods wrap simple `publish` calls whereas the other methods in this class query the `move_group` via services.

Thus, the current behavior is (1) inconsistent, (2) not documented, and (3) makes people add arbitrary long `sleep` calls after the function call.

**However**, ApplyPlanningScene is a MoveGroupCapability [that has to be added manually in each projects `move_group.launch`](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch#L59) and the PlanningSceneInterface has been around quite long.
Thus, simply changing the implementation would break many use-cases.
As a downward-compatible workaround I propose to check whether the service exists and either (1) call the detected service or (2) print an appropriate warning telling the user to enable ApplyPlanningScene in their move_group and afterward continue with the current publish.
With ROS-m,n, or o we could eventually remove the publish then.

**Comment by rhaschke** [comment]
+1

**Comment by andreaskoepf** [comment]
+1, we at Xamla had trouble with the asynchronous (unreliable) nature of this too. @v4hn, @rhaschke  Does someone of you want to work on this during WMD? Otherwise I could review the code and the proposed solution over the weekend  to fix this on Tuesday.

**Comment by v4hn** [comment]
On Sat, Aug 20, 2016 at 03:36:22AM -0700, Andreas Köpf wrote:
> +1, we at Xamla had trouble with the asynchronous (unreliable) nature of this too.
> @v4hn, @rhaschke  Does someone of you want to work on this during WMD?
> Otherwise I could review the code and the proposed solution over the weekend to fix this on Tuesday.

I will be with you on WMD, so we can discuss things there and I can try to advise you.

As for all `simple enhancement` tickets, just add a note saying you will work on it.

**Comment by v4hn** [comment]
@andreaskoepf do you claim this issue for tomorrow?

**Comment by andreaskoepf** [comment]
@v4hn Yes, let's discuss this later. Would be happy to work on this.

**Comment by v4hn** [comment]
This has been merged upstream in the meanwhile.
