### ISSUE TITLE
Move existing IK tests

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#4]
@jrgnicho did a great job of [creating KinematicsBase tests](https://github.com/ros-planning/moveit_kinematics_tests), but they have not been integrated into the main MoveIt! project and they are not run by travis. We would like to pull this whole repo into the main moveit codebase and have them triggered by travis/catkin every time

Things to consider:
- Do we need to import both robots or can we base them on the PR2 or [Fanuc](https://github.com/ros-planning/moveit_ros/pull/729#issuecomment-236131127) robots?
- The URDFs should probably be moved to moveit_resources
- How long do the tests take and how much output?
- What is the overlap between these tests and the IK tests the PR2 already has in moveit?

**Comment by jrgnicho** [comment]
@davetcoleman 
 - There's already tests for the PR2 so no changes should be required there.  Adding a new robot into the unit testing would involve creating the ikfast solver for it and a moveit config package.  All of that is certainly doable  
 - In addition to the URDFs we'd also need to move the moveit_config packages into moveit_resources
 - All tests run in about 20s and the output is roughly 70 lines.
 - The tests program was inspired by the [pr2 test](https://github.com/ros-planning/moveit_pr2/blob/indigo-devel/pr2_moveit_tests/kinematics/src/test_kinematics_as_plugin.cpp) so there's definitely an overlap.

**Comment by davetcoleman** [comment]
> Adding a new robot into the unit testing would involve creating the ikfast solver for it and a moveit config package

I thought your tests already work, essentially. They just need to be moved...

**Comment by jrgnicho** [comment]
@davetcoleman yes, if you were to just move that whole repo it should just work.

**Comment by davetcoleman** [comment]
So do you think its a good idea to add this to our standard test coverage?

Post-repo merge I think we should make a pull request to review and add this. The tests themselves should probably go into either moveit_core, moveit_ros, or moveit_ikfast

**Comment by v4hn** [comment]
@jrgnicho ping. What's the state here?

**Comment by jrgnicho** [comment]
@v4hn sorry this fell off my radar.
I'll create the PR for this.

**Comment by 130s** [comment]
Coincidentally I've started working on this (since it's so useful. Thanks @jrgnicho!) and opened https://github.com/ros-planning/moveit_kinematics_tests/pull/7 yesterday.

**Comment by davetcoleman** [comment]
+1 to actually moving the whole repo here

**Comment by davetcoleman** [comment]
Seems @rhaschke is cleaning this up here: https://github.com/ros-planning/moveit/pull/1272

**Comment by jrgnicho** [comment]
Yes this can be closed as #1272 replaces it

**Comment by rhaschke** [comment]
Closing via #1272.
