### ISSUE TITLE
error: conflicting declaration  moveit indigo  

### ISSUE THREAD

**Issue by Chunting** [ros-planning/moveit#446]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: [Indigo]
* OS Version: e.g. Ubuntu 14.04
* Source:  https://github.com/ros-planning/moveit.git

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.
After download the moveit project, I run catkin_make | grep error,
but it failed, the error message is showed as below, do I need to rename the typedef variables?

> In file included from /opt/ros/indigo/include/geometric_shapes/bodies.h:40:0,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/distance_field/include/moveit/distance_field/find_internal_points.h:41,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/distance_field/src/distance_field.cpp:38:
> /opt/ros/indigo/include/geometric_shapes/shapes.h:268:34: error: conflicting declaration ‘typedef class boost::shared_ptr<shapes::Shape> shapes::ShapePtr’
>  typedef boost::shared_ptr<Shape> ShapePtr;
>                                   ^
> In file included from /home/chunting/catkin_ws/src/moveit/moveit_core/macros/include/moveit/macros/class_forward.h:40:0,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/distance_field/include/moveit/distance_field/distance_field.h:40,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/distance_field/src/distance_field.cpp:37:
> /home/chunting/catkin_ws/src/moveit/moveit_core/distance_field/include/moveit/distance_field/distance_field.h:54:22: error: ‘shapes::ShapePtr’ has a previous declaration as ‘typedef class std::shared_ptr<shapes::Shape> shapes::ShapePtr’
>  MOVEIT_CLASS_FORWARD(Shape);
>                       ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/macros/include/moveit/macros/declare_ptr.h:52:33: note: in definition of macro ‘MOVEIT_DECLARE_PTR’
>    typedef std::shared_ptr<Type> Name##Ptr;                                                                             \
>                                  ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/distance_field/include/moveit/distance_field/distance_field.h:54:1: note: in expansion of macro ‘MOVEIT_CLASS_FORWARD’
>  MOVEIT_CLASS_FORWARD(Shape);
>  ^
> In file included from /opt/ros/indigo/include/geometric_shapes/bodies.h:40:0,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/distance_field/include/moveit/distance_field/find_internal_points.h:41,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/distance_field/src/distance_field.cpp:38:
> /opt/ros/indigo/include/geometric_shapes/shapes.h:271:40: error: conflicting declaration ‘typedef class boost::shared_ptr<const shapes::Shape> shapes::ShapeConstPtr’
>  typedef boost::shared_ptr<const Shape> ShapeConstPtr;
>                                         ^
> In file included from /home/chunting/catkin_ws/src/moveit/moveit_core/macros/include/moveit/macros/class_forward.h:40:0,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/distance_field/include/moveit/distance_field/distance_field.h:40,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/distance_field/src/distance_field.cpp:37:
> /home/chunting/catkin_ws/src/moveit/moveit_core/distance_field/include/moveit/distance_field/distance_field.h:54:22: error: ‘shapes::ShapeConstPtr’ has a previous declaration as ‘typedef class std::shared_ptr<const shapes::Shape> shapes::ShapeConstPtr’
>  MOVEIT_CLASS_FORWARD(Shape);
>                       ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/macros/include/moveit/macros/declare_ptr.h:53:39: note: in definition of macro ‘MOVEIT_DECLARE_PTR’
>    typedef std::shared_ptr<const Type> Name##ConstPtr;
>                                        ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/distance_field/include/moveit/distance_field/distance_field.h:54:1: note: in expansion of macro ‘MOVEIT_CLASS_FORWARD’
>  MOVEIT_CLASS_FORWARD(Shape);
>  ^
> In file included from /opt/ros/indigo/include/geometric_shapes/shape_operations.h:40:0,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/link_model.cpp:39:
> /opt/ros/indigo/include/geometric_shapes/shapes.h:268:34: error: conflicting declaration ‘typedef class boost::shared_ptr<shapes::Shape> shapes::ShapePtr’
>  typedef boost::shared_ptr<Shape> ShapePtr;
>                                   ^
> In file included from /home/chunting/catkin_ws/src/moveit/moveit_core/macros/include/moveit/macros/class_forward.h:40:0,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/link_model.h:46,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/link_model.cpp:37:
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/link_model.h:50:22: error: ‘shapes::ShapePtr’ has a previous declaration as ‘typedef class std::shared_ptr<shapes::Shape> shapes::ShapePtr’
>  MOVEIT_CLASS_FORWARD(Shape);
>                       ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/macros/include/moveit/macros/declare_ptr.h:52:33: note: in definition of macro ‘MOVEIT_DECLARE_PTR’
>    typedef std::shared_ptr<Type> Name##Ptr;                                                                             \
>                                  ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/link_model.h:50:1: note: in expansion of macro ‘MOVEIT_CLASS_FORWARD’
>  MOVEIT_CLASS_FORWARD(Shape);
>  ^
> In file included from /opt/ros/indigo/include/geometric_shapes/shape_operations.h:40:0,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/link_model.cpp:39:
> /opt/ros/indigo/include/geometric_shapes/shapes.h:271:40: error: conflicting declaration ‘typedef class boost::shared_ptr<const shapes::Shape> shapes::ShapeConstPtr’
>  typedef boost::shared_ptr<const Shape> ShapeConstPtr;
>                                         ^
> In file included from /home/chunting/catkin_ws/src/moveit/moveit_core/macros/include/moveit/macros/class_forward.h:40:0,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/link_model.h:46,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/link_model.cpp:37:
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/link_model.h:50:22: error: ‘shapes::ShapeConstPtr’ has a previous declaration as ‘typedef class std::shared_ptr<const shapes::Shape> shapes::ShapeConstPtr’
>  MOVEIT_CLASS_FORWARD(Shape);
>                       ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/macros/include/moveit/macros/declare_ptr.h:53:39: note: in definition of macro ‘MOVEIT_DECLARE_PTR’
>    typedef std::shared_ptr<const Type> Name##ConstPtr;
>                                        ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/link_model.h:50:1: note: in expansion of macro ‘MOVEIT_CLASS_FORWARD’
>  MOVEIT_CLASS_FORWARD(Shape);
>  ^
> make[2]: *** [moveit/moveit_core/distance_field/CMakeFiles/moveit_distance_field.dir/src/distance_field.cpp.o] Error 1
> make[1]: *** [moveit/moveit_core/distance_field/CMakeFiles/moveit_distance_field.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> make[2]: *** [moveit/moveit_core/robot_model/CMakeFiles/moveit_robot_model.dir/src/link_model.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> In file included from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:38:0:
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/robot_model.h:72:20: error: ‘ModelInterfaceSharedPtr’ in namespace ‘urdf’ does not name a type
>    RobotModel(const urdf::ModelInterfaceSharedPtr& urdf_model, const srdf::ModelConstSharedPtr& srdf_model);
>                     ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/robot_model.h:72:51: error: ISO C++ forbids declaration of ‘urdf_model’ with no type [-fpermissive]
>    RobotModel(const urdf::ModelInterfaceSharedPtr& urdf_model, const srdf::ModelConstSharedPtr& srdf_model);
>                                                    ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/robot_model.h:99:9: error: ‘ModelInterfaceSharedPtr’ in namespace ‘urdf’ does not name a type
>    const urdf::ModelInterfaceSharedPtr& getURDF() const
>          ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/robot_model.h:446:3: error: ‘ModelInterfaceSharedPtr’ in namespace ‘urdf’ does not name a type
>    urdf::ModelInterfaceSharedPtr urdf_;
>    ^
> In file included from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/joint_model_group.cpp:38:0:
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/robot_model.h:72:20: error: ‘ModelInterfaceSharedPtr’ in namespace ‘urdf’ does not name a type
>    RobotModel(const urdf::ModelInterfaceSharedPtr& urdf_model, const srdf::ModelConstSharedPtr& srdf_model);
>                     ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/robot_model.h:72:51: error: ISO C++ forbids declaration of ‘urdf_model’ with no type [-fpermissive]
>    RobotModel(const urdf::ModelInterfaceSharedPtr& urdf_model, const srdf::ModelConstSharedPtr& srdf_model);
>                                                    ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/robot_model.h:99:9: error: ‘ModelInterfaceSharedPtr’ in namespace ‘urdf’ does not name a type
>    const urdf::ModelInterfaceSharedPtr& getURDF() const
>          ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/robot_model.h:446:3: error: ‘ModelInterfaceSharedPtr’ in namespace ‘urdf’ does not name a type
>    urdf::ModelInterfaceSharedPtr urdf_;
>    ^
> In file included from /opt/ros/indigo/include/geometric_shapes/shape_operations.h:40:0,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:39:
> /opt/ros/indigo/include/geometric_shapes/shapes.h:268:34: error: conflicting declaration ‘typedef class boost::shared_ptr<shapes::Shape> shapes::ShapePtr’
>  typedef boost::shared_ptr<Shape> ShapePtr;
>                                   ^
> In file included from /home/chunting/catkin_ws/src/moveit/moveit_core/macros/include/moveit/macros/class_forward.h:40:0,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/robot_model.h:41,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:38:
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/link_model.h:50:22: error: ‘shapes::ShapePtr’ has a previous declaration as ‘typedef class std::shared_ptr<shapes::Shape> shapes::ShapePtr’
>  MOVEIT_CLASS_FORWARD(Shape);
>                       ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/macros/include/moveit/macros/declare_ptr.h:52:33: note: in definition of macro ‘MOVEIT_DECLARE_PTR’
>    typedef std::shared_ptr<Type> Name##Ptr;                                                                             \
>                                  ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/link_model.h:50:1: note: in expansion of macro ‘MOVEIT_CLASS_FORWARD’
>  MOVEIT_CLASS_FORWARD(Shape);
>  ^
> In file included from /opt/ros/indigo/include/geometric_shapes/shape_operations.h:40:0,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:39:
> /opt/ros/indigo/include/geometric_shapes/shapes.h:271:40: error: conflicting declaration ‘typedef class boost::shared_ptr<const shapes::Shape> shapes::ShapeConstPtr’
>  typedef boost::shared_ptr<const Shape> ShapeConstPtr;
>                                         ^
> In file included from /home/chunting/catkin_ws/src/moveit/moveit_core/macros/include/moveit/macros/class_forward.h:40:0,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/robot_model.h:41,
>                  from /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:38:
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/link_model.h:50:22: error: ‘shapes::ShapeConstPtr’ has a previous declaration as ‘typedef class std::shared_ptr<const shapes::Shape> shapes::ShapeConstPtr’
>  MOVEIT_CLASS_FORWARD(Shape);
>                       ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/macros/include/moveit/macros/declare_ptr.h:53:39: note: in definition of macro ‘MOVEIT_DECLARE_PTR’
>    typedef std::shared_ptr<const Type> Name##ConstPtr;
>                                        ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/include/moveit/robot_model/link_model.h:50:1: note: in expansion of macro ‘MOVEIT_CLASS_FORWARD’
>  MOVEIT_CLASS_FORWARD(Shape);
>  ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:51:44: error: ‘ModelInterfaceSharedPtr’ in namespace ‘urdf’ does not name a type
>  moveit::core::RobotModel::RobotModel(const urdf::ModelInterfaceSharedPtr& urdf_model,
>                                             ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:51:75: error: ISO C++ forbids declaration of ‘urdf_model’ with no type [-fpermissive]
>  moveit::core::RobotModel::RobotModel(const urdf::ModelInterfaceSharedPtr& urdf_model,
>                                                                            ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp: In constructor ‘moveit::core::RobotModel::RobotModel(const int&, const ModelConstSharedPtr&)’:
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:55:3: error: ‘urdf_’ was not declared in this scope
>    urdf_ = urdf_model;
>    ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:57:15: error: invalid type argument of unary ‘*’ (have ‘int’)
>    buildModel(*urdf_model, *srdf_model);
>                ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp: In member function ‘moveit::core::LinkModel* moveit::core::RobotModel::constructLinkModel(const urdf::Link*)’:
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:969:21: error: ‘CollisionSharedPtr’ is not a member of ‘urdf’
>    const std::vector<urdf::CollisionSharedPtr>& col_array =
>                      ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:969:21: error: ‘CollisionSharedPtr’ is not a member of ‘urdf’
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:969:45: error: template argument 1 is invalid
>    const std::vector<urdf::CollisionSharedPtr>& col_array =
>                                              ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:969:45: error: template argument 2 is invalid
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:969:58: error: invalid type in declaration before ‘=’ token
>    const std::vector<urdf::CollisionSharedPtr>& col_array =
>                                                           ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:970:56: error: ‘CollisionSharedPtr’ is not a member of ‘urdf’
>        urdf_link->collision_array.empty() ? std::vector<urdf::CollisionSharedPtr>(1, urdf_link->collision) :
>                                                         ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:970:56: error: ‘CollisionSharedPtr’ is not a member of ‘urdf’
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:970:80: error: template argument 1 is invalid
>        urdf_link->collision_array.empty() ? std::vector<urdf::CollisionSharedPtr>(1, urdf_link->collision) :
>                                                                                 ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:970:80: error: template argument 2 is invalid
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:976:41: error: request for member ‘size’ in ‘col_array’, which is of non-class type ‘const int’
>    for (std::size_t i = 0; i < col_array.size(); ++i)
>                                          ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:977:20: error: invalid types ‘const int[std::size_t {aka long unsigned int}]’ for array subscript
>      if (col_array[i] && col_array[i]->geometry)
>                     ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:977:36: error: invalid types ‘const int[std::size_t {aka long unsigned int}]’ for array subscript
>      if (col_array[i] && col_array[i]->geometry)
>                                     ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:979:59: error: invalid types ‘const int[std::size_t {aka long unsigned int}]’ for array subscript
>        shapes::ShapeConstPtr s = constructShape(col_array[i]->geometry.get());
>                                                            ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:983:54: error: invalid types ‘const int[std::size_t {aka long unsigned int}]’ for array subscript
>          poses.push_back(urdfPose2Affine3d(col_array[i]->origin));
>                                                       ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:988:23: error: ‘VisualSharedPtr’ is not a member of ‘urdf’
>      const std::vector<urdf::VisualSharedPtr>& vis_array = urdf_link->visual_array.empty() ?
>                        ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:988:23: error: ‘VisualSharedPtr’ is not a member of ‘urdf’
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:988:44: error: template argument 1 is invalid
>      const std::vector<urdf::VisualSharedPtr>& vis_array = urdf_link->visual_array.empty() ?
>                                             ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:988:44: error: template argument 2 is invalid
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:988:57: error: invalid type in declaration before ‘=’ token
>      const std::vector<urdf::VisualSharedPtr>& vis_array = urdf_link->visual_array.empty() ?
>                                                          ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:989:75: error: ‘VisualSharedPtr’ is not a member of ‘urdf’
>                                                                std::vector<urdf::VisualSharedPtr>(1, urdf_link->visual) :
>                                                                            ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:989:75: error: ‘VisualSharedPtr’ is not a member of ‘urdf’
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:989:96: error: template argument 1 is invalid
>                                                                std::vector<urdf::VisualSharedPtr>(1, urdf_link->visual) :
>                                                                                                 ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:989:96: error: template argument 2 is invalid
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:991:43: error: request for member ‘size’ in ‘vis_array’, which is of non-class type ‘const int’
>      for (std::size_t i = 0; i < vis_array.size(); ++i)
>                                            ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:992:22: error: invalid types ‘const int[std::size_t {aka long unsigned int}]’ for array subscript
>        if (vis_array[i] && vis_array[i]->geometry)
>                       ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:992:38: error: invalid types ‘const int[std::size_t {aka long unsigned int}]’ for array subscript
>        if (vis_array[i] && vis_array[i]->geometry)
>                                       ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:994:61: error: invalid types ‘const int[std::size_t {aka long unsigned int}]’ for array subscript
>          shapes::ShapeConstPtr s = constructShape(vis_array[i]->geometry.get());
>                                                              ^
> /home/chunting/catkin_ws/src/moveit/moveit_core/robot_model/src/robot_model.cpp:998:56: error: invalid types ‘const int[std::size_t {aka long unsigned int}]’ for array subscript
>            poses.push_back(urdfPose2Affine3d(vis_array[i]->origin));
>                                                         ^
> make[2]: *** [moveit/moveit_core/robot_model/CMakeFiles/moveit_robot_model.dir/src/joint_model_group.cpp.o] Error 1
> make[2]: *** [moveit/moveit_core/robot_model/CMakeFiles/moveit_robot_model.dir/src/robot_model.cpp.o] Error 1
> make[1]: *** [moveit/moveit_core/robot_model/CMakeFiles/moveit_robot_model.dir/all] Error 2
> make: *** [all] Error 2
> Invoking "make -j8 -l8" failed

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by v4hn** [comment]
You tried to build the `kinetic-devel` branch of the repository.
This is possible if you also recompile some other repos, but you probably just want to compile the `indigo-devel` branch instead.
