### ISSUE TITLE
Release (Kinetic 0.9.5 and IJ altogether)

### ISSUE THREAD

**Issue by 130s** [ros-planning/moveit#457]
https://github.com/ros-planning/moveit/issues/86 is a regression that makes hard to use Kinetic and now it's fixed already. I'd like to make a quick patch release. Let me know by 6th Monday if there's any objections.

TODO:
- [x] Indigo https://github.com/ros-planning/moveit/pull/452
- [x] Kinetic https://github.com/ros-planning/moveit/pull/466
- [x] ABI check by @v4hn https://github.com/ros-planning/moveit/issues/457#issuecomment-284162045
- [ ] Release Kinetic
- [ ] Release Indigo.
- [ ] Release Jade.

**Comment by v4hn** [comment]
Currently, we have a regression in the rviz display that #452 should fix.
With current head, the visualization of the planning scene will disappear when you hide the panel (e.g. hide the docking bar which contains the panel).

Please do not release without a fix for this.

**Comment by 130s** [comment]
Ok. 

I also want to make releases for IJ at the same time, simply because that makes the release job way easier. So, please list up any TODOs for IJ too.

**Comment by v4hn** [comment]
On Sat, Mar 04, 2017 at 11:05:17AM -0800, Isaac I.Y. Saito wrote:
> I also want to make releases for IJ at the same time,
> simply because that makes the release job way easier.
> So, please list up any TODOs for IJ too.

In this case please give me one more day to do abi checks.
I can only run them at work, and I don't plan to go there on Sunday :)

**Comment by v4hn** [comment]
Ok, apart from #452, you got green light from my perspective.

**Comment by 130s** [comment]
So for this quick patch release, do we just increment the patch/micro version for each distro (Unfortunately I missed the relevant part of the maintainer's meeting today)?

**Comment by v4hn** [comment]
patch release -> patch version :)

With indigo and jade, we pretty much agreed not to bump anything but the patch version number.

**Comment by 130s** [comment]
K https://github.com/ros/rosdistro/pull/14135
J https://github.com/ros/rosdistro/pull/14132
I https://github.com/ros/rosdistro/pull/14133

Patch version incremented per each distro.
