### ISSUE TITLE
No kinematic solvers

### ISSUE THREAD

**Issue by BasB1** [ros-planning/moveit#481]
### Description

Good day,

I want to implement moveit! on the Kuka Youbot.
To create the package configuration i used the setup assistant.
In the planning groups i cannot select any kind of kinematic solver.
The drop down just says "none".

I tried to make a package on an other PC with the solvers and copied it to the youbots PC.
When i run the trajectory execution it gives a error that it cannot find the specified kinematic solver.

I tried googling this problem, reinstalled moveit through source, git clone etc. but i feel like i'm out of options.

### Your environment
* ROS Distro: indigo
* OS Version: Ubuntu 14.04
* Source/binary, tried them all

### Steps to reproduce
I cant tell you how to reproduce the problem. ROS might be the problem?

### Expected behaviour
I can chose the kinematic solver.

### Actual behaviour
I can not chose the kinematic solver.
Just the option "none".

### Backtrace or Console output
n/a

**Comment by v4hn** [comment]
make sure you have the `ros-indigo-moveit-kinematics` and the `ros-indigo-track-ik` packages installed on your system.
The assistant only lists plugins that are installed.

**Comment by BasB1** [comment]
Thank you. That did it.

**Comment by davetcoleman** [comment]
This will help future users with this problem: https://github.com/ros-planning/moveit/pull/485
