### ISSUE TITLE
[Ubuntu Zesty] Build failure around Boost

### ISSUE THREAD

**Issue by 130s** [ros-planning/moveit#504]
Please see the error message at https://github.com/ros-planning/moveit/issues/486#issuecomment-300911832

This blocks MoveIt! release into ROS Lunar https://github.com/ros-planning/moveit/issues/486

I'm not sure if similar error occurs on other platforms, but due to the [higher version of `boost`](
http://www.ros.org/reps/rep-0003.html#lunar-loggerhead-may-2017-may-2019) than the one in Xenial, it'd be worth checking Ubuntu `Yakkety`, Debian `Stretch` too (I can run prerelease test on Yakkety soon to see if any issues rise).

If someone can take a look that'll be appreciated. Just let us know by adding a comment then.

**Comment by mikaelarguedas** [comment]
I would guess the same issue will appear on Stretch (given that it ships with the same version of boost as Zesty).
The issue doesnt seem to appear on Yakkety. But the build fails on another package for an unrelated reason IMO: moveit_setup_assistant.

There is a gist [here](https://gist.github.com/mikaelarguedas/7731b4100e7ed78b6aab73f052ffac79) with the prerelease console outputs for Yakkety and Zesty for anyone wanting to investigate the failures

**Comment by mikaelarguedas** [comment]
@130s is it possible to make a new release with the fix from https://github.com/ros-planning/moveit/issues/505 so that every moveit package can be released except MSA ?
Thanks!
