### ISSUE TITLE
Cleanup Code API page

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#51]
http://moveit.ros.org/code-api/

- Switch links to jade or kinetic (if available)
- Add missing links that could be helpful to users
- Remove hydro section

**Comment by dbolkensteyn** [comment]
I'll remove hydro and add jade and kinetic instead.

**Comment by dbolkensteyn** [comment]
https://github.com/ros-planning/moveit.ros.org/pull/44

**Comment by davetcoleman** [comment]
thanks!
