### ISSUE TITLE
Migrate docker to main repo

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#52]
Steps to complete migration:

- [x] merge first PR
- [x] Setup on dockerhub and verify it works: https://hub.docker.com/r/moveit/moveit/builds/
- [x] cherry-pick this to I/J with the keyword "kinetic" replaced.
- [x] Add documentation on moveit website
- [x] Switch moveit_ci to use this docker image
- [x] Document that moveit_docker is deprecated

**Comment by davetcoleman** [comment]
@v4hn if you or any other maintainers are interested, I would like to share the ``moveit`` account on dockerhub with others besides myself, so that I'm not the only one with access. To do this you'll need to create an account on dockerhub.com and tell me your username (hopefully the same as github)

**Comment by v4hn** [comment]
On Tue, Aug 16, 2016 at 12:13:17PM -0700, Dave Coleman wrote:
> @v4hn if you or any other maintainers are interested, I would like to share the ``moveit`` account on dockerhub with others besides myself, so that I'm not the only one with access. To do this you'll need to create an account on dockerhub.com and tell me your username (hopefully the same as github)

I'm not interested as I don't use docker. I feel it brings about bad habits.
But yes, a bus factor >1 should be ensured, so it would be great if someone else could step up.

**Comment by davetcoleman** [comment]
@130s ?

**Comment by davetcoleman** [comment]
@rhaschke actually gave the the idea to use docker for testing and maintaining moveit - I know he uses them

**Comment by rhaschke** [comment]
> @rhaschke actually gave the the idea to use docker for testing and maintaining moveit - I know he uses them

That was a misunderstanding, actually ;-)
However, I like the idea of docker in principle. But I'm not really acquainted to it yet.
I just created a dockerhub account, named `rhaschke`.

**Comment by davetcoleman** [comment]
@rhaschke has been added. I also forgot but @ruffsl is an owner of the dockerhub team as well, since he made the OSRF images that moveit's builds on top of.

**Comment by davetcoleman** [comment]
I just finished fully migrating our docker containers to the consolidated moveit repo
