### ISSUE TITLE
Display RobotState crashed rviz

### ISSUE THREAD

**Issue by cuixiongyi** [ros-planning/moveit#528]
## Description
When add moveit_ros_visualization-RobotState, if there a link without visual element in URDF, rviz will crash.
When I added the visual element, it worked find and displayed the robot.

**Example link URDF without visual, will crash:**
```
<link
    name="robot_tip">
    <inertial>
      <origin
        xyz="0 0.0 0.0"
        rpy="0 0 0" />
      <mass
        value="0.0" />
      <inertia
        ixx="0.0"
        ixy="0.0"
        ixz="0.0"
        iyy="0.0"
        iyz="0.0"
        izz="0.0" />
    </inertial>
   </link>

```
**Example link URDF with visual, will not crash:**
```
<link
    name="robot_tip">
    <inertial>
      <origin
        xyz="0 0.0 0.0"
        rpy="0 0 0" />
      <mass
        value="0.0" />
      <inertia
        ixx="0.0"
        ixy="0.0"
        ixz="0.0"
        iyy="0.0"
        iyz="0.0"
        izz="0.0" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://kuka_robot_kr6_r1620/meshes/Robot_L6.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
  </link>
```

Overview of your issue here.

### Your environment
* ROS Distro: [Indigo]
* OS Version: e.g. Ubuntu 14.04 64bit
* Binary build
* If binary, which release version?
  dpkg version of ros-indigo-moveit-ros-visualization        0.7.9-0trusty-20170517-195545-0800

### Steps to reproduce
remove any visual element of a robot URDF
Then launch its moveit_config

   `roslaunch robot_moveit_config demo.launch`
Then open a new rviz

`rosrun rviz rviz`

Add moveit_ros_visualization-RobotState
It will crash (Segmentation fault (core dumped))

### Expected behaviour
It should display the robot in rviz

### Actual behaviour
rviz crashed, Segmentation fault (core dumped)

### Backtrace or Console output
Segmentation fault (core dumped)

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by v4hn** [comment]
You are right, I can reproduce this on 14.04 with the current ros-indigo branch.
Crap :/

Apparently aac7921666821fa7b38c0228b390dbc8d133d833 is the faulty commit, reverting it fixes the error.
However, the crash is not directly related to the code there but occurs somewhere inside qt/rviz' event system.
I'll have a look.

**Comment by v4hn** [comment]
@cuixiongyi could you checkout #530 and verify that it solves the problem?

**Comment by cuixiongyi** [comment]
Yes, I tried your branch. It won't crash any more. 
Thank you for responding. You are amazingly fast.
Yeah, rviz isn't the most stable software. Sometimes it will crash upon open.

**Comment by v4hn** [comment]
On Fri, Jun 16, 2017 at 02:00:19PM -0700, Xiongyi Cui wrote:
> Yes, I tried your branch. It won't crash any more.
> Thank you for responding. You are amazingly fast.

In this case I'm actually the one responsible for the bug (for a change...)
and knew what to look for. Don't count on it on other occasions. :)

@130s I suppose we want to have this fixed with the next sync, if that's possible...

**Comment by 130s** [comment]
> @130s I suppose we want to have this fixed with the next sync, if that's possible...

Yeah, critical bug fixes should be prioritized. Started tracking at #533.
