### ISSUE TITLE
Release 201706

### ISSUE THREAD

**Issue by 130s** [ros-planning/moveit#533]
There is/are some bug fixes that seem (kind of) critical:
- [x] https://github.com/ros-planning/moveit/issues/528

[Next Indigo sync may happen soon, sometime within June](https://github.com/ros-planning/moveit/issues/528#issuecomment-309140751), so if there's no other requests I'll make a new release early in the week of 18th for IKL.

**Comment by 130s** [comment]
I think the minimum required for this patch release is #528 and that is already merged. If there are any other changes that anyone wants to include in the next sync, please let us know here ASAP. Otherwise I'll  make a quick release on Tuesday Pacific.

FYI I see more than 5 PRs that look green on Travis.

**Comment by v4hn** [comment]
> FYI I see more than 5 PRs that look green on Travis.

@davetcoleman and I just merged many of them - there are still more than 5 green ones, but
most of them required further investigations before a merge.

Go ahead with a release 👍

**Comment by 130s** [comment]
I https://github.com/ros/rosdistro/pull/15325
K https://github.com/ros/rosdistro/pull/15326#thread-subscription-status
L https://github.com/ros/rosdistro/pull/15327

Thanks every one esp. @v4hn @davetcoleman
