### ISSUE TITLE
moveit_commander fails in Indigo 

### ISSUE THREAD

**Issue by cschindlbeck** [ros-planning/moveit#559]
Hi,

 i tried to run:
"import moveit_commander"

but got this error

```
Traceback (most recent call last):
  File "/home/makromikro/catkin_ws/src/agilus/scripts/test.py", line 8, in <module>
    import moveit_commander
  File "/home/makromikro/catkin_ws/devel/lib/python2.7/dist-packages/moveit_commander/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 3, in <module>
  File "/home/makromikro/catkin_ws/src/moveit/moveit_commander/src/moveit_commander/planning_scene_interface.py", line 48, in <module>
    import pyassimp
  File "/usr/lib/python2.7/dist-packages/pyassimp/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/lib/python2.7/dist-packages/pyassimp/core.py", line 23, in <module>
    from . import structs
ImportError: cannot import name structs

```
Im running ros indigo on 14.04
i also tried reinstall pyassimp but it doesn't help.

can somebody please help me?

**Comment by v4hn** [comment]
On Mon, Jul 24, 2017 at 08:44:22AM -0700, Christopher Schindlbeck wrote:
>   File "/usr/lib/python2.7/dist-packages/pyassimp/core.py", line 23, in <module>
>     from . import structs
> ImportError: cannot import name structs

`pip uninstall pyassimp; pip install pyassimp` - although that will confuse your ubuntu package manager.

I know this is a rather stupid question, but are you positive this is not on 16.04?
This error is well-known in 16.04 because Ubuntu packaged an entirely broken version of `pyassimp`.
I haven't seen it on 14.04 so far.

**Comment by cschindlbeck** [comment]
Yeah this is 14.04 

`lsb_release -a`
`No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
`

The pip install did not work for me :

`Requirement already satisfied (use --upgrade to upgrade): pyassimp in /usr/local/lib/python2.7/dist-packages
Cleaning up...`

Is it possible that the error comes from installing pyassimp via apt-get install libassimp ? 

Could this be a rights problem? For example, libassimp.so has only read rights for the user

**Comment by v4hn** [comment]
The idea of the `pip` command was to remove the version installed by `apt` and instead
install the latest version available through `pip`. I wrote the exact command line off the top of my head,
so maybe you have to lookup the exact command to do that yourself.

Sorry, I've never heard of this problem on 14.04 until now, so hopefully this is specific to your setup...
We can't really help you there.

**Comment by cschindlbeck** [comment]
Removed the error by installing assimp over pip and more importantly, deleting pyassimp from /usr/lib/python2.7/dist-packages
