### ISSUE TITLE
[indigo] ikfast plugin fails to compile with c++11 enabled

### ISSUE THREAD

**Issue by hartmanndennis** [ros-planning/moveit#584]
#515 was cherry-picked to indigo but did someone test this on indigo? As far as I can see there are no tests for this and the template is never compiled so Travis doesn't fail.
Using c++11 fails for me on indigo with all updated 14.04 packages (with the indigo-release docker image as well) because of ambiguous isnan calls in the ikfast solver source. This is because of [this bug](https://sourceware.org/bugzilla/show_bug.cgi?id=19439) which is fixed in later libc versions but not in the one used in 14.04.
So I think this should be reverted in indigo and this would also prevent #575 because #537 added C++11 features.

**Comment by gavanderhoorn** [comment]
I think we could also resolve the ambiguous `isnan(..)` calls (like was done in https://github.com/ros-industrial/motoman_experimental/commit/2981de24185b196fc3a345a96f273aba6fe85e38).

The template could be updated, and that should work on Indigo as well.

---

This was one of the reasons why I hesitated in #515 to cherry-pick this to Indigo.

**Comment by hartmanndennis** [comment]
The template script would probably need to change all isnan calls to std::isnan like in your example. A simple `#undef isnan` sadly doesn't work.

**Comment by gavanderhoorn** [comment]
`<ugly>`Could we not `#define isnan std::isnan` right before the `#include "_ROBOT_NAME___GROUP_NAME__ikfast_solver.cpp"`?`</ugly>`

**Comment by hartmanndennis** [comment]
That could work. It does compile with this hack.

**Comment by gavanderhoorn** [comment]
I've added some comments to your PR.

Thanks for reporting and submitting btw 👍

**Comment by v4hn** [comment]
> As far as I can see there are no tests for this and the template is never compiled so Travis doesn't fail.

A test for this is very much welcome!

Thanks a lot for your work here. 👍

**Comment by v4hn** [comment]
closing in favor of #619
