### ISSUE TITLE
stack smash while planning with a collision object in the planning scene

### ISSUE THREAD

**Issue by dh562231640** [ros-planning/moveit#588]
### Description

stack smashing detected, and move-group will died with exit code -6 It happens when add a collision object in the planning scene and try to plan with this collision object in the planning scene. And log file can not be found by the path it gives to me

### Your environment
* ROS Distro: Kinetic
* OS Version: e.g. Ubuntu 16.04
* Binary build verision 0.9.8-0xenial-20170628-083013-0800

### Steps to reproduce
add a collision object to a planning scene and drag the end effector on the object (crash it), then the rviz will died. or set some way points which has collision with the object and use move_group.CartecomputesianPath() and then move group will died.

### Expected behaviour
I think it should avoid such shutdown for move-group and rviz, It should raise error and fail planning.

### Actual behaviour
move-group or rviz shutdown

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by v4hn** [comment]
I can't reproduce this with my setup.

Please provide more details. Do you observe this with a local source-build too?

**Comment by dh562231640** [comment]
@v4hn Thanks for the advice! I am trying to use source build one only to met a catkin_make error:

moveit/moveit_core/collision_detection_fcl/CMakeFiles/moveit_collision_detection_fcl.dir/build.make:110: recipe for target 'moveit/moveit_core/collision_detection_fcl/CMakeFiles/moveit_collision_detection_fcl.dir/src/collision_world_fcl.cpp.o' failed
make[2]: *** [moveit/moveit_core/collision_detection_fcl/CMakeFiles/moveit_collision_detection_fcl.dir/src/collision_world_fcl.cpp.o] Error 1
CMakeFiles/Makefile2:15921: recipe for target 'moveit/moveit_core/collision_detection_fcl/CMakeFiles/moveit_collision_detection_fcl.dir/all' failed
make[1]: *** [moveit/moveit_core/collision_detection_fcl/CMakeFiles/moveit_collision_detection_fcl.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Do you know why this happens and how to get through this?

**Comment by gavanderhoorn** [comment]
Please include more of the console output.

The part that you show here does not include the actual error, just the bit that says "something went wrong".

**Comment by dh562231640** [comment]
Thank you for the quick reply but the outcome is really too much as I can only copy part of it:

/usr/include/fcl/traversal/traversal_node_octree.h:93:29: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   void OcTreeDistance(const OcTree* tree1, const OcTree* tree2,
                             ^
/usr/include/fcl/traversal/traversal_node_octree.h:93:50: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   void OcTreeDistance(const OcTree* tree1, const OcTree* tree2,
                                                  ^
/usr/include/fcl/traversal/traversal_node_octree.h:108:34: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   void OcTreeMeshIntersect(const OcTree* tree1, const BVHModel<BV>* tree2,
                                  ^
/usr/include/fcl/traversal/traversal_node_octree.h:123:33: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   void OcTreeMeshDistance(const OcTree* tree1, const BVHModel<BV>* tree2,
                                 ^
/usr/include/fcl/traversal/traversal_node_octree.h:138:61: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   void MeshOcTreeIntersect(const BVHModel<BV>* tree1, const OcTree* tree2,
                                                             ^
/usr/include/fcl/traversal/traversal_node_octree.h:154:60: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   void MeshOcTreeDistance(const BVHModel<BV>* tree1, const OcTree* tree2,
                                                            ^
/usr/include/fcl/traversal/traversal_node_octree.h:169:35: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   void OcTreeShapeIntersect(const OcTree* tree, const S& s,
                                   ^
/usr/include/fcl/traversal/traversal_node_octree.h:189:47: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   void ShapeOcTreeIntersect(const S& s, const OcTree* tree,
                                               ^
/usr/include/fcl/traversal/traversal_node_octree.h:208:34: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   void OcTreeShapeDistance(const OcTree* tree, const S& s,
                                  ^
/usr/include/fcl/traversal/traversal_node_octree.h:225:46: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   void ShapeOcTreeDistance(const S& s, const OcTree* tree,
                                              ^
/usr/include/fcl/traversal/traversal_node_octree.h:243:41: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   bool OcTreeShapeDistanceRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                         ^
/usr/include/fcl/traversal/traversal_node_octree.h:243:62: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   bool OcTreeShapeDistanceRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                                              ^
/usr/include/fcl/traversal/traversal_node_octree.h:243:80: error: expected unqualified-id before ‘*’ token
   bool OcTreeShapeDistanceRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                                                                ^
/usr/include/fcl/traversal/traversal_node_octree.h:243:80: error: expected ‘)’ before ‘*’ token
/usr/include/fcl/traversal/traversal_node_octree.h:243:80: error: expected initializer before ‘*’ token
/usr/include/fcl/traversal/traversal_node_octree.h:292:42: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   bool OcTreeShapeIntersectRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                          ^
/usr/include/fcl/traversal/traversal_node_octree.h:292:63: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   bool OcTreeShapeIntersectRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                                               ^
/usr/include/fcl/traversal/traversal_node_octree.h:292:81: error: expected unqualified-id before ‘*’ token
   bool OcTreeShapeIntersectRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                                                                 ^
/usr/include/fcl/traversal/traversal_node_octree.h:292:81: error: expected ‘)’ before ‘*’ token
/usr/include/fcl/traversal/traversal_node_octree.h:292:81: error: expected initializer before ‘*’ token
In file included from /usr/include/fcl/traversal/traversal_node_setup.h:48:0,
                 from /home/dh/catkin_ws/src/moveit/moveit_core/collision_detection_fcl/src/collision_world_fcl.cpp:40:
/usr/include/fcl/traversal/traversal_node_octree.h:445:40: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   bool OcTreeMeshDistanceRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                        ^
/usr/include/fcl/traversal/traversal_node_octree.h:445:61: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   bool OcTreeMeshDistanceRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                                             ^
/usr/include/fcl/traversal/traversal_node_octree.h:445:79: error: expected unqualified-id before ‘*’ token
   bool OcTreeMeshDistanceRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                                                               ^
/usr/include/fcl/traversal/traversal_node_octree.h:445:79: error: expected ‘)’ before ‘*’ token
/usr/include/fcl/traversal/traversal_node_octree.h:445:79: error: expected initializer before ‘*’ token
/usr/include/fcl/traversal/traversal_node_octree.h:532:41: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   bool OcTreeMeshIntersectRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                         ^
/usr/include/fcl/traversal/traversal_node_octree.h:532:62: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   bool OcTreeMeshIntersectRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                                              ^
/usr/include/fcl/traversal/traversal_node_octree.h:532:80: error: expected unqualified-id before ‘*’ token
   bool OcTreeMeshIntersectRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                                                                ^
/usr/include/fcl/traversal/traversal_node_octree.h:532:80: error: expected ‘)’ before ‘*’ token
/usr/include/fcl/traversal/traversal_node_octree.h:532:80: error: expected initializer before ‘*’ token
/usr/include/fcl/traversal/traversal_node_octree.h:720:36: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   bool OcTreeDistanceRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                    ^
/usr/include/fcl/traversal/traversal_node_octree.h:720:57: error: invalid use of template-name ‘fcl::OcTree’ without an argument list
   bool OcTreeDistanceRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                                         ^
/usr/include/fcl/traversal/traversal_node_octree.h:720:75: error: expected unqualified-id before ‘*’ token
   bool OcTreeDistanceRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                                                           ^
/usr/include/fcl/traversal/traversal_node_octree.h:720:75: error: expected ‘)’ before ‘*’ token
/usr/include/fcl/traversal/traversal_node_octree.h:720:65: error: expected ‘;’ at end of member declaration
   bool OcTreeDistanceRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                                                 ^
/usr/include/fcl/traversal/traversal_node_octree.h:720:84: error: expected unqualified-id before ‘const’
   bool OcTreeDistanceRecurse(const OcTree* tree1, const OcTree::OcTreeNode* root1, const AABB& bv1,
                                                                                    ^
/home/dh/catkin_ws/src/moveit/moveit_core/collision_detection_fcl/src/collision_world_fcl.cpp:315:83: error: expected ‘}’ at end of input
 const std::string collision_detection::CollisionDetectorAllocatorFCL::NAME_("FCL");
                                                                                   ^
In file included from /usr/include/fcl/traversal/traversal_node_setup.h:48:0,
                 from /home/dh/catkin_ws/src/moveit/moveit_core/collision_detection_fcl/src/collision_world_fcl.cpp:40:
/usr/include/fcl/traversal/traversal_node_octree.h: In member function ‘void fcl::OcTreeSolver<NarrowPhaseSolver>::OcTreeIntersect(const int*, const int*, const fcl::Transform3f&, const fcl::Transform3f&, const fcl::CollisionRequest&, fcl::CollisionResult&) const’:
/usr/include/fcl/traversal/traversal_node_octree.h:87:42: error: request for member ‘getRoot’ in ‘tree1->’, which is of non-class type ‘const int’
     OcTreeIntersectRecurse(tree1, tree1->getRoot(), tree1->getRootBV(), 
                                          ^
/usr/include/fcl/traversal/traversal_node_octree.h:87:60: error: request for member ‘getRootBV’ in ‘tree1->’, which is of non-class type ‘const int’
     OcTreeIntersectRecurse(tree1, tree1->getRoot(), tree1->getRootBV(), 
                                                            ^
/usr/include/fcl/traversal/traversal_node_octree.h:88:42: error: request for member ‘getRoot’ in ‘tree2->’, which is of non-class type ‘const int’
                            tree2, tree2->getRoot(), tree2->getRootBV(), 
                                          ^
/usr/include/fcl/traversal/traversal_node_octree.h:88:60: error: request for member ‘getRootBV’ in ‘tree2->’, which is of non-class type ‘const int’
                            tree2, tree2->getRoot(), tree2->getRootBV(), 
                                                            ^
/usr/include/fcl/traversal/traversal_node_octree.h:89:36: error: there are no arguments to ‘OcTreeIntersectRecurse’ that depend on a template parameter, so a declaration of ‘OcTreeIntersectRecurse’ must be available [-fpermissive]
                            tf1, tf2);
                                    ^
/usr/include/fcl/traversal/traversal_node_octree.h: In member function ‘void fcl::OcTreeSolver<NarrowPhaseSolver>::OcTreeDistance(const int*, const int*, const fcl::Transform3f&, const fcl::Transform3f&, const fcl::DistanceRequest&, fcl::DistanceResult&) const’:
/usr/include/fcl/traversal/traversal_node_octree.h:101:41: error: request for member ‘getRoot’ in ‘tree1->’, which is of non-class type ‘const int’
     OcTreeDistanceRecurse(tree1, tree1->getRoot(), tree1->getRootBV(), 
                                         ^
/usr/include/fcl/traversal/traversal_node_octree.h:101:59: error: request for member ‘getRootBV’ in ‘tree1->’, which is of non-class type ‘const int’
     OcTreeDistanceRecurse(tree1, tree1->getRoot(), tree1->getRootBV(), 
                                                           ^
/usr/include/fcl/traversal/traversal_node_octree.h:102:41: error: request for member ‘getRoot’ in ‘tree2->’, which is of non-class type ‘const int’
                           tree2, tree2->getRoot(), tree2->getRootBV(),
                                         ^
/usr/include/fcl/traversal/traversal_node_octree.h:102:59: error: request for member ‘getRootBV’ in ‘tree2->’, which is of non-class type ‘const int’
                           tree2, tree2->getRoot(), tree2->getRootBV(),
                                                           ^
/usr/include/fcl/traversal/traversal_node_octree.h: In member function ‘void fcl::OcTreeSolver<NarrowPhaseSolver>::OcTreeMeshIntersect(const int*, const fcl::BVHModel<BV>*, const fcl::Transform3f&, const fcl::Transform3f&, const fcl::CollisionRequest&, fcl::CollisionResult&) const’:
/usr/include/fcl/traversal/traversal_node_octree.h:116:46: error: request for member ‘getRoot’ in ‘tree1->’, which is of non-class type ‘const int’
     OcTreeMeshIntersectRecurse(tree1, tree1->getRoot(), tree1->getRootBV(),
                                              ^
/usr/include/fcl/traversal/traversal_node_octree.h:116:64: error: request for member ‘getRootBV’ in ‘tree1->’, which is of non-class type ‘const int’
     OcTreeMeshIntersectRecurse(tree1, tree1->getRoot(), tree1->getRootBV(),
                                                                ^
/usr/include/fcl/traversal/traversal_node_octree.h: In member function ‘void fcl::OcTreeSolver<NarrowPhaseSolver>::OcTreeMeshDistance(const int*, const fcl::BVHModel<BV>*, const fcl::Transform3f&, const fcl::Transform3f&, const fcl::DistanceRequest&, fcl::DistanceResult&) const’:
/usr/include/fcl/traversal/traversal_node_octree.h:131:45: error: request for member ‘getRoot’ in ‘tree1->’, which is of non-class type ‘const int’
     OcTreeMeshDistanceRecurse(tree1, tree1->getRoot(), tree1->getRootBV(),
                                             ^
/usr/include/fcl/traversal/traversal_node_octree.h:131:63: error: request for member ‘getRootBV’ in ‘tree1->’, which is of non-class type ‘const int’
     OcTreeMeshDistanceRecurse(tree1, tree1->getRoot(), tree1->getRootBV(),
                                                               ^
/usr/include/fcl/traversal/traversal_node_octree.h: In member function ‘void fcl::OcTreeSolver<NarrowPhaseSolver>::MeshOcTreeIntersect(const fcl::BVHModel<BV>*, const int*, const fcl::Transform3f&, const fcl::Transform3f&, const fcl::CollisionRequest&, fcl::CollisionResult&) const’:
/usr/include/fcl/traversal/traversal_node_octree.h:147:46: error: request for member ‘getRoot’ in ‘tree2->’, which is of non-class type ‘const int’
     OcTreeMeshIntersectRecurse(tree2, tree2->getRoot(), tree2->getRootBV(),
                                              ^
/usr/include/fcl/traversal/traversal_node_octree.h:147:64: error: request for member ‘getRootBV’ in ‘tree2->’, which is of non-class type ‘const int’
     OcTreeMeshIntersectRecurse(tree2, tree2->getRoot(), tree2->getRootBV(),
                                                                ^
/usr/include/fcl/traversal/traversal_node_octree.h: In member function ‘void fcl::OcTreeSolver<NarrowPhaseSolver>::MeshOcTreeDistance(const fcl::BVHModel<BV>*, const int*, const fcl::Transform3f&, const fcl::Transform3f&, const fcl::DistanceRequest&, fcl::DistanceResult&) const’:
/usr/include/fcl/traversal/traversal_node_octree.h:163:45: error: request for member ‘getRoot’ in ‘tree2->’, which is of non-class type ‘const int’
                               tree2, tree2->getRoot(), tree2->getRootBV(),
                                             ^
/usr/include/fcl/traversal/traversal_node_octree.h:163:63: error: request for member ‘getRootBV’ in ‘tree2->’, which is of non-class type ‘const int’
                               tree2, tree2->getRoot(), tree2->getRootBV(),
                                                               ^
/usr/include/fcl/traversal/traversal_node_octree.h: In member function ‘void fcl::OcTreeSolver<NarrowPhaseSolver>::OcTreeShapeIntersect(const int*, const S&, const fcl::Transform3f&, const fcl::Transform3f&, const fcl::CollisionRequest&, fcl::CollisionResult&) const’:
/usr/include/fcl/traversal/traversal_node_octree.h:177:10: error: expected ‘;’ before ‘bv2’
     AABB bv2;
          ^
/usr/include/fcl/traversal/traversal_node_octree.h:177:13: error: statement cannot resolve address of overloaded function
     AABB bv2;
             ^
/usr/include/fcl/traversal/traversal_node_octree.h:178:39: error: ‘bv2’ was not declared in this scope
     computeBV<AABB>(s, Transform3f(), bv2);
                                       ^
/usr/include/fcl/traversal/traversal_node_octree.h:179:9: error: missing template arguments before ‘obb2’
     OBB obb2;
         ^
/usr/include/fcl/traversal/traversal_node_octree.h:180:25: error: ‘obb2’ was not declared in this scope
     convertBV(bv2, tf2, obb2);
                         ^
/usr/include/fcl/traversal/traversal_node_octree.h:181:45: error: request for member ‘getRoot’ in ‘tree->’, which is of non-class type ‘const int’
     OcTreeShapeIntersectRecurse(tree, tree->getRoot(), tree->getRootBV(),
                                             ^
/usr/include/fcl/traversal/traversal_node_octree.h:181:62: error: request for member ‘getRootBV’ in ‘tree->’, which is of non-class type ‘const int’
     OcTreeShapeIntersectRecurse(tree, tree->getRoot(), tree->getRootBV(),
                                                              ^
/usr/include/fcl/traversal/traversal_node_octree.h: In member function ‘void fcl::OcTreeSolver<NarrowPhaseSolver>::ShapeOcTreeIntersect(const S&, const int*, const fcl::Transform3f&, const fcl::Transform3f&, const fcl::CollisionRequest&, fcl::CollisionResult&) const’:
/usr/include/fcl/traversal/traversal_node_octree.h:197:10: error: expected ‘;’ before ‘bv1’
     AABB bv1;
          ^
/usr/include/fcl/traversal/traversal_node_octree.h:197:13: error: statement cannot resolve address of overloaded function
     AABB bv1;
             ^
/usr/include/fcl/traversal/traversal_node_octree.h:198:39: error: ‘bv1’ was not declared in this scope
     computeBV<AABB>(s, Transform3f(), bv1);
                                       ^
/usr/include/fcl/traversal/traversal_node_octree.h:199:9: error: missing template arguments before ‘obb1’
     OBB obb1;
         ^
/usr/include/fcl/traversal/traversal_node_octree.h:200:25: error: ‘obb1’ was not declared in this scope
     convertBV(bv1, tf1, obb1);
                         ^
/usr/include/fcl/traversal/traversal_node_octree.h:201:45: error: request for member ‘getRoot’ in ‘tree->’, which is of non-class type ‘const int’
     OcTreeShapeIntersectRecurse(tree, tree->getRoot(), tree->getRootBV(),
                                             ^
/usr/include/fcl/traversal/traversal_node_octree.h:201:62: error: request for member ‘getRootBV’ in ‘tree->’, which is of non-class type ‘const int’
     OcTreeShapeIntersectRecurse(tree, tree->getRoot(), tree->getRootBV(),
                                                              ^
/usr/include/fcl/traversal/traversal_node_octree.h: In member function ‘void fcl::OcTreeSolver<NarrowPhaseSolver>::OcTreeShapeDistance(const int*, const S&, const fcl::Transform3f&, const fcl::Transform3f&, const fcl::DistanceRequest&, fcl::DistanceResult&) const’:
/usr/include/fcl/traversal/traversal_node_octree.h:216:10: error: expected ‘;’ before ‘aabb2’
     AABB aabb2;
          ^
/usr/include/fcl/traversal/traversal_node_octree.h:216:15: error: statement cannot resolve address of overloaded function
     AABB aabb2;
               ^
/usr/include/fcl/traversal/traversal_node_octree.h:217:29: error: ‘aabb2’ was not declared in this scope
     computeBV<AABB>(s, tf2, aabb2);
                             ^
/usr/include/fcl/traversal/traversal_node_octree.h:218:44: error: request for member ‘getRoot’ in ‘tree->’, which is of non-class type ‘const int’
     OcTreeShapeDistanceRecurse(tree, tree->getRoot(), tree->getRootBV(),
                                            ^
/usr/include/fcl/traversal/traversal_node_octree.h:218:61: error: request for member ‘getRootBV’ in ‘tree->’, which is of non-class type ‘const int’
     OcTreeShapeDistanceRecurse(tree, tree->getRoot(), tree->getRootBV(),
                                                             ^
/usr/include/fcl/traversal/traversal_node_octree.h: In member function ‘void fcl::OcTreeSolver<NarrowPhaseSolver>::ShapeOcTreeDistance(const S&, const int*, const fcl::Transform3f&, const fcl::Transform3f&, const fcl::DistanceRequest&, fcl::DistanceResult&) const’:
/usr/include/fcl/traversal/traversal_node_octree.h:233:10: error: expected ‘;’ before ‘aabb1’
     AABB aabb1;
          ^
/usr/include/fcl/traversal/traversal_node_octree.h:233:15: error: statement cannot resolve address of overloaded function
     AABB aabb1;
               ^
/usr/include/fcl/traversal/traversal_node_octree.h:234:29: error: ‘aabb1’ was not declared in this scope
     computeBV<AABB>(s, tf1, aabb1);
                             ^
/usr/include/fcl/traversal/traversal_node_octree.h:235:44: error: request for member ‘getRoot’ in ‘tree->’, which is of non-class type ‘const int’
     OcTreeShapeDistanceRecurse(tree, tree->getRoot(), tree->getRootBV(),
                                            ^
/usr/include/fcl/traversal/traversal_node_octree.h:235:61: error: request for member ‘getRootBV’ in ‘tree->’, which is of non-class type ‘const int’
     OcTreeShapeDistanceRecurse(tree, tree->getRoot(), tree->getRootBV(),
                                                             ^
/usr/include/fcl/traversal/traversal_node_octree.h: At global scope:
/usr/include/fcl/traversal/traversal_node_octree.h:238:3: error: expected unqualified-id at end of input
   }

**Comment by gavanderhoorn** [comment]
With C/C++ errors: always scroll up to the first error that is reported and copy-paste that. The rest is most of the times not interesting.

**Comment by dh562231640** [comment]
Below is the error from the very beginning
It seems that something bad happened in the library FCL but I just do not know how to deal with that.

In file included from /usr/include/fcl/ccd/motion_base.h:46:0,
                 from /usr/include/fcl/collision_object.h:45,
                 from /usr/include/fcl/broadphase/broadphase.h:43,
                 from /home/dh/catkin_ws/src/moveit/moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_common.h:43,
                 from /home/dh/catkin_ws/src/moveit/moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_robot_fcl.h:40,
                 from /home/dh/catkin_ws/src/moveit/moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_world_fcl.h:40,
                 from /home/dh/catkin_ws/src/moveit/moveit_core/collision_detection_fcl/src/collision_world_fcl.cpp:37:
/usr/include/fcl/BV/RSS.h: In member function ‘fcl::FCL_REAL fcl::RSS::volume() const’:
/usr/include/fcl/BV/RSS.h:114:39: error: ‘template<class S> struct fcl::constants’ used without template parameters
     return (l[0] * l[1] * 2 * r + 4 * constants::pi * r * r * r);
                                       ^
In file included from /usr/local/include/fcl/geometry/collision_geometry.h:44:0,
                 from /usr/local/include/fcl/narrowphase/collision_object.h:43,
                 from /usr/local/include/fcl/broadphase/broadphase_collision_manager.h:44,
                 from /usr/local/include/fcl/broadphase/broadphase_bruteforce.h:42,
                 from /usr/include/fcl/broadphase/broadphase.h:233,
                 from /home/dh/catkin_ws/src/moveit/moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_common.h:43,
                 from /home/dh/catkin_ws/src/moveit/moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_robot_fcl.h:40,
                 from /home/dh/catkin_ws/src/moveit/moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_world_fcl.h:40,
                 from /home/dh/catkin_ws/src/moveit/moveit_core/collision_detection_fcl/src/collision_world_fcl.cpp:37:
/usr/local/include/fcl/math/bv/AABB.h: At global scope:
/usr/local/include/fcl/math/bv/AABB.h:49:7: error: ‘fcl::AABB’ is not a template type
 class AABB

**Comment by gavanderhoorn** [comment]
Did you follow the [moveit installation instructions](http://moveit.ros.org/install/source/) for source builds?

Please provide some info on how you build moveit from source.

**Comment by dh562231640** [comment]
I just did as it told me. nothing different

**Comment by dh562231640** [comment]
I solved it!
it is the pcl that I installed from the source that replaced the old one and the downloaded one is not good for moveit and made the moveit runs bad.
Thank you for the helping

**Comment by felixvd** [comment]
So this can be closed.
