### ISSUE TITLE
planning_scene.distanceToCollision( robot_state ) returns a max value

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit#591]
### Description

.distanceToCollision and collision_result.distance are giving nonsensical values.

### Your environment
* ROS Distro: Indigo
* OS Version: Ubuntu 14.04
* Binary version 0.7.12-0trus

### Steps to reproduce
Minimal example here: https://github.com/UTNuclearRoboticsPublic/standalone_collision_check

### Expected behaviour
I spawn a collision cube then try to measure the distance with planning_scene.distanceToCollision(). It should return something like ~0.5m.

### Actual behaviour
The returned value is 1.78e308

### Backtrace or Console output
n/a

### Comments
I'm fairly certain the cube is published correctly because MoveIt plans around it and the green cube is visible & listed in RViz.

**Comment by AndyZe** [comment]
Just checked ... same issue on Kinetic.

**Comment by AndyZe** [comment]
I did eventually get it working per https://github.com/ros-planning/moveit/issues/430. I guess I was mixing syntax. The functional code:

`  ros::init (argc, argv, "collision_check");
  ros::NodeHandle nh;

  ros::Duration(1.0).sleep();

  // Set up the MoveIt scene
  robot_model_loader::RobotModelLoader robot_model_loader("robot_description");
  robot_model::RobotModelPtr kinematic_model = robot_model_loader.getModel();
  planning_scene::PlanningScene planning_scene(kinematic_model);
  robot_state::RobotState robot_state = planning_scene.getCurrentState();
  collision_detection::AllowedCollisionMatrix acm = planning_scene.getAllowedCollisionMatrix();

  // Spawn a virtual collision object (for testing)
  spawn_collision_cube(nh);

  // Spin while checking minimum collision distance
  while ( ros::ok() )
  {
    //process collision objects in scene
    moveit::planning_interface::PlanningSceneInterface planning_scene_interface_;
    std::map<std::string, moveit_msgs::CollisionObject> c_objects_map = planning_scene_interface_.getObjects(); //error here
    for(auto& kv : c_objects_map){
      planning_scene.processCollisionObjectMsg(kv.second);
    }

  //print distance
  ROS_INFO_STREAM("Distance to Collision: " << planning_scene.distanceToCollision(robot_state));

    ros::Duration(1.).sleep();
  }`

**Comment by v4hn** [comment]
```
  // Spin while checking minimum collision distance
  while ( ros::ok() )
  {
    //process collision objects in scene
    moveit::planning_interface::PlanningSceneInterface planning_scene_interface_;
    std::map<std::string, moveit_msgs::CollisionObject> c_objects_map = planning_scene_interface_.getObjects(); //error here
    for(auto& kv : c_objects_map){
      planning_scene.processCollisionObjectMsg(kv.second);
    }
```

Congratulations on getting it to work.

Please note that it would be better to work with the `/get_planning_scene` service (for which there is no generic wrapper function in the `PlanningSceneInterface` yet, patches welcome) and update the relevant part of the planning scene; alternatively you could create a `PlanningSceneMonitor` and have it subscribe to `move_group/monitored_planning_scene` to receive `move_group`'s PlanningScene with a small delay.

The code above will never delete a collision object from the planning scene - `getObjects()` never returns `REMOVE` operations.
