### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by gerac83** [ros-planning/moveit#608]
I found a typo as below:

https://github.com/ros-planning/moveit/blob/4bc43c56ca2a5293f3ef8d55796ec586cfde5f69/moveit_planners/ompl/ompl_interface/src/detail/ompl_console.cpp#L40

it should be ompl_interface. I have no idea if this is relevant at all.

**Comment by bmagyar** [comment]
Thanks,  nice catch!  I'll look further into this today.

**Comment by bmagyar** [comment]
I couldn't find any traces in the current moveit codebase of using this file at all.
As it does nothing but prints, I think it may even be time for this file to be retired...

**Comment by v4hn** [comment]
If it is not referenced +1 to drop it.

**Comment by bmagyar** [comment]
I'll sort that out :+1:

**Comment by simonschmeisser** [comment]
can be closed?

**Comment by bmagyar** [comment]
Yeah, thanks!
