### ISSUE TITLE
MotionPlanning Display auto-active in RViz

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#633]
1. Run rviz.
2. Add a MotionPlanningDisplay (in case it is not there)
3. *Disable* the display and save the configuration
4. Close rviz
5. Start rviz again and load the saved configuration (or start via `rviz -d <config.rviz>`)

### Expected behaviour
The loaded MotionPlanningDisplay should still be disabled, as this is what the user saved

### Actual behaviour
The Display is enabled and active.

### Your environment
This should be reproducible on indigo and kinetic

**Comment by rhaschke** [comment]
Doesn't pose an issue anymore.
