### ISSUE TITLE
default_planner_config in MoveIt Setup Assistant

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#637]
For some time now, MoveIt provides a way to specify an OMPL default planner for each group. (See [here](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp#L270)).
[Here](https://github.com/TAMS-Group/tams_ur5_setup/blob/master/tams_ur5_setup_moveit_config/config/ompl_planning.yaml#L69)'s an example of this in a configuration.

It would be nice to be able to set this via the MoveIt Setup Assistant.

**Comment by akgoins** [comment]
I am looking into this issue.

**Comment by mlautman** [comment]
This has been resolved
