### ISSUE TITLE
Extract point of end effector

### ISSUE THREAD

**Issue by ThadeuVBrito** [ros-planning/moveit#672]
### Description

I am trying to get point of the arm tool  using MoveIt!. With this points I will create a code in C++ for motion planning the arm.
Now I am looking for ways to do this.

### Your environment
* ROS Distro: [Indigo]
* OS Version: Ubuntu 14.04

### Steps to reproduce
```
To make this environment I follow the steps:
cd ~/catkin_ws/src
git clone https://github.com/Kinovarobotics/kinova-ros.git kinova-ros
cd ~/catkin_ws
catkin_make

roslaunch j2n6s300_moveit_config demo.launch 
```

### Expected behaviour
Get a space coordinate of the manipulator.

### Actual behaviour
Trying use all features in Rviz display. But that does not tell the location of the arm tool.

### Backtrace or Console output
The number 2 is the point of interesting.

![extract_points](https://user-images.githubusercontent.com/29926059/31949438-9d1afdf6-b8d9-11e7-8e33-b15c4c317845.jpg)

**Comment by ThadeuVBrito** [comment]
I found a way, I do not know if is the best way. But works!
If it is help any people in future, just use the basic command:

`rostopic echo <name_of_topic_out_tool_pose>`

In my case, this command informs the position in XYZ and Orientation of the tool.

**Comment by bmagyar** [comment]
Yep but keep in mind that this assumes that you have a topic publishing this pose. You may encounter cases when there isn't any. You can also use `tf` to get some information if it's regarding the current state.

For similar questions in the future I'd direct you to the [moveit-users mailing list](https://groups.google.com/forum/#!forum/moveit-users). We treat incoming _issues_ on github seriously and to keep it that way it's best to put questions where they belong ;)

**Comment by gavanderhoorn** [comment]
@bmagyar: I would actually suggest that this sort of questions should be posted on ROS Answers. That is the appropriate support channel.

**Comment by bmagyar** [comment]
Good point!  :+1:

**Comment by ThadeuVBrito** [comment]
I agree too, but another day I posted a question in ROS Answers about configuration in MoveIt! and a guy said to post here. Sorry for the inconvenience.

**Comment by gavanderhoorn** [comment]
@ThadeuVBrito: can you post a link to the ROS Answer question?

**Comment by gavanderhoorn** [comment]
I can imagine that *build errors* and bug reports would be redirected here. But general questions about usage and configuration should probably go to ROS Answers.

**Comment by ThadeuVBrito** [comment]
Yes, I can.
