### ISSUE TITLE
MoveGroupInterface::setStartStateToCurrentState() leaves MotionPlanningRequest.start_state empty.

### ISSUE THREAD

**Issue by bmagyar** [ros-planning/moveit#675]
### Description

My intuition tells me this should fetch the current state and apply it. Instead it simply resets the shared_ptr of the current state variable. Anyone knows any hidden logic behind this?

https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp#L421

### Your environment
All versions are affected, the lines of code in question are from Ioan Suchan.

**Comment by jrgnicho** [comment]
PR #661 addresses this

**Comment by bmagyar** [comment]
Awesome, thanks!
