### ISSUE TITLE
Source code that makes PR2 pick and place objects onth table

### ISSUE THREAD

**Issue by tomato1986** [ros-planning/moveit#689]
Hi
I would like to have the source code that makes PR2 model pick and place object like following youtube demo.
When I read source code list page, there is a package "moveit_ros_manipulator" in moveit package.
However, actual github package does not have the package.
Where I can get moveit_ros_manipulation?
https://www.youtube.com/watch?v=Jk_s98U5ob8

### Your environment
* ROS Distro: Indigp
* OS Version:  Ubuntu 14.04
*

**Comment by bmagyar** [comment]
Hi,

Short answer: `moveit_ros_manipulation` can be found in this repository.
Long answer: This is an issue tracker for software issues. Please raise your questions about usage on [ROS answers](https://answers.ros.org/questions/)
