### ISSUE TITLE
 moveit::core::RobotState::setVariablePositions API question 

### ISSUE THREAD

**Issue by abishekh** [ros-planning/moveit#710]
### Description
`void moveit::core::RobotState::setVariablePosition  (  const std::string & variable, double  value)`
`void moveit::core::RobotState::setVariablePosition  ( int index, double  value ) `

### Your environment
* ROS Distro: [Kinetic]
* OS Version: Ubuntu 16.04
* Source 

Is there any particular reason why there aren't  'const' versions of the API for the second argument (double value) ? I see the vector and array versions are const  `moveit::core::RobotState::setVariablePositions ( const std::vector< std::string > & variable_names, const std::vector< double > & variable_position) ` but I was wondering about setting individual values specifically.

**Comment by rhaschke** [comment]
Usually it doesn't make sense to declare constness for arguments passed by value (i.e. creating a copy), because the function can do anything it likes with those args.
Arrays / vectors are passed by reference. Here the const declaration promises, that the function will not change those arguments.

**Comment by abishekh** [comment]
thats exactly the functionality I'm looking for with setVariablePosition() .

**Comment by rhaschke** [comment]
Which functionality you are exactly referring to? Please be more specific.
Is there anything you are still missing?

**Comment by abishekh** [comment]
Functionality that I'm looking for : 

> API that promises that the function will not change the arguments. 

Especially when setting a joint position or constraint or similar.

**Comment by rhaschke** [comment]
As I said above, all versions of `setVariablePosition()` will not change the passed joint position arguments.
Either because the argument is passed by value (i.e. copied for use in the function) or because it's passed by const reference / const pointer.
