### ISSUE TITLE
OMPL Info and Debug logs are shown since latest update, even though verbose/debug mode is not specified

### ISSUE THREAD

**Issue by haisongdong-harrison** [ros-planning/moveit#719]
### Description
OMPL Info and Debug logs are shown since latest update, even though verbose/debug mode is not specified.

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04
* Binary build:  0.9.10

### Steps to reproduce
From package created with Setup Assistant, launch move_group.launch with arguments `debug` and `info` set to false.

### Expected behaviour
Not to see OMPL Debug or Info logs in the terminal.

### Actual behaviour
![image](https://user-images.githubusercontent.com/13168445/33864994-ebf2a4d6-df32-11e7-97d9-a095c8b62115.png)

### Backtrace or Console output
https://gist.github.com/hansondon/229df6962bb55389cc72fcb2b2fa7832

**Comment by beckss** [comment]
Same issue here.

**Comment by guihomework** [comment]
same here :+1:
