### ISSUE TITLE
attached bodies are not shown in trajectory visualization anymore

### ISSUE THREAD

**Issue by rhaschke** [ros-planning/moveit#723]
Since MoveIt 0.9.10 attached bodies are not shown in trajectory visualization using rviz.
Is anybody aware of changes related to that? I appreciate any hint. Otherwise I will go and bisect...

**Comment by v4hn** [comment]
This issue is a bit underspecified...

Do you mean if you send a `moveit_msgs::DisplayTrajectory` with `AttachedCollisionObjects` in `trajectory_start.attached_collision_objects`, then they are not shown in the visualized trajectory?
I'm not aware of any change there.

**Comment by jeffreyling** [comment]
I ran into a similar issue, and I think I found the problem. In [PR 663](https://github.com/ros-planning/moveit/pull/663/files) the function `attachedBodiesToAttachedCollisionObjectMsgs` in `robot_state/conversions.h` should take a vector reference as argument, not a vector copy. 

This is messing up the part where the attached bodies are supposed to be added to the msg.

**Comment by rhaschke** [comment]
@jeffreyling Thanks for tracking this down. I will have a look.

**Comment by rhaschke** [comment]
Closing via #724
