### ISSUE TITLE
Setup assistant does not show collision geometries

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#780]
The preview robot state in the moveit setup assistant shows the visual meshes attached to links.
This is all good and nice for many of the dialogs (setting up the planning groups, poses, etc),
but it is not a good idea when the user tries to setup the allowed collision matrix for their models.
In this dialog, at least optionally, we should visualize the collision geometry instead.

This is especially important if you have "invisible walls" in your description - fixed links that have a collision geometry, but don't have a visual geometry associated. Currently they cannot be highlighted.

**Comment by rhaschke** [comment]
I could take care of this somewhere in April.

**Comment by v4hn** [comment]
It's somewhat frustrating to find issues I wrote two years ago about the same thing after I just wrote a new issue...
Anyway, here's my alternative proposal for a fix as written in #2291 :

> The "Self-Collisions" tab in the MoveIt Setup Assistant highlights the pair of relevant links in the 3d visualization when a specific collision pair is inspected/clicked on.
> Highlighting works by changing the color of the visual geometry of the link. But in many situations, people add geometry to the robot description that consists of collision geometry only and highlighting will not show anything for the respective link.
> Instead, these cases should be detected and the collision geometry should be shown in the highlight-color.
