### ISSUE TITLE
Buggy behavior caused by magic numbers in computeCartesianPath

### ISSUE THREAD

**Issue by mlautman** [ros-planning/moveit#783]
If you use [computeCartesianPath with Eigen::Affine3d](https://github.com/ros-planning/moveit/blob/61e2e304d2bb537784042ef96f510baa3610d865/moveit_core/robot_state/src/robot_state.cpp#L1903-L1955) you can get different results than if you pass in a vector with a single waypoint [computeCartesianPath with EigenSTL::vector_Affine3d](https://github.com/ros-planning/moveit/blob/61e2e304d2bb537784042ef96f510baa3610d865/moveit_core/robot_state/src/robot_state.cpp#L1985-L2025). The underlying issue is the magic +5 [here](https://github.com/ros-planning/moveit/blob/61e2e304d2bb537784042ef96f510baa3610d865/moveit_core/robot_state/src/robot_state.cpp#L1925). If you call computeCartesianPath with a EigenSTL::vector_Affine3d with a single point in it, the magic +5 doesn't happen and you can get paths returned with two waypoints which makes the testJointSpaceJump function meaningless. This is semi-related to [#773](https://github.com/ros-planning/moveit/issues/773) but different enough that it made sense to me to open a separate issue.

**Comment by davetcoleman** [comment]
This makes sense

**Comment by davetcoleman** [comment]
Is this still an issue @mlautman ?
