### ISSUE TITLE
No known features for CXX compiler 

### ISSUE THREAD

**Issue by keshavchintamani** [ros-planning/moveit#826]
### Description
I have successfully compiled ros-desktop-full from source on my mac using LLVM/Clang 5.0.1. I used the homebrew LLVM because some packages in MoveIt required OpenMP, which is not provided by AppleClang.

I've hit a roadblock with this issue with  rviz_visual_tools (also see https://github.com/PickNikRobotics/rviz_visual_tools/issues/71 ) 

```
CMake Error in rviz_visual_tools/CMakeLists.txt:
  No known features for CXX compiler

  "Clang"

  version 5.0.1.
```

I've looked all around for a solution but I cant seem to figure it out. The only related issue I could find was: 

https://cmake.org/pipermail/cmake/2016-December/064722.html

In my case: 
build/rviz_visual_tools/CMakeFiles/ is empty

I tried to pass in these cmake args
-DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_FIND_FRAMEWORK=LAST 

but no luck.

I've tried both catkin_make and catkin tools to build. 

### Your environment
* ROS Distro: Kinetic
* OS Version: macOS Sierra V.10.12.1
* Source build 
* CMake - 3.10
* LLVM/Clang 5.0.1 

* If source, which git commit or tag?
For rviz_visual_tools : origin/kinetic-devel
for moveit : origin/kinetic-devel

### Steps to reproduce
Build ros-kinetic-desktop-full on OSX with latest Homebrew LLVM/Clang 5.0.1 (with toolchain)

export CC=$(brew --prefix llvm)/bin/clang-5.0
export CXX=$(brew --prefix llvm)/bin/clang++
export CPPFLAGS="-I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include/c++/v1/"
export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

Build ros_control 
Build move_it

### Actual behaviour
CMake Error in rviz_visual_tools/CMakeLists.txt:
  No known features for CXX compiler

  "Clang"

  version 5.0.1.

**Comment by rhaschke** [comment]
This issue should be filed in https://github.com/PickNikRobotics/rviz_visual_tools.
Regardless of that, it is strange that you get this error for this package only. Most of the other packages also need a cxx compiler...
