### ISSUE TITLE
Issue while running move_group_python_interface_tutorial.py

### ISSUE THREAD

**Issue by sakshri20** [ros-planning/moveit#842]
I am new to both moveit and python and I am following this tutorial:
http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/pr2_tutorials/planning/scripts/doc/move_group_python_interface_tutorial.html 

but I am getting an error while executing the following command:
rosrun moveit_tutorials move_group_python_interface_tutorial.py

Here is the console output:

============ Starting tutorial setup
[ INFO] [1523909730.395710578]: Loading robot model 'pr2'...
[ INFO] [1523909730.730948123]: Loading robot model 'pr2'...
[ WARN] [1523909730.747445345]: The root link base_footprint has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1523909730.773330740]: Loading robot model 'pr2'...
[ WARN] [1523909730.790229082]: The root link base_footprint has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1523909730.814649078]: Loading robot model 'pr2'...
[ WARN] [1523909730.831617816]: The root link base_footprint has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1523909730.857104219]: Loading robot model 'pr2'...
[ WARN] [1523909730.874879240]: The root link base_footprint has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
Traceback (most recent call last):
  File "/home/sakshi/ws_moveit/src/moveit_tutorials/doc/pr2_tutorials/planning/scripts/move_group_python_interface_tutorial.py", line 243, in <module>
    move_group_python_interface_tutorial()
  File "/home/sakshi/ws_moveit/src/moveit_tutorials/doc/pr2_tutorials/planning/scripts/move_group_python_interface_tutorial.py", line 70, in move_group_python_interface_tutorial
    scene = moveit_commander.PlanningSceneInterface()
  File "/home/sakshi/ws_moveit/src/moveit/moveit_commander/src/moveit_commander/planning_scene_interface.py", line 62, in __init__
    self._psi = _moveit_planning_scene_interface.PlanningSceneInterface()
Boost.Python.ArgumentError: Python argument types in
    PlanningSceneInterface.__init__(PlanningSceneInterface)
did not match C++ signature:
    __init__(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)

I am using ubuntu 16.04, ros kinetic and python 2.7. 
Can someone please suggest me a solution or direct me to a similar issue where a solution is discussed.

**Comment by BryceStevenWilley** [comment]
I just ran into this issue as well. The problem comes from the fact that https://github.com/ros-planning/moveit/pull/835 was recently merged, which added name-spacing capabilities to most of the python interface, meaning that you have to pass in the namespace string. This is why in
```
Boost.Python.ArgumentError: Python argument types in
PlanningSceneInterface.init(PlanningSceneInterface)
did not match C++ signature:
init(_object*, std::__cxx11::basic_string<char, std::char_traits, std::allocator >)
```
The C++ signature expects a string. It seems that PR forgot to change [this line](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_commander/src/moveit_commander/planning_scene_interface.py#L62) to pass the string. It's an easy fix, I'll open a PR for it soon.
