### ISSUE TITLE
unknown simbol in libmoveit_planning_scene_interface

### ISSUE THREAD

**Issue by horagong** [ros-planning/moveit#857]
### Description

It was compiled without error but produced runtime error.
```
dyld: Symbol not found: __ZN6moveit18planning_interface22PlanningSceneInterfaceC1Ev
Expected in: /opt/ros/lunar/lib/libmoveit_planning_scene_interface.0.9.11.dylib
```
```
nm /opt/ros/lunar/lib/libmoveit_planning_scene_interface.0.9.11.dylib | egrep __ZN6moveit18planning_interface22PlanningSceneInterfaceC1Ev
```
### Your environment
* OS Version: mac
* Source or Binary build? source
* If source, which git commit or tag?  the recent c8419

**Comment by rhaschke** [comment]
This is strange. The symbol translates to the default constructor:
`moveit::planning_interface::PlanningSceneInterface::PlanningSceneInterface()`, which is not even declared in the MoveIt headers. So no idea, why you compiler creates symbols for this.
I think, this is noot MoveIt related, but an issue of your compiler/linker. Maybe you use a modified header?
