### ISSUE TITLE
Melodic: Unmanaged instances to `std::shared_ptr`? 

### ISSUE THREAD

**Issue by bmagyar** [ros-planning/moveit#866]
A new method has been added to the api, `std::shared_ptr createSharedInstance`

https://github.com/ros/class_loader/pull/95

It may be a more robust way to handle plugins than the current practice of `createUnmanagedInstance` with raw pointers.

**Comment by v4hn** [comment]
> It may be a more robust way to handle plugins than the current practice

Yes. Where's the pull-request :)

**Comment by davetcoleman** [comment]
+1

**Comment by bmagyar** [comment]
I'll try to do it today

**Comment by rhaschke** [comment]
Will be fixed by https://github.com/ros-planning/moveit/pull/1104.
