### ISSUE TITLE
moveit_commander import error

### ISSUE THREAD

**Issue by huiwenzhang** [ros-planning/moveit#887]
### Description

When I try to use moveit python interface in python 3, I can't import moveit_commander correctly. Module roscpp_initializer missing.

### Environment
* ROS Distro: [Indigo]
* OS Version: Ubuntu 14.04
* binary installed with `sudo apt-get install ros-indigo-moveit`

I guess the problem happens because moveit python interface does not support python 3. However, I have to use another python 3 package in my project. Does anyone know how to fix this?

**Comment by bmagyar** [comment]
AFAIK ROS currently only supports Python2.7 officially. Although there are
ongoing efforts towards Python 3 support, it's not fully covered yet.

You should only expect it from perhaps Kinetic and onwards. I doubt Indigo
will receive new features at this point in time.
