### ISSUE TITLE
Setup Assistant 2

### ISSUE THREAD

**Issue by MohmadAyman** [ros-planning/moveit#894]
### Description

Hello there, I'm Mohamad Ayman a Computer Engineering Masters student and a Google Summer of Code student.

My proposal this summer focuses on improving the Setup Assistant by automating the generation of some configurations and adding more GUIs to make the generation of some easier and more straight forward, along with improving the integration with Gazebo where we one wont have to add configs or edit the robot file manually for it to work with gazebo.

Below are the description of the improvements broken into tasks, I will update the tasks each time a related PR is opened, any suggestions or feedback are highly appreciated.

[Project description on Google Summer of Code website.](https://summerofcode.withgoogle.com/projects/#5374298588446720)

- [x] New screen for automatically generating interfaces to low level controllers
[**~~PR Setup assistant automating generation of controllers configs~~**](https://github.com/ros-planning/moveit/pull/908) 
**~~pull request #951~~** 
**~~pull request #994~~**

- [x]  Improving gazebo integration.
**~~pull request #956~~** 
**~~pull request #936~~** 

- [x] Perception screen for using laser scanner point clouds.
**~~pull request #969~~** 

- [x] New grasping screen for setting up end effectors.
**[Blocked for now because the backend is still not ready]**

- [x] Parse existing text files [launch/config/package] and adding more GUIs for loading and saving settings.
**[Basically each of the previous points contribute to this point]** 

- [x] others
~~#1022~~
~~#1017~~ 
~~#1013~~
~~#995~~
~~#924~~
#1020

**Comment by simonschmeisser** [comment]
We are about to start working on our own "mikado_setup_assistant" (name not final) for our software, sharing plugins either way sounds like a great idea! (I.e. having a plugin system should hopefully also allow loading these in a different host application)

**Comment by davetcoleman** [comment]
@MohmadAyman I would say the plugins should be a lower priority than the other features we are focusing on, but if there was time at the end of the summer then of course it sounds great

**Comment by MohmadAyman** [comment]
Hi @simonschmeisser , have you guys started working on your "mikado_setup_assistant"?

**Comment by davetcoleman** [comment]
@MohmadAyman please update this issue with your final updates, then we should consider closing it

**Comment by MohmadAyman** [comment]
Done,

Can we leave it until the tutorials have been updated? so they don't get forgotten.

**Comment by davetcoleman** [comment]
I believe this can now be closed. Congrats @MohmadAyman for a very successful GSoC project! Your continued involvement in MoveIt! including code review and code contributions are always welcomed :100:

**Comment by MohmadAyman** [comment]
I've opened a PR for the Plugin based SA #1243 , would be nice to have your input.
