### ISSUE TITLE
Controllers Widget

### ISSUE THREAD

**Issue by MohmadAyman** [ros-planning/moveit#933]
### Description

Adding a new window for controllers specific settings to the setup assistant.

This issue is to discuss the status and progress of the screen, discuss how the GUI should look and what options/settings should we include.

The controllers settings are exported to `ros_controllers.yaml`, which is then used by `ros_controllers.launch` which is utilized in `gazebo.launch` introduced in [PR 936](https://github.com/ros-planning/moveit/pull/936).

![](https://raw.githubusercontent.com/MohmadAyman/school/master/s1.png)
![](https://raw.githubusercontent.com/MohmadAyman/school/master/s2.png).
![](https://raw.githubusercontent.com/MohmadAyman/school/master/s3.png).

This issue follows the upgrade to the setup assistant discussed [in issue 894](https://github.com/ros-planning/moveit/issues/894).

The window is going to be very much like the `Planning Groups` window, adding controllers, editing controllers ... 
@davetcoleman @mcevoyandy

**Comment by davetcoleman** [comment]
Thanks for posting this!

> sorry for my poor photo editing skills.

Edit directly in the GPresentation doc I shared with you - do you have write access?

Reword subtitle to "MoveIt! Simulation Controller" (capitalization)

Group should be a drop down (add down arrow on right side). So should initial pose name

Title of the widget should maybe be "Controllers" so that it also encompases general ROS Control configuration?

**Comment by MohmadAyman** [comment]
> Edit directly in the GPresentation doc I shared with you - do you have write access?

Yes I do have access, [here](https://docs.google.com/presentation/d/1DU--GRFGhTw43O-qVTdrCs39Osu4T_PIeItMLoC_jbs/edit?usp=sharing).

> Title of the widget should maybe be "Controllers" so that it also encompases general ROS Control configuration?

"Controllers" makes sense, but I thought maybe we add the gazebo_integration related stuff here, or would it be better to separate
 them in different windows?

Added the drop down and capitalized, thanks for the feedback.

**Comment by MohmadAyman** [comment]
Updated the issue description.

**Comment by davetcoleman** [comment]
Gazebo integration might get crowded on this same screen, but I think making full mock-ups of both screens will help answer that.

**Comment by MohmadAyman** [comment]
@davetcoleman @mcevoyandy I've updated the screenshots, can you please have a look?

**Comment by davetcoleman** [comment]
The mockups look much better! Now for the design review :)

Screen 1:

- Need a button to delete a controller
- Add a button at the top to automatically create default FollowJointTrajectory controllers based on each existing planning group. 
- Improve description at top of screen to explain these are optional ros_control controllers that help with Gazebo also.

Screen 2:

- Controller type should be a drop down box (illustrate this with a down arrow)
- Have a button for 'Add Joint Group' to make setup easier
- Needs a save button? I'm not sure

Screen 3:

- It says "Available Groups" but i think you meant "Available Joints". However I'd have a screen for both.

**Comment by MohmadAyman** [comment]
Thanks for the feedback, I'll be working on addressing the comments.

**Comment by MohmadAyman** [comment]
The [PR 951](https://github.com/ros-planning/moveit/pull/951) for the new  window is ready :+1: .
