### ISSUE TITLE
New line in tutorial formatter

### ISSUE THREAD

**Issue by Ridhwanluthra** [ros-planning/moveit#944]
### Description

Need to write the comments for the code in a new line. I am not sure how to do this using the tutorial-formatter

### Your environment
* ROS Distro: [Kinetic]
* OS Version: Ubuntu 16.04
* Source build

### Steps to reproduce
Just write a tutorial and type on different lines.

### Expected behavior
// hey
// hey1
should come as 
hey
hey1

### Actual behaviour
they come as
heyhey1

**Comment by Ridhwanluthra** [comment]
@mlautman

**Comment by v4hn** [comment]
See #945 for my feedback. The same applies here.
Also, if you have a particular problem with a tutorial you work on, please file a pull-request for it and add comments where you want feedback.

**Comment by mlautman** [comment]
Play around with /**/ to see if that gets you what you are looking for. If not, just keep trying different things and building locally until you find what you are looking for.
