### ISSUE TITLE
SRDF syntax error should trigger fatal error

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#967]
When the SRDF description contains invalid xml, MoveIt still starts up "successfully", but considers only the information encountered before the syntax error.

The proper solution is to fail with an appropriate error message.

**Comment by kkufieta** [comment]
Made a PR to fix this issue here: https://github.com/ros-planning/srdfdom/pull/41

**Comment by v4hn** [comment]
Thank you @kkufieta !
